### ISSUE TITLE
How to use Applewin controls?

### ISSUE THREAD

**Issue by Forest31** [AppleWin/AppleWin#1019]
Cursor keys are apparently in the newest version but they don't work. I can't use the arrow keys or the numpad, even with the respective keys to use them (caps lock, num locks etc) turned on. I've tried everything short of breaking into the emulator itself to force these keys to work. It is driving me nuts and so far, no one has given thought to fixing it!

I have caps lock on for games that need it, but the arrow keys don't work. Space works to start the program but for games like worm of Bemer, I have no clue what is wrong

This really needs to be addressed. In the next update, could you PLEASE add the option to redefine keysets from the emulator menu? Winvice allows it, why not Applewin? I get trying to stay as close as possible to the machine but it shouldn't be at the cost of usability.

**Comment by tomcw** [comment]
Hmm... not quite sure what you are talking about here.

Dedicated cursor keys(*) can be used to mimic the Apple //e cursors keys and/or be used as a joystick.
Have you read the AppleWin.chm help doc?
See AppleWin Configuration -> Input Settings.

(*) ie. on a full-size keyboard with actual keys dedicated for up/down/left/right.

You mention the numpad, so are you talking about the cursors on the numpad 2/4/6/8 keys?

**Comment by Forest31** [comment]
How?
Yes, no luck
Yes, the number pad refuses to work even with num lock on and caps enabled. 
I have. All i see are Joystick (cursor keys) Joystick (numpad), mouse and disabled. Numpad doesn't work, Cursors doesn't work, Mouse does for some games. There's no documentation for what keys do what on the emulator, i've checked.
Often times i'm flying blind and it's incredible stressful.

**Comment by sicklittlemonkey** [comment]
You only mention one game: "worm of Bemer". There is no Apple II version of
this game, AFAIK.
Perhaps you could be more specific about a particular problem with a
particular piece of software.
The keys do whatever the currently running software wants them to do.

**Comment by tomcw** [comment]
I will close this soon unless more specific info is given.

**Comment by tomcw** [comment]
Closing, due to lack of info from OP.
