### ISSUE TITLE
WOZ: Glutton

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1021]
@peterferrie said on Slack (17 Jan 2022):

>Slight timing variation would help with Glutton, too.  100% failure in AppleWin, MAME struggles but eventually boots it.

[Glutton.zip](https://github.com/AppleWin/AppleWin/files/7884926/Glutton.zip)

**Comment by tomcw** [comment]
Boots occasionally (1 in 10?), but I'll take a look.

**Comment by tomcw** [comment]
@mr-stivo said on Slack:

>This is a strange one.  It booted 2 out of 10 times for me. Adjusting the weak bits 1's rate doesn’t seem to help. Reducing the head window size from 4 bits to 3 bits will get it to always boot but the boot times range from 30 seconds to 75 seconds. The 3 bit head window with no delay gets it to always boot in less than 30 seconds.

>But it really likes the jitter. 2% jitter and it always boots in under 15 seconds. I’ve never seen a disk quite like this one.

>I should add I’m using my own emulator and a slightly modified openemulator.

**Comment by univta0001** [comment]
I have tested using my own emulator. This image is using optimal bit timing of 32. It is not able to boot when there is no timing jitter on the optimal bit timing. However, once the timing jitter is enabled at 50% randomness, between 32 and 33, it can always boot.

**Comment by tomcw** [comment]
@peterferrie: this new [AppleWin 1.30.8.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.8.0) is booting Glutton everytime now.

I need to see which of the 2 woz-related fixes in this version had this positive effect!

**Comment by tomcw** [comment]
The fix was actually both the woz-related fixes in 24378313c337a44c2ffea4e10aed455b5dfa27ad, ie:
- Significant bit-cells after a gap between latch access upped from 50 to 100
- Minor track sync mod: Update bitStream position for current track before re-calc'ing position for new track

So from these 2 fixes, the issue was likely track sync, and needing a longer run of bit-cells to get the nibble sync.

**Comment by tomcw** [comment]
Continues to work with 1.30.9 and 1.30.10, so closing as fixed.
