### ISSUE TITLE
WOZ: The Toy Shop

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1023]
Matthew Eric D'Asaro said on Slack (22 Jan 2022):
>I had no problems imaging the copy-protected "MASTER DISK" which contains the boot program and it will indeed boot in all the emulators. The challenge is that the data disks containing the actual toy templates, "TOY DISK 1" and "TOY DISK 2", are also copy-protected and they do not work in emulation. To complicate matters, you can't actually tell if the data disks work until you go to print a model. The software won't let you print a model until it has verified that it can communicate with a printer. Grr. Of all the emulators available, I was able to make printing work in MicroM8 and VII (to the point that it produced an output file) and in AppleWin I was able to make the program think that there was a printer connected by telling it I have an Epson LX-80 connected to an Apple parallel interface in slot 1, but I couldn't actually retrieve the output. Once the printer is setup you can try to print a model. It will ask to read the 'B' side of the "MASTER DISK" and then the 'A' side again and then it will ask for the first data disk "TOY DISK 1" or whatever. However, this is as far as I have been able to get. It won't accept my images of the original data disks at all.

qkumba said:
>AppleWin fails to find one sector on track 2 of the first data disk.  MAME can read this sector, so it looks like an AppleWin issue this time.

4am's set of images: [The Toy Shop.zip](https://github.com/AppleWin/AppleWin/files/7920343/The.Toy.Shop.zip)

**Comment by tomcw** [comment]
For data disk 1, T$02, it's a perfect data alignment that's causing the "Find next address field" routine (at $4280) to miss the $D5 prologue nibble.

Details:
- the data on the track is packed as 6x 3-sectors, where each 3-sector has a address header: D5 9D trk sec chk AA
  - where sec = {96, 97, 9A, 9B, 9D, 9E} for sectors [0..5]
  - so T$02 = D5 9D 9A sec chk AA
- the code will seek from T$00 to T$02
- subroutine at $423D reads the track, and does so by reading each of the six 3-sectors _once_, maintaining a table of what's been read so far at [$D055..D05A], where $30=unread, $00=read

The problem is in reading S$00.
This immediately follows S$01 on the track, and typically S$01 gets read first.
Here's the code to find the next address field:
```
4280	; Find next addr field
		; Post: C=1: error
		;	C=0, Y=(2D)=sector
	Y = #$fa
	(30) = $fa			; timeout = $606
4284
		; NB. the fast-path is $20 cycles, ie. same as a disk nibble
		; but every 256th loop is a slow-path
-		iny
		bne +
			inc (30)
			beq 427e	; error
+		jsr 4234		; read nibble
--		cpx #$D5
		bne	-
		jsr 4234		; read nibble
		cpx #$9D
		bne	--
		jsr 4234		; read translated nibble (trk)
		(2C) = A
		jsr 4234		; read translated nibble (sector)
		(2D) = A
		jsr 4234		; read translated nibble (chk)
		A ^= (2C) ^ (2D)
		bne -
		jsr 4234		; read nibble
		cpx #$AA
		bne	-
	clc				; ok
	Y = (2D)
	(27) = (D043 + Y)
	(29) = (D049 + Y)
	(2B) = (D04F + Y)
	rts
```

And here's the sequence of events for the $S00 failing case:

```
4280	; Find next addr field
. Have already read sector 1, so now just reading nibbles looking for $D5 then $9D
. Found 1st $D5 at offset $F81 / bitOffset $7C08, which is a short field of "D5(1)D5(1)D5(1)FF(2)FF(2)FF(2)FF(2)FF   D5   9D"
	. NB. Y=$FB
. Next nib=D5, !=9D
. Next nib=D5, !=9D
. Next nib=FF, !=9D
	Y=$FC
. Next nib=FF, !=D5
	Y=$FD
. Next nib=FF, !=D5
	Y=$FE
. Next nib=FF, !=D5
	Y=$FF
. Next nib=FF, !=D5
	Y=$00
	inc (30)	; (30)=FF / NB. slow-path
	; missed reading D5 from latch!
. Next nib=9D, !=D5
```

So the perfect alignment means that the slow-path (Y increments from $FF to $00) is taken, and the address field D5 gets missed. Once the code & disk are aligned like this, then it will always fail to read S$00!

**Comment by medasaro** [comment]
Thank you @tomcw for your efforts investigating this. If I am understanding you code snippet and explanation correctly, it is the fact that the the data rate from the emulated drive is perfect with no "wow or flutter" that is causing this problem? Would the "correct" fix be to have AppleWin intentionally introduce some slight changes in the data rate from the emulated drive? Or for the .woz to accurately capture the real imperfect data rate as read from the disk? Because this title apparently works in MAME, is MAME doing something similar with varying the data rate slightly? Thanks again for your efforts.

-Matthew D'Asaro

**Comment by H82lose** [comment]
Hi
Any progress with implementing Pig Font into Apple Win ? I know you mentioned to write a program to have Apple Win use the Fonts ?

Thanks

Patrick




Sent from Yahoo Mail for iPhone


On Sunday, January 23, 2022, 3:27 AM, TomCh ***@***.***> wrote:




Matthew Eric D'Asaro said on Slack (22 Jan 2022):


I had no problems imaging the copy-protected "MASTER DISK" which contains the boot program and it will indeed boot in all the emulators. The challenge is that the data disks containing the actual toy templates, "TOY DISK 1" and "TOY DISK 2", are also copy-protected and they do not work in emulation. To complicate matters, you can't actually tell if the data disks work until you go to print a model. The software won't let you print a model until it has verified that it can communicate with a printer. Grr. Of all the emulators available, I was able to make printing work in MicroM8 and VII (to the point that it produced an output file) and in AppleWin I was able to make the program think that there was a printer connected by telling it I have an Epson LX-80 connected to an Apple parallel interface in slot 1, but I couldn't actually retrieve the output. Once the printer is setup you can try to print a model. It will ask to read the 'B' side of the "MASTER DISK" and then the 'A' side again and then it will ask for the first data disk "TOY DISK 1" or whatever. However, this is as far as I have been able to get. It won't accept my images of the original data disks at all.


qkumba said:


AppleWin fails to find one sector on track 2 of the first data disk. MAME can read this sector, so it looks like an AppleWin issue this time.


The Toy Shop.zip

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peterferrie** [comment]
I was wrong about MAME doing the right thing.  It behaves exactly as AppleWin does, and eventually fails the read for exactly the same reason.

**Comment by tomcw** [comment]
Lots of discussion in Slack:
- @medasaro confirmed that VII and microm8 both eventually fail with: "Please place 'Toy Shop' data disk 1, side A in the drive"
- and MAME too (by @peterferrie above)

My current speculation:
- Maybe it's a sync track issue (in AppleWin at least), since AppleWin definitely has a track sync problem with _Balance of Power_. EG. if the seek from T00 to T02 always landed in sector 1, then wouldn't sector 0 would always be read first and read correctly?

NB. I made a change to AppleWin (not committed yet) to try to fix the track sync issue with _Balance of Power_ (but it didn't fix _B of P_), and this helped with Toy Shop (data disk 1) in that it got past track 2... but then got stuck on track 4, with exactly the same problem!

**Comment by medasaro** [comment]
I appear to have found an "interesting" title then... Glad I could be of "help". Thanks to all who have been trying to figure this out.

-Matthew D'Asaro

**Comment by tomcw** [comment]
After this tweak to `ReadTrack()` - 24378313c337a44c2ffea4e10aed455b5dfa27ad (the "Minor track sync mod" bit) - then AppleWin always gets past the "perfect data alignment" issue above.

I also wrote a function to dump the 3-sector it was in after a seek to T$02, and it wasn't consistent, so demonstrating that this wasn't a "sync track" issue.

**Comment by tomcw** [comment]
(The following is just a re-cap of what I wrote on Slack)

Focussing on "TOY DISK 1" (side A), there are 5 woz images:
- 3 from @medasaro 
- 1 from 4am
- 1 from Disk Blitz

**The only one that _works_ is Disk Blitz's - ie. the print completes.**
The other tend to get stuck with the message: "Please place 'Toy Shop' data disk 1, side A in the drive"

I wrote some debug code to check the 35 tracks (where phase = track * 2), and ran it against these 5 woz images.
FYI, the "Between sectors: X and Y" just means that at bit position 0 this is between the sector headers for sector X & Y.

[notes-track-dumps.txt](https://github.com/AppleWin/AppleWin/files/7974395/notes-track-dumps.txt)

This also shows clearly why some images get stuck at track-3: eg. the 1st woz, where phase=6.00 only has 1 sector).
And the 3rd woz which gets stuck at track-9, as phase=18.00 only has 5 sectors.

You can see that nearly all the tracks with missing sector(s) are too short.
They should be ~$C700 bits, but the ones missing sectors are eg. $A60A, $4146 and even just $DE bits! ("the Toy Shop - TOY DISK 1 - Side A - image attempt 2.woz" for phase 50.0).

The exception to this is @medasaro's "image of copy" (ie. the Locksmith copy) - "the Toy Shop - TOY DISK 1 - Side A - image of copy.woz".
This has all tracks of the right length, but Phase=18.0 has only 5 sectors.
So I dumped this out, and you can see that the Address Field (header / "hdr") is corrupt:
"D5   CB(1)AB   AA   FF   FF", when it should be "D5   9D   AB   96   chk   AA"  (I didn't calc the chksum("chk"), but it's not important to see that the nibbles are corrupt.)

Here's the text dump of this track:
[TTS-DataDisk1-ImageOfCopy-T$09.txt](https://github.com/AppleWin/AppleWin/files/7974407/TTS-DataDisk1-ImageOfCopy-T.09.txt)

As I said on Slack: why the bad images?  I don't know. Maybe Disk Blitz has an idea - eg. why is AppleSauce truncating the track, sometimes drastically (in the $DE length case). Perhaps there's something in the .a2r raw images that is causing this. But that said, Disk Blitz’s woz of this disk's side is the only one that is a good image.

**Comment by tomcw** [comment]
AppleWin did have a subtle issue with `ReadTrack()`, but this was for a corrupt "TOY DISK 1 (side A)" image (although the specific T$02 track was fine).

Beyond that, this overall `Toy Shop` problem is currently purely down to corrupt images, not an emulation issue.

**Comment by tomcw** [comment]
Labelling this as a bug, since AppleWin did have a subtle issue.

I am closing this issue, as @peterferrie has made some fixes to [passport](https://github.com/a2-4am/passport), such that it now reports defective RW18 tracks (by verifying all 6 sectors).
