### ISSUE TITLE
Hacked AppleWin for slot 5 boot (for pascal) Help?

### ISSUE THREAD

**Issue by dhlav** [AppleWin/AppleWin#1033]
Hi, I'm quite new to all the github stuff, but I have checked out the latest and modified it so it sets the hard drive to slot 5 instead of slot 7. Used this for pascal setup/booting (pascal wont boot slot 7). Works good in testing here. I'd like to at least contribute this hacked version back maybe as a branch or whatever. Can anyone give me a clue how to get it back up? Pull request? I might need a simple step by step. Don't want to hurt the repo. Thanks. Dave Hlavac.

**Comment by audetto** [comment]
Fork the repo, and create a branch with your new code.
If and when you think it is clean enough, create a PR to merge it here.

**Comment by dhlav** [comment]
Ok, many thanks. FYI, this is just a hack job substituting 5 for 7, and you can't have disk card ii on 5 either. Just to get me going and a basis for others, if needed. I've already forked it. Haven't pushed anything to my repo yet. I will try and set this up and do it the ~proper~ way with a config as noted via cmd line to start. Shouldn't be too crazy. Someone already set the hd firmware to be slot independent. One thing to note is the hd firmware card has a fixed 32767 reported block count. So formatting under pascal always makes the size 32767. If you format/use a different size outside of applewin/emulated pascal formatter, the images work and show the size correctly. Just an fyi.

**Comment by tomcw** [comment]
Probably this needs adding for command line support:
- -s5 hdc
- -s7 hdc
- -s5h1 \<pathname\>
- -s5h2 \<pathname\>

where 'hdc' = hard disk controller.

btw, it was me that made the hd firmware slot independent (#996), with the intention of adding this slot 5 support at some stage.

>One thing to note is the hd firmware card has a fixed 32767 reported block count. So formatting under pascal always makes the size 32767. If you format/use a different size outside of applewin/emulated pascal formatter, the images work and show the size correctly.

How else would this be reported? IE, yes, the firmware has a fixed 32767, but what are alternative ways to support this?

**Comment by dhlav** [comment]
It's just in the pascal formatter, so somehow it's reading the disk size as that (probably from unitstatus/status). I'll check and see if it can be worked around/supported, but since only the first n blocks of an image is all that's needed for pascal, can probably make images externally. You can take the 800k pascal 3.5 floppy image and works/reports just fine, until you format it. :)

**Comment by tomcw** [comment]
OK, I see what you mean now: as AppleWin's "hybrid" Hard Disk Controller card supports HDDs (up to 32MB) and 800KB 3.5" disks, then the card's firmware will report an 800KB disk as being 32767 blocks (ie. 16MB).

**Comment by dhlav** [comment]
Yep, but **only** in the FORMATTER application in pascal (only run to format disks). All else in pascal is fine. This may not be a big thing right now. Haven't even tried prodos yet on this. Thanks for the help. :)

Do you think hard drive cards should be able to be put into both slots at the same time? I have no idea if that's a true use-case.

**Comment by tomcw** [comment]
>Yep, but **only** in the FORMATTER application in pascal (only run to format disks). All else in pascal is fine. This may not be a big thing right now.

We could modify the firmware on-the-fly if the Hard Disk Controller card has a .hdv (hard disk) or a .po (800KB floppy). We could even support it depending which unit/volume (0 or 1) is selected, for the mixed case, ie. a .hdv _and_ a .po at the same time.

Anyway, let's put this to one side for now.

>Do you think hard drive cards should be able to be put into both slots at the same time?

Yes, definitely.

**Comment by sicklittlemonkey** [comment]
Are there spare softswitch locations the firmware could pull the real size
from?

**Comment by tomcw** [comment]
I guess it depends how "the FORMATTER application in pascal" gets the device's block count.

Ultimately it must read the 16-bit value at $CsFC, ie...
https://github.com/AppleWin/AppleWin/blob/83e56924f735a1bfc6b443a7f2861924ec94f921/firmware/HDD/hddrvr.a65#L339

So when AppleWin copies the 256-byte firmware to $Cs00 (or the Hard Disk Controller card's unit number changes), then AppleWin just needs to overwrite this with the correct value.

btw, I don't know why it is using $7FFF (which is 16MB) when $FFFF is clearly better (for a larger 32MB HDD).

**Comment by hasseily** [comment]
Similarly (I think), there's a 2mg out there of Dark Heart of Uurkrul that will only boot from slots 4-6.

**Comment by tomcw** [comment]
Also "Perplexing Puzzles" 800K 2mg only boots from slot 5.
NB, [this image](https://archive.org/details/wozaday_Perplexing_Puzzles_800K) is an 800K woz, which isn't supported in AppleWin yet.

**Comment by tomcw** [comment]
To do:
- [ ] Fix-up the firmware to reflect the current image size: 0x0640 (800KiB 2mg) or 0xFFFF (32MiB hdv).
- [ ] This also has to change when `unit number` changes.
   - As you may have a 800K image on unit 0, and a 32M image on unit 1

**Comment by tomcw** [comment]
NB. ProDOS STATUS command support added to HDD Controller firmware in 2cbecdda6860f22a887493a9b766d82d5558b613.

This is a far better solution than what I proposed above (ie. modify the firmware on-the-fly).

I think this issue can be closed now, as there a way (albeit cmd line, not GUI) to put a HDD Controller into slot 5, and also the correct volume size is returned now via the ProDOS STATUS command.
