### ISSUE TITLE
Pooyan feels too fast at authentic speed

### ISSUE THREAD

**Issue by ualaa1** [AppleWin/AppleWin#1045]
Using the .woz version
Tested using the Apple II+, IIe and enhanced IIe modes.
This is the only game I tested so far that seems to have that speed issue.
It feels like playing slightly overclocked rather than being correct

**Comment by tomcw** [comment]
btw, I will close this soon unless more specific info is given.

**Comment by tomcw** [comment]
Closing, due to lack of info from OP.
