### ISSUE TITLE
Uthernet II save state

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#1052]
Hi

I have got the save state ready, but I have a question about size.
The easiest way is to save the entire 32K memory area. Is it too much?

I thought I could skip saving the RX and TX buffers and reset them to 0, but this does not work well with the running code which would see these areas moving.

Alternatively I could save only what is in transit (not yet sent, or not yet "read"), but this could be tricky.

It is anyway impossible to save and load in the middle of a network operation, as the other side wont work.

Any other suggestion?

**Comment by tomcw** [comment]
Saving the whole 32K memory area is fine.
(There are other cards that save more memory, eg. VidHD for II+ saves 39K)

>It is anyway impossible to save and load in the middle of a network operation, as the other side wont work.

Yes - the same restriction exists for other realtime comms cards, like Uthernet I and SSC (Serial card).

**Comment by audetto** [comment]
Makes sense, there is a PR now https://github.com/AppleWin/AppleWin/pull/1054.

This works well for a pcap backend, but not using libslirp, where I would have to save its state too.
That would mean some problems moving the save states between OSes, but at the moment they would not work either... need to think about it.

**Comment by tomcw** [comment]
PR #1054 now merged, so closing this issue.

**Comment by tomcw** [comment]
PR #1054 now merged, so closing this issue.
