### ISSUE TITLE
filenames containing '#' are truncated when loading via save-states

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1066]
I have this file:
`Dangerous Dave Goes Nutz (Softdisk #160).po`
I save the state while debugging.  If I try to load the state, the requested filename is "Dangerous Dave Goes Nutz (Softdisk".  If I accidently accept that filename, then "Dangerous Dave Goes Nutz (Softdisk.dsk" is created, an error is shown, the session exits, and then AppleWin restarts.

**Comment by tomcw** [comment]
Hi Peter - thanks for raising this.

The "#" character is a comment in YAML, so the disk image name is getting truncated at the point of the "#".
As a workaround you can text-edit the YAML save-state file, and put quotes around the `Filename`, eg:

```
          Floppy:
            Filename: "Dangerous Dave Goes Nutz (Softdisk #160).po"
```

I'll fix this bug in the next release.

**Comment by tomcw** [comment]
FYI: new AppleWin 1.30.9.0 release [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.9.0) with this fixed.

**Comment by peterferrie** [comment]
Confirmed working for me.  Thanks.
