### ISSUE TITLE
démarrage

### ISSUE THREAD

**Issue by Stigmamax** [AppleWin/AppleWin#1068]
impossible d'écrire un listing. la commande list donne des colonnes de chiffres et non les lignes basic que j'ai entrées.
version 1.30.8.0
[https://www.maximages.fr/forums/divers/emu_applewin.jpg](https://www.maximages.fr/forums/divers/emu_applewin.jpg)

**Comment by audetto** [comment]
You have entered monitor (see the `*` prompt).
Applesoft Basic is `]`.

Try one of these

https://apple.stackexchange.com/questions/37546/how-to-exit-assembler-back-to-applesoft-basic-on-apple-ii-gs

**Comment by Stigmamax** [comment]
a quel moment faut-il entrer ce caractère ?

**Comment by audetto** [comment]
Deja faudrait-il savoir comment tu es arrive la.

En tout cas, cela n'a rien a voir avec AppleWin.
Si tu veux qu'on t'aide, il faut rajouter (beaucoup) plus d'information.

**Comment by Stigmamax** [comment]
c'est l'émulateur applewin - apple ][ //e version 1.30.8.0
J'ai cliqué sur Drive1 et entré un nom pour créer une disquette. C'est
juste pour recopier un vieux programme que j'avais fait en 1992.
Après je suis un peu perdu. Je me suis retrouvé avec des lignes en
assembleur 6502







____________________________________________________________________
*Cutish sur Steam <https://store.steampowered.com/app/1222170/Cutish/>*

**Comment by audetto** [comment]
copy MASTER.DSK to something else.
insert it in Disk 1.
Boot.
Write your basic program.

As I said, this is not related to AppleWin, try a real Apple ][, buy a floppy disk and put it in the drive.
You will end up in the same situation. You need to start from a valid DOS 3.3 disk to format another one. This is MASTER.DSK.

**Comment by Stigmamax** [comment]
merci pour l'aide. J'avais un vrai Apple II et je l'ai vendu cet après midi
par manque de place.







____________________________________________________________________
*Cutish sur Steam <https://store.steampowered.com/app/1222170/Cutish/>*

**Comment by audetto** [comment]
de rien

**Comment by Stigmamax** [comment]
Bon ça marche... presque.
Mais quand je tape une ligne "CLS: RANDOMIZE TIMER: KEY OFF"
il l'a transforme en "CLS:R AND OMIZETIMER:KEYOFF"

**Comment by audetto** [comment]
Je crois que vous vous tromper d'ordinateur ou de language.

Y a pas de `CLS`, pas de `RANDOMIZE` et pas de `KEY OFF` non plus, dans le APPLESOFT BASIC...

**Comment by Stigmamax** [comment]
argghhh c'est vrai. Il me faut trouver une image disk du DOS 3.3 alors.

**Comment by audetto** [comment]
MASTER.DSK contient deja le DOS 3.3.

Il vaudrait mieux lire cela: https://www.calormen.com/jsbasic/reference.html ou http://cini.classiccmp.org/pdf/Apple/AppleSoft%20II%20Basic%20Programming%20Manual.PDF

**Comment by Stigmamax** [comment]
j'ai pourtant lancé le Master.DSK
J'ai besoin de la fonction Randomize car je veux entrer un de mes vieux softs.

**Comment by Stigmamax** [comment]
ce manuel ? https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Software/Languages/Applesoft%20BASIC/Manuals/Applesoft%20II%20BASIC%20Programming%20Reference%20Manual.pdf

**Comment by tomcw** [comment]
Am I okay to close this now?
(I'll give it a few days, then close it)
