### ISSUE TITLE
WOZ: Run For It fails after selecting K/J

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1078]
Tracing back from the BRK crash...

```
0F12: JSR 0B22  ; copy "platform level" full-screen to HGR1
      JSR 0F50
      :
0F36: RTS


0F50:
      :
0F5F: JSR 0FB1
      :
0F89: RTS


0FB1:
      :
      CMP #$8D
0FB7: BNE +

+
0FC8: CMP #$A0
      BCS +  ; A >= 0xA0
      JMP 0FF9
+     CMP #$DB
      BCC +  ; A < 0xDB
      JMP 0FF9
+
0FD6:
0FF6: JMP 0FFD

0FFD:
100A: JSR 1FB8

1FB8:
1FBA: BPL 1FF7

1FF7: ASL $00
      BRK  ; crash/hang
```

**Comment by mr-stivo** [comment]
Cracking the disk with passport creates a working image. Maybe this will help with troubleshooting
![Screen Shot 2022-04-01 at 10 26 44 AM](https://user-images.githubusercontent.com/18107373/161177599-7c5d9c07-4dc3-4a1d-a7fe-0295c727c345.png)
[Run For It - Disk 1, Side A_cracked.woz.zip](https://github.com/AppleWin/AppleWin/files/8393978/Run.For.It.-.Disk.1.Side.A_cracked.woz.zip)
.

**Comment by Michaelangel007** [comment]
@Tom Back in Dec. I reversed engineered a good chunk of Run For It's codebase. Do you want me to share my debugger script/symbols?

**Comment by tomcw** [comment]
Thanks Michael, that could be very useful! Please attach here.

**Comment by Michaelangel007** [comment]
Here ya go! This is for a future "Apple Games Disassembly Project".  

You'll probably want to scroll down to:

```
// ========================================
// Functions
// ========================================
```

but there are lots of goodies in here, such as RWTS calls. :-)  I also started a list of unknown functions but that is probably less useful. Still, if you figure any out left me know.

[run_for_it.txt](https://github.com/AppleWin/AppleWin/files/8403252/run_for_it.txt)

**Comment by Michaelangel007** [comment]
Other useful stuff:

* All the variables starting with `z` are in Zero-Page
* It requires the latest version of AppleWin's Debugger  since I'm using a new `@` placeholder in `SYM` to auto-generate a function names.

i.e.
```
sym @ = 0960
```

This will autogenerate `_0960` label. That is ,it is equivalent to a manual: `sym _0960 = 960`

**Comment by tomcw** [comment]
Thanks for sharing all that work Michael - there's a lot of effort gone into all that!

**Comment by tomcw** [comment]
I figured out the copy-protection issue that was tripping up AppleWin: bit-slip using LSS reset ($C0ED).

After reading T$01,S$0F address prologue, then at $B8DC: JMP 335

```
0335:A0 20                LDY #$20          #+32
0337:8E 8D 03             STX $038D      038D:60
033A:88                   DEY                   
033B:F0 4E                BEQ $038B      038B   
033D:BD 8C C0             LDA $C08C,X    C0EC:00
0340:10 FB                BPL $033D      033D   
0342:49 D5                EOR #$D5          #-43
0344:D0 F4                BNE $033A      033A   
0346:EA                   NOP                   
0347:BD 8C C0             LDA $C08C,X    C0EC:00
034A:10 FB                BPL $0347      0347   
034C:C9 AA                CMP #$AA          #-86
034E:D0 F2                BNE $0342      0342   
0350:A0 56                LDY #$56          #+86
0352:BD 8C C0             LDA $C08C,X    C0EC:00
0355:10 FB                BPL $0352      0352   
0357:EA                   NOP                   
0358:EA                   NOP                   
0359:9D 8D C0             STA $C08D,X    C0ED:00	; reset LSS
035C:88                   DEY                   
035D:84 26                STY GBASL      0026:F5
035F:BD 8C C0             LDA $C08C,X    C0EC:00
0362:10 FB                BPL $035F      035F   
0364:BC 00 BA             LDY $BA00,X    BA60:F6
0367:A4 26                LDY GBASL      0026:F5
0369:99 00 BC             STA $BC00,Y    BC0F:00
036C:D0 EE                BNE $035C      035C   
036E:84 26                STY GBASL      0026:F5
0370:BD 8C C0             LDA $C08C,X    C0EC:00
0373:10 FB                BPL $0370      0370   
0375:BC 00 BA             LDY $BA00,X    BA60:F6
0378:A4 26                LDY GBASL      0026:F5
037A:99 00 BB             STA $BB00,Y    BB0F:0C
037D:C8                   INY                   
037E:D0 EE                BNE $036E      036E   
0380:AD 52 BC             LDA $BC52      BC52:AC	; =0xAC when we arrive at 0389
0383:29 F0                AND #$F0          #-16
0385:C9 90                CMP #$90         #-112
0387:F0 02                BEQ $038B      038B   
0389:18                   CLC                   	; OK path (A=0xA0, Y=0x00, LBR=0373) - but not a protection indicator
038A:60                   RTS                   
038B:38                   SEC         				; NG path (ie. failed to find "D5AA" data hdr)
038C:60                   RTS                   
```

Look at (T$01) S$0E vs S$0F - the latter is a mess!
(But with the bit-slip on S$0F, then these nibbles are not the actual ones read)

```
84D9:   E7   F9   FE(1)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF   D5   AA   96   FF   FE   AA   AB   AF   AE   FA   FB   DE   AA   E8(7)FF   9F	; read D5AA96 detected - Vol:FE Trk:01 Sec:0E Chk:F1 
85F9:(1)FF(2)FF(2)FF(2)FF(2)FF(1)D5   AA   AD(1)DD   CD   B4   D9   D6   CB   B7   E7   E6   97   BB   FE   BD   AC   EE   AC   9B   AB   A6   FD   F2   A7   B6   BE
8704:   DE   B3   AD   AB   9E   A6   9B   9A   A7   D6   B6   FA   ED   BF   D9   DF   A7   D6   BB   EB   BD   F7   BF   FA   ED   B6   9D   FC   D6   D6   FB   B7
8804:   B5   D7   B7   AF   E9   9F   9D   AC   97   A6   AC   B2   E9   CD   F3   F7   BC   D7   D6   BB   F5   BD   D6   B6   97   E7   EE   F6   EB   9F   A6   9F
8904:   B2   B3   BF   FC   B7   F5   DD   CB   FB   DE   F3   FA   BA   F4   BD   F3   FA   FF   EE   F5   ED   EE   E9   B2   F4   EA   CF   9F   9D   DE   F3   DF
8A04:   FB   DE   F3   CB   E7   ED   F3   FA   CE   DE   F3   DF   EE   B3   B6   EA   F2   E6   D7   9F   9E   DF   FD   9E   D6   EB   FD   F2   D9   DB   F5   DF
8B04:   E6   D7   A6   AE   E6   D7   A6   D6   CF   E6   DA   EA   FD   F2   D6   DD   F5   DF   E6   D7   A6   AE   E6   D7   A6   D6   CF   E6   EF   F3   F4   E7
8C04:   E6   D7   9F   D7   CF   E6   DE   E5   FD   F2   D6   DD   F5   DF   E6   D7   A6   AE   E6   D7   9F   D7   CF   E6   D7   EC   FD   F2   DB   D9   F5   DF
8D04:   E6   D7   9F   AF   E6   D7   A6   D6   CF   CF   E9   E6   D7   A6   A6   A6   A6   A6   A6   9F   FF   E5   BB   CB   FC   B7   B6   9A   E5   E6   D7   9F
8E04:   9D   FF   E9   BD   DF   E7   EC   A6   FF   FF   E5   BA   CF   9F   9F   A6   AE   E6   DA   DE   A6   B4   E6   FA   E5   E6   D7   A6   A6   A6   9E   DE
8F04:   A6   DF   EF   E5   F3   9E   F2   9F   AC   CD   9D   B9   FE   D6   EA   E7   E6   D7   A6   F4   B6   9A   EE   97   D3   E9   B7   E6   FA   E5   E6   D7
9004:   A6   F4   B6   9A   DF   EF   E5   F3   9E   F2   9F   AC   CD   9D   B9   FE   D6   EA   E7   E6   D7   A6   F4   B6   9A   EE   96   CF   E9   B7   B7   DE
9104:   AA   EB   F0(5)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF   D5   AA   96   FF   FE   AA   AB   AF   AF   FA   FA   DE	; read D5AA96 detected - Vol:FE Trk:01 Sec:0F Chk:F0 
9229:   AA   EC(8)FF(2)FF   FC   FF(2)FF(2)FF(2)FF(1)D5   AA   AD(1)95(2)95(2)95   95   95   95   95   95   95   95   95   95   95   95   95   95   95   95   95   95
933F:   95   95   95   95   95   95   95   95   95   95   95   95   95   95   9B(2)95   9E   9D(1)9E   95   97   9D   9E(1)9B(2)9B(2)96   9F(2)9B(2)9B(1)97(1)9B   97
944D:   9B(1)97(1)9B(2)97   95   95   9D(1)9D(2)9B(1)97(2)9B   97   9B(1)97(2)9B(2)97   9D(2)9B   96(1)9B   9F(1)9B(1)9E   95   97   9E   9E(1)9B(2)9E(1)9B   9B(1)9B
9566:(1)9D(2)96(1)9B(1)97(2)9D   96(1)97   9E   9B   97   97   9E(1)9D(1)97   95   95   9D(1)95   95   95   9D(1)96   96(1)9E   9F(1)9F(1)96   95   9B(1)97(1)9B   97
9677:   9B(1)97(1)9B(2)97   95   95   9D(1)9D(2)9B(1)97(2)9B   97   9B(1)97(2)9B(2)97   9D(2)9B   96(1)9B   9E(1)9B   97   9D   9B   97   9B(1)97(2)9D   96(1)9E(1)9B
978F:   97   9E(1)9B   97   9B(1)97(2)9D   96(1)95   95   9D(1)95   9B(2)95   9B(2)97(2)9B   97   95   95   9D(1)9D(2)9E   9E(1)9E   95   97   9D   9E(1)9B(2)9B(2)96
98A4:   9F(2)9B(2)9F(1)9B(1)9E   95   97   9E   9E(1)9B(2)9E(1)9B   9B(1)9B(1)9D(2)96(1)9B(1)97(2)9D   96(1)97   9E   9B   97   97   9E(1)9D(1)97   95   95   9D(1)95
99BA:   95   95   9D(1)96   9B(1)97(2)9B   97   9B(1)9B(1)9D(1)97   9B(1)97(1)9B   97   9B(2)95   95   9D(2)9B(1)9B   9D(1)97   96(1)9E   9F(1)9F(1)96   95   97   9D
9ACC:   9B   97   9B(1)97(2)9D   96(1)9E(1)9B   97   9E(1)9B   97   9B(1)97(2)9D   96(1)95   95   9D(1)95   97(2)97(1)9F(1)95   9B(2)97(2)9D(1)97   9F   FF   FF   FF
9BE0:   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF
9CE0:   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   FF   EE(1)F0(1)F3   C0   DF   CF   F3   FC   FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF
```

Anyway, I have something slightly wrong with the LSS reset emulation.

**Comment by Michaelangel007** [comment]
> Thanks for sharing all that work Michael - there's a lot of effort gone into all that!

Thanks.  I was bored for a week, hehe. =P

While it isn't that good of a game it was one of the games I played as a kid and so it struck my curiosity and am I finally making my way through my back-log of games.  I have a half-a-dozen games I want to reverse engineer.

I'm still new to `.WOZ`. I had to look up `LSS` = Logic State Sequencer.  I probably should spend more time reading Sather. =P

That's definitely a funny use of Q6H load data latch, no?

Here is my DOS3.3 annotated source showing the equivalent [READ16](https://htmlpreview.github.io/?https://github.com/Michaelangel007/apple2_dos33/blob/master/dos33.html#READ16) section for reference.

OT: While this isn't directly relevant there is some interesting stuff in the 1987 [SWIM Chip User's Reference](http://bitsavers.trailing-edge.com/pdf/apple/disk/sony/SWIM_Chip_Users_Ref_198801.pdf).  It discusses GCR Encoding, MFM Encoding, Trans-Space Machine, 

NOTE: SWIM = Sander-Wozniak Integrated Machine = IWM (Integrated Woz Machine) + ISM (Integrated Sander Machine).

**Comment by mr-stivo** [comment]
Maybe this can help your troubleshooting. Tracing the boot on my emulator, it hits $0359 two times. When it sets the sequencer back to shift mode at $035F the data register should equal (on my emulator at least) $F0.

`0359: 9D 8D C0   STA $C08D,X (absolute,x)    A=0xAD X=0x60 Y=0x56 sp=0x1F2   flags=0xB5 [Nv-BdIzC]   data_reg=04
035C: 88         DEY                         A=0xAD X=0x60 Y=0x55 sp=0x1F2   flags=0x35 [nv-BdIzC]   data_reg=04
035D: 84 26      STY $26 (zeropage)          A=0xAD X=0x60 Y=0x55 sp=0x1F2   flags=0x35 [nv-BdIzC]   data_reg=C1
035F: BD 8C C0   LDA $C08C,X (absolute,x +)  A=0xF0 X=0x60 Y=0x55 sp=0x1F2   flags=0xB5 [Nv-BdIzC]   data_reg=F0


0359: 9D 8D C0   STA $C08D,X (absolute,x)    A=0xAD X=0x60 Y=0x56 sp=0x1F2   flags=0xB5 [Nv-BdIzC]   data_reg=04
035C: 88         DEY                         A=0xAD X=0x60 Y=0x55 sp=0x1F2   flags=0x35 [nv-BdIzC]   data_reg=04
035D: 84 26      STY $26 (zeropage)          A=0xAD X=0x60 Y=0x55 sp=0x1F2   flags=0x35 [nv-BdIzC]   data_reg=C1
035F: BD 8C C0   LDA $C08C,X (absolute,x +)  A=0xF0 X=0x60 Y=0x55 sp=0x1F2   flags=0xB5 [Nv-BdIzC]   data_reg=F0`

**Comment by mr-stivo** [comment]
It noticed a non write protected woz will boot ok in AppleWin but I asked original poster about it and he said the original disk is write protected and boots ok on real hardware.

Setting a breakpoint at $0362, setting A to $F0 and setting N gets the write protected version to boot ok in AppleWin.

My emulator's LSS implementation is much different than yours and I'm a bit rusty when it comes to the LSS behavior but I'm wondering if when AppleWin executes `STA $C08D,X`, is it/should it continuously shift right the write protect status into the data register (2 times every CPU cycle) until it executes `LDA $C08C,X`?

[Run For It - Disk 1, Side A_not_wp.woz.zip](https://github.com/AppleWin/AppleWin/files/8410817/Run.For.It.-.Disk.1.Side.A_not_wp.woz.zip)

**Comment by sicklittlemonkey** [comment]
Yeah, that should approximate the correct behaviour. AppleWin doesn't
actually emulate the individual sequencer operations.

**Comment by mr-stivo** [comment]
> Yeah, that should approximate the correct behaviour. AppleWin doesn't actually emulate the individual sequencer operations.
> […](#)

Maybe just setting the data register to $FF when $C0ED is accessed since the number of cycles between a `STA $C08D,X` and a `LDA $C08C,X` is likely enough that the sequencer would fill it with 1's anyways. Just a thought.

**Comment by tomcw** [comment]
I also found that if I keep the LSS "reset" for longer (eg. skip 3 bit-cells instead of 1 bit-cell) then it works correctly.

>It noticed a non write protected woz will boot ok in AppleWin but I asked original poster about it and he said the original disk is write protected and boots ok on real hardware.

I think the game should still work when _not_ write-protected. The reason is that there's a high score table. So presumably high scores can be saved to disk. NB. I can't get this to work though :-/

**Comment by mr-stivo** [comment]
I was thinking the minimum number of cycles between $C0ED and $C0EC appearing on the address bus in any normal situation would be 4. Depending on how quickly the LSS responds, that would be 8 or 9 LSS cycles. If the disk is write protected or not we would shift right in 1 or 0 at least 8 times leaving the data register as $FF for write protected and $00 for not write protected. So I was thinking when $C0ED was accessed, just set the data register to $FF if write protected or $00 if not and this shouldn't have any impact on other disks since it's closer the the actual behavior of the real hardware.

Of course, this was just what I was thinking. =)  It's an interesting problem for a lightweight LSS implementation... fun to think about.

This was from Visual 6502:
cycle | ab | db | rw | Fetch | pc | a | x | y | s | p
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0000 | 8d | 1 | STA Abs | 0000 | aa | 00 | 00 | fd | nv‑BdIZc
1 | 0001 | ed | 1 |   | 0001 | aa | 00 | 00 | fd | nv‑BdIZc
1 | 0001 | ed | 1 |   | 0001 | aa | 00 | 00 | fd | nv‑BdIZc
2 | 0002 | c0 | 1 |   | 0002 | aa | 00 | 00 | fd | nv‑BdIZc
2 | 0002 | c0 | 1 |   | 0002 | aa | 00 | 00 | fd | nv‑BdIZc
3 | c0ed | c0 | 0 |   | 0003 | aa | 00 | 00 | fd | nv‑BdIZc
3 | c0ed | aa | 0 |   | 0003 | aa | 00 | 00 | fd | nv‑BdIZc
4 | 0003 | ad | 1 | LDA Abs | 0003 | aa | 00 | 00 | fd | nv‑BdIZc
4 | 0003 | ad | 1 | LDA Abs | 0003 | aa | 00 | 00 | fd | nv‑BdIZc
5 | 0004 | ec | 1 |   | 0004 | aa | 00 | 00 | fd | nv‑BdIZc
5 | 0004 | ec | 1 |   | 0004 | aa | 00 | 00 | fd | nv‑BdIZc
6 | 0005 | c0 | 1 |   | 0005 | aa | 00 | 00 | fd | nv‑BdIZc
6 | 0005 | c0 | 1 |   | 0005 | aa | 00 | 00 | fd | nv‑BdIZc
7 | c0ec | 00 | 1 |   | 0006 | aa | 00 | 00 | fd | nv‑BdIZc
7 | c0ec | 00 | 1 |   | 0006 | aa | 00 | 00 | fd | nv‑BdIZc

**Comment by tomcw** [comment]
A quick test with a write-protected disk in the drive.
```
  LDA $C0EA ; Select drive 1
  LDA $C0E9 ; Selected drive on
-     LDA $C0EC ; Wait until we read 0xD5 from latch
      BPL -
    CMP #$D5
    BNE -
  LDA $C0EC ; Immediately read latch into A (so high bit won't be set)
  STA $C0ED ; Read write protect
  LDX $C0EC ; Read latch into X
```

The second test reads the data latch twice (into A and X), before reading the write protect state into Y.

Test # | AppleWin | //e |
-- | -- |--
1 | ![Run For It - Disk 1, Side A_wp_000000000](https://user-images.githubusercontent.com/6696896/163856001-1684ae6e-3ad3-4558-a332-1361eee25320.png) | ![DSC_2491](https://user-images.githubusercontent.com/6696896/163856027-cba723ee-636f-4f8e-a00b-44e7c9896343.JPG)
2 | ![Run For It - Disk 1, Side A_wp_000000001](https://user-images.githubusercontent.com/6696896/163856100-e6c33c00-dd28-4e4b-8d79-8108857acae0.png) | ![DSC_2492](https://user-images.githubusercontent.com/6696896/163856118-eb108337-850f-4ff4-87b3-b72c7765e2fd.JPG)

@mr-stivo said:

>Maybe just setting the data register to $FF when $C0ED is accessed since the number of cycles between a `STA $C08D,X` and a `LDA $C08C,X` is likely enough that the sequencer would fill it with 1's anyways. Just a thought.

Yes, it looks like I should be doing that.

My reading of Sather (page 9-21) was that only bit7 (called "QA") would have the write protect bit shifted in (from the right), and not that the whole 8-bit data register gets shifted right. eg, he says:
- "...and idly shifts the state of the write protect switch **right** into the data register..."
- "...shifts the state of the write protect switch into QA of the data register, ..."

But I see now (eg. 9-14): "The **data register** is a very versatile 8-bit IC that can shift left, shift right,..." + also Fig. 9.7 lists "SHIFT RIGHT" as a Data Reg. Control.

**Comment by tomcw** [comment]
btw, "Stickybear Town Builder" (from John's WOZ TEST IMAGES) also has identical protection - eg. at $359.
At the time I just assumed the disk needed to be writeable.

**Comment by tomcw** [comment]
Regarding the copy-protection, there is a slightly different code path depending on whether the disk is write protected or not.

The write-protected path reads an extra nibble in the routine at $335 (see above), and then this is compensated in the later routine at $3AB. The data is de-synchronised (so $C0ED is accessed to reset the LSS, and re-sync), and also the read of the data latch with write-protect status (eg. $FF) gets included in the nibblized data!

So after calling the $335 routine to read T$01,S$0F, some time later there's code at $38E which decodes the nibblized data read from T$01,S$0F. Specifically in the subroutine at $3AB it checks the write protect status again, setting a counter at $02 depending on the WP status:

```
3AB
        :
	ldy #$55
	lda	$fbc0	; VERSION3: differentiate between IIe & IIc(=0x00)
	beq +

	ldx $038d	; X=0x60
3BB	lda $c08d,x
	lda $c08e,x
	bpl +
	dey
+	sty $02		; ($02) = 0x55 (not write-protected) or 0x54 (write-protected)
```

Here's the full routine:

```
3AB ; entrypoint
	tya
	pha
	cmp #$87	; Initial value from $38E
	bne ++		; 3ca

	ldy #$55
	lda	$fbc0	; VERSION3: differentiate between IIe & IIc(=0x00)
	beq +

	ldx $038d	; X=0x60
3BB	lda $c08d,x
	lda $c08e,x
	bpl +
	dey
+	sty $02		; ($02) = 0x55 (not write-protected) or 0x54 (write-protected)

	ldx #0
	stx $01

	;

++	ldy $02

	ldx $01
	bmi +	; 3dc

	ldx $bbff,y		; X=0xAC
	dey
	bne ++
	
	lda	#$ff
	sta $01
	bne ++	; == bra 3e0

+	ldx $bb00,y
	iny

++	sty $02
	
	pla
	tay
	lda $033c,x	; return A (b3:0)
	rts

=======================================

38E	ldy #$87
	jsr $3ab
	dey
-		jsr $3ab
		asl
		asl
		asl
		asl
		sta $00
		jsr $3ab
		ora $00
		sta ($3e),y	; (3e)=$2000
		tya
		dey
		cmp #0
		bne -
	rts
```

**Comment by tomcw** [comment]
Some simply code to test reading the write-protect (mimicking Run For It)...

0300:A2 60 AD EA C0 AD E9 C0 AD EC C0 10 FB C9 D5 D0 F7 EA EA 9D 8D C0 88 84 FF AD EC C0 AE EC C0 AC EC C0 00 00 00 00 00 00

Results on real h/w:

![DSC_2492](https://user-images.githubusercontent.com/6696896/164916978-70c5fdec-d937-43ff-b5e2-3752d16412a0.png)
![DSC_2493](https://user-images.githubusercontent.com/6696896/164916983-c2b4edf2-7e1b-469d-9e4a-62297a487a2e.png)

**Comment by tomcw** [comment]
@mr-stivo:

>When it sets the sequencer back to read/shift mode at $035F the data register should equal (on my emulator at least) $F0.

The first read of the data latch is always $FF (and sometimes the 2nd too), as you can see from my real h/w results above.

**Comment by mr-stivo** [comment]
@tomcw 

I realized it should be $FF after posting that. My emulator's default lightweight LSS was coming up with $F0- enough 1's to make Run For It happy but not the correct result. I also have an optional P6 rom based LSS that was coming up with $FF. The difference was bothering me so I reviewed Sather's information again and realized the $FF result is the correct one. In my case, my lightweight LSS was shifting right only one time per cpu cycle when it should have been shifting right two times per cycle. To fix it I now right shift in two bits per cycle ($C0 for write protected) and now my results are correct.

That code above is very useful for testing the write protect behavior, thanks for posting it.

**Comment by tomcw** [comment]
After 93ea5b3, here's the output from AppleWin with the [above short bit of code](https://github.com/AppleWin/AppleWin/issues/1078#issuecomment-1107538406)...

Write-protected disk:
![Run For It - Disk 1, Side A_wp_000000000](https://user-images.githubusercontent.com/6696896/164987549-78563f30-ce23-434c-83d2-9cc1e206e100.png)

Not write-protected disk:
![Run For It - Disk 1, Side A_not_wp_000000000](https://user-images.githubusercontent.com/6696896/164987551-f36e5803-a947-4360-991c-5948cf05a5d2.png)

So AppleWin doesn't ever give the double $FF (for the write-protected case), but this is probably close enough.
Since this fixes "Run For It", I'm closing this issue.

**Comment by sicklittlemonkey** [comment]
Thanks for all the examples Tom, and well done.
I must admit I'm surprised that lower-level emulation of the LSS hasn't been needed.
But I suppose copy protection can't be *too* demanding, timing-wise. ; - )

**Comment by tomcw** [comment]
btw, (note to self) I reverted to using 0x80 instead of 0xFF for the value in the data latch when the disk is write protected. So in this code...
```
0359:9D 8D C0             STA $C08D,X    C0ED:00	; reset LSS
035C:88                   DEY                   
035D:84 26                STY GBASL      0026:F5
035F:BD 8C C0             LDA $C08C,X    C0EC:00
```
...it immediately reads $80 from the data latch.

And the game still boots 100% of the time!

So I think the real fix was here where it uses up remaining cycles in `checkWriteProtAndInitWrite` mode:
https://github.com/AppleWin/AppleWin/blob/a5c41dd8ca40944f3a2fbaa6bea99f188883dfdd/source/Disk.cpp#L1794-L1797
