### ISSUE TITLE
Support Mockingboard and Mouse at same time

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1080]
The use-case is this new game: [Witch Trial](http://www.golombeck.eu/index.php?id=57&L=1)

A quick hack could be to support Phasor (slot 4) and Mouse (slot 5), but I'd need to check if the game supports the mouse interface in slot 5.

Longer term I am refactoring the MB/Phasor support so that it's not hardcoded to slots 4/5, and can be put into any slot.
And we'll need a better Config GUI too (#853).

**Comment by mgolombeck** [comment]
Mouse interface is supported in any slot but 3 I think so support in slot 5 would be fine. Would be nice to have a choosable support of only one mockingboard in slot 4 or 5. 

Von meinem iPhone gesendet

**Comment by tomcw** [comment]
Thanks for confirming this, Marc.
I think Witch Trail (which looks great, btw), is the first title ever to use both Mockingboard and Mouse!

**Comment by tomcw** [comment]
With the refactor done in 71c67cf this now allows slot4=Mouse card and slot5=Mockingboard (or Phasor) card.
I've tested it works with _Witch Trial_.

When I do the next AppleWin release (still TBC) then this will be supported.

**Comment by tomcw** [comment]
NB. New [AppleWin 1.30.14.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.14.0) release now supports Mouse card & Mockingboard at the same time.
