### ISSUE TITLE
Uthernet II: TCP socket is closed with WSAECONNRESET just before its natural end

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1095]
(Spun off from #518)

@audetto said:

Oliver reported an issue whereby the TCP socket is closed with WSAECONNRESET just before its natural end, so the last few seconds of the stream are lost.

The suspect is that this only happens on a non-virtualised Windows PC (which I don't have right now), and so far have been unable to replicate, nor do we have any idea why this happens.

There are not enough data points to pin point anything in particular.

**Comment by audetto** [comment]
Oliver found a possible explanation with a problem on Microsoft side

<<<
Maybe/likely there's no real issue at all. When looking through the Google hits on the topic, I went by https://support.microsoft.com/en-us/topic/an-application-may-receive-the-10054-error-when-the-application-receives-data-from-a-connection-on-a-computer-that-is-running-windows-7-or-windows-server-2008-r2-if-a-tdi-filter-driver-is-installed-73fd74a9-51c2-3663-e965-e1187b1cfc92 and read the sentence:

A Transport Driver Interface (TDI) filter driver is installed on the computer. For example, a TDI filter driver is installed when you install McAfee VirusScan.
>>>

No other machine has demostrated the same error.

**Comment by tomcw** [comment]
I assume from the MS article that @oliverschmidt is running on Windows 7 (or Server 2008 R2), and with (eg) McAfee or something else that installs a TDI filter driver.

I have tested a few a2streams on AppleWin running on a Win7-64 machine (using A2Stream v1.2 so I can quickly fast-forward to near the end):
http://a2retro.de/OA01/OA-001.a2stream
http://a2retro.de/OA04/OA-KFest13-Woz.a2stream

NB. I don't have McAfee installed.

When listening to them, they both sound like they finish correctly before returning to the A2Stream frontend.

Ideally I can just close this issue as being a Win7 & McAfee related issue.

---

Where would I expect to see the WSAECONNRESET error?
I guess in function `tfe_arch_receive_frame()` after calling `p_pcap_dispatch()` ?
So would I just extend the code so that on a failure, it calls `WSAGetLastError()` ?


btw, I'm reading the description for `pcap_dispatch()` [here](https://www.winpcap.org/docs/docs_412/html/group__wpcapfunc.html#ga60ce104cdf28420d3361cd36d15be44c), and it says that:

>The number of packets read is returned. 0 is returned if no packets were read from a live capture (if, for example, they were discarded because they didn't pass the packet filter, or if, on platforms that support a read timeout that starts before any packets arrive, the timeout expires before any packets arrive, or if the file descriptor for the capture device is in non-blocking mode and no packets were available to be read) or if no more packets are available in a ``savefile.'' A return of -1 indicates an error in which case [pcap_perror()](https://www.winpcap.org/docs/docs_412/html/group__wpcapfunc.html#gac3b6784c6c2623b93b22f6f219bd470e) or [pcap_geterr()](https://www.winpcap.org/docs/docs_412/html/group__wpcapfunc.html#ga81305cb154e4497e95bbb9b708631a3a) may be used to display the error text. A return of -2 indicates that the loop terminated due to a call to [pcap_breakloop()](https://www.winpcap.org/docs/docs_412/html/group__wpcapfunc.html#gae0dc50910fabbd375fab8a1352a6cf33) before any packets were processed. If your application uses [pcap_breakloop()](https://www.winpcap.org/docs/docs_412/html/group__wpcapfunc.html#gae0dc50910fabbd375fab8a1352a6cf33), make sure that you explicitly check for -1 and -2, rather than just checking for a return value < 0.

But the code just checks the return value for "not equal to zero", ie:

https://github.com/AppleWin/AppleWin/blob/93ea5b3e60e840a396bdead6e98ccd190a4f4020/source/Tfe/tfearch.cpp#L458-L461

We don't use `pcap_breakloop()`, but it sounds like a return value of -1 is possible.
So I think this code should be changed to "greater than zero" for success.

**Comment by oliverschmidt** [comment]
> I assume from the MS article that @oliverschmidt is running on Windows 7

I'm running Windows 10.

> No other machine has demostrated the same error.

For that very reason I personally would suggest to not further invest effort into this issue. I personally would consider https://github.com/AppleWin/AppleWin/issues/1088 much more worth of having effort invested to.

Just my two cents,
Oliver

**Comment by audetto** [comment]
Agreed. We should close.

For completeness and if anyone ever hit it again, we could just add that the error comes from the TCP stack, not pcap.

https://github.com/AppleWin/AppleWin/blob/93ea5b3e60e840a396bdead6e98ccd190a4f4020/source/Uthernet2.cpp#L659

And Oliver has generated a pcap log file with this issue. Is it ok to add it here?

**Comment by oliverschmidt** [comment]
> And Oliver has generated a pcap log file with this issue. Is it ok to add it here?

At least from my POV, that's perfectly fine.

**Comment by audetto** [comment]
[Levels.pcap.zip](https://github.com/AppleWin/AppleWin/files/8584096/Levels.pcap.zip)

Packets 4830-4831 are suspicious.

**Comment by tomcw** [comment]
I fixed the very minor issue with `pcap_dispatch()` - and agree with closing this issue too.
