### ISSUE TITLE
Adventure Construction Set: cannot create adventure disks successfully with 2 drives

### ISSUE THREAD

**Issue by Newsdee** [AppleWin/AppleWin#1117]
Adventure Construction Set has a feature to create new game disks to play. 
When I try to create a new game disk for "Rivers of Light", I can only get it to work when using a single disk drive.

If I use two disk drives:
- With "original" disk drive speed, the adventure is not recognized to play (it keeps asking me to insert the adventure disk)
- With "enhanced" disk drive, it seems to run but the resulting game has no text (no screen title, no instructions, etc)

It works successfully only when I use one disk drive and swap disks to create the adventure.
On original hardware though, two disk drives worked fine (that's how I played ACS back in the day)

Let me know if you'd like me to attach disk images.

**Comment by Newsdee** [comment]
I should add that all the images (including the blank disk to be formatted) are in .nib format

**Comment by tomcw** [comment]
Firstly which version of AppleWin are you using?

The .nib format could be a red flag here, as it's a terrible disk image format, with subtle issues and limitations.
Can you try .woz instead?

You can create a blank (ie. unformatted) .woz by just clicking the 'Drive 2' icon, and a filename (with a .woz extension) that doesn't exist, eg. "NewGame.woz". (If you need to INIT/format the disk, then see 'Creating Disk Images' in the AppleWin.chm help doc)

**Comment by Newsdee** [comment]
I tested with a blank WOZ image on drive- 2, and it didn't work for either enhanced or authentic speeds.
In both cases, it creates an adventure disk that runs, but has blank text (so doesn't show anything on screen in title and character creation screen). A new .woz image works with a single drive, though.

**Comment by tomcw** [comment]
Thanks. Useful info about blank woz.

Which version of AppleWin are you using?
Which ACS images are you using? (provide a link)

**Comment by Newsdee** [comment]
I'm using 1.29.16.0 (latest stable as per the github readme)

I got the disks from  here (archive of all ACS games); under the "Apple II\00 Master disks\" folder:
https://drive.google.com/file/d/1GmwfKkU3FG2L988ZKpYiLCns70CL64Lq/view

**Comment by tomcw** [comment]
I downloaded the "ACS Project v1" archive, and tried to reproduce the issue using: "ACS Program Disk Side 1 (Main Master).dsk", but it is working for me for all these combinations:

(All with: 2 drives, "enhanced" disk drive speed)

1. AppleWin 1.29.16.0, blank.dsk
2. AppleWin 1.29.16.0, blank.nib
3. AppleWin 1.30.11.0, blank.dsk
4. AppleWin 1.30.11.0, blank.nib
5. AppleWin 1.30.11.0, blank.woz

For all cases, my repro steps are:

0. Boot from "ACS Program Disk Side 1 (Main Master).dsk"
1. Select '2' for 2 Disk Drives (and SPACE for keyboard control)
2. 'M' to Make an adventure disk
3. Select "Rivers of Light"
4. When instructed, insert "ACS z Data Disk Side 2 (Main Master).dsk" into drive-1
6. When instructed, insert a blank, unformatted .dsk or .nib or .woz (for AppleWin 1.30.0 or higher) into drive-2
7. When instructed, insert "ACS Program Disk Side 1 (Main Master).dsk" into drive-1
8. "The adventure disk is ready!" (SPACE to continue)
9. 'P' to Play an adventure
10. "Put your adventure disk in drive two"... it's already in drive-2 from the 'M'ake operation
11. Display shows: "Rights of Light,  by Stuart..." + Mockingboard tune playing (SPACE)
12. Display shows: "Rights of Light. Are we each destined to live..." + Mockingboard tune playing (SPACE)
13. Create new player, then "The action moves to the fertile crescent"
14. I can SAVE GAME, and reboot, and restart playing this adventure with my newly created character

btw. I've now updated AppleWin's "latest stable release" to 1.30.10.0.
(The very latest version is 1.30.11.0, but this was only released a few days ago, so I will give this more time before making this the "latest stable release", but equally there's no reason not to use this _very latest_ version.)

**Comment by tomcw** [comment]
@Newsdee - basically I can't reproduce this.
Can you try with AppleWin 1.30.11.0?
Can you check my repro steps, and let me know where things diverge for you?

**Comment by Newsdee** [comment]
Yes - I confirm - the new version fixed it. Thanks!

**Comment by Newsdee** [comment]
Tested that the scenario creates the disk succesfully

**Comment by tomcw** [comment]
Glad you got it working.

>Tested that the scenario creates the disk succesfully

btw, what type of disk image did you use in the end? (DSK, NIB or WOZ?)
