### ISSUE TITLE
emulated-memory corruption sometimes crashes AppleWin

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1126]
[KARATEKA.zip](https://github.com/AppleWin/AppleWin/files/9455284/KARATEKA.zip)

1. Place this under /DEMO in Total Replay
2. Boot Total Replay
3. Press "K", "R", Space, Right arrow, to start demo
4. AppleWin sometimes exits.

**Comment by tomcw** [comment]
Thanks Peter - I can repro this AppleWin crash bug, with an unprotected .woz in drive-1.

FYI, the A2 code touches $C0EE (Disk II controller's writeMode=off) to cause the crash:

![crash](https://user-images.githubusercontent.com/6696896/187528805-4bb674b2-128e-458f-94ac-3a029b7879ec.png)

The AppleWin crash occurs if the _very first_ Disk II controller I/O accesses are:
- $C0EF: writeMode=on
- $C0EE: writeMode=off... crash

**Comment by peterferrie** [comment]
Thanks Tom.  I would have never found the cause.  It was unpredictable
in my case if it would crash or just switch to weird graphics modes.

**Comment by tomcw** [comment]
Fixed - but @peterferrie if you need a new build then just let me know. (Otherwise there's nothing planned for a few weeks or so.)

**Comment by tomcw** [comment]
Officially fixed in this new [AppleWin 1.30.12.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.12.0).

**Comment by peterferrie** [comment]
Thanks.  I don't need a build.  I fixed my bug, too.
