### ISSUE TITLE
debugger: search range off by one?

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1127]
example, s 0:1fff dd
will search only 0..1ffe.  I expected it to look at 1fff, too.
If it's intentional, then I'll have to be more careful.

**Comment by peterferrie** [comment]
> The notation you are using is `s <address-start>:<length> <hex>`, so for the
> specific example you gave, with a length of 1fff it will only search
> [0...1ffe].

':' appears to be interpreted as an end address, unless there's a parsing issue.
4000:A9 41 85 01
S 4000:4003 1
returns no found, but.
S 4000:4004 1
returns 4003.

So, I should stop using ':' as the end address?

> There is alternate notation (using comma instead of colon) which is: `s
> <address-start>,<address-end> <hex>`, which should search [0...1fff].

Okay, I will switch to that.

> But when I tried this _there is_ an off-by-one bug.
> So let me get this fixed, and then supply you with an update.

Thanks.

**Comment by tomcw** [comment]
>':' appears to be interpreted as an end address

Yes, you're right (I got it backwards)...

![help-s](https://user-images.githubusercontent.com/6696896/187988902-929e265c-3694-4fc5-ab33-66645221f539.png)

Regardless, there's still an off-by-one bug.

**Comment by tomcw** [comment]
Repro:

4000:A9 41 85 01
40FE:A9 41 85 01

; Quick tests for "found" case
s 4000:4003 1
s 4000,4 1
s 40FE:4101 1
s 40FE,4 1

; Quick tests for "not found" case
s 4000:4002 1
s 4000,3 1
s 40FE:4100 1
s 40FE,3 1

**Comment by tomcw** [comment]
@peterferrie - here's a point-release which fixes #1126 and this one:
[AppleWin-1.30.11.1.zip](https://github.com/AppleWin/AppleWin/files/9472764/AppleWin-1.30.11.1.zip)

Can you give it a go, and confirm that it fixes things for you? (I'll do a proper release soon)

**Comment by peterferrie** [comment]
Yes, working for me.  Thanks!

**Comment by tomcw** [comment]
Closing as confirmed as fixed.

**Comment by tomcw** [comment]
Officially fixed in this new [AppleWin 1.30.12.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.12.0).

**Comment by Michaelangel007** [comment]
@tomcw Thanks for fixing this off-by-one bug.

@peterferrie I've been using the `:` notation for decades.  It should be inclusive as documented with the examples.
