### ISSUE TITLE
Video mode: Color (PAL Monitor) rendering bottom TEXT lines for Rainbow

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1131]
The corrupted lines are shimmering.
NB. Also been an issue from when PAL color-killer was added at 1.29.14.0

![Tests-Various_Rainbow](https://user-images.githubusercontent.com/6696896/192112163-a30886f0-aa09-4a23-a554-a7fa36ff8d99.png)

cf. #1119

**Comment by tomcw** [comment]
After fixing the floating-bus issue (when mixed mode and vert >=160) - 9df0ea1e21d7ba8cfbadc2cf1a74c0c30a61f7f6, it now displays like this (stable, not shimmering):

![Tests-Various_000000001](https://user-images.githubusercontent.com/6696896/193475150-6d71dd18-ffe1-46b9-8609-c340e2ae5de4.png)

**Comment by tomcw** [comment]
Fixed by not re-enabling color-burst in mixed mode & vert >= 160:

![Tests-Various_000000000](https://user-images.githubusercontent.com/6696896/193475751-aa71f74e-9d0b-4512-84b2-5fd992afd9dc.png)

**Comment by tomcw** [comment]
BASIC code:
```
fill $0400..07FF with $00	;  color=0
fill $2000..3FFF with $80	; hcolor=4

v=052 color=01
v=053 color=01
v=054 color=01 	hcolor=5
v=055 color=01 	hcolor=5

v=056 color=13
v=057 color=13
v=058 color=13 	hcolor=1
v=059 color=13 	hcolor=1

v=060			hcolor=6
v=061			hcolor=6

v=062			hcolor=2
v=063			hcolor=2

;

v=118			hcolor=0 (0,100)	; what's this for? (Apple II?)
v=119			hcolor=0 (0,100)	; what's this for?
v=122			hcolor=0 (0,100)	; what's this for?
v=123			hcolor=0 (0,100)	; what's this for?

A = 9200		; $23F0
B = 13168		; $3370
FOR I = 0 TO 7: POKE A + I,0: POKE B + I,0: NEXT
[3370..3377] = 0	; v=052, h<018  -- these 8 addrs are in the MIXED visible area
[23F0..23F7] = 0	; v=056, h<021  -- these 8 addrs are in the MIXED visible area
```

I can remove the 4 "hcolor=0" lines at v=118,119,122,123 and it still works OK. (Perhaps it's for the original Apple II?)

**Comment by tomcw** [comment]
ASM code:
```
0300:AD 57 C0             LDA $C057   
0303:AD 53 C0             LDA $C053   
0306:AD 54 C0             LDA $C054   
0309:AD 50 C0               LDA $C050   ; Read floating bus (GRAPHICS on / TEXT off)
030C:D0 FB                  BNE $0309   

; wait 2 scanlines (130 cycles)
030E:AD 56 C0             LDA $C056    ; switch from HGR to GR
0311:A0 16                LDY #$16    
0313:88                     DEY         
0314:D0 FD                  BNE $0313   

0316:EA                   NOP         
0317:AD 57 C0             LDA $C057    ; switch from GR to HGR
031A:4C 09 03             JMP $0309   
```

**Comment by tomcw** [comment]
Set breakpoint at $30E  (bp 30e)

#### NTSC //e hits this at vert(dec) positions:
; rainbow effect for the 2x double-line GR rows:
v=52
v=56

; mid-screen, below rainbow, and in visible area:
v=118
v=122

; MIXED from v=160:
v=160
v=162
 :
v=238
v=240
 :
v=260

#### PAL //e hits this at vert(dec) positions:
; rainbow effect for the 2x double-line GR rows:
v=52
v=56

; mid-screen, below rainbow, and in visible area:
v=118
v=122

; MIXED from v=160:
v=160
v=162
 :
v=238
v=241	; different to NTSC from here
v=243
 :
v=311

NB. it doesn't matter about the hits in MIXED (v>=160), since MIXED take precedence over HGR (ie. it stays in TEXT mode).

And the mid-screen GR/HGR switches at v=118 and v=122 don't matter since this area if black for both GR and HGR screen.

**Comment by xotmatrix** [comment]
```
v=118			hcolor=0 (0,100)	; what's this for? (Apple II+?)
v=119			hcolor=0 (0,100)	; what's this for?
v=122			hcolor=0 (0,100)	; what's this for?
v=123			hcolor=0 (0,100)	; what's this for?
```
Those four `HCOLOR=0` lines are indeed for the Apple ][+. The hide this artefact.

![2022-10-08_15-47-36](https://user-images.githubusercontent.com/14209329/194725506-10bc624c-b87b-4656-ae82-6414d43dd35a.png)

**Comment by tomcw** [comment]
Hmm... when I remove the 4 "hcolor=0" lines at v=118,119,122,123(*), I'm not seeing that artifact under AppleWin emulation (for Apple II+ NTSC or PAL).

I know AppleWin's  Apple II+ video emulation isn't perfect for video mode switching - Deater has mentioned this before.

(*) In the BASIC version of the code I have, this means just remove BASIC lines 140 and 150.

**Comment by xotmatrix** [comment]
This isn't a mode switch glitch. This is caused by horizontal blanking differences in the Apple II+ and Apple IIe machines.

```
10  HGR
20  REM  SET RIGHT COLUMN PIXEL
25  REM  HCOLOR=1,3,5,7
30  HCOLOR= 1
35  HPLOT 279,0 TO 279,191
40  REM  SET LEFT COLUMN PALETTE
45  REM  HCOLOR=4,5,6,7
50  HCOLOR= 4
55  HPLOT 0,0 TO 0,191
```

**Comment by tomcw** [comment]
Thanks @xotmatrix for the range of examples and the explanation.
That example from _The Thing_ is really interesting! Great spot!

This now makes sense. I just need to get my "Apple II europlus" working to check this - although from what you say on Twitter, perhaps this got fixed in later II+ models:
>It looks like it may have also been fixed in the RFI revision of the Apple II and possibly Rev 7. Both have altered video generation logic.

And re.

>However, I think the point of the `HCOLOR=0` lines is just to hide the magenta artifacts on an early Apple II, though they may also be used as sentinel values for the timing loop. I didn't examine the disassembly.

Yes, I agree: it seems it's just to hide the artifacts (and are not sentinel values for the timing loop).

btw, in investigating the Rainbow code, it motivated me to add new AppleWin debugger commands: (in the next release)
- `bpv vpos`   : break when video scanner is at vpos
- `wa # v`      : add watch # to show video scanner's next data (main data + depending on mode: aux data for 14M or SHR)

**Comment by xotmatrix** [comment]
Nice. This gave me the same impulse to add video scanner registers to my own emulator's debugger.

I'm just guessing about it being fixed before the Apple //e. They do have different circuits but that's all I know. I have a Rev 7 in my closet I will check. I wish I had room to have everything set up at once.

**Comment by tomcw** [comment]
Thanks - I'll update here (next month?) when I've tested on my Apple II europlus.

**Comment by tomcw** [comment]
### Output from my Apple II europlus after removing lines 140 & 150:
![DSC_2771](https://user-images.githubusercontent.com/6696896/210013723-a3124490-fd42-4b4b-9e77-2755c02f7de9.JPG)

After trimming line 140 (to just do Y=123):
![DSC_2772](https://user-images.githubusercontent.com/6696896/210013743-10e68914-fd29-4d2d-a3f8-2b64885eb845.JPG)

After trimming line 140 (to just do Y=123) & line 150 (to just do Y=119):
![DSC_2774](https://user-images.githubusercontent.com/6696896/210013796-9bcf8bac-2be0-4c5e-b012-6fc25c80e197.JPG)
