### ISSUE TITLE
-s2 ssc command-line option?

### ISSUE THREAD

**Issue by skiphipdata** [AppleWin/AppleWin#1132]
Right now, there is a "-s2 empty" command line option to remove the SSC. However, once run there is no way to "put the SSC back in" that I can find, other than clearing out the config data from the registry and letting AppleWin re-initialize to defaults. There is a "-s1 parallel" option that accomplishes this for the parallel card. It would be nice to be able to re-enable the SSC in like manner.

Or better yet, can we just add the parallel and serial cards as checkbox options in the GUI?

**Comment by tomcw** [comment]
Can you try this new [AppleWin 1.30.12.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.12.0), which supports the command line "-s2 ssc".

**Comment by skiphipdata** [comment]
Great, it works!

**Comment by tomcw** [comment]
>Or better yet, can we just add the parallel and serial cards as checkbox options in the GUI?

Add this as a vote for #853.

**Comment by tomcw** [comment]
Closing.
