### ISSUE TITLE
Cannot capture screenshots on Windows 10

### ISSUE THREAD

**Issue by LordEvyl** [AppleWin/AppleWin#1135]
Help. Tried print screen, but nothing happens. If so, where do the images save?

**Comment by xotmatrix** [comment]
It saves it where the last disk image was loaded from.

**Comment by tomcw** [comment]
>It saves it where the last disk image was loaded from.

Hint: if you want to see where this is, then F7 (to enter debugger), then type `cd` followed by RETURN.

(Closing this issue, as I've tested on Windows 10, and it definitely works)
