### ISSUE TITLE
Starting Jeeves on AppleWin? How?

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#1138]
Can't seem to get Jeeves running in AppleWin. Haven't tried it on real hardware, but others claim it works in Virtual ][. So not sure if there is a special hardware requirement? Or certain option that needs to be enabled? Basically it says "This Apple isn't equipped to employ Jeeves." - which of course is some sort of vague friendly error reporting..

I tried several options like more RAM, an official rom/firmware dump, mouse, that sort of thing. In looking at the advertisement for it, it says it needs a $15 interrupt card or a Thunderclock. So this leads me to believe AppleWin is doesn't emulate the necessary hardware. Personally I'd like to see the Thunderclock or TimeMaster II H.O. emulated as solution.

ftp://ftp.apple.asimov.net/pub/apple_II/images/productivity/misc/Jeeves 1.0.dsk

**Comment by xotmatrix** [comment]
Installing the NS.CLOCK.SYSTEM driver on the disk does not solve the problem.

**Comment by tomcw** [comment]
I've had a very quick look.

There's a card detection routine at $2536 where it scans slots 7 to 1 for two cards, the 2nd of which matches the "ThunderClock Plus" firmware. (I don't know what the 1st card is, although the initial ROM matching routine _partially_ matches the Disk II firmware.)

```
2536 ; init for slot 7
 :
253A ; check next slot
253D ; check if card type #1
;        0  1  2  3  4  5    FF
; Cn00: -- 20 -- 00 -- 03 (not 00?)

25FC ; check if card is ThunderClock Plus
;        0  1  2  3  4  5  6
; Cn00: 08 -- 28 -- 58 -- 70
```

AppleWin doesn't support either of these cards, so Jeeves won't run.

**Comment by xotmatrix** [comment]
I'm a ProDOS idiot but I believe that's the ProDOS clock card detection routine it runs when it starts. Assuming Jeeves uses the ProDOS clock interface, it should work with the NSC driver installed. I tested it with MAME's Thunderclock emulation and Jeeves will not boot on it either. I think the problem is something else.

**Comment by tomcw** [comment]
Can you share your Jeeves disk with the NSC driver installed? Thanks.

**Comment by xotmatrix** [comment]
I installed the driver on disk image listed above using the `NSC.II.v0.9B.PO` utility disk.

[Jeeves 1.0 NSC.dsk.zip](https://github.com/AppleWin/AppleWin/files/9847253/Jeeves.1.0.NSC.dsk.zip)

**Comment by tomcw** [comment]
>Seems like a mouse card emulation issue in AppleWin

Could be! :-)

I've not tried your "Jeeves 1.0 NSC.dsk" yet, but I traced the mouse commands that Jeeves sends to the Mouse card in AppleWin:
- INIT MOUSE
- SET MOUSE: 0x08 = Interrupt on VBL

AppleWin only generates mouse VBL interrupts if SET MOUSE is issued with bit0 set (ie. Mouse On), so SET MOUSE: 0x09

If I manually set this bit during Jeeves' "Testing...", then I get to the "SET SOFTWARE CLOCK" screen.

OK, from the Apple IIc Technical Reference Manual (ch.9 "Mouse and Game Input", page 192):
- $00 Turns mouse off
 :
- $08 Turns mouse off, VBlInt active
- $09 Sets transparent mode, VBlInt active

So this is definitely a bug in AppleWin's Mouse card support.

**Comment by burniouf** [comment]
was tracking the code...reached the same conclusion !
JEEVES seems to require BOTH a clock and an IRQ source....
ThunderClock provides both, but you can get same with NSC + MOUSE VBL
(JEEEVES seems also to deal with RAMWORKS support, hitting $C07x to install IRQ vectors for banks $0-> $1F)
i use same logic with A2osX and i DO set mouse mode to $9 as required by mouse firmware to enable VBL IRQ..i noticed it is required by //e mouse card

**Comment by tomcw** [comment]
https://mirrors.apple2.org.za/ftp.apple.asimov.net/documentation/misc/APPLE%20II%20Technical%20Notes-Mouse.zip -> "Mouse _2523003 Mode Byte SetMouse.pdf"

"A mode byte of $08 (mouse off but VBL interrupt on) will generate VBL interrupts."

**Comment by nick3092** [comment]
> was tracking the code...reached the same conclusion !
> JEEVES seems to require BOTH a clock and an IRQ source....


It doesn't require a clock card, just a mouse card. I was able to boot it on my enhanced IIe which has a mouse card, but has no clock card (or romxe, or any other clock source). It also boots on my fully stock //c, which also has no hardware clock. And I confirmed the same in MAME using aple2ee, where I only had a mouse card slotted - no clock card.

It does prompt you to manually enter the date and time for the soft clock upon boot.

**Comment by tomcw** [comment]
>I was able to boot it on my enhanced IIe which has a mouse card, but has no clock card

Thanks @nick3092 - that categorically confirms the bug in AppleWin.

**Comment by tomcw** [comment]
Tests 0000e8b with: Jeeves
...and: Dazzle Draw, Blazing Paddles, Archon II: Adept, Orge[Fix], Dragon Wars.
...and: Fantavision, Contiki 1.3, Arkanoid, CopyII+ v9.1, BeagleWrite, MultiScribe, GEOS.

**Comment by Keatah** [comment]
Love it! Thanks for the fix.
