### ISSUE TITLE
SNES MAX wrong button mapping for Logitech F310 Gamepad

### ISSUE THREAD

**Issue by Eriknoc** [AppleWin/AppleWin#1141]
In Windows Controller Properties, buttons 1-8 are
A,B,X,Y,Lb,Rb,Back,Start  [Logitech F310 Gamepad]

In AppleWin, the buttons are incorrectly mapped to buttons
Y,B,A,X,Lb,Rb,Lb,Rb  [emulated SNES gamepad]

The correct mapping would be
B,A,Y,X,Lb,Rb,Select,Start  [emulated SNES gamepad]

Note: Lb/Rb = L/R btns, not gamepad directions or the F310 analog triggers (Z Axis).

**Comment by tomcw** [comment]
Hmm... I got the code from Lukazi himself (ie. specifically for Logitech F310).
I don't have a Logitech F310, and have only tested AppleWin with Dualshock 4 & DualSense controllers.

btw, if you start AppleWin with `-snes-max-alt-joy1`, then it'll use an alternate button mappings for the SNES MAX card. But this alt mapping is specifically for the "8BitDo NES30 Pro", eg:

```
> applewin.exe -snes-max-alt-joy1
```

I'm guessing that this doesn't help at all?

From the info you provided, I should be able to add another alternate button mapping.

**Comment by Eriknoc** [comment]
Thank you very much for taking this issue.  :-)

To complete the full Windows Controller Properties button map (the full 1-10)
[F310] 1-10 are A,B,X,Y,Lb,Rb,Back,Start
[F310] 9-10 are the analog stick buttons L and R (should be ignored, IMHO)

Correct.  Using "applewin.exe -snes-max-alt-joy1" at the command prompt did not work.  That actually set it to the following:
[SNES] p1: A,B,n/a,X,Y,n/a,Lb,Rb,Lb,Rb
[SNES] p2: Y,B,A,X,Lb,Rb,Lb,Rb,Select,Start

The correct mapping I gave in my first post would be the perfect match to the SNES gamepads.  In my humble opinion, I think buttons 9-10 should be ignored.

**Comment by Eriknoc** [comment]
I do have a few other types of gamepads I can test out.  Would you prefer that I open a separate issue for each gamepad type?

**Comment by tomcw** [comment]
>Would you mind if I reported any issues with those, and would you prefer that I open a separate issue for each gamepad type?

Sure, and best to track each in a separate issue.

> I was also thinking to make things easier on the user to have AppleWin autodetect the gamepad

If they are USB devices, then it's possible to detect using VID/PID id's.

**Comment by Eriknoc** [comment]
I have included included everything listed under "Device Functions:".
[Logitech F310 Gamepad Hardware Ids.txt](https://github.com/AppleWin/AppleWin/files/10037675/Logitech.F310.Gamepad.Hardware.Ids.txt)

Now that I'm thinking about it, I've noticed that every game console emulator allows the user to map their own buttons.  Would that be a simpler approach as opposed to keeping a list of VID/PID id's?

**Comment by tomcw** [comment]
I'm considering supporting a simple text mapping file (eg. in .yaml format) that allows you to specify the mappings for the 10 buttons. This way I'll have a generic way for other controllers to be added later on.

I could collect these .yaml files, and include them in future AppleWin releases.

**Comment by Eriknoc** [comment]
Are REV, Col, or DEVICE UP & U id's useful to you?  If not, then I'll just focus on getting the VID/PID id's only.

**Comment by tomcw** [comment]
Thanks for asking, but currently REV isn't useful.
(And I don't know what the others are: "Col, or DEVICE UP & U id's" ...but probably not useful either)

btw, I'm close to having something to share with you, in terms of a new build to test out a simple mapping file.

**Comment by Eriknoc** [comment]
Awesome!  :-)

**Comment by tomcw** [comment]
@Eriknoc, here's a build with support for a user-defined text file which allow an alternate controller button mapping:

[AppleWin1.30.12.1.zip](https://github.com/AppleWin/AppleWin/files/10245042/AppleWin1.30.12.1.zip)

Use the following command line:
`> applewin -snes-max-user-joy1 controller-ds4.yaml`

The file `controller-ds4.yaml` is contained in the zip. This is the mapping file for the Sony PS4 DualShock 4 controller.

NB, there are unused buttons (eg. 7, 8, 11, 12) so you will need to figure out where these unused buttons are for your controllers. Buttons start from 1 (ie. not 0), and can be specified from 1 to 16 inclusive.

Also the `HID` and `Description` key/values are only read in by AppleWin, but don't do anything; so for now, you can just leave these as they are.

To test this, I use the following test save-state file for SNES MAX:
https://github.com/AppleWin/AppleWin-Test/blob/master/v2/SNES_MAX-slot4.aws.yaml

I hope all this makes sense, but ask if anything is unclear.

**Comment by tomcw** [comment]
Hmm... downloading that save-state gives a file wrapped in HTML, which is no what we want! So I've attached a zip of the save-state file here (you will need to unzip the file before using with AppleWin):

[SNES_MAX-slot4.aws.yaml.zip](https://github.com/AppleWin/AppleWin/files/10259081/SNES_MAX-slot4.aws.yaml.zip)

And here's a batch file that works for me: [test.zip](https://github.com/AppleWin/AppleWin/files/10259093/test.zip)
(btw, the %~dp0 variable just expands to drive letter + path)

> The only Joystick options I got were-
> Joystick 1: Disabled, PC Joystick https://github.com/AppleWin/AppleWin/issues/1, Keyboard (cursors), Keyboard (numpad), Mouse
> Joystick 2: Disabled, PC Joystick https://github.com/AppleWin/AppleWin/issues/2, PC Joystick https://github.com/AppleWin/AppleWin/issues/1 Thumbstick https://github.com/AppleWin/AppleWin/issues/2
> 

This is correct - currently I haven't hooked anything up to AppleWin UI.

**Comment by tomcw** [comment]
NB. the (Config -> Input properties) 'Joystick 1' & 'Joystick 2' drop-downs don't need to be set to anything (eg. you could even set them as 'Disabled' !), without affecting the SNES MAX joystick support.

The SNES MAX support works by just directly reading whatever is connected as JOYSTICKID1 and JOYSTICKID2 via the Windows joystick API.

Also I can plug a USB joystick in _after_ starting AppleWin, and the joystick will just start working from within AppleWin.

What doesn't work, is if I plug the USB joystick into a USB port, and then unplug it and switch it to a different USB port. For this to work (in the different USB port) I need to close and restart AppleWin.

**Comment by Eriknoc** [comment]
Oh yeah.  I forgot that the Joystick selections are for the general non-card based analog joysticks/paddles with push buttons.  Heh.  Silly me.  Sorry for the mix-up.

I have been leaving the gamepad plugged into the same USB port.  If I do change ports or devices, I do restart the emulator.  The new .yaml and .bat files are working good on my end now.

I ended up reinstalling the drivers for Logitech F310 gamepads.  Now p1 is now working correctly using my own custom button mapped file, but p2 buttons still has the incorrect mapping from my first post.
[controller-logitechF310.zip](https://github.com/AppleWin/AppleWin/files/10266690/controller-logitechF310.zip)

**Comment by tomcw** [comment]
By p1 and p2 I understand you mean player1 and player2.

For the 2nd F310 controller, then you'll need to add these extra options to your existing command line:
`-snes-max-user-joy2 controller-logitechF310.yaml`

So your complete command line becomes:
`applewin -snes-max-user-joy1 controller-logitechF310.yaml -snes-max-user-joy2 controller-logitechF310.yaml -load-state "%~dp0\SNES_MAX-slot4.aws.yaml"`

NB, it's okay to reference the same YAML file for both `-snes-max-user-joy1` and `-snes-max-user-joy2`.

**Comment by Eriknoc** [comment]
> By p1 and p2 I understand you mean player1 and player2.

Correct.

> ... you'll need to add these extra options to your existing command line:

Got it.  I've updated my batch file and both gamepads now work perfectly.  Thank you.  :-)

Shall I start making YAML files for my other gamepads and adapters for uploading here?  Or should I say, to each respective issue?  That is... if you still even want to keep them as separate issues.  Or did you want to hold off for now?

**Comment by tomcw** [comment]
> I've updated my batch file and both gamepads now work perfectly. 

That's great!

> Shall I start making YAML files for my other gamepads and adapters for uploading here?

Yes, and probably simplest to just attach them all here. (And add a reference to each issue number so we have a link to that info too.)

Thanks.

**Comment by Eriknoc** [comment]
What do you think about the format being: "controller_make_ModelName.yaml"?

The reason why I would use underscores as separators is because the dash is used in Lik-Sang and could potentially be used in other makes or models.  Uppercase would be used in the model only as the first letter and as word separators.
e.g. "controller_lik-sang_SuperSmartjoy.yaml"

**Comment by tomcw** [comment]
Your naming convention sounds fine.

I am considering extending the YAML file to contain multiple controller definitions. If I do this then I'll have to figure out a good way to support this from the Config's GUI.

**Comment by Eriknoc** [comment]
(1) #1141 - Logitech F310 Gamepad {this issue}
(2) #1142 - Raphnet 2x adapters (1 for NES, 1 for SNES)
(1) #1148 - Saitek P2500 Cyborg Rumble Force Pad
(2) #1149 - Saitek P990 Dual Analog Pad & P2900 Wireless Gamepad
(1) #1150 - Lik-Sang Super Smartjoy SNES to USB converter
(1) added - Chinese(multiple) Dual PS2 USB adapter
Total devices = 8

[controller_YAML_files.zip](https://github.com/AppleWin/AppleWin/files/10328524/controller_YAML_files.zip)

**Comment by tomcw** [comment]
Thanks @Eriknoc for creating & attaching all those files.
I've tested loading each one into AppleWin (using my Sony DS4 controller) - really just to confirm that all files load correctly.

And I've committed them all into the main repo: fd3e2a0

My plan for the imminent release is just to include them in the distro zip in a "snesmax" subfolder.
And then I can look at improving the UI in a future release.

I will of course credit you in the help file & release notes.

**Comment by tomcw** [comment]
>I will of course credit you in the help file & release notes.

If you are okay, then can you let me have your name? Otherwise I'll just use `@Eriknoc`
Thanks!

**Comment by Eriknoc** [comment]
Sure.  Erik Struiksma.

**Comment by tomcw** [comment]
Thanks.

I've created a new issue (#1158) to consider future UI improvements, so will close this issue now.

NB. Released this in [AppleWin 1.30.13.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.13.0).
