### ISSUE TITLE
Some symbols in A2_BASIC.SYM are overshadowing ZP locations

### ISSUE THREAD

**Issue by tilleul** [AppleWin/AppleWin#1144]
Some symbols (those I found are: P.ADD, P.OR, P.AND, P.REL, P.MUL, P.PWR, P.NEQ) are constants and not zero page locations. Yet they're declared after the corresponding locations in A2_BASIC.SYM and thus overshadow (in the debugger) the following locations : OLDTEXT, LINNUM, DATLIN, INPTR, XREG, DATPTR and part of RESULT.

Simply commenting these symbols seem enough for the debugger to properly display the zp locations symbols. As I'm not sure I understand the format of the SYM file and the implications of such a modification, I have not issued a PR.

**Comment by tomcw** [comment]
>Some symbols (those I found are: P.ADD, P.OR, P.AND, P.REL, P.MUL, P.PWR, P.NEQ) are constants and not zero page locations.

Yes, I agree...

From SCDOC-1.DSK, file "S.D000":

```
2210 *--------------------------------
2220 *      MATH OPERATOR BRANCH TABLE
2230 *
2240 *      ONE-BYTE PRECEDENCE CODE
2250 *      TWO-BYTE ADDRESS
2260 *--------------------------------
2270 P.OR   .EQ $46      "OR" IS LOWEST PRECEDENCE
2280 P.AND  .EQ $50
2290 P.REL  .EQ $64      RELATIONAL OPERATORS
2300 P.ADD  .EQ $79      BINARY + AND -
2310 P.MUL  .EQ $7B      * AND /
2320 P.PWR  .EQ $7D      EXPONENTIATION
2330 P.NEQ  .EQ $7F      UNARY - AND COMPARISON =
2340 *--------------------------------
2350 MATHTBL
2360        .DA #P.ADD,FADDT-1  $C8...200...+
2370        .DA #P.ADD,FSUBT-1  $C9...201...-
2380        .DA #P.MUL,FMULTT-1 $CA...202...*
2390        .DA #P.MUL,FDIVT-1  $CB...203.../
2400        .DA #P.PWR,FPWRT-1  $CC...204...^
2410        .DA #P.AND,AND-1    $CD...205...AND
2420        .DA #P.OR,OR-1      $CE...206...OR
2430 M.NEG  .DA #P.NEQ,NEGOP-1  $CF...207...>
2440 M.EQU  .DA #P.NEQ,EQUOP-1  $D0...208...=
2450 M.REL  .DA #P.REL,RELOPS-1 $D1...209...<
```
