### ISSUE TITLE
Save State Corrupts YAML file

### ISSUE THREAD

**Issue by paulhlee1967** [AppleWin/AppleWin#1147]
After doing a SAVE STATE and subsequently opening applewin with the "-LOAD-STATE" command line, various memory errors occur.  Seems to occur more often when UthernetII and a Phasor or Mockingboard are both active, but this is not ALWAYS the case.

-Memory: hex data must be an even number of nibbles on line address: FD40
-Memory: Missing map name: Auxiliary Memory Bank01

Version 1.30.12

**Comment by tomcw** [comment]
Can you attach the corrupt state file here.
EG. either zip it, or rename to a .txt file (...then attach it).

Also if you reverted to AppleWin 1.30.11, does the corruption still occur?

**Comment by tomcw** [comment]
@paulhlee1967 - have you been able to reproduce this with an older AppleWin?

Can you attach a zipped save-state showing this issue.

**Comment by paulhlee1967** [comment]
I think it’s something in my pc actually. I upgraded to the latest version today of AppleWin and was able to save a state and then reopen it without issue. Sent from my iPhoneOn Jan 2, 2023, at 4:13 AM, TomCh ***@***.***> wrote:﻿
@paulhlee1967 - have you been able to reproduce this with an older AppleWin?
Can you attach a zipped save-state showing this issue.

**Comment by tomcw** [comment]
OK, I'll close this issue, but if you manage to reproduce again and suspect AppleWin, then we can reopen this issue.
