### ISSUE TITLE
SNES MAX gamepad support - Saitek P2500 Cyborg Rumble Force Pad

### ISSUE THREAD

**Issue by Eriknoc** [AppleWin/AppleWin#1148]
https://www.manualsdir.com/models/saitek/p2500.html

USB\VID_06A3&PID_FF0C&REV_0109

Button: 1= *X, 2= *Y, 3= *A, 4= *B, 5= *Z, 6= *C, 7= *L, 8= *R, 9= analog L btn, 10= analog R btn,
11= S(stands for Shift) -- don't map / if software is installed, keyboard keys and mouse buttons are mapped to the buttons
12= Digital -- don't map / this actually toggles between d-pad and analog L

SNES map suggestions:
1st : 1= Y, 2= X, 3= B, 4= A, 5= Select, 6= Start, 7= L, 8= R, 9= n/a, 10= n/a, 11= n/a, 12=n/a
2nd : 1= Y, 2= X, 3= B, 4= A, 5= L, 6= R, 7= Select, 8= Start, 9= n/a, 10= n/a, 11= n/a, 12=n/a
3rd : 1= Y, 2= X, 3= B, 4= A, 5= L, 6= R, 7= L[dup], 8= R[dup], 9= Select, 10= Start, 11= n/a, 12= n/a

*note: Buttons numbers are marked as numbers on the gamepad. I'm using naming from the sega saturn and sega genesis 6-btn gamepads to describe their positioning.

**Comment by tomcw** [comment]
Closing this issue as support for this is in [AppleWin 1.30.13.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.13.0).
