### ISSUE TITLE
SNES MAX gamepad support - Saitek P990 Dual Analog Pad & P2900 Wireless Gamepad

### ISSUE THREAD

**Issue by Eriknoc** [AppleWin/AppleWin#1149]
Saitek P990 Dual Analog Pad  _**{same mapping as Saitek P2900 Wireless Gamepad}**_
https://www.manualsdir.com/models/saitek/p990.html
USB\VID_06A3&PID_040B&REV_0100

Saitek P2900 Wireless Gamepad  _**{same mapping as Saitek P990 Dual Analog Pad}**_
https://www.manualsdir.com/manuals/136142/saitek-p2900.html
USB\VID_06A3&PID_040C&REV_0120

Buttons:
1= *X, 2= *A, 3= *B, 4= *Y, 5= *L1, 6= *R1, 7= *L2, 8= *R2, 9= *C, 10= *Z,
11= analog L btn, 12= analog R btn,
13= FPS(Start) -- don't map / if software is installed, keyboard keys and mouse buttons are mapped to the buttons
14= Analog -- don't map / this actually toggles between d-pad and analog L

SNES map suggestions:
1st : 1= Y, 2= B, 3= A, 4= X, 5= L, 6= R, 7= n/a, 8= n/a, 9= Start, 10= Select
2nd : 1= Y, 2= B, 3= A, 4= X, 5= L, 6= R, 7= Select, 8= Start, 9= R[dup], 10= L[dup]

*note: Buttons numbers are marked as numbers on the gamepad. I'm using naming from the sega saturn and sega genesis 6-btn gamepads to describe their positioning.

**Comment by tomcw** [comment]
Closing this issue as support for this is in [AppleWin 1.30.13.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.13.0).
