### ISSUE TITLE
SNES MAX gamepad support - Lik-Sang Super Smartjoy SNES to USB converter

### ISSUE THREAD

**Issue by Eriknoc** [AppleWin/AppleWin#1150]
HID\VID_6666&PID_0667&REV_0130

X = 1, 10, Z Rotation -
A = 2,  5, Z Axis +
B = 3,  6, Z Rotation +
Y = 4, 11, Z Axis -
L = 7
R = 8
Select = 9
Start = 12

The D-pad is mapped to the analog X/Y Axis and to the following buttons.
Up = 13, Right = 14, Down = 15, Left = 16

The device's digital directional "Point of View Hat" is not present, thus not used.

**Comment by tomcw** [comment]
Closing this issue as support for this is in [AppleWin 1.30.13.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.13.0).
