### ISSUE TITLE
DOS 3.2.1 init command produces bad .NIB data

### ISSUE THREAD

**Issue by fadden** [AppleWin/AppleWin#1151]
Procedure to reproduce in AppleWin:

- Boot DOS 3.3 system master
- "BRUN BOOT13"
- Insert DOS 3.2.1 system master nibble image in drive
- Enter "6 [return]" to boot disk
- Insert .NIB image in drive 2
- "INIT HELLO,D2"

This appears to work, but if you view the resulting image with a hex dump tool, there are regions that look like this:
```
001be0: f5 d7 ab ab f5 f6 ad db f7 f6 d6 ad ab ab ab ab  ················
001bf0: fd fb ba b5 ba de de aa eb ff ff ff ff 00 00 00  ················
001c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
001c10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
[...]
001d20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
001d30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
001d40: 00 00 00 00 00 00 00 00 00 00 00 00 00 ff ff ff  ················
001d50: ff ff ff ff d5 aa b5 ff fe aa ab aa aa ff ff de  ················
001d60: aa ff ff ff ff ff ff ff ff ff ff ff d5 aa ad b7  ················
001d70: d6 b7 bd fb db d6 df f7 ef ed dd af b7 b5 bb f6  ················
```
There is no dead space in a .NIB, so the $00 bytes shouldn't be there.  I'm guessing this is the "gap 1" area, as it always seems to appear before sector 0, but it's getting filled with $00 rather than $ff for some reason.  The regions are 336 bytes long.

Attached in [aw13zero.zip](https://github.com/AppleWin/AppleWin/files/10198354/aw13zero.zip):
- dos321-master.nib - DOS 3.2.1 system master (from Asimov)
- aw-init.nib - a sample demonstrating the above
- 3.2.1-blank.nib - a correct nibble image somebody sent me a while back

**Comment by tomcw** [comment]
Hi Andy,

The $00 bytes in the .NIB are intentional.
Formatting (or INIT'ing) a $1A00 long .NIB track would always give a "DISK II DRIVE TOO SLOW" under ProDOS's format.

See here for too much detail:
https://github.com/AppleWin/AppleWin/issues/125#issuecomment-342977995

Or the TL;DR version:
> Because .nib has a longer track buffer, then it can fit a whole track even when using the too large Gap3 sizes.
 :
> My current working solution is to monitor the written bytes, detect when all 16 sectors have been written (ie. a full track), then to clamp the track length to 0x18B0. I do this by keeping the last 0x18B0 bytes, and zeroing the remaining bytes.

I made this change 4+ years ago. These days, I'd just say use .WOZ.

I guess you are using CiderPress to validate the .NIB, and it's flagging these AppleWin formatted/INIT'ed .NIBs as bad?

**Comment by fadden** [comment]
> I guess you are using CiderPress to validate the .NIB, and it's flagging these AppleWin formatted/INIT'ed .NIBs as bad?

I've been doing a bit of work. CiderPress currently has [an issue](https://github.com/fadden/ciderpress/issues/30) with recognizing newly-formatted DOS 3.2 disks, because CP expects the data fields to be present when trying to auto-detect the sector layout.

Sounds like the idea is to have disk nibbles whose timing is 32us, 36us, 40us, or 10784us.  I suppose that works. :-)
