### ISSUE TITLE
Support Gameport copy protection dongles

### ISSUE THREAD

**Issue by medasaro** [AppleWin/AppleWin#1153]
I would very much like to see support for emulating gameport copy protection dongles for the Apple II. These were used in certain professional software. I am aware of two varieties. The simpler variety just consists of internal resistors to set the voltages on GC0-GC3 to specific values. The more complex implemented a combinatorial logic circuit that would set one or more of PB0-PB2 based on the states of AN0-AN3. I have reverse-engineered one example of such a dongle ([SpeedStar DataKey.pdf](https://github.com/AppleWin/AppleWin/files/10205288/SpeedStar.DataKey.pdf).) I would like to suggest adding controls to the "Input" or "Advanced" tabs of the "AppleWin Configuration" dialog that would allow setting the (emulated) voltages on each of GC0-GC3 and / or entering a truth-table for PB0-PB2 based on AN0-AN3. If we can agree on the best method for doing this, I am happy to write the code.

-Matthew D'Asaro

**Comment by tomcw** [comment]
Hi Matthew - this sounds like a great idea!

I'd envisage a drop-down menu in the Config GUI (as you suggest either the "Input" or "Advanced" tabs).

The drop-down would offer any supported devices that can connect to the 16-pin internal game port (ie. copy protection dongles, and possibly other things like the Sirius Joyport).

From your reverse-engineered schematic, it wouldn't be tricky to add support for this one, but consideration would be needed so that more dongles can be added. (Save-state support would be needed too.)

btw, do you have the software (eg. .woz) that uses this SpeedStar DataKey dongle?

**Comment by medasaro** [comment]
Thank you so much for the quick and encouraging reply, @tomcw. I am really thrilled that you are open to adding hardware protection dongle support to AppleWin.

First, you asked for a .woz of the SpeedStar program. It can be found at https://www.dropbox.com/sh/lsszb9xqrl3gyt5/AAAZMZofSYRv3FSMjrih8aJTa?dl=0 but note that the original disk (only known surviving copy) was modified at some point in the past, so the best we have is a working reconstruction. See the Readme.txt file.

Second, I was imagining more of a "universal" interface that would allow the user to specify the resistor values or truth-table for the protection dongle in use, thus avoiding needing to modify AppleWin code for every possible protection dongle, at the expense of requiring more effort on the user to set it up correctly. However, it sounds like you were imagining a much simpler interface that just required the user to select the correct protection dongle from a list, but which would require adding code to AppleWin for each known protection dongle. Can you comment on your thoughts on this tradeoff?

Third, doing some more research on this, it appears that protection dongles were extremely rare in the Apple II era and only a handful of software titles are even known to have used them. The only solid reference I could find to another piece of software was apparently some early versions of "Word Juggler" (https://en.wikipedia.org/wiki/Word_Juggler) although there was speculation that some BBS programs and maybe early versions of Microsoft Multiplan used one. This would lend itself toward a specific implementation in AppleWin for each dongle being feasible. Again, I would appreciate your thoughts on how you think this is best handled, now and going forward.

-Matthew D'Asaro

**Comment by medasaro** [comment]
I have created a pull request that adds a driver for the Speed Star protection dongle. Please review at your leisure. https://github.com/AppleWin/AppleWin/pull/1154

-Matthew D'Asaro

**Comment by tomcw** [comment]
Thanks for the PR - I will take a look and make comments directly in that PR (#1154).

>However, it sounds like you were imagining a much simpler interface that just required the user to select the correct protection dongle from a list, but which would require adding code to AppleWin for each known protection dongle. Can you comment on your thoughts on this tradeoff?

Yes - keep it simple is best (no point over engineering a solution), especially since there weren't a great number of these dongles.

**Comment by tomcw** [comment]
Remaining work:
- [ ] Add save-state support

**Comment by tomcw** [comment]
Note, to trigger the dongle check:
- Boot "SPEED STAR™ - Disk 1, Side A - Repaired.woz"
- Enter a simple BASIC program, eg. `10 FOR I=0 TO 100: ?I: NEXT`
- &L
- $C063 is read at PC=$7547
- Without the dongle, then it crashes to the monitor
- With the dongle, then it outputs some ADDRESS/LENGTH table, then you can CALL 2049 to run

NB. HELLO (implicitly BRUN SPEEDSTAR) and RUN DEMO, **do not** do the dongle check.

**Comment by medasaro** [comment]
One comment on the behavior without the dongle: On an Apple II+ or non-enhanced IIe (real or emulated) the software will freeze indefinitely instead of dropping to the monitor. On an enhanced IIe it will drop to the monitor.

-Matthew

**Comment by tomcw** [comment]
FYI, I've changed the Config->Advanced UI from "Copy Protection Dongle" to "Game I/O Connector", since this is more generic and will allow for simpler extension in the future is other devices are supported in this game-i/o port. (043bc49)

**Comment by tomcw** [comment]
btw, @medasaro, I have this protection dongle:
![DSC_2733-crop](https://user-images.githubusercontent.com/6696896/210152335-9fec2804-5ea2-4792-acd9-ffd1d551b400.png)
(It's even simpler than yours: it just pulls PB1 low, leaving PB0 and PB2 untouched.)
Sadly I can't find the software that actually uses it.
I'm asking on Slack (Applesauce channel).

**Comment by tomcw** [comment]
@medasaro - a mod'ed version of your truth table program to also test AN3 (so all 16 annunciator combos) and read the 3x PBs + 4 analogue inputs: [SoftKey Truth Table.zip](https://github.com/AppleWin/AppleWin/files/10328847/SoftKey.Truth.Table.zip)

**Comment by tomcw** [comment]
Output from my Hayden dongle:
![DSC_2779-crop](https://user-images.githubusercontent.com/6696896/210172544-03a440ba-c0f2-4690-822d-b3a9b255fcbb.png)

**Comment by tomcw** [comment]
The Hayden dongle won't be supported until I find the corresponding software (and this support will be tracked by a new issue).

Closing this issue.

**Comment by sicklittlemonkey** [comment]
That utility looks very handy, and that Hayden dongle looks rather inconvenient!

**Comment by tomcw** [comment]
re. "Hayden dongle looks rather inconvenient":
>it just pulls PB1 low, leaving PB0 and PB2 untouched

Yep - on a //e: you can't run the built-in self-test, and with a joystick plugged into the external port, you can't use PB1.

**Comment by tomcw** [comment]
NB. Released this in [AppleWin 1.30.13.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.13.0).

**Comment by tomcw** [comment]
I presented a short (~10 minute) talk at KansasFest 2023, titled: "Copy protection via the Game I/O connector", which includes a few slides on easch of the various protection dongles (Hayden, SDS, Dynatech/Corptechs, Robocom Ltd):
https://www.youtube.com/watch?v=XXG6XKnaNZk&t=5632s

**Comment by tomcw** [comment]
>The only solid reference I could find to another piece of software was apparently some early versions of "Word Juggler" [...]
See #1317 - it wasn't a protection dongle, but just for shift (and maybe control) keys.

**Comment by tomcw** [comment]
>The Hayden dongle won't be supported until I find the corresponding software (and this support will be tracked by a new issue).

See #1312 for Hayden protection dongle.
