### ISSUE TITLE
No-Intro A2R support

### ISSUE THREAD

**Issue by Cibomatto2002** [AppleWin/AppleWin#1185]
Will we get to see the A2R support that No-intro supports? If not how can I change A2R to work with this emulator

**Comment by tomcw** [comment]
I've never heard of No-intro before.

I had a look and there's only 467 A2R images for the Apple II:
https://datomatic.no-intro.org/index.php?page=search&s=221
... and 5 for the Apple II Plus, and 4 for the Apple IIe.

I would imagine that the equivalent .WOZ for all these A2Rs are on https://archive.org/
So try searching for the WOZ there.

I have no plans to support the A2R format.
NB. To convert from A2R to WOZ, then you'll need a mac, and use [Applesauce](https://applesaucefdc.com/software/).

**Comment by Michaelangel007** [comment]
The reason we _don't_ want to supportt the `.a2r` format is because:

* It is in a state of flux (pardon the pun)
* Proprietary
* Doesn't add anything that .woz doesn't aready

https://wiki.reactivemicro.com/Applesauce#Applesauce_Image_File_Format_.28.WOZ_and_.A2R.29

> In comparison .A2R, or the raw data format, contains all the data on the disk including timing. All flux transitions read for the disk are saved in this file. The size of a file is about 20Megs. The file specs has not been fully finalized, published, or released yet. It also may not be released since it's proprietary to Applesauce and leaves John Morris a lot more freedom to modify things as he sees fit rather then be locked in to one set of rules.

**Comment by Cibomatto2002** [comment]
Ok thanks for your time.
