### ISSUE TITLE
Option to have CAPS LOCK off upon startup

### ISSUE THREAD

**Issue by paulhlee1967** [AppleWin/AppleWin#1187]
Would be nice to be able to have CAPS LOCK turned OFF on startup.  An optional toggle or at least have that setting saved with the save state file.

**Comment by tomcw** [comment]
What is your use case for starting up with CAPS off?

I agree that it should be persisted to the save-state file.

**Comment by paulhlee1967** [comment]
Well as long think it through more, the persistent save file might not be the right place.  Rather, the caps lock in the emulator should follow the caps lock on the real machine. I do all of my work in AppleWin emulating an enhanced //e under Prodos. This configuration allows me to issue AppleSoft commands in lowercase. I do coding in Merlin and ProgramWriter and it’s just easier in lowercase. Sent from my iPhoneOn Feb 23, 2023, at 4:10 AM, TomCh ***@***.***> wrote:﻿
What is your use case for starting up with CAPS off?
I agree that it should be persisted to the save-state file.

**Comment by tomcw** [comment]
>Rather, the caps lock in the emulator should follow the caps lock on the real machine.

The problem with that is that all pre-Apple IIe software will assume uppercase, eg. DOS 3.3.

If I used the state of CAPS LOCK on the real machine (ie. very likely lowercase), then I'd be inundated with bug reports. That's the reason AppleWin defaults to uppercase (which is at odds with CAPS LOCK being off on Windows).

I think a command line switch is the best thing here.

**Comment by paulhlee1967** [comment]
Yes a command line option would be the right thing here. Agreed. Sent from my iPhoneOn Feb 25, 2023, at 11:17 AM, TomCh ***@***.***> wrote:﻿

Rather, the caps lock in the emulator should follow the caps lock on the real machine.

The problem with that is that all pre-Apple IIe software will assume uppercase, eg. DOS 3.3.
If I used the state of CAPS LOCK on the real machine (ie. very likely lowercase), then I'd be inundated with bug reports. That's the reason AppleWin defaults to uppercase (which is at odds with CAPS LOCK being off on Windows).
I think a command line switch is the best thing here.

**Comment by xotmatrix** [comment]
In my emulator, I have the option to invert the host CapLock state. When the host computer has it off (as is normal), the emulator has it on. It sounds confusing but I don't even think about it because the emulated Apple's CapsLock is generally in the state I want it when I start it.

**Comment by tomcw** [comment]
Thanks. I'm going with the cmd line:

> applewin.exe -capslock=off

**Comment by tomcw** [comment]
FYI, new [AppleWin 1.30.14.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.14.0) release adds the -capslock=off option.

**Comment by paulhlee1967** [comment]
Awesome! Can’t wait to try it out! Thank You. Sent from my iPhoneOn Mar 5, 2023, at 2:30 PM, TomCh ***@***.***> wrote:﻿
FYI, new AppleWin 1.30.14.0 release adds the -capslock=off option.
