### ISSUE TITLE
AppleWin sometimes opens a tiny window, and there's no way to make it regular size

### ISSUE THREAD

**Issue by philgoetz** [AppleWin/AppleWin#1190]
Usually, AppleWin opens a window that is, I think, 1540 x 1052 pixels.
This is difficulty for me, since my screen is only 1440 pixels wide, but workable.

Lately, without my changing the executables at all, every version of AppleWin that I have after 1.23 opens up the same half-size window that v1.23 had: 770x526.  This comes and goes.  A week ago, I could choose either between a tiny window I couldn't read, or a fullscreen window that wouldn't let me see the function key icons and was extremely distorted because my monitor is mounted vertically.

Also, when this happens, Applewin always makes me accept the GNU license when it opens.

Then a few days later, Applewin suddenly started working correctly again.
Today, it suddenly again opens a 770x526 window.
My most-recent version is 1.30.11.0.
I just downloaded 1.30.13.0, and it does the same thing.

I would suspect there was a config file somewhere screwing this up, except that I've tried 5 different versions and they all have different config files, but always have the same problem at the same time.
Maybe a registry entry.

**Comment by tomcw** [comment]
What version of Windows are you on?

From the AppleWin.chm (help doc), in Appendix -> Troubleshooting it says:

> Can't switch to 2x windowed mode: 
> - If the resolution isn't high enough to support 2x windowed mode, then AppleWin will refuse to switch. 
> - For different versions of Windows this is slightly different: 
>   - Windows 7 requires: 1181 x 808 
>   - Windows 10 (1909) requires: 1181 x 818 

So this should easily be able to fit into a 1440 wide display.

Once AppleWin starts, are you able to switch to the larger 2x mode, using CTRL+F6?

>Also, when this happens, Applewin always makes me accept the GNU license when it opens.

This is only shown when the AppleWin version changes, ie. you switch between different AppleWin's.
The version check is done against this Registry entry:
HKEY_CURRENT_USER\Software\AppleWin\CurrentVersion\Configuration\Version

Also (for some reason) if AppleWin is unable to write to the Registry, then "Version" won't be set, and it'll do the GPL prompt each time.
You can use RegEdit (before & after running AppleWin) to check if it's updated this "Version" value.

NB. by default there is no config file. AppleWin just uses the Registry. And all versions will just overwrite the settings in the same place. If AppleWin can't write to the Registry, then you can tell it to use a local config INI file instead, eg:
>applewin.exe -conf applewin-cfg.ini

**Comment by tomcw** [comment]
By default AppleWin isn't multi monitor aware.

I can see from the code, there's an (undocumented!) command line switch `-multimon`.
Using this switch, then on start-up, it'll use the Registry's saved "Window x/y position" to position the AppleWin window correctly for the multiple monitors, eg:

> applewin.exe -multimon

This is possibly useful to you if you want AppleWin to start-up on the 2nd monitor (ie. the one on the right, assuming you have them to the left & right).

**Comment by philgoetz** [comment]
On Tue, Feb 28, 2023 at 4:05 PM TomCh ***@***.***> wrote:

> By default AppleWin isn't multi monitor aware.
>
> I can see from the code, there's an (undocumented!) command line switch
> -multimon.
> Using this switch, then on start-up, it'll use the Registry's saved
> "Window x/y position" to position the AppleWin window correctly for the
> multiple monitors, eg:
>
> applewin.exe -multimon
>
> This is possibly useful to you if you want AppleWin to start-up on the 2nd
> monitor (ie. the one on the right, assuming you have them to the left &
> right).
>

That's very helpful!  I always have to do extra work to move the window
on-screen, because I can't just drag it on-screen, because the part of the
window you need to grab is off-screen.  I just tried it, and it works!

(I use AppleWin frequently, to run just one program: an educational arcade
game that I wrote 38 years ago, which I now use to study Spanish vocab.)

**Comment by tomcw** [comment]
Great stuff! So (more or less) is this particular issue dealt with?
IE. can I close this one?

**Comment by philgoetz** [comment]
Yes, I think so. Thanks so much for this program!

**Comment by tomcw** [comment]
I've added some info about -multimon to AppleWin.chm.
Closing.

**Comment by philgoetz** [comment]
That was a great idea! Thanks.
