### ISSUE TITLE
Debugger: Step-over WAIT can fail

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1194]
Repro:
- A=$FF  ; WAIT for $28882 cycles
- PC is at code: `JSR WAIT`  ($FCA8)
- CTRL+SPACE (to step-over)
- Debugger stops inside WAIT ($FCAC) after $280E8 cycles, and with $1A on the stack
- NB. At this point you can't SHIFT+SPACE to step-out, as the WAIT value ($1A) is still on the stack, so you need to single-step until after the `PLA`.

NB. Step-over succeeds for `JSR WAIT` for other values of A, eg. $78, $7F, $F0, $F8, $FD.
But also fails for A=$FE (with $0E on the stack).

**Comment by tomcw** [comment]
The reason for it stopping in the WAIT function is that the Debugger's `CmdStepOver()` (from an initial `JSR`) only attempts to do 0xFFFF steps before stopping.

So a crude fix would be to just up this max number of steps.

But it'd be a better user experience to report that the step-over cmd stopped because it'd done the max number of steps.

**Comment by audetto** [comment]
Why not move to 64 bit integers for all cycle related counting?
Including `nExecutedCycles` which I have always found super complicated.

**Comment by Michaelangel007** [comment]
This is a known issue.

The 64K limit was placed to avoid the debugger hanging.  I don't have any problems with it being updated to say a 20-bit number.

**Comment by sicklittlemonkey** [comment]
A safer version could log a message to the console every X cycles. Press
escape (or something) to stop the step over operation.

**Comment by audetto** [comment]
> Why not move to 64 bit integers for all cycle related counting? Including `nExecutedCycles` which I have always found super complicated.

Not quite the same thing. Ignore my comment.

**Comment by Michaelangel007** [comment]
That's not a bad idea Nick!  i.e. Every 64K cycles print a warning to the console.

```
Warning: Stepping-over taking a long time. > 64K cycles.
```

The hotkey is a little more complicated since it seems we should have two keys along with adding a new (sub-state) to the debugger:

* `ESC` Cancel stepping-over
* `???` Keep stepping over

**Comment by tomcw** [comment]
You could just default to "keep stepping-over", so you only need ESC to cancel.

```
Warning: Step-over taking a long time (> 64K opcodes). ESC to cancel operation.
```

**Comment by Michaelangel007** [comment]
Repro:

    <F7>
    BPX 302
    <F7>
    CALL-151
    300:A9 FF 20 A8 FC 60
    E003G
    CALL 768

**Comment by Michaelangel007** [comment]
Trivial fix addresses the CPU stopping inside WAIT with A=FF.

```c
g_nDebugSteps = 0xFFFFF; // GH #1194
```

I've requested feedback from Nox Archaist (Mark and qkumba) to see if they want/need a higher value.

**Comment by Michaelangel007** [comment]
Screenshots showing new behavior in PR #1203

**Comment by tomcw** [comment]
The fix from @Michaelangel007 was:
- Up the max steps to 0xFFFFF (from 0xFFFF)
- If step-out succeeds the debugger' feedback is:
  - "Stop reason: Register PC matches 'Go until' address $nnnn"
- If step-out fails, new (QoL) feedback from the debugger is:
  - "ERROR: Didn't step over JSR! (RTS $nnnn not found!)"
  - "INFO: Didn't step over JSR! (RTS $nnnn on top of stack.)"
  - "WARN: Didn't step over JSR! (Stack has RTS $nnnn but needs fixup: $xx bytes)"

@Michaelangel007: this is assigned to you, so please close if you are happy that all work has been done.

**Comment by Michaelangel007** [comment]
Thanks for the merge and summary!  I bumped up the debugger version to 2.9.1.17 for this issue (db5b668e) and updated the `Debugger_Changelog.txt`. (Forgot to do that in the PR.)
 
@tomcw When the next version of AppleWin is about to be released (1.30.15) I'll need to bump the debugger version to 2.9.2.0. 
 I've added task #1206 for [milestone 52](https://github.com/AppleWin/AppleWin/milestone/52):

* [x] Bump Debugger version to 2.9.2 for 1.30.15

**Comment by Michaelangel007** [comment]
The _Nosh Kosh_ [game](https://github.com/Michaelangel007/apple2_games_disassembly_project/tree/master/N/nosh_kosh) is an Applesoft program compiled with Microsoft's TASC and it can easily trigger the new `nMaxSteps = 0xFFFFF` limit. :-/ 

i.e. `BPX 71DA`.

Probably should make this a config variable so the user can fine-tune as needed instead of hard-coding the max value.

**Comment by dfgordon** [comment]
I got `please report 'nMaxSteps = 0xFFFFF' to [here]` while stepping through ProDOS code that reads a text file.  In this case it didn't look to me like the reason was actually that max steps was reached (response was instantaneous at slowest speed and it stopped after 1 LDA into the subroutine at $9C67).  The caller is messing with text holes including those used by firmware which is perhaps the reason weird stuff happens.

At various points both the INFO and WARN variety appeared.

Not sure how meaningful this is, but it said "please report" so I am.

**Comment by tomcw** [comment]
@dfgordon - thanks for the report.

If possible, can you attach a save-state file (.yaml) and any associated disk image(s).
btw, you'll need to zip them up to attach to this issue.

Create the save-state (F11 from AppleWin) just before the point of doing the step-over.
(It's fine to do F11 from within the AppleWin debugger)

**Comment by dfgordon** [comment]
OK done, if you boot the image you can do `BPM 400,400` *after* it displays its graphical menu.  Then select enter game and the breakpoint will be triggered.  Ctrl-space 5 times to get the warning.  This code has now been fixed so it doesn't do anything wrong with screen holes (I think).

[issue1194.zip](https://github.com/user-attachments/files/24374436/issue1194.zip)

**Comment by Michaelangel007** [comment]
> Not sure how meaningful this is, but it said "please report" so I am.

Thanks for taking the time to report this!

While fixing this is equivalent to attempting to solve the unsolvable [Halting Problem](https://en.wikipedia.org/wiki/Halting_problem) I wasn't sure if we would still run into edge cases with a larger "timeout" out-in-the-wild. This report even with a larger values re-iterates that we really need a few QoL things:

* A custom max `nMaxSteps` counter,
* A new debugger config command to get/set this value,
* Nick's suggestion of continuing to executing but press `ESC` to cancel, and
* Tom's optimization that we only need to check `ESC` in `CmdStepOver()`.
