### ISSUE TITLE
A question about Phasor / Mockingboard

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#1216]
I realise this questions comes 4 years too late, but...

Re-reading my code to handle Mockingboard cards, my understanding (dont ask me where is comes from!) is that a Mockingboard card fits into 2 slots: 4 and 5 at once. I thought it was a chunky card... But I cant see any evidence of this in the AppleWin source code.

I can actually insert a Mockingboard and a Phasor in the 2 slots.

2nd question is: what happens if I insert 2 such cards? I guess some fancy software could use them both..., but otherwise nothing wrong with it?

Have I got it right?

**Comment by Michaelangel007** [comment]
Tom can correct if I'm wrong but my understanding is that a [Mockingboard](https://en.wikipedia.org/wiki/Mockingboard) only fits in 1 slot.  Each [AY-3-8910](https://en.wikipedia.org/wiki/General_Instrument_AY-3-8910)  provides 3 voices.  Some (all?) Mockingboards provide dual 8910 sockets for 6 voices.

Ultima 5 supports dual Mockingboards in slot 4 and 5 respectively for a total of 12 voices but IIRC only max 9 are used.

**Comment by audetto** [comment]
Ok, so it just any other card. I will delete some nonsense I wrote.

**Comment by Michaelangel007** [comment]
Nerdy Pleasures has a really nice post with pictures showing the various Mockingboards.

http://nerdlypleasures.blogspot.com/2022/09/apple-ii-sound-cards-gaming-niche.html
