### ISSUE TITLE
Sometimes cannot mount 800k or HDV images

### ISSUE THREAD

**Issue by burniouf** [AppleWin/AppleWin#1227]
AppleWin 1.30.14.0 : Why cannot mount 800k image anymore as S7D1 or S7D2 ???

**Comment by burniouf** [comment]
intermitent....managed to reproduce : 
![image](https://github.com/AppleWin/AppleWin/assets/8941204/96bd83d2-8d41-4586-976d-d0a1ebdb5f5f)

**Comment by audetto** [comment]
The error is displayed when a HD is inserted as a Floppy.
What are you clicking exactly to cause it?

**Comment by burniouf** [comment]
I try to select a 800k image to mount as S7D2.
But it happends sometimes....sometimes it happends even if selecting a 32Mb image.

**Comment by tomcw** [comment]
Some background details:

If I try to insert an 800K image into S6D1 or S6D2 (eg. F3 or F4) then I get the message about "this UniDisk 3.5/Apple IIGS/hard-disk image is not supported", eg:

![image](https://github.com/AppleWin/AppleWin/assets/6696896/a2d432e3-690f-4b01-bf8e-0d5dcc34f65f)

If I try to insert a 32MB image into S6D1 or S6D2 (eg. F3 or F4)  then I get this message:

![image](https://github.com/AppleWin/AppleWin/assets/6696896/05510fb7-b655-46b1-99ad-82d53d126870)

I need to take a look at the code, to consider how it could *sometimes* take the wrong code-path for FDD, when it should use the HDD code-path.

**Comment by sean-gugler** [comment]
Possibly helpful: I notice that after failing to open it as a floppy, I have to EJECT that floppy drive - even though it failed and there's apparently nothing there - before it will release the lock on that file and allow me to mount it as a HDD.

Seen in v1.30.18

**Comment by xotmatrix** [comment]
I can confirm this on v1.30.19. AppleWin is getting into a bad state when the floppy fails to mount. The fact that the Eject function is not disabled in the main window supports this. Once ejected, the image can be mounted as a hard disk. Attempting to eject from the configuration menu does not resolve the problem.

**Comment by tomcw** [comment]
Thanks both, I am able to reproduce this now.

Repro:
- Try to insert an 800K image into S6D1
   - this fails, but as noted, it doesn't close the file handle
- Try to insert _the same_ 800K image into S7D1
   - this fails (since the file is still open)
