### ISSUE TITLE
Disassembly of current line is illegible in "black & white" mode

### ISSUE THREAD

**Issue by sh95014** [AppleWin/AppleWin#1231]
1. Boot AppleWin v1.30.14.1 and invoke debugger
2. `bw`

Observe that the current (where the PC points to) line is white-on-white. see screenshots below at $C27F:

![BW](https://github.com/AppleWin/AppleWin/assets/95387068/d0e73581-31a3-44bd-9961-edcb628d9f5a)

(Color mode works fine)

![Color](https://github.com/AppleWin/AppleWin/assets/95387068/1635684c-4de0-49ac-99f8-3c1fb5b749ad)

As far as I can tell, `ConfigColorsReset()` incorrectly maps both `FG_DISASM_PC_X` and `BG_DISASM_PC_X` to white.

**Comment by Michaelangel007** [comment]
Thanks for the bug report!  Fixed.
