### ISSUE TITLE
Wizardry V 

### ISSUE THREAD

**Issue by Darthfecker** [AppleWin/AppleWin#1232]
Whenever I try to enter the maze, the game freezes after the password protection scheme during the load screen saying "Entering Heart of the Maelstrom"

**Comment by tomcw** [comment]
Hi - can you attach a save-state file just before you enter the maze?
(You'll have to zip it first before attaching)

**Comment by tomcw** [comment]
Hi - reminder: can you attached a save-state just before entering the maze? Or describe the steps I need to take to reproduce this issue. Thanks.
