### ISSUE TITLE
Joystick axis shaping

### ISSUE THREAD

**Issue by xotmatrix** [AppleWin/AppleWin#1237]
A recent change (#1162) fixed the long-standing joystick detection problems I've had, so many, many thanks for fixing that. But it appears we need to look into axis shaping since XInput analog sticks are physically bound to a circle. This makes reaching the Apple paddle/joystick "corners" impossible.

![AppleWin_2023-06-03_14-03-52](https://github.com/AppleWin/AppleWin/assets/14209329/1620935a-8ffb-466b-aa10-cbf821e7b5f9)

Also, thank you for making building AppleWin with VS2022 completely painless. Building AppleWin is something I had been putting off forever. I'm not a dynamite C++ programmer but I may be able to offer better help in the future.

**Comment by audetto** [comment]
Yes, see for a previous discussion here: https://github.com/AppleWin/AppleWin/issues/429

In Linux, it uses a remap from circle to square: https://github.com/audetto/AppleWin/blob/944b84574ac788dfa9a66bea5e524d053cac1118/source/linux/paddle.cpp#L60

**Comment by xotmatrix** [comment]
Shoot, I somehow missed that issue. In any event, I think it needed to be surfaced ahead of the next release's improved controller detection.

> remap from circle to square
That's an interesting solution. I've tried different schemes but I always seem to go back to multiplying by sqrt(2).

**Comment by tomcw** [comment]
@xotmatrix 
>In any event, I think it needed to be surfaced ahead of the next release's improved controller detection.

Yes, it'll be in the next release (whenever that happens... but soon I'd hope).

**Comment by tomcw** [comment]
Fixed in [AppleWin 1.30.15.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.15.0), so closing this issue.
