### ISSUE TITLE
DISC II controller emulation not precise enough

### ISSUE THREAD

**Issue by Dietrich-L** [AppleWin/AppleWin#1243]
Recently upon porting my CPM-65 operating system to my Apple II, I ran into 2 issues with the Emulation of the DISC II controller:
I'm using my own disc-I/O routines. Emulation was Apple IIe, because I needed 80 col support. AppleWin Version is 1.30.14.1
Issue 1
The was a type in the code to read a GCR44 coded byte
`read_gcr44

RGCR1	lda DISK_SHIFT,X
	BPL RGCR1
	rol a
	sta PTR

RGCR2	lda DISK_SHIFT,X
	BPL RGCR1
	and PTR
	rts`
The error is the second BPL RGCR1. It should read BPL RGCR2. Interestingly the code worked on AppleWin. Of course the real machine crashed...

Issue 2
In my sector write routine in the time critical part, there was a 1us additional delay due to erroneous page alignment of my code.
Again the code worked on AppleWin. Of course the real machine crashed too.

It would be helpful to improve the emulation such, that errors and timing inaccuracies are not tolerated by AppleWin. AppleWin was a recommendation by Stan Georgiev and I like it a lot. Great testing bed.

Dietrich

**Comment by Dietrich-L** [comment]
I am using a DSK image. That might explain it. I will test this with a WOZ image. Can you point me to a suitable converter dsk —> WOZ for WIN 10?

Dietrich

**Comment by tomcw** [comment]
There's `dsk2woz` here: https://github.com/TomHarte/dsk2woz
But you'll need to compile the C code into an executable yourself.

**Comment by tomcw** [comment]
And there's this `DskToWoz2` here: https://github.com/cmosher01/DskToWoz2
This one has pre-built executables for all OS's.

Hmm, but it says:
>Images must be normal DOS 3.x disks with a normal VTOC at track $11.

If you DSK if CP/M then it likely won't work.

**Comment by univta0001** [comment]
Another way is to use Applewin to convert DSK to WOZ (indirectly).

Step to do in Applewin

1.  Insert Disk Copier program (like Disk Muncher) in Disk 1
2.  Insert Blank Woz in Disk 2. In order to create a blank woz, when selecting for file, if the file is not in the selected folder, the blank woz file will be created in Applewin.
3.  After copier program is started, switch Disk 1 with CPM65
4.  Make a copy from Disk 1 to Disk 2. It should be able to convert from DSK to WOZ using AppleWin

**Comment by Dietrich-L** [comment]
@univta0001 
Thanks, that did the trick nicely. Although I used a blank WOZ from the internet. I was unable to make AppleWin create one. Maybe I didn‘t try hard enough.

The WOZ copy boots and performs fine.

Now I will investigate, whether the faulty BIOS crashes with this image…

Dietrich

**Comment by Dietrich-L** [comment]
I can now confirm, that the WOZ image truely reflects the real behaviour of DISC II - i.e. in both cases the faulty code does not work.

Thanks for the help.

Dietrich

**Comment by Dietrich-L** [comment]
solved

**Comment by tomcw** [comment]
@Dietrich-L - what about issue 2? Or did that turn out to be a non-issue?

**Comment by Dietrich-L** [comment]
I case 2 the newly written sector was writte, but unreadable and in my code, the system hung. As it should be.

Dietrich
