### ISSUE TITLE
Support 80 Col Card for Apple II+

### ISSUE THREAD

**Issue by Dietrich-L** [AppleWin/AppleWin#1244]
I own an Apple II+ with a generic 80 column card. I'm using APPLEWIN 1.30.14.1.
Unfortunately the Apple II+ emulation has no 80 col card support, so I have to use the Apple IIe emulation, which works fine.
Please add 80 col support also for Apple II+

Dietrich

**Comment by tomcw** [comment]
There's a very old issue that is tracking Videx 80 Column card support for the II and II+ here: #105.
I'm going to close and mark this as a duplicate of that issue, but if you mean something else, then I can reopen this one.

**Comment by Dietrich-L** [comment]
Correct. Sorry for the duplicate. I actually found #105 but did not really understand it correctly.
