### ISSUE TITLE
Boot from slot#5 not possible

### ISSUE THREAD

**Issue by Dietrich-L** [AppleWin/AppleWin#1245]
AppleWin cannot boot from slot#5. The real machine of course can.
Is it feasible to allow booting from slot 5?

Dietrich

**Comment by tomcw** [comment]
Hi @Dietrich-L - can you be more precise about what you want to boot from slot 5?
EG. 5.25" floppy, 3.5" floppy or hard disk image?

**Comment by Dietrich-L** [comment]
Ahh, sorry. I would like to boot from another Disc II. In my real machine, I actually have a Disc II in slot#6 with a BMOW Floppy EMU and an Ehring Disc II compatible in slot#5 with 2 5.25“ Floppies. So I can boot from real floppies there.

Dietrich

**Comment by Dietrich-L** [comment]
I just noticed, that this is already handled in pull request #337.

**Comment by tomcw** [comment]
If you just need a Disk II Controller in slot 5, then you can do this from AppleWin's Configuration -> Disk tab.
See the AppleWin.chm document (F1 from AppleWin).

NB. Slot 5 needs to be empty before you can enable this card.

**Comment by Dietrich-L** [comment]
I have activated the Disc II controller in slot #5 and I‘m able to access disc images there on both drives. However I was not able to boot from drive 1 in slot #5, as I can on my real machine by entering PR#5.

Dietrich

**Comment by tomcw** [comment]
Hmm... this works for me:

Configure: slot 6 and slot 5 both have a disk ii controller.
(slot 7 empty)

### Example 1:
- Slot 6: Drive 1 and 2 empty
- Slot 5: Drive 1 = "DOS 3.3 System Master.woz", Drive 2 = empty

F2 (power cycle)
CTRL+F2 (break to BASIC prompt)
PR#5 boots the disk.

### Example 2:
- Slot 6: Drive 1 = "The Apple at Play.woz", Drive 2 = empty
- Slot 5: Drive 1 = "DOS 3.3 System Master.woz", Drive 2 = empty

F2 (power cycle)
Boots "The Apple at Play.woz", then I quit to BASIC prompt.
PR#5 boots the disk.

**Comment by Dietrich-L** [comment]
Ok:

> F2 (power cycle)
CTRL+F2 (break to BASIC prompt)
PR#5 boots the disk

did the trick - thanks. I found it also in the help file, but it is really a bit cryptic there ..

**Comment by Dietrich-L** [comment]
Solved

**Comment by Michaelangel007** [comment]
Self-reminder that we probably should update the Help docs to make this a little clearer.
