### ISSUE TITLE
Keycodes for ESC and CTRL-U not properly transmitted by RDKEY ($FD0C)

### ISSUE THREAD

**Issue by Dietrich-L** [AppleWin/AppleWin#1246]
I programmed a software to use some command codes for user input via the keyboard. To get the keys, I use the ROM routine RDKEY in the Apple IIe emulation with 80 col mode on. This works fine for all codes except ESC and CTRL-U. 
- ESC is not transmitted at all. Instead an invers + is displayed. If I press ESC again the normal cursor reappears.
- CTRL-U gives code $A0 which translates into a blank

How can I get these control codes properly?

Dietrich

**Comment by inexorabletash** [comment]
You're seeing the results of the 80 column firmware being active. See the Apple IIe Technical Reference Manual, page 57-58, which talks about the RDKEY behavior. 

If you want a raw key code, don't use the monitor and look at the KBD I/O location directly (and tickle KBDSTRB to clear) - TRM page 12. This is what most non-trivial programs do. 

(Page numbers from the 1985 edition)

**Comment by Dietrich-L** [comment]
Ok, I see. 
This explains the ESC behaviour, but not why CTRL-U is not working. Any ideas on this?

Dietrich

**Comment by xotmatrix** [comment]
It treats the right arrow (ctrl-u) as the "retype" key. It will return whatever character is under the cursor when the right arrow is pressed.

**Comment by Dietrich-L** [comment]
Ah, thanks a lot. I will poll KBD direkly then….

**Comment by Dietrich-L** [comment]
Solved
