### ISSUE TITLE
Support Robocom BitStik's "Interface Module" protection key

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1247]
Robocom Ltd's Robo Graphics system came with a 3-axes joystick (BitStik) which connected to the Game I/O connector via a "Interface Module" protection key.

Here's what is displayed if the Interface Module isn't detected:
![_requires_bitstik_hardware_ROBO1000](https://github.com/AppleWin/AppleWin/assets/6696896/f4a0219e-b3ee-4af2-82cb-db6346231b93)

**Comment by tomcw** [comment]
There are 3 (UK) Robocom Ltd variants, each with their own unique Interface Module: Robo 500, Robo 1000 and Robo 1500. In the US these were sold as Robo Systems CAD 1 (equivalent to Robo 1000) Robo Systems CAD 1+ and Robo Systems CAD 2.

See this csa2 thread, "Robo-1000 and IIgs compatibility?" : https://groups.google.com/g/comp.sys.apple2/c/uVPHyhML5bM

The 3 UK variants (Robo 500/1000/1500) disk images are available here:
https://archive.org/download/Antoine_Applesauce_Vignau
EG: "Robo 1000 Graphics System - System Master (Robocom Ltd)":
https://archive.org/download/Antoine_Applesauce_Vignau/Robo%201000%20Graphics%20System%20-%20System%20Master%20%28Robocom%20Ltd%29/

NB. they are in .a2r format, so you'll need to convert to .woz (eg. using [a2woz](https://github.com/adafruit/a2woz)).

Also on Internet Archive is these images .dsk image:
https://archive.org/details/a2__requires_bitstik_hardware_ROBO1000
https://archive.org/details/a2__requires_bitstik_hardware_PLOTTER

They are not cracked, and being .dsk are missing the extra disk image meta-data to pass the copy-protection. IE. even if you have the "Interface Modules" installed they still won't boot.

**Comment by tomcw** [comment]
My notes from inspecting the three Robo 500/1000/1500 images:

[Robocom notes.txt](https://github.com/AppleWin/AppleWin/files/12073443/Robocom.notes.txt)

**Comment by audetto** [comment]
I was trying to test this code and found that after converting the .a2r images they don't boot, nor do they contain a valid prodos disk

If I boot from them I get

![image](https://github.com/AppleWin/AppleWin/assets/212523/a5663be8-fb85-4c25-990e-10026f249619)

a2woz completes without any issues.

**Comment by tomcw** [comment]
Which .a2r did you convert?

I converted `Robo 1000 Graphics System - Disk 1, Side A.a2r` to woz, and am attaching it here:
[Robo 1000 Graphics System - Disk 1, Side A.zip](https://github.com/AppleWin/AppleWin/files/12139805/Robo.1000.Graphics.System.-.Disk.1.Side.A.zip)
This works fine for me. What about you?

**Comment by tomcw** [comment]
@audetto - I've not heard back, but this sounds like a problem on your side.
btw, I plan to release a new AppleWin later today.

**Comment by audetto** [comment]
Please, go ahead

**Comment by tomcw** [comment]
Thanks - I'll leave this open for a bit longer, in case you want to try the WOZ image I attached (above) and notice any issues.

**Comment by audetto** [comment]
All sorted. I was inserting it as a HD rather than a floppy.

This surprises me a bit:

https://github.com/AppleWin/AppleWin/blob/cd2f29b72313a8bb98dfa5029819869b84e447c0/source/DiskImageHelper.cpp#L875

There is basically no way to detect if a HD file is really a HD file.
But I guess there is nothing to do about it.

**Comment by tomcw** [comment]
We could make the hard disk image detection code more "defensive", eg. detect if it's a .WOZ and reject it (as currently there's no AppleWin support for 3.5" .WOZ images).

For now I don't plan to do anything about it (unless you feel strongly).

Anyway, let me close this issue.

**Comment by tomcw** [comment]
Hugh Hood sent me Interface Modules (dongles) for the 1000 & 1500 series.

The dongles work without a BitStik joystick connected.
And they return a stable, constant value for each AN0-AN2 combination.

**Comment by tomcw** [comment]
Notes on how to test 'Robo Systems CAD-2P v2.7' (from Hugh Hood):
- Use Apple IIe (enhanced)
- Set Game I/O connector = Robocom Ltd - Robo 1500, CAD-2P
- Set slot 3 = Saturn 128
- Set slot 4 = Mouse card
- Insert libraryv253.nib into drive 2
- Boot draft27.dsk from drive 1
