### ISSUE TITLE
Window Size Upon Opening Varies

### ISSUE THREAD

**Issue by paulhlee1967** [AppleWin/AppleWin#1259]
Most of the time when I open AppleWin, it is the larger size as shown in the attached file. Sometimes however it opens up in the smaller size. How can I make it open the same size all the time (preferably the smaller size)?
<img width="1519" alt="applewin_different_sizes" src="https://github.com/AppleWin/AppleWin/assets/77712544/81ae6d2c-61f1-43a4-8c76-5888fb653f90">

**Comment by tomcw** [comment]
When you change the window size (eg. F6 or the icon on the RHS), then this new scale (1x or 2x) is stored in the Registry. Then when you close AppleWin and restart it, it pulls this scale value from the Registry and sets the window size accordingly.

But from your screenshot, I can see you have 2 instances of AppleWin open at the same time. Whichever instance last sets the window scale size will be the one that updates the Registry. The way it works isn't designed to work with multiple instances of AppleWin and use the Registry.

If you are using multiple instances, then you can use the `-conf pathname` command line option to use a local .ini file instead of the Registry. Can you try that? (See the AppleWin.chm help file for info about this)

**Comment by paulhlee1967** [comment]
Pressing F6 switches between windowed and full screen mode. The issue I have is that in windowed mode, sometimes it shows larger and sometimes smaller. I can't figure out why. On Dec 9, 2023, at 10:09 AM, TomCh ***@***.***> wrote: When you change the window size (eg. F6 or the icon on the RHS), then this new scale (1x or 2x) is stored in the Registry. Then when you close AppleWin and restart it, it pulls this scale value from the Registry and sets the window size accordingly. But from your screenshot, I can see you have 2 instances of AppleWin open at the same time. Whichever instance last sets the window scale size will be the one that updates the Registry. The way it works isn't designed to work with multiple instances of AppleWin and use the Registry. If you are using multiple instances, then you can use the -conf pathname command line option to use a local .ini file instead of the Registry. Can you try that? (See the AppleWin.chm help file for info about this) — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by tomcw** [comment]
>Pressing F6 switches between windowed and full screen mode.

Yes, you're right! I edited my comment to reflect this.

>The issue I have is that in windowed mode, sometimes it shows larger and sometimes smaller.

Are you running multiple instances of AppleWin?

**Comment by paulhlee1967** [comment]
Yes I do run typically two instances. Sent from my iPhoneOn Dec 10, 2023, at 4:18 AM, TomCh ***@***.***> wrote:﻿

Pressing F6 switches between windowed and full screen mode.

Yes, you're right! I edited my comment to reflect this.

The issue I have is that in windowed mode, sometimes it shows larger and sometimes smaller.

Are you running multiple instances of AppleWin?

**Comment by tomcw** [comment]
OK, here's a way it could be happening...

1. Start AppleWin (1st instance). It opens as a small window size, so you press Ctrl+F6 to make it larger
2. Start AppleWin (2nd instance). This opens as a large window size, but on your desktop you don't have enough space, so you use Ctrl+F6 to make it smaller.
3. Later on you close both instances
4. Start AppleWin, and this opens as a small window size.

**In general, the window size is saved to the Windows Registry whenever you press Ctrl+F6.**

So in the above sequence, the last time Ctrl+F6 was pressed (at step 2) it made the window smaller, so it's this small size that gets saved, and then reused when you open AppleWin next time.

>How can I make it open the same size all the time (preferably the smaller size)?

There is no command line (or other option) to force a window scale factor.
So the only way is to avoid resizing (ie. avoid using Ctrl+F6)...

Start AppleWin and if it's a large window size, then press Ctrl+F6 (so make it a smaller size).
Now never touch Ctrl+F6 again

**Comment by paulhlee1967** [comment]
That’s the trick!  CTRL-F6. I’m not sure if it’s in the docs but I didn’t see it. Thanks Tom!Sent from my iPhoneOn Dec 10, 2023, at 12:57 PM, TomCh ***@***.***> wrote:﻿
OK, here's a way it could be happening...

Start AppleWin (1st instance). It opens as a small window size, so you press Ctrl+F6 to make it larger
Start AppleWin (2nd instance). This opens as a large window size, but on your desktop you don't have enough space, so you use Ctrl+F6 to make it smaller.
Later on you close both instances
Start AppleWin, and this opens as a small window size.

In general, the window size is saved to the Windows Registry whenever you press Ctrl+F6.
So in the above sequence, the last time Ctrl+F6 was pressed (at step 2) it made the window smaller, so it's this small size that gets saved, and then reused when you open AppleWin next time.

How can I make it open the same size all the time (preferably the smaller size)?

There is no command line (or other option) to force a window scale factor.
So the only way is to avoid resizing (ie. avoid using Ctrl+F6)...
Start AppleWin and if it's a large window size, then press Ctrl+F6 (so make it a smaller size).
Now never touch Ctrl+F6 again
