### ISSUE TITLE
Mockingboard not detected for Werewolf!!

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1260]
@GreatHierophant reported this on Slack:
>The game Werewolf, which was dumped late last year, advertises Mockingboard Speech and Sound support on its box. I have tried the game in AppleWin and cannot hear any speech or any music or sound effect that sounded like it was generated by a Mockingboard

From the BASIC program "H!O" on `Werewolf!! (4am crack) disk 1A.dsk`:

```
1  TEXT : POKE 1020,1: IF  PEEK (50176) = 255 THEN  GOSUB 1060
 :
1060  HOME : VTAB 10: HTAB 3: PRINT "DO YOU HAVE MOCKINGBOARD INSTALLED": HTAB 4: PRINT "IN SLOT #4 (STANDARD POSITION) ?": PRINT : HTAB 15: PRINT "Y)ES  N)O"
```

Address 50176 = $C400, so it's reading 6522 register 0 (IRB) and if it's 255 then it prompts the user to confirm there's a Mockingboard in slot 4.

AppleWin just returns ORB (ie. 0x00 after power-on) for a read of IRB, whereas it needs to use DDRB to set the input bits to 1's. (See #952)

**Comment by univta0001** [comment]
MAME is able to run Werewolf.

On inspection, on boot up, both $C400 and $C401 are with value 0xff.

The behavior of MAME implementation is as follows:

1) $C400 will return 0xff on boot up.
2) When $C400 is set with value (for e.g. 0xa5), the value of $C400 is still 0xff.
3) When $C402 is set to 0xff, the value of $C400 becomes 0xa5
4) Setting $C402 to 0x00, the value of $C400 becomes 0x00

The same behavior happens for $C401 with the corresponding $C403 changes.

**Comment by tomcw** [comment]
Thanks @univta0001 for confirming the MAME behaviour.
What you describe is as expected for ORB/IRB ($C400) and DDRB ($C402).

I will fix AppleWin, and also update [mb-audit](https://github.com/tomcw/mb-audit) to test these 6522 regs after a reset.

**Comment by tomcw** [comment]
Updated mb-audit (v1.50) to test these 6522 regs after a reset:
https://github.com/tomcw/mb-audit/commit/1504f0483dbf21dafb03e9aba1328aa6a60bc621

**Comment by tomcw** [comment]
btw, I strongly suspect that this "Werewolf!" weak Mockingboard check will also fail for the MEGA Audio card, as its 6522's IRB always(?) reads as 0x00. See the screenshot in the first comment here: https://github.com/tomcw/mb-audit/issues/9
