### ISSUE TITLE
Build error if DEBUG is defined

### ISSUE THREAD

**Issue by sh95014** [AppleWin/AppleWin#1265]
In z80.cpp, there's:

```c++
#if defined(DEBUG)
        if (debug.maincpu_traceflg)
            log_message(LOG_DEFAULT,
                        ".%04x %i %-25s A%02x F%02x B%02x C%02x D%02x E%02x "
                        "H%02x L%02x S%04x",
                        (unsigned int)z80_reg_pc, /*CLK*/ 0,
                        mon_disassemble_to_string(e_comp_space, z80_reg_pc,
                        p0, p1, p2, p3, 1, "z80"),
                        reg_a, reg_f, reg_b, reg_c,
                        reg_d, reg_e, reg_h, reg_l, reg_sp);
#endif
```

that would fail to build if `DEBUG` is defined, and those declarations seem to come from a debug.h that doesn't exist (anymore?). Seems like that should be `#ifdef DEBUG_Z80` or even `#if 0` instead.

Thoughts? (Right now I'm adding an extra `#ifndef` downstream to exclude the block, which seems unnecessarily gross.)

**Comment by audetto** [comment]
To my knowledge nobody defines `DEBUG`. It was probably a mistake, and nobody ever compiled it. This is why you get the error.

VS uses `_DEBUG` and in gcc it is normally `NDEBUG` but we don't use it here.

**Comment by tomcw** [comment]
I've renamed the DEBUG macro to DEBUG_Z80, and made all 4 instances of the code now read as:
```
#if 0 && defined(DEBUG_Z80)
```

This is just a hang over from pulling in this open source code from another project.
