### ISSUE TITLE
One on One (4am and san inc crack) does not boot on Enhanced //e with Mockingboard

### ISSUE THREAD

**Issue by sh95014** [AppleWin/AppleWin#1266]
1. Use disk image: https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/sports/one_on_one/One%20on%20One%20%284am%20and%20san%20inc%20crack%29.zip
2. Set emulator to Enhanced //e with Mockingboard in slots 3 and 4.
3. Disk boots to a garbled low-res graphics screen (normal), but then either hangs or beeps endlessly.

* Changing the configuration to //e or ][+ both work.
* Removing the Mockingboard makes Enhanced //e also work.
* Affects Linux and macOS ports also.

**Comment by xotmatrix** [comment]
Exact same issue in MAME. I don't have a Mockingboard to test on real hardware but it seems like a problem with the disk image. [4sports](https://github.com/a2-4am/4sports) version of One on One (san inc, prodos) fails to start for any machine with a Mockingboard under AppleWin and MAME.

**Comment by univta0001** [comment]
The failure seems to be due to calling the Mockingboard interrupt handling routine that resides in bank 2 at address $E9B3. In Apple 2e or ][+, the banking mode is set to Bank 2 but in enhanced 2e somehow Bank 2 is switch off using $c081 at ROM address $C449

**Comment by xotmatrix** [comment]
This Mockingboard/IRQ problem is confirmed by [Great Hierophant](http://nerdlypleasures.blogspot.com/2022/09/apple-ii-sound-cards-gaming-niche.html). It's described there as a 65C02 problem but testing under emulation appears to show that the presence of a 65C02 alone does not trigger it (not does the absence of a 65C02 fix it). It looks like it's an incompatibility with the Enhanced ROM as [univta0001](https://github.com/univta0001) says.

**Comment by sh95014** [comment]
Oh, wow! Thanks for all the informative responses!

"One on One will hang instead of run if run in a system with a 65C02 like the Enhanced Apple IIe or a system which simulates one like the Apple IIgs."

**Comment by xotmatrix** [comment]
@sh95014 This crack works on an Enhanced //e.
https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/collections/san_inc_prodos/one%20on%20one%2020k%20file%20PRODOS%20%28san%20inc%20pack%29.dsk
