### ISSUE TITLE
Printing AppleWorks Word Processor File to text file (ProDOS 1.1.1) (Apple //e) (AppleWorks 2)

### ISSUE THREAD

**Issue by Apple2edude** [AppleWin/AppleWin#1273]
I have been trying to print an AppleWorks word file to a windows text file through AppleWin. There have been multiple ways I tried to do this. The first one is using AppleWorks' print command to have it print to the text file, which was successful, but the result was not what I needed: 

![Screenshot 2024-01-18 120037](https://github.com/AppleWin/AppleWin/assets/157042114/574aaed5-71f1-4ff4-a74d-d1deaee12ac6)

After that, I started following [this](https://apple2.callapple.org/begin/articles/progtxted.html) website's directions so that it can print exactly what it looks like, and over trial and error, wielded this result:

![Screenshot 2024-01-18 120421](https://github.com/AppleWin/AppleWin/assets/157042114/120ab1ff-8a7e-4334-acc7-e385b979b323)

which is exactly what I needed. However, due to staring at my screen for hours trying to make it work, I forgot what I did. I was wondering if there was a specific configuration of settings that I need to do this.

**Comment by tomcw** [comment]
My suggestion is to use [CiderPress](https://a2ciderpress.com) or the newer [CiderPress II](https://ciderpress2.com).

Both have a built in viewer/converter for AppleWorks files:

```
AppleWorks 3.0 documents:

    Word processor to Rich Text Format (supports left/right margins, centering, bold, italic, etc).
    Database to CSV (suitable for import into Excel or other applications).
    Spreadsheet to CSV (for import into Excel or other spreadsheets; some formulas may not convert).
```

**Comment by Apple2edude** [comment]
Thanks for the helpful suggestion!
