### ISSUE TITLE
.po files wont load on latest applewin version

### ISSUE THREAD

**Issue by GIKAS123** [AppleWin/AppleWin#1280]
Here is my logfile:
CmdLine: -log -s7-empty-on-exit -h1  "C:\Apps\Apple 2 [TOSEC v2012-04-23]\Apple II - Games - [PO] (TOSEC-v2010-01-16_CM)\Balance of Power.po"
g_sStartDir = C:\Apps\AppleWin1.30.13.0\
AppleWin version: 1.30.17.0
Init: CoInitializeEx(), hr=0x00000000
Init: SysClk_InitTimer(), res=1
Init: GdiSetBatchLimit()
Init: GetProgramDirectory()
RegDeleteValue(.bin) failed (0x00000005)
RegSetValue(.woz) failed (0x00000005)
RegSetValue(DiskImage) failed (0x00000005)
RegSetValue(DiskImage\DefaultIcon) failed (0x00000005)
RegSetValue(DiskImage\shell\open\command) failed (0x00000005)
RegSetValue(DiskImage\shell\open\ddeexec) failed (0x00000005)
RegSetValue(DiskImage\shell\open\ddeexec\application) failed (0x00000005)
RegSetValue(DiskImage\shell\open\ddeexec\topic) failed (0x00000005)
Init: RegisterExtensions()
Init: FrameRegisterClass()
MBCardMgr::ctor() g_bDisableDirectSound=0, g_bDisableDirectSoundMockingboard=0
MockingboardCard::ctor: AY8910_InitAll()
MockingboardCard::ctor: Reset()
MockingboardCard::ctor: AY8910_InitAll()
MockingboardCard::ctor: Reset()
Main: LoadConfiguration()
Main: JoyInitialize()
Main: VideoInitialize()
Main: FrameCreateWindow() - pre
WM_CREATE
WM_CREATE: CreateGdiObjects()
0: Βασικό πρόγραμμα οδήγησης ήχου - 
1: SAMSUNG (Ήχος οθόνης Intel(R)) - {0.0.0.00000000}.{80c7c533-2439-40dc-9391-0cd2f7c40eee}
2: Ηχεία / Ακουστικά (Realtek High Definition Audio) - {0.0.0.00000000}.{3a9cb5de-899a-493c-9254-655bc7e0aea6}
Number of sound devices = 3
DSCreate succeeded for sound device #0
WM_CREATE: DSInit()
DirectInputInit: g_bDisableDirectInput=0
DirectInputUninit
DirectInputInit: DirectInputUninit()
DirectInputInit: DirectInput8Create(), hr=0x00000000
DirectInputInit: CreateDevice(), hr=0x00000000
DirectInputInit: SetDataFormat(), hr=0x00000000
DirectInputInit: SetCooperativeLevel(), hr=0x00000000
DirectInputInit: Acquire(), hr=0x00000000
DirectInputInit: SetTimer(), id=0x00000001
WM_CREATE: DIMouse::DirectInputInit()
Spkr Config: soundtype = 1 (WAVE)
Spkr_DSInit: SetVolume(0) res = 00000000
Spkr_DSInit(), res=1
WM_CREATE: SpkrInitialize()
WM_CREATE: DragAcceptFiles()
WM_CREATE (done)
FrameCreateWindow: SetTimer(), id=0x00000002
Main: FrameCreateWindow() - post
Init: DoHardDiskInsert(HDD1), res=0
Main: DebugInitialize()
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
Main: MemInitialize()
Unable to register for PrintScreen key(s):

. PrintScreen
. Shift+PrintScreen
. Ctrl+PrintScreen
Main: RegisterHotKeys()
Main: HookFilterForKeyboard()
Main: DiskReset()
Main: HDDReset()
Main: Snapshot_Startup()
Main: EnterMessageLoop()
MBCardMgr: DSGetSoundBuffer(), hr=0x00000000
MBCardMgr: DSZeroVoiceBuffer(), res=1
MBCardMgr: SetVolume(), hr=0x00000000
WM_CLOSE
KillTimer(g_TimerIDEvent_100msec), res=1
WM_CLOSE (done)
WM_DESTROY
DirectInputUninit
DirectInputUninit: Unacquire(), hr=0x00000000
DirectInputUninit: KillTimer(), res=1
WM_DESTROY (done)
Main: LeaveMessageLoop()
Main: DSUninit()
Main: UnhookFilterForKeyboard()
Exit: SysClk_UninitTimer()
Exit: CoUninitialize()
*** Logging ended

Everything else works fine and the problem focuses only on the .po files with the error message: ''failed to insert harddisk(s)''

**Comment by tomcw** [comment]
"Balance of Power.po" isn't a harddisk image - it's a floppy image.

Use this command line:
> -log -s7-empty-on-exit -d1 "C:\Apps\Apple 2 [TOSEC v2012-04-23]\Apple II - Games - [PO] (TOSEC-v2010-01-16_CM)\Balance of Power.po"

NB. I just changed "-h1" to "-d1".

**Comment by GIKAS123** [comment]
> "Balance of Power.po" isn't a harddisk image - it's a floppy image.
> 
> Use this command line:
> 
> > -log -s7-empty-on-exit -d1 "C:\Apps\Apple 2 [TOSEC v2012-04-23]\Apple II - Games - [PO] (TOSEC-v2010-01-16_CM)\Balance of Power.po"
> 
> NB. I just changed "-h1" to "-d1".

Hey! Sorry for the delayed responce! So the thing is that if I try to load any .po game as a floppy it just refuses to work and I get a screen like this
![image](https://github.com/AppleWin/AppleWin/assets/89347312/eab4500c-86a4-41b6-bac9-539102d594e5)
All other types of files work perfectly

**Comment by tomcw** [comment]
It looks like you are getting your images from here, right?
https://ia902908.us.archive.org/view_archive.php?archive=/25/items/Apple_2_TOSEC_2012_04_23/Apple_2_TOSEC_2012_04_23.zip

There shouldn't be anything wrong with .po images.
In fact, I tried this one (at random) and it works:
https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/Flapple%20Bird%205.25.po

**Comment by GIKAS123** [comment]
> It looks like you are getting your images from here, right? https://ia902908.us.archive.org/view_archive.php?archive=/25/items/Apple_2_TOSEC_2012_04_23/Apple_2_TOSEC_2012_04_23.zip
> 
> There shouldn't be anything wrong with .po images. In fact, I tried this one (at random) and it works: https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/Flapple%20Bird%205.25.po

Yeah thats where I gotthe files from... 

That file you sent me worked fine! However on many of the other .po files I get the same error.. .I tried switching machines and even clones but nothing worked sadly... .do .dsk and .nib files work perfectly on everything I tried

**Comment by tomcw** [comment]
These images: "Balance of Power (1987)(Mindscape)[cr Coast to Coast].po" and "Baltic 1985 (1984)(SSI).po" are corrupt.

I can reproduce your AppleWin crashes.
And I tried in the latest MAME 0.262, and this also gives identical crashes.

If you want to play these games, then find alternative images.

**Comment by xotmatrix** [comment]
I believe the problem is those disk images are in DOS Order (`*.do`), not ProDOS Order (`*.po`). If they are renamed with `.do` or `.dsk` extensions, they should work (eg. Balance of Power works when renamed). Or you can use a utility like CiderPress to convert them to proper `.po` disks and then they will work correctly in emulators and with ProDOS block devices. This is a problem that is merely annoying with `.dsk` files that could be in either order, but `.do` and `.po` specify a _specific order_ and there are way too many disks (ProDOS and otherwise) with .po extensions but with DOS Order sectors, even from people who should know better.

**Comment by tomcw** [comment]
Thanks @xotmatrix, you've got it!
Renaming these .po's with an extension of either .do or .dsk allows the image to work (I confirmed for both images).

As a minimum I will add a comment to the Troubleshooting part of the help doc.

**Comment by GIKAS123** [comment]
> I believe the problem is those disk images are in DOS Order (`*.do`), not ProDOS Order (`*.po`). If they are renamed with `.do` or `.dsk` extensions, they should work (eg. Balance of Power works when renamed). Or you can use a utility like CiderPress to convert them to proper `.po` disks and then they will work correctly in emulators and with ProDOS block devices. This is a problem that is merely annoying with `.dsk` files that could be in either order, but `.do` and `.po` specify a _specific order_ and there are way too many disks (ProDOS and otherwise) with .po extensions but with DOS Order sectors, even from people who should know better.



> Thanks @xotmatrix, you've got it! Renaming these .po's with an extension of either .do or .dsk allows the image to work (I confirmed for both images).
> 
> As a minimum I will add a comment to the Troubleshooting part of the help doc.

Thank you both so much! The renamed disks finally work perfectly!
