### ISSUE TITLE
Reason for asking 42 tracks version in emulator in window

### ISSUE THREAD

**Issue by ngchungtak** [AppleWin/AppleWin#1282]
I have cracked captain good night but I need two more tracks for single side even I have used 40 tracks. So that I need 42 tracks version in window apple II e emulator. Thanks for your reading ! I should be grateful if you can add a parameter in config. for allowing change to 42 tracks in emulators.

**Comment by xotmatrix** [comment]
qkumba got Captain Goodnight down to 262 blocks that could fit on 33 tracks. Crack harder.

**Comment by tomcw** [comment]
I agree - this isn't a strong enough use-case for increasing the track count.
Closing as: won't fix.

**Comment by ngchungtak** [comment]
Thanks for your reading !
