### ISSUE TITLE
AppleWin Mockingboard/Phasor emulation issue, some voices don't play.

### ISSUE THREAD

**Issue by RetroGamer1971** [AppleWin/AppleWin#1283]
Good Day you you fine folks!

Firstly, I apologize for the length of this message. Just wanted to give all details possible.
My name is CJ and I wanted to compliment you on this wonderful app! I just downloaded and unzipped this yesterday and began playing. It is so easy to use and perfectly emulates my old Apple IIe just as I remember it in my teens! My favorite games to play were the Ultimas but I never was able to acquire the sound cards of the day and my MIDI interface never worked in the game so this app made my wishes come true.
Anyway the issue I found is probably minor but still annoying. I setup AppleWin with 2 Mockingboards in the assigned slots 4 & 5 and ran Ultima IV and V. I setup music for them and the 12 voices displayed and tests worked perfectly. A couple hours after taking a break from running AppleWin, I came back to play it, making no changes, but now several of the Mockingboard voices are no longer playing on Ultima IV or V (the only games I've played in the emulator). It seems only the background/rhythm sounds output now. I don't get the "main" notes. I tried clearing out the slots and running empty slots then reinstalling them, same issue. I tried using only 1 slot at a time but only the same sounds play no matter what Mockingboard type or which slot I use (4 or 5). I even tried using the Phaser(sp?) card (which I had no experience with before) as the Help file says the Phaser is equivalent to 2 MBs, but that only produced the same sub-sounds, if you will, whether in slot 4 or 5. I even deleted all AppleWin files and app, in the folder I unzipped them to, and re-unzipped all files for the 1.30 version in the same folder, hoping to remove some config that was saved with the unwanted change I could not reverse but still have the sound board issue.if I had known I would have saved the State it was in when working well. Can you help me with this? Could it be specific to these games? But they ran great, as intended originally for quite a while. Is AppleWin saving settings somewhere other than my created root folder? Does my description make sense? :P 
Again sorry for the lengthy message. I hope to hear back soon and have a great day. Contact me here or I can offer my personal email for further contact. Thank you again and Great job on this, really! 👯‍♂️

**Comment by tomcw** [comment]
I gave AppleWin 1.30.17.0 a quick go with Ultima V, with MBs in slots 4 and 5 - and it works fine.
(I assume you are using 1.30.17 too?)

Some things to try:
- check you've setup Ultima V with MBs in slots 4 & 5... eg. if I configure Ultima with MBs in slots 3 & 4, then I just get the "bass line" playing.
- check your speaker hardware... are both speakers working?
- generate a save-state file (F11) at the point it's not working, zip it up and attach it to this issue.

**Comment by tomcw** [comment]
As an aside (but for completeness!), I also configured AppleWin with: slot4=Phasor and slot5=MB; then...

1.  configured Ultima V with slot4=Phasor, which works fine.
    - as it should, as Phasor starts up as a MB-C
2.  but then I re-configured Ultima V with slot4=MB-C and slot5=MB-C... and this also results in just the "bass line" playing.
    - a bug in Ultima V, since the Phasor card has not been switched back to MB-C mode

**Comment by RetroGamer1971** [comment]
Thank you Tom for the quick response and tests. Yes, it was a speaker issue. I experimented with the volume mixer on Windows speaker settings and had to adjust the Balance setting and got all voices back. It turned out my daughters were playing around and messed up one the the speaker's connection. With all music and sounds working I played for over an hour until a disk read froze the emulator. Annoying to lose all that progress but I just have to remember to "Save often!" which has been an RPG video game adage since I started playing in the 80's!
~CJ    On Sunday, February 25, 2024 at 11:49:48 AM PST, TomCh ***@***.***> wrote:  
 
 


As an aside (but for completeness!), I also configured AppleWin with: slot4=Phasor and slot5=MB; then...
   
   - configured Ultima V with slot4=Phasor, which works fine.      
      - as it should, as Phasor starts up as a MB-C

   - but then I re-configured Ultima V with slot4=MB-C and slot5=MB-C... and this also results in just the "bass line" playing.      
      - a bug in Ultima V, since the Phasor card has not been switched back to MB-C mode

**Comment by tomcw** [comment]
>Yes, it was a speaker issue.

That's good to hear your figured it out!

>Annoying to lose all that progress but I just have to remember to "Save often!" which has been an RPG video game adage since I started playing in the 80's!

Yep! :-)
btw, you can save the Apple II computer state using F11, and you can do this at any time (not just when Ultima V lets you).
