### ISSUE TITLE
CPU emulation: AppleWin crashes when doing a 16-bit read from 6502 address 0xFFFF

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1285]
Repro from debugger:
- out c083  ; set LC to HIGH RAM mode
- fffe: cd 00 20 ; CMP $2000
- 2000: ea
- r a=ea
- r pc=fffe
- \<SPACE\> to step

This will cause AppleWin to crash! ...because `mem+64K` is unmapped.
(Correct result is to set Z=1, and not crash :-)

A simple fix for this is to `mmap` (or the equivalent under Windows) so that virtual addresses `mem` and `mem+64K` both point to the same physical 64K "page".

**Comment by tomcw** [comment]
In PR #1286, I've gone for the "poor workaround" which will work on pre-Windows 10 OS's.

**Comment by audetto** [comment]
Disclaimer: I have not debugged anything.

I was thinking at the implications of this and how to implement it in a system without sophisticated `mmap` abilities.

1. Single byte reads can be solved with `& $FFFF`
2. Multi byte could be turned into many single byte reads
3. BTW, do they wrap only at `$FFFF` or at every `$FF`?
4. How does this interact with the idea from https://github.com/AppleWin/AppleWin/issues/795#issue-630380206

If multi byte reads are allowed and don't wrap at every page, the idea of multiple small physical pages and an extra indirection is dead.

So the question for me is: should multi byte reads be allowed?

**Comment by tomcw** [comment]
>2. Multi byte could be turned into many single byte reads

That's correct, but the issues are:
a) having to rewrite some of the 6502 emulation code to switch from a 16-bit read to 2x 8-bit reads (+ write tests for all this)
b) expect some performance loss

So it's a lot of work _just_ for this `$FFFF` edge-case (which in 20+ years nobody has ever raised).

The great thing about this "circular buffer" solution is that there's no need to do (a) or be impacted by (b).
Therefore it's a cheap solution with zero impact on existing code.

>3. BTW, do they wrap only at `$FFFF` or at every `$FF`?

Just at `$FFFF`.

>4. How does this interact with the idea from https://github.com/AppleWin/AppleWin/issues/795#issue-630380206

That's another idea...

In addition to your point-2 (turn multi-byte into many single-byte reads) this idea is about doing all byte reads through page pointers (just as AppleWin currently does for byte writes). NB. currently AppleWin maintains a flat, contiguous 64KiB `mem` buffer for any read (except for the I/O area at $Cnnn).

**Comment by tomcw** [comment]
>So the question for me is: should multi byte reads be allowed?

If we can do this "circular buffer" (eg. via `mmap`) then it's a cheap solution for this extreme edge case.
