### ISSUE TITLE
Providing Apple //gs emulation in AppleWin

### ISSUE THREAD

**Issue by ajack2001my** [AppleWin/AppleWin#1289]
Is this something in the pipeline? Is @tomcw or any other developer interested in doing this? Sorry if this was asked before, I did a search, but nothing came out and I was surprised nobody asked before.

**Comment by sicklittlemonkey** [comment]
Basically a separate computer, so rather unlikely.
ISTR somebody did do a PR for GSPlus which added II, IIe, IIc support, but
it was rejected because it was stale by the time it was evaluated. ; _ ;

Cheers,
Nick.

**Comment by xotmatrix** [comment]
I expect the Apple IIgs emulator Crossrunner will support earlier models long before AppleWin supports the GS.

**Comment by tomcw** [comment]
I found this #491 (but this is more about a specific IIgs game, than requesting that AppleWin support IIgs machines).

If you want an all encompassing emulator for Apple II 8 & 16-bit machines then MAME is the best (and only?) option.
Or speak to @ibrumby about CrossRunner (or Kent Dickey about KEGS).

Anyway, I agree with Nick's comment.
Closing as won't fix.
