### ISSUE TITLE
save state and (absolute) disk path

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#1290]
In a `.aws.yaml` file only the filename of a floppy is saved.

There are times when it is desirable to have the state full independent and store all the absolute paths.
Other times, I guess, one wants to move the state files (and disks around), so a relative path is more appropriate.

Would it be acceptable to add some flag so that the absolute path is stored in the yaml file?

**Comment by sicklittlemonkey** [comment]
It could also check for the file first, then use the full path if it wasn't found. (Another thing to argue about!)

**Comment by audetto** [comment]
The *flag* is not obvious, since there are no free arguments to use.
Storing the full path and use it is as a fallback is probably a better idea.
Or even making it fully relative from the save state paths.

At the moment, this works if the `chdir` is in the right position, otherwise it opens a file dialog.
But with up to 6 disks inserted, this can't really scale.

It depends a bit what are the accepted use cases of save files.

**Comment by tomcw** [comment]
Yes - what you are both saying...

On loading a save-state:

1. Try loading the current path + filename
2. If that fails then try loading the save-state's absolute path + filename
3. If that fails then prompt the user to locate the file

So for floppy disks & harddisks, just add an extra "Absolute path" (eg. after the "Filename") in the save-state file.

**Comment by tomcw** [comment]
Fixed in PR #1294. Closing.
