### ISSUE TITLE
Possibility to add tooltip to AppleWin icons

### ISSUE THREAD

**Issue by wyatt-wong** [AppleWin/AppleWin#1291]
Is it possible to add tooltip to AppleWin icons ?

**Comment by tomcw** [comment]
Which icons would like want tooltips for?
(And what info would the tooltips display?)

NB. the Drive1 and Drive2 icons already show tooltips - showing which disk is mounted in that drive.

**Comment by tomcw** [comment]
Closing as invalid due to lack of details.
