### ISSUE TITLE
Floppy Disk Format?

### ISSUE THREAD

**Issue by Degamisu** [AppleWin/AppleWin#1306]
What format do i use for new floppies? im using cider press. thanks

**Comment by tomcw** [comment]
Using CiderPress II, then "Create Disk Image" defaults to 140KB / ProDOS / Unadorned ProDOS-order (.po)... this seems like a good one to use. I guess it also depends on what you plan to do with the new image.

**Comment by Degamisu** [comment]
nice! im new to applewin, i used ciderpress I and not II

**Comment by Degamisu** [comment]
got an error:

`UNABLE TO OPEN PRODOS`

i did the format you said to do.

**Comment by tomcw** [comment]
This is correct - CiderPress has just created a blank disk (in ProDOS-order) without any bootable DOS.

Like I said, it depends what you plan to do - what's your intention?

**Comment by Degamisu** [comment]
quite simple really, I made an Apple Basic script I want to run. I am sort of new to the floppy directories, as i usually just let my //e save for me. the code looks like this (draws the mandelbrot set):

MANDELBROT.BAS
```basic
10 HGR
20 X1=-2.5: X2=1.5: Y1=-1: Y2=1
30 DX=(X2-X1)/279: DY=(Y2-Y1)/159
40 FOR Y=0 TO 159
50 FOR X=0 TO 279
60 A=0: B=0: C=X1+X*DX: D=Y1+Y*DY
70 COLOR = 0
80 FOR I=1 TO 50
90 T=A*A-B*B+C
100 IF ABS(T) > 1E10 THEN COLOR = I: GOTO 130
110 B=2*A*B+D
120 IF ABS(B) > 1E10 THEN COLOR = I: GOTO 130
130 A=T
140 IF A*A+B*B>4 THEN COLOR = I: GOTO 150
150 NEXT I
160 IF COLOR = 0 THEN COLOR = 15 ' Inside the set, color black
170 HCOLOR=COLOR
180 HPLOT X,Y
190 NEXT X
200 PRINT "COMPLETED ROW "; Y
210 NEXT Y
```

**Comment by Degamisu** [comment]
got it to work finally. just had to format it to DOS 3.3 and not PRODOS.

**Comment by Degamisu** [comment]
## UPDATE

I might be stupid, but i cant figure out how to convert the text from a bas file into something the IIe can read. The first line is always a jumbled up mess which breaks the code.
