### ISSUE TITLE
WOZ: Infocom Shogun fails to boot

### ISSUE THREAD

**Issue by angstsmurf** [AppleWin/AppleWin#1315]
The woz-a-day version of Infocom's Shogun available at the Internet Archive will display a disk error at the title screen. Works fine in MAME. 

https://archive.org/download/wozaday_Shogun/Shogun%20%28woz-a-day%20collection%29.zip

**Comment by tomcw** [comment]
Thanks for reporting this.

Reproduced (using HEAD, later than AppleWin 1.30.18)

![Shogun - Side 3_000000000](https://github.com/AppleWin/AppleWin/assets/6696896/a2feeb4d-9c35-48d7-909a-cae1a36c1982)

---

cf. Zork Zero / #926

>"Having problems reading side `#3`, please reinsert it." Then the game will report "Disk I/O Error, Please hit [RETURN]"

If I apply the same "fix" (as discussed in that issue), then Shogun boots.
IE, after this line:

https://github.com/AppleWin/AppleWin/blob/a88040c3eff43120b7612afa85aa5cee4e4c5665/source/Disk.cpp#L698
```
	if (stateChanged) m_magnetStates = 0;
```

**Comment by tomcw** [comment]
@angstsmurf - this got fixed in AppleWin 1.30.19 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.19.0).

**Comment by angstsmurf** [comment]
Great!
