### ISSUE TITLE
WOZ: Pollywog fails to boot

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1316]
in v1.30.18.0, I see a "bad dynamic_cast" on start.  MAME runs okay, so I think that the image is intact.

[Pollywog - Disk 1, Side A.zip](https://github.com/user-attachments/files/16035699/Pollywog.-.Disk.1.Side.A.zip)

**Comment by tomcw** [comment]
Hmm... with that version (and HEAD) I just see "ERR1" top-right corner, then it clears the screen to inverse "C"s, then repeats.

If you get a "bad dynamic_cast", can you attach a (zipped) save-state file before this crash.

**Comment by peterferrie** [comment]
The system is in a bad state.  I can't even select the floppy drive from
the UI.  I have to use F8.
Boot PROM is missing.  I broke something.

**Comment by peterferrie** [comment]
[b1.aws.zip](https://github.com/user-attachments/files/16037459/b1.aws.zip)

**Comment by peterferrie** [comment]
My mistake.  The missing boot PROM was the hint.  Somehow in the registry, slot 6 card was zeroed.  Separately, if you write-protect the WOZ then it boots.

**Comment by tomcw** [comment]
Thanks for the save-state file.

The behaviour that I'm seeing is a crash to monitor at $C60F.

Your slot setup:
- 7: hdc with 4cade.hdv attached as the 2nd HDD unit (and no 1st HDD unit)
- 6: empty slot
- 5: diskii controller, with PollyWog.woz in the 1st drive

Note: After the crash to the monitor, `C500G` boots the game.

The reason for the monitor crash, is that the hdc firmware checks for a HDD attached (as the 1st unit). There isn't, so it does `JMP C600`... and crash to monitor (as there's no code at C600, just floating bus data).

NB. I don't see "bad dynamic_cast".

I will resolve this as invalid.

**Comment by peterferrie** [comment]
Yes, invalid is fine.  The problem was registry corruption on my side.  I
don't know how, but there is no bug,
