### ISSUE TITLE
Support for Applied Engineering RAMWorks II

### ISSUE THREAD

**Issue by airnocker** [AppleWin/AppleWin#1336]
Hi, I've been using AppleWin sin 1.26.1.1 from 2017 and have used it quit a lot in 2018-2021 for updating some Apple II/IIe source codes I developed back in 1978-1987  I used in the laser entertainment business.  We used AE's RAMWorks II primarily as RAM drives in Apple IIe's in conjunction with the AE TimeMaster RT clock board along with four 65C02 32K SRAM coprocessor boards, each driving 4 8bit dual, multiplying DACs.

Using AppleWin with Bob Sander-Cederlof's S-C Assembler 2.0 loaded into regular Apple memory to modify and update these source code files worked fine as long as I first booted AppleWin with a DOS3.3 bootable disk.  The source code updating made the work go so much faster and easier with a Windows keyboard and in conjunction with CiderPress and Kyroflux utilities, even though I still have and use (occasionally) my 1983 Apple IIe w/the RAMWorks II card and S-C Assembler.  Normally, with the IIe, we would used the prescribed method for loading the S-C Assembler 2.0 to run from the RAMWorks II board.

I see that AE's RAMWorks III memory expansion board has been supported for a while and request consideration to include the RAMWorks II board as well, for the above stated reason.

I also want to report some issues that I've experienced recently when using AppleWin 1.30.14.1 in Monitor mode for changing memory location values using my Win10Pro 22H2, Build 19045.5011 with 32GB of memory on an Intel Core i5-10400F, 6-Core clocked at 2.90GHz.  Simply changing a single memory address value with  407F:FD<Return> would give the normal monitor mode screen indications that action was performed but when viewing this memory address with 407F<Return> it was not updated.  This happened randomly but frequently in a single AppleWin session.  This would also happen occasionally when running an Applesoft program that would read binary file data loaded into memory and convert a 2's complement 2K array of values into integer values.  Rebooting AppleWin would typically resolve these issues.

Today I downloaded AppleWin 1.30.17.0 and will see if these behaviors have been resolved.

Thanks for your support of AppleWin!

**Comment by tomcw** [comment]
This is a request for AE's RAMWorks II.

btw, the other issue reported:
>in Monitor mode for changing memory location values

Given the maturity of AppleWin, if something fundamental like this didn't work, then we'd be getting a deluge of reports (which we've not). So if this is truely an issue, then there must be other factors. If it continues to occur, then raise a new issue; but let's keep this issue just for the RAMWorks II request.

**Comment by tomcw** [comment]
RAMWorks II User Manual here:
https://mirrors.apple2.org.za/ftp.apple.asimov.net/documentation/hardware/ae/AE%20RAMWorks%20II%20User%27s%20Manual.pdf

**Comment by airnocker** [comment]
Thanks for your reply TomCh.

I was implying that the monitor mode memory "writes" were systemic.  As I
mentioned, I've used AppleWin version 221128A for hundreds and hundreds of
hours since 2018 and never experienced this issue until recently.  I
thought it worth reporting, but I am glad to hear that no one else has
experienced this.

I agree to limit my feature request for AE RAMWorks II emulation in
AppleWin.  I've owned and used mine in my IIe since 1984.

Thank you for the RW II PDF manual.   I appreciate the thought. I do have
my original which I scanned to PDF years ago.

Alden
______________________________
Everything Depends on Everything Else

**Comment by sicklittlemonkey** [comment]
> when viewing this memory address with 407F

How are you writing to and viewing this memory address?

**Comment by airnocker** [comment]
Hi Nick,

As I stated in my first email, when in Monitor Mode I *write* to any free
memory address allocated for my 2D array data as follows:
start address:hex value<space>hex value etc. <Return>
As an example to what I recently experienced randomly on multiple
occasions, let us assume $407F and $4080 have values of $00 and $FF
respectively.

I would type:
*407F:32 20<Return>   to write $32 and $20 into $407F and $4080 memory
addresses respectively.

To view (read) these memory locations in Monitor Mode I type:
*407F.4080<Return>  and would expect to see...
*32 20

...but would see no changes and instead get back
*00 FF

I'm an experienced old timer at this.

I'm using a logitech wireless keyboard with my Win10Pro system and at first
thought it must be a kbd glitch, but I get no other kbd glitches from
anything else I use my computer for.  But even with fresh batteries and the
USB bluetooth receiver 6 inches away from the keyboard it still would
occasionally happen.

Trying up to 2 or 3 times to change the memory location values would be to
no avail but by the 3rd or 4th time the new values would be reflected.


Alden
______________________________
Everything Depends on Everything Else

**Comment by sicklittlemonkey** [comment]
Hi Alden. Thanks for the details.

As Tom said, if writing to memory was broken - even intermittently - nothing would work. ; - )
So you must be experiencing a more nuanced problem.
Fortunately, this is where an emulator might be able to help …

Get ready to write your data, then hit F7 to enter the AppleWin Debugger.
Type the following:
bpmw 407F
That adds a memory breakpoint on writes to 407F.
Then hit F7 again to exit, and attempt your write to 407F.
You should end up back in the debugger with a message such as:
Stop reason: Memory access at $407F

At this time you could also check the Soft-switches area of the display.
In particular you would want to check the state of RAMWRT (the 02 line).
![Soft-switches area of the Debugger](https://github.com/user-attachments/assets/28ceae56-735d-48e6-975a-17dddb5863f2)

I hope that helps you find the source of the problem.

Cheers,
Nick.

**Comment by airnocker** [comment]
Not sure if I should make sure you understand that this behavior has
NOTHING whatsoever to do with the RAMWorks II card and only applies to the
standard lower 48K memory range of AppleWins IIe emulation.

Alden
______________________________
Everything Depends on Everything Else

**Comment by airnocker** [comment]
Thanks for the debugger tip.  I've known of the AppleWin Debugger,
activated the screen but never used it.

Again, my example was arbitrary and simple.  It is rare that I'm only
changing a single memory address value.
BUT! I will now try opening the debugger screen the next time this happens.

PLUS, I upgraded from 1.30.11.0 to 1.30.17.1 a few nights ago and didn't
experience any issues BLOADing binary blocks and editing them in Monitor
Mode.

Alden
______________________________
Everything Depends on Everything Else

**Comment by tomcw** [comment]
>This is a request for AE's RAMWorks II.

I've looked at both RamWorks II and RamWorks II manuals, but I'm struggling to see what is different between these cards!

Both have 32 sockets for RAM chips, which can be combinations of 64KiB or 256KiB. So if all sockets are populated with 256KiB RAM, then this gives a total of 8192KiB = 8MiB.

Also both use the I/O location $C073 to set the current 64K bank.

Can anyone explain the difference between the cards?

**Comment by airnocker** [comment]
I have the RamWorks II board with the 512MB expansion board for a total of
1.5MB so mine is fully populated with 64KB chips.

I have manuals for both RamWorks II & III.

1.5MB was the max memory for RW II, 2MB for RW III.  RW III supported
doubled hires graphics with 820-64-B and IIe enhanced motherboards.

You could mix 64 and 256KB chips but only in a manner that did not exceed
the max allowed memory capacity, 1.5MB for RW II and 3MB with RW III when
using memory expander boards.

8MB was not possible.

Alden
______________________________
Everything Depends on Everything Else

**Comment by tomcw** [comment]
>1.5MB was the max memory for RW II

So if you start AppleWin like this, then you'll get 1.5MiB:
`>applewin.exe -r 24`

ie. 24 x 64KiB = 1.5MiB

**Comment by airnocker** [comment]
Thanks.

Well, that may be helpful if executing applewin.exe with that "switch"
enables the use of RW II's RamDrive functionality for use with DOS 3.3.
Page 13, Chapter 5 of RW II's User Manual discusses using the 1.5MB memory
expander as RamDrives.
Being able to execute in AppleWin the DOS command  ]PRINT CHR$(4); "BRUN
RAMDRIVE,S5,D1" is what I'm wishing for.

You think it will? (fingers crossed)

Alden
______________________________
Everything Depends on Everything Else

**Comment by airnocker** [comment]
It worked!

Thanks Tom!!


Alden
______________________________
Everything Depends on Everything Else

**Comment by tomcw** [comment]
That's great!

btw, if you want, you can add more RAM (up to 8MiB), eg:
`>applewin.exe -r 127`

Since this is working, let me close this.

**Comment by airnocker** [comment]
Yes, please!

I surmised that the 8MB limit was an ApplWin one.  But I just needed an
accurate RW II 1.5MB emulation.
