### ISSUE TITLE
Ramworks bank count

### ISSUE THREAD

**Issue by burniouf** [AppleWin/AppleWin#1349]
Why Ramworks emulation is set as a maximum of 127 pages in the range of 0..126 page numbers ? 
should be 128 for a range of 0..127.... or even 256 for having maximum range of 0..255 page numbers. 

![image](https://github.com/user-attachments/assets/5a4c046d-993c-49f7-b513-d829c7fb47a1)

**Comment by tomcw** [comment]
It looks like the current total Apple //e memory you can have is **exactly 8MiB**, ie. 64KiB main memory + 127 x 64KiB aux memory.

So if I allow 256 x 64KiB of aux memory, then the total Apple //e memory would be: 16MiB + 64KiB.

**Comment by tomcw** [comment]
btw, there's already a feature request for this here: #478.

So let me classify this as a question, and close it.
(Also it's trivial to extend for 16MiB, so I'll so the milestone for this request to the next AppleWin release)

**Comment by burniouf** [comment]
An Apple //e can have 64k main memory, + 64k AUX memory.
Ramworks trick was to "multiply" 64k AUX memory, with default //e AUX bank set as bank 00.
Additional logic was added on ths board to ALWAYS use bank 00 for displaying TEXT80  & DHGR. but up to 128 banks were possible from 00 to 7F. Some modern clones extanded to 00..FF

So an Apple //e can have potentially 64k MAIN + 16mb AUX
