### ISSUE TITLE
PR#6 does not completely reset the machine state

### ISSUE THREAD

**Issue by sh95014** [AppleWin/AppleWin#1354]
**Note from downstream**
https://github.com/sh95014/AppleWin/issues/50 was filed by @callapple against the macOS port, but issue is present in Windows (and Linux) so I'm sending this upstream. Sorry, but I'm not able to test on actual hardware right now.

**Describe the bug**
PR#6 in DOS 3.3 does not reset the machine start and perform a startup, with the Apple //e at the top of the screen

**To Reproduce**
1. Boot DOS
2. do a PR#6

**Expected behavior**
Machine state should clear screen, place Apple //e at top of screen and boot current floppy / HDD

**Actual behavior**
Just boots disk and places user in a continuation of DOS further down the screen

**Screenshots**
![Screenshot 2024-12-29 at 10 06 32](https://github.com/user-attachments/assets/a720e542-2297-4eac-9a8d-cb8518c590d5)

**Comment by xotmatrix** [comment]
This is the expected behavior for a floppy disk controller in slot 6.

**Comment by tomcw** [comment]
Yes, as @xotmatrix says this is expected behaviour.
(Closing)
