### ISSUE TITLE
Problem running Wrath Of Denethenor  

### ISSUE THREAD

**Issue by H82lose** [AppleWin/AppleWin#204]
Wrath Of Denethenor hangs in Applewin's latest version ,  just gets to the title screen ,  shows a small rectangular box with the author's name ,  flashes back and forth ,  also the drive icons flash back and forth ,  makes a terrible noise ,  and that's as far as you can get with this game .   I know ,  and I'm not sure of the actual Applewin version ,  but at one time I was able to run Wrath Of Denethenor!   

Just thought you would like to check this out..

thanks..

Patrick.

**Comment by tomcw** [comment]
Fixed in  5fdc879  / AppleWin 1.26.0.1.
