### ISSUE TITLE
Pig-Font Chip.

### ISSUE THREAD

**Issue by H82lose** [AppleWin/AppleWin#205]
Anyway of adding the customized Pig-Font Chip?   This would be the same chip that is under the II+ Keyboard ,   that houses all the characters that display on the screen ,  but this rom would be so so so much better ,  this would not only have all the upper and lower case characters but all the really cool  characters like -

Skull & Crossbones
LIttle Apple ( with byte missing out of it  :O)  )
Little Piggie  that faces  to the left , right ,  and center

etc....    

  I can send you the rom image if you like ,  it's just a small rom image and I think this would be an awesome addition to the II+ model  :O)   You don't even have to have an option to enable it ,  it will just always be there when some one wishes to use these particular characters .

Thanks...

Patrick.

**Comment by tomcw** [comment]
Now AppleWin support video ROMs for the Enhanced //e (#574), it should be pretty simply to extend for custom 2K TEXT ROMs for II/II+ machines.

Perhaps just overload the cmd-line switch `-videorom <file>`... if the ROM size is 2K, then replace the II/II+ video ROM.

**Comment by tomcw** [comment]
![pig-font](https://user-images.githubusercontent.com/6696896/48738261-4a1cc500-ec48-11e8-8e19-2192c7715b6b.png)

(Second 64 char block is flashing)

**Comment by tomcw** [comment]
Added tests here: https://github.com/AppleWin/AppleWin-Test/commit/2e9799335000119eb5703ca26af21942fbb8dfca.

**Comment by tomcw** [comment]
@H82lose , @Keatah : There's a new build 1.27.13, [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.13) which supports this feature.
