### ISSUE TITLE
Debugger G(o) command should use normal speed

### ISSUE THREAD

**Issue by sicklittlemonkey** [AppleWin/AppleWin#217]
Full-speed might have been needed in the past or in certain circumstances (trace?) but debugging emulation speed needs to be slowed down to 1MHz - usually because you need to control some game etc to hit a breakpoint.

**Comment by tomcw** [comment]
As discussed in #384, I have started to support a revised g(o) and a new gg debugger command at these commits: 0b6c5bb and 743add8.

The "spec" (now extended to include speaker/Mockingboard sound) is:

command | run at normal speed | run at full speed | video quality | sound quality
--|--|--|--|--
g(o) | yes | only if disk active, etc | precise(*) | precise
gg | no | always | periodic | muted

Video quality: (*)
- When running with g(o)
  - (normal speed), then it's assume there's enough PC time to render the video per 6502 cycle.
  - (full speed), then use periodic video update.
- When running with gg (full speed), then use periodic video update.

**Comment by Michaelangel007** [comment]
Tom, thanks for adding this patch. The  `go` and `gg` are good additions.

**Comment by tomcw** [comment]
There are still some edge-cases to straighten out, eg:

1. In MODE_STEPPING (`g` mode) ESCape will exit back into the debugger.
This means you can't use ESC to interact with the emulated Apple II.
IMO we shouldn't treat ESC specially. Instead the user can use either press F7 or click the Debug button.

2. Decide the behaviour for the cases when you do one of these actions:

- CTRL+RESET (eg. CTRL+F2 or CTRL+BREAK)
  - This seems OK and doesn't seem to affect MODE_STEPPING
- F2 (eg. reboot/power-cycle)
  - Currently this will just switch from MODE_STEPPING to MODE_RUNNING!
- Loading a save-state
  - Consider: running game1 and I have some breakpoints setup, then I load the save-state for game2 (where the BPs no longer make sense). Is this acceptable?
- Change configuration, eg. Apple II's h/w config
  - We probably want the same behaviour as loading a save-state.

**Comment by sicklittlemonkey** [comment]
> In MODE_STEPPING (g mode) ESCape will exit back into the debugger.
> This means you can't use ESC to interact with the emulated Apple II.
> IMO we shouldn't treat ESC specially. Instead the user can use either
press F7 or click the Debug button.

This pissed me off just tonight. I agree, ESC shouldn't be a special key,
just F7.

All the others are fine to leave the debugging state as is, I think.

Is it possible to turn off the debugger? For instance if there are
breakpoints set, they have to be cleared or F7 leaves the debugger enabled.

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
> Is it possible to turn off the debugger? 

Nick, my long term plans are:

* 6502 -- no debugger
* 65c02 -- no debugger
* 65d02 -- debugger

I'm willing to bet 80% of the users don't use (or even know) about the debugger.  The few that do, can manually switch to the psuedo 65d02 CPU.

**Comment by tomcw** [comment]
re. 65d02
Presumably you'll need variants for 6502 and 65C02?

**Comment by tomcw** [comment]
Closing this, as the above 2 commits address my comment from a week ago where I said:
>There are still some edge-cases to straighten out
