### ISSUE TITLE
Full screen: Option to turn off all drive status & keyboard caps state

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#224]
Full screen should be full screen, and not have any annunciators or indicators present. Or have the ability to turn them on and off.

**Comment by tomcw** [comment]
#168 is a mix of multiple requests (screen centring, hiding the drive/keyboard state). So I've renamed this issue to be specific for hiding the drive/keyboard state.

**Comment by tomcw** [comment]
FYI, new experimental build: [v1.26.3.2](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.2).
On the Configuration property sheet there's now a check box to toggle this UI.

NB. I still need to add this to the AppleWin.chm.

**Comment by tomcw** [comment]
Updated AppleWin.chm @ 64d8675. Closing.
