### ISSUE TITLE
Bug on "Enhanced Apple //e" mode?

### ISSUE THREAD

**Issue by bigladiesman** [AppleWin/AppleWin#237]
Hi, I'm just an unexperienced retrogemer who doesn't know much about advanced computing.

This morning, I was playing some roms with the emulator when I tried to open the game "Trek of the 49ers". When I clicked on the Apple icon to start it, the diagnostic screen (some colors and then a black screen with the message "SYSTEM OK" after a long beep) appeared instead of the game, and now jumps whenever I run any ROM on "Enhanced Apple //e" mode (works alright on the other modes). I tried deleting the emulator and re-installing it, and even reverting to olf versions, to no avail: colours, beep, "system OK".

Anyone knows how to fix this?

Thanks.

**Comment by tomcw** [comment]
The best way to triage this would be via a save-state file (eg. zip it up and attach to this issue).
Anyway, since this is >4 years old now (and I've never heard of anyone else with this issue) I am going to close it.
