### ISSUE TITLE
(Debugger) Save debugger "text screen" to clipboard / file ...

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#239]
From c.e.a2
https://groups.google.com/forum/#!topic/comp.emulators.apple2/LZiuwztHBMM

"When I have a page of disassembled text displayed on the Applewin debugger screen, what is the easiest way to get it to a print file on my PC.  For example, if I was using the Apple's monitor code (]call -151) to disassemble code, I would do "1<CTRL-P>" followed by something like "800L", or "800LLLLL", or "800.8FF" and AppleWin would put the text into Printer.txt on my PC.  I'd like to do the similar thing but from the Applewin debugger window. 

This would be especially helpful while displaying code in the upper memory ranges of $D000..$FFFF, when RAM is being used and its not the same as the monitor code. "

**Comment by Michaelangel007** [comment]
Another bump for saving the disassembly to a file from c.s.a2.

This bug should be split into 2 feature requests as they involve similar but different work.

* Save debugger "text screen" to clipboard
* Save debugger disassembly to file

Maybe add a new  `DISasm <range>`  command.

**Comment by Michaelangel007** [comment]
Another alternative would be to add a new command:

* `dsave "file",start,end`

**Comment by TigerLeep** [comment]
Is there any update on this?  I'm trying to figure out how to get an assembly listing from the AppleWin debugger to a file on my PC.  If I have to take screenshots and OCR it, I'll find a way, but it would be wonderful if I could get it some easier way.

**Comment by Michaelangel007** [comment]
No update however you CAN use the Printscreen key (might also need a modifier key Ctrl/Shift/Alt) while in the debugger to save the current screen to the clipboard.

It is tedious for more then 1 screen's worth and will require some block-selection to trim the EOLs but feasible.

**Comment by tomcw** [comment]
>No update however you CAN use the Printscreen key (might also need a modifier key Ctrl/Shift/Alt) while in the debugger

Ctrl + PrintScreen.

**Comment by Michaelangel007** [comment]
Thanks Tom!

**Comment by Michaelangel007** [comment]
Closing since:

* `Ctrl`-`PrintScreen` works
* It is now documented in the CHM (Debugger > Windows)
