### ISSUE TITLE
CyclesThisFrame not saved to save-state file

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#255]
Spun off from #241:

>Try the end credits of French Touch's "Ansi Story".

...

>btw. to reproduce this, I found it simpler to create a save-state file at the end credits part,

...

>btw. I mentioned a repro using the save-state file. This is no good, since the `g_dwCyclesThisFrame` value is not being saved. So on AppleWin start-up, this is initialised to zero, so the floating bus will be wrong after loading a saved-state

**Comment by Michaelangel007** [comment]
For AppleWin 1.26, we'll need to save and/or recalculate them:

    g_nVideoClockVert
    g_nVideoClockHorz

**Comment by tomcw** [comment]
I assume that g_nVideoClockHorz = g_nVideoClockVert % 65, right?

**Comment by Michaelangel007** [comment]
Almost; the values need to be capped so they stay in range. IIRC,

Horz = cycles % 65
Vert = (cycles / 65) % 262

**Comment by tomcw** [comment]
Work completed in  #315 / commit c798157. Closing.
