### ISSUE TITLE
Corrupt video rendering in NTSC_PreMerge

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#259]
I'm using nightly build v16 and consistently get corrupt rendered Apple text/graphics, eg:

![badtext](https://cloud.githubusercontent.com/assets/6696896/5688488/c498350e-984f-11e4-890e-2bce51bd9414.png)
![badhgr](https://cloud.githubusercontent.com/assets/6696896/5688489/c6dde93a-984f-11e4-8dd5-d6572a8ca1d6.png)

This is using the Video Mode = 'Color (TV emulation)'.

I have also tried pulling from the git branch, and building myself (VS2010). Again I get the same results in both Debug and Release configs.

Can you repro this?

**Comment by Michaelangel007** [comment]
We need to track down what commit introduced this.

Can you go all the back to the beginning of the branch and tell me what commit # is good ?

**Comment by Michaelangel007** [comment]
I *do* know that the updateFramebuffer{Monitor}{Single,Double}Scanline weren't converted properly from the #define over an inline func.

Can you try this simple version and see if you still get the problem?

        inline void updateFramebufferMonitorSingleScanline( uint16_t signal, bgra_t *pTable )
        {
            /* */ uint32_t *pLine0Address = getScanlineThis0Address();
            const uint32_t color0 = getScanlineColor( signal, pTable );

            /* */  *pLine1Address = color0 | ALPHA32_MASK;
            /* */  *pLine0Address = color0 | ALPHA32_MASK;
            /* */ g_pVideoAddress++;
        }

**Comment by tomcw** [comment]
For reference, I sync'd with the HEAD of NTSC_PreMerge (ae6f1c9f0fd01ccd01b6e9d290941b3579918543), and rebuilt on a different Win7-64 machine using VS2013-Express. Again both Debug and Release had the same corrupt video rendering.

**Comment by tomcw** [comment]
Actually you hit the nail on the head in your comment above... if I disable 50% Scanline mode, then the rendered is fine.

**Comment by tomcw** [comment]
So for completeness here's a summary (use CTRL+SHIFT+F9 to toggle 50% Scanline mode):

Monochrome (Custom): 50% mode is fine
Standard: 50% is fine
Text Optimized (aka B&W TV): 50% gives corrupt rendering
TV (aka Color TV): 50% gives corrupt rendering
Amber: 50% is fine
Green: 50% is fine
White: 50% is fine

So it's just the two TV modes that have this bad rendering, and only when 50% scanline mode is enabled.

**Comment by tomcw** [comment]
btw. I switched to your simplified `updateFramebufferMonitorSingleScanline()` but still got the same results.

Hopefully now you know it's 50% scanline mode, you should be able to repro this issue.

**Comment by tomcw** [comment]
Fixed in ad55b0f1369be7edd82f7d91244ad985f8211275.
(RGB arithmetic was underflowing.)
