### ISSUE TITLE
AppleWin 1.26a Known Bugs

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#261]
Known Issues:
- ~~(Video) Video corruption on F9 (introduced with commit ce94b596637dac685cb4008f66267e5b461559ea)~~ TC: 3 Apr 2016: Can't reproduce.
- ~~(Video) Benchmark speeds lower then NTSC05~~ Now tracked in #424.
- ~~(Video) Slow rendering due to double indirection~~ Now tracked in #401.
- ~~(Video,Debugger) On startup while showing the logo, debugger command `\` shows logo instead of black screen~~ TC: 3 Apr 2016: Can't reproduce.
- ~~(Video) Blurry fonts e6deaee6ae5838e73cbbcbe83c75461643322cae~~ Fixed:  f3cb2e35bf66bac87075af21611c1e87c51e6c10
- (Audio) faint clicking every few seconds (caused by starving the Mockingboard??) (#262)
- ~~(Video) Video corruption when 50% scanline mode is enabled (#259)~~ Fixed.
- (Debugger) Updated help text #242 #243 #244 #245 #246
- ~~(Video) Hard-coded character set. Need to use the BMPs for Original, Pravets 82, Pravets 8M, Pravets 8A. (Need to verify if the BMP's need a cleanup as they include an extra column of pixel padding.)~~ Fixed: 749e151
- (Debugger) Ctrl-Tab, Ctrl-Shift-Tab cycling code & data. (#263)

Wish-list:
- ~~(Video) Laser 128EX char set~~ Duplicate of #77.

**Comment by Michaelangel007** [comment]
Blurry Fonts:

    CALL-151
    C050 C053 C057
    C00D:1

Start of biset:
pass - e681c97c3b2fe94b94673dfe1e061a75050d3bee
fail - e1c56ba38693127790ab5cd3320668f04334e1f1

**Comment by tomcw** [comment]
>(Audio) faint clicking every few seconds (caused by starving the Mockingboard??)

I've spun this off into a new bug: #262

**Comment by tomcw** [comment]
•(Video) Video corruption when 50% scanline mode is enabled (#259)

**Comment by Michaelangel007** [comment]
Must be in introduced within the last 6 commits

* e1c56ba38693127790ab5cd3320668f04334e1f1
* e6deaee6ae5838e73cbbcbe83c75461643322cae
* f5869776ddb040d64805c62e2431c493812d76c9
* dfc4ef6d139c3f4ebca376f834bd50dfc119ceb9
* f794f3f4c6428b52375ecc45a82e381343e1a1be
* ba1a08b96bcf3635a69dec53aa0ae4f5a5d8adc0

**Comment by Michaelangel007** [comment]
Blurry DHGR text introduced with 

* e6deaee6ae5838e73cbbcbe83c75461643322cae fail Remove alt CHROMA_BLUR, added NTSC_REMOVE_WHITE_RINGING, NTSC_REMOVE_BLACK_GHOSTING

**Comment by Michaelangel007** [comment]
Fixed with commit f3cb2e35bf66bac87075af21611c1e87c51e6c10

**Comment by Michaelangel007** [comment]
Laser 128EX Roms

http://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Computers/LASER/LASER%20128/ROM%20Images/

Need to verify which ROM version my Laser 128EX is ...

**Comment by tomcw** [comment]
Hi Michael,
I think we should create new bugs for these untracked items: (assuming they are both still valid issues)
- (Video) Benchmark speeds lower then NTSC05
- (Video) Slow rendering due to double indirection

Then we can close this top-level issue.

**Comment by tomcw** [comment]
Closing this top-level issue, as outstanding items are now being tracked in dedicated issues.
