### ISSUE TITLE
Mouse interface: READMOUSE not reflecting a previous call to HOMEMOUSE

### ISSUE THREAD

**Issue by benoit0123** [AppleWin/AppleWin#266]
As I investigate on the other bug (leading to a crash to monitor prompt) within my program.
I tried to perform some playing with the basic mouse interface (passive mode only: no interrupt here).
I modified the P15preview.zip so that the disk image Peersoftv15.do now includes a simple binary program name APWINMOUSTST which will in sequence.
Init the mouse;
Set mouse mode to transparent (#1)
Calls clampmouse both for X (from 1 to 40) and for Y (from 3 to 21)
Calls homemouse (expecting that the returned mouse position will then be (1 for X and 3 for Y).
Calls readmouse to populate the screenholes.
However, the returned values for both X and Y where 0 for each coordinate.
The only documentation I have on hand (AppleMouse // User's manual (For the Apple //e, ][+ and II)
PN 030-0243-A (c) 1983
page 48 says:
"
HOMEMOUSE sets the mouse poistion registers on the peripheral card to their lower boundaries (equivalent to the upper left corner of a screen image of the clamping window). HOMEMOUSE does not update the screen holes; to change the screen holes values to home position, your program must follow it with READMOUSE" (which i did in my sample program.
"
As I do not have any real hardware on hand till the week end to come. I am just posting this message as a potential issue. Maybe I am wrong with the interpretation of the specification.
As the archive has been updated with the binary and source files used to demonstrate the "bug", feel free to base your own testing using them.
The URL for downloading is the same that is: http://bgilon.free.fr/apple2/P15preview.zip.

Best regards,
Benoît

**Comment by tomcw** [comment]
Hi Benoît,
Please test with real hardware if possible, and then report the results here.
Thanks.

**Comment by benoit0123** [comment]
Issue solved: by choosing the "Restrict mouse to Applewin window" in the configuration panel and then explicitly clicking within the Applewin window (otherwise, the mouse position is not correctly reported with the READMOUSE despite that the window already has the keyboard focus).

**Comment by tomcw** [comment]
Thanks for the update. I'll close this issue.
