### ISSUE TITLE
Added SAM/DAC sound card support 

### ISSUE THREAD

**Issue by rmacri** [AppleWin/AppleWin#270]
Hi, I've added support for a SAM (8 bit DAC) card to AppleWIn, my fork here:
https://github.com/rmacri/applewin
Have integrated it into the sound settings property pages, it properly greys out if slot5 is busy with the Z80 card, etc. As this is my first github submission I'm not sure what to do next.

The disk image folder includes the SAM software and I have some music software that I've been playing with in the emulator and on my real Apple //e with a home-made DAC card (16 sound 4 simultaneous drum machine). Let me know if you're interested.
-Riccardo

**Comment by tomcw** [comment]
Thanks for sharing your work.

I will review the commits in your fork, and provide feedback here.

Once (and assuming) we can iron out any issues then a next step would be to create a pull request, so that your work can be merged back into master.

**Comment by rmacri** [comment]
Thanks, happy to explain what I've done!
Basically piggy backing on the speaker code. As my drum program uses both the speaker and SAM simultaneously (Apple speaker is metronome), I implemented a quieting for the Apple speaker whilst the SAM is active.

**Comment by tomcw** [comment]
Hi Riccardo,

I took a quick look: the changes look small, so shouldn't be a problem merging to master.

I haven't run the SAM .dsk, but presumably you have to tell the software which slot the SAM card is in?

Can you add the GPL header to your new DAC.cpp file?
Just copy it from any other .cpp file in AppleWin.

Thanks.

**Comment by rmacri** [comment]
GPL header added.

The "HELLO" in the SAM DSK sets the slot in line 15, gets poked into 
38140 (into the driver).

The original was slot 4, but given that is the usual mouse card slot, 
slot 5 is really the only other choice. Hence my changes assume SAM is 
exclusive to the Phasor. In my case I use mouse card + SAM so I didn't 
worry about a slot 4 option.

Let me know when you have it working and I'll send you something 
interesting to try with it.

PS: On this page is the physical card I've built since I lost my SAM 
(scroll down, photo at top is the real SAM).
http://blog.juicylizard.com/?p=258

Regards

**Comment by tomcw** [comment]
Hi Riccardo,

I wonder if you can rename the files DAC.cpp & DAC.h to SAM.cpp & SAM.h?
(The DAC is specific to the SAM card. Maybe in the future another card will be emulated which also has a DAC, so  we should make this distinction clear now.)

Can you explain why in `IOWrite_DAC()`, you **invert** the high bit of the 8-bit value?
IE:
```
g_nSpeakerData = (d ^ 0x80) << 8;
```

I have this building and running now with the demo dsk in your repo's branch. It seems to be running nicely. If possible, then please send me the work you have been doing with SAM. I'm very curious to see/hear this! :)

BTW. With SAM in slot 5, we should be able to configure AppleWin to have a Phasor (or Mockingboard) in slot 4. IMO, it's not important to support this combination now; and since there's a known sound bug (#174) that occurs with simultaneous speaker+Mockingboard playback, then I expect SAM+Mockingboard to also suffer.

Thanks.

**Comment by rmacri** [comment]
Hi Tom, renames done and pushed to my fork.

 > Can you explain why in IOWrite_DAC(), you invert the high bit of
 >the 8-bit value?

Its converting the unsigned samples the DAC expects to signed which WAV 
uses. I updated the table in the comments to explain it better.

I agree that its unlikely anyone wants a SAM with another sound card.
The things are exceedingly rare. Mine came with my second hand //e in 
the mid 80s. Then I went and lost it which is why I was determined to 
build my own replacement.

Here's the drum software, bootable ProDOS floppy:
http://home.juicylizard.com/DRUM8.zip.
Happy for this to be shared. 30 years in the making.
(blog page to come).

Once loaded, [F]ile, [L]oad and you can try:
   DEMO, BONGODEMO and ROCKIT.

Let me know how it goes!

**Comment by tomcw** [comment]
Hi Riccardo,

That's great - I love your drum machine sequencer!
btw. What rate are you playing back the samples?

Thanks for making those filename & code changes - I understand now.

Can you create a pull request, then I can look at merging your changes back into master.

**Comment by rmacri** [comment]
Hi, glad you like it. The sample rate is a whopping 8kHz but if you play 
with the t[U]ne (which impacts the tempo, unfixed) you'll find there's 
time to spare. I'd considered using the extra 64kB in the //e and 
targetting 11kHz or more, put the audio mixing code in page 0 to make up 
for the bank switching etc. Never too late I guess.

Also considered building a "Super SAM" with a bunch of DAC chips on it 
to offload the mixing and allow full 8 bits per sample, but unlikely 
I'll get around to that.

It'll be cool to mention the official AppleWin SAM support when I get 
around to youtubing/writing this up - big thanks for taking interest in 
it. Pull request done.

**Comment by tomcw** [comment]
Merged #272 (565fd7967b4724596e15f2422768913e1401ee03) into master.

Thanks Riccardo!

**Comment by rmacri** [comment]
Thank you too, Tom.
Regards

**Comment by rmacri** [comment]
Tom, thought you'd like to know I gave appleWin a mention on my blog and 
Youtube video for drum8, which has already been picked up by 
bent-tronics.com!

http://blog.juicylizard.com/?page_id=284

**Comment by tomcw** [comment]
That's great - thanks for sharing!
