### ISSUE TITLE
Joystick button setting

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#28]
**BerliOS Feature Request #2244**

**Date:** 2006-May-31 06:49
**Submitted By:** pberb
**Category:** User Interface
**Assigned To:** tomch
**Priority:** 5
# 

Date: 2006-May-31 06:49
Sender: pberb
Logged In: YES 
user_id=28726
Browser: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.3) Gecko/20060426
Firefox/1.5.0.3

I would be most grateful if AppleWin changed the PC
joystick button mappings from #5 and #6 to #2 and #3;
or better yet, add an area where you can define your
own PC joystick button settings in Input Joystick
Control. :)

**Comment by tomcw** [comment]
Swap buttons 0 & 1 was done in 1.29.8.0.
Closing.

**Comment by j-rodman** [comment]
As of 1.29.16.0, the button swap does not appear to work.

Method.  

1 - Tried Lode runner.  The buttons are in very confusing positions by default.
2 - opened input configuration. 
3 - checked the 0/1 swap
4 - clicked OK
5 - the buttons are still in the same unchanged awkward positions.
