### ISSUE TITLE
Timing issue with DEC (abs)

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#288]
# Opcode 0xCE, DEC (abs):

AppleWin v1.25.0.3, NMOS 6502:
* DEC $20FF is **5 cycles**

Real NMOS 6502:
* DEC $20FF is **6 cycles**

AppleWin v1.25.0.3, CMOS 65C02:
* DEC $20FF is **5 cycles**

CMOS 65C02:
* [Rockwell 65C00 Datasheet](http://archive.6502.org/datasheets/rockwell_r65c00_microprocessors.pdf), DEC (abs) is **6 cycles**

NB1. NMOS: Opcode 0xEE, INC (abs) is 6 cycles (both Apple 1.25.0.3 and a real NMOS 6502).
NB2. CMOS: Opcode 0xEE, INC (abs) is 6 cycles (both Apple 1.25.0.3 and a Rockwell 65C02 datasheet).

**Comment by sicklittlemonkey** [comment]
Doesn't make sense. No changes were made. They should all be 6.

Cheers,
Nick.
​

**Comment by tomcw** [comment]
Thanks Nick. Yes, it's clearly just a mistake in AppleWin - one that I picked up on when generating unit tests for all opcodes & comparing to the 65C02 opcode chart in #271.

**Comment by Michaelangel007** [comment]
Thanks for taking the initiative on the Great Whitespace Cleanup :-)

I've synced up 65d02.h to all the change in 65C02.h

This patch is almost ready sans one question:

Could you clarify why all the // invalid" was removed in commit  https://github.com/AppleWin/AppleWin/commit/df5635dc111752194a60df4f760a80f6a591dce8 please? Thanks

**Comment by tomcw** [comment]
Fixed in 614dfc1257cc7fc32fb344be27944f145cdd8935. Closing.
