### ISSUE TITLE
More CPU errors (mostly 65C02 undocumented opcodes)

### ISSUE THREAD

**Issue by sicklittlemonkey** [AppleWin/AppleWin#292]
Just when you thought it was safe to go back in the water ...

Somehow both cpu6502.h and cpu65C02.h have this wrong. It should be 4 cycles:
			case 0x2D:   ABS        AND  CYC(2)  break;

I notice we make an attempt to implement some 65C02 undocumented opcodes. Except ...

This and 22, 42, 62, 82, C2, E2 NOPs are fine, 2 bytes, 2 cycles like a traditional NOP:
			case 0x02: $ IMM        NOP  CYC(2)  break;

These and all other X3, X7, XB, and XF NOPs are 1 byte but should be 1 cycle:
			case 0x03: $            NOP  CYC(2)  break;
			case 0x07: $            NOP  CYC(2)  break;
			case 0x0B: $            NOP  CYC(2)  break;
			case 0x0F: $            NOP  CYC(2)  break;

These NOPs look fine:
			case 0x44: $ ZPG        NOP  CYC(3)  break;
			case 0x54: $ zpx        NOP  CYC(4)  break;
			case 0xD4: $ zpx        NOP  CYC(4)  break;
			case 0xF4: $ zpx        NOP  CYC(4)  break;

This should probably just be ABS (not ABSX) NOP; 8 cycles is correct:
			case 0x5C: $ ABSX_OPT   NOP  CYC(8)  break;

These should be 4 cycle absolute (not ABSX) which read memory (affecting softswitches etc) but not affecting the CPU (A, P flags etc), so we probably need a new opcode instead of NOP, say LDD (from Laughton) or RDM or something:
			case 0xDC: $ ABSX_OPT   NOP  CYC(4)  break;
			case 0xFC: $ ABSX_OPT   NOP  CYC(4)  break;

Summary:
http://6502org.wikidot.com/errata-other-65c02opcodes
Reference/details:
http://www.6502.org/tutorials/65c02opcodes.html
http://laughtonelectronics.com/Arcana/KimKlone/Kimklone_opcode_mapping.html

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,
Thanks for checking all of these (I don't know how I missed 0x2D!  :)
I've fixed all these issues & updated the opcode unit-tests in 9f32050c60337e50ef5324bd539304886504e4de.
