### ISSUE TITLE
distorted sound in wine

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#294]
Hi,

I'm running AppleWin in wine and I get a very bad sound out of it.

Even if the emulator itself is silent (e.g. at the ] prompt), any other sound currently played is badly distorted.
I can hear the start beep (very harsh) and while I am at the ] prompt all sounds are damaged.
Then as soon as AppleWin exits, sounds is back to normal.

I am using the default settings

Device: SoundCard
SoundCards: No SoundCards (it happens with other cards as well)

I think an other bad interaction with wine (or wine and pulseaudio).
If anybody could give me a general overview how sound is handled in AppleWin I will try to create an other simple example app to submit to wine devel to see if anything can be done to improve the situation.

Thanks

**Comment by tomcw** [comment]
@audetto - you've raised some recent AppleWin issues where you say you are running under Wine.
Is this 2 year old distorted sound issue still a problem?

**Comment by audetto** [comment]
Just tried with 1.26.2.4, wine 2.9 and cannot hear the sound distortion.

Closing it.
