### ISSUE TITLE
Debug assertion triggered

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#295]
Hi,

I've been running AppleWin in debug and I can reliably trigger an assertion.

It's line 195 of SoundCore.cpp, g_uNumVoices = 66 (= uMAX_VOICES)

To get there,

- run AppleWin 
- select Sound -> Device = Disabled
- exit AppleWin
- run AppleWin
- select Sound -> Device = Sound Card
- click OK
- Assertion

I don't think it is a big assertion as the following anyway checks the same thing, just a bit annoying.

**Comment by tomcw** [comment]
Thanks for the report. I've fixed this in master (it looks like it would result in a resource leak).
