### ISSUE TITLE
VS2015 unresolved external in Release

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#296]
I'm building AppleWin with VS2015 in Release and I get an unresolved external for

inline COLORREF DebuggerGetColor( int iColor )

Now, I agree with VS.
This function is declared inline in the header file Debugger_Color.h and only defined (inline) in the .cpp

It is used though in many other .cpp files.
It cannot be declared inline (nor the definition can be moved to .h as it references g_aColors which is not exported).

I guess all other VS (and 2015 in Debug) simply ignore inline (which is just a hint anyway).

I have not prepared a pull request, but the change is trivial (remove the 2 inline).

**Comment by Michaelangel007** [comment]
http://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-visual-studio-2008

        MSVC++ 14.0 _MSC_VER == 1900 (Visual Studio 2015)
        MSVC++ 12.0 _MSC_VER == 1800 (Visual Studio 2013)
        MSVC++ 11.0 _MSC_VER == 1700 (Visual Studio 2012)
        MSVC++ 10.0 _MSC_VER == 1600 (Visual Studio 2010)
        MSVC++ 9.0  _MSC_VER == 1500 (Visual Studio 2008)
        MSVC++ 8.0  _MSC_VER == 1400 (Visual Studio 2005)
        MSVC++ 7.1  _MSC_VER == 1310 (Visual Studio 2003)
        MSVC++ 7.0  _MSC_VER == 1300
        MSVC++ 6.0  _MSC_VER == 1200
        MSVC++ 5.0  _MSC_VER == 1100

**Comment by Michaelangel007** [comment]
Yeah, one of the problems with C++ is that `inline` is merely a hint -- it is not mandatory.  With MSVC one needs to use MS's proprietary  `__forceinline` -- I would be curious to know if that changes the semantics for externals.
