### ISSUE TITLE
RamWorks III ProDrive (ramdisk utility) corrupts 80 column display during disk access.

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#297]
Using disk image - AE Super Desktop Expander 5.3.1 ProDOS ProDrive.po

If you create a RamDisk and then do things with it..
The screen briefly flashes when you're in 80-column mode and access the RamDisk via "cat" prodos command. It's alright in 40-column mode. The standard ProDos RamDisk doesn't do that.\

This of course happening from the BASIC ] prompt. Or Copy II+ 9.1 "catalog" in 80 columns. I believe other commands do this as well like, PREFIX SAVE BLOAD and BSAVE. Maybe other commands do too.

Let's call it the 80 column RamWorks bug.

**Comment by Keatah** [comment]
This is how you do it.
Set up a ramdisk Applewin.exe - r 127

Boot this disk image -
ftp://ftp.apple.asimov.com/pub/apple_II/images/hardware/storage/memory/AE_Super_AppleWorks_Desktop_Expander_5_3_1_ProDrive_ProDOS.DSK

Select 4, then 1 to create a ramdisk. Note the inverse 80-column display.
Type "CAT S3,D2" to see the problem again.

**Comment by Keatah** [comment]
This is how you do it.
Set up a ramdisk Applewin.exe - r 127

Boot this disk image -
ftp://ftp.apple.asimov.com/pub/apple_II/images/hardware/storage/memory/AE_Super_AppleWorks_Desktop_Expander_5_3_1_ProDrive_ProDOS.DSK

Select 4, then 1,  to create a ramdisk. Note the inverse 80-column display.
Type "CAT,S3,D2" to see the problem again.

**Comment by tomcw** [comment]
I've pre-released a new AppleWin 1.26.2.4 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.4) that fixes this.

**Comment by Keatah** [comment]
Yes that seems to fix it. kthxbye

**Comment by tomcw** [comment]
Thanks for confirming.
