### ISSUE TITLE
WeeGUI crashes in AppleWin

### ISSUE THREAD

**Issue by sicklittlemonkey** [AppleWin/AppleWin#300]
WeeGUI is Quinn Dunki's MouseText GUI toolkit. She did a session on it at KansasFest:
https://www.youtube.com/watch?v=6csiwLzR_2Y

For me, BRUN WEEGUI crashes to the monitor at $7B03.
https://github.com/blondie7575/WeeGUI/blob/master/weegui.dsk

I haven't looked into it at all ... my weekend is over!

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
Hmm, quick tests: GSport doesn't crash but doesn't work, and Virtu crashes in the same way as AppleWin.

That's all I can test for now. Maybe this WeeGUI image is no good.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,

The first line of BASICDEMO does this:
1 PRINT CHR$(4)"brun weegui"

It loads at A=$7B00.
The disassembly from this address looks like rubbish:

    7B00: 07 nop
    7B01: 00 BRK
    7B02: 0C 1A 20 TSB $201A
    ...

Using the //e monitor to list a page of disassembly at a time there's always a few undefined (???) opcodes present. I then opened the .dsk with Ciderpress, and disassembling as "IIgs monitor listing (short regs)" makes more sense.

EG. The opcode 0xDA (at $8B0D) now disassembles as PHX, which seems to fit.

Anyway if it's IIgs code, then that explains(?) why it doesn't crash with GSport.

**Comment by sicklittlemonkey** [comment]
Thanks for looking, Tom.

Sorry for not checking more closely. (We had a mains water leak in the wall
on the weekend ...)

Hmm, the file is corrupt at the beginning. The //e listing looks fine after
the first couple of pages. I'll contact Glenn about it.

It's not IIgs code, but since the IIgs utilizes every possible opcode it
will disassemble without error. ; - )

Note that even the enhanced disassembler doesn't decode the new 65C02
opcodes.
http://www.llx.com/~nparker/a2/opcodes.html

I just tested the previous version of the disk:
https://github.com/blondie7575/WeeGUI/blob/b04af05f79878d1c3e293bc2def8bd7f4e804445/weegui.dsk

It works fine in AppleWin. Have a look! : - )

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
So yeah, it turned out to be a problem with the WeeGUI disk creation in their project.

Closing.

Cheers,
Nick.
