### ISSUE TITLE
Mouse unavailable for GraphicsMagician v12.82

### ISSUE THREAD

**Issue by johnnystarr** [AppleWin/AppleWin#306]
I've enabled the mouse on port 4 in enhanced Apple iie mode.  When using option '2' (picture editor) I see the standard cursor yet the mouse doesn't work at all.  I've tried enabled/disabling every mouse related feature and even ran in multiple modes.  Is it possible that this version of GraphicsMagician just doesn't work with AppleWin?  I've tested this same version on https://www.scullinsteel.com/apple2/ with no issues.  I'm looking to use this for a new homebrew graphical text adventure I'm writing.  I would be fine with using the JS version if only I could retrieve the files.

**Comment by tomcw** [comment]
Hi,
Where can I find this version (v12.82)?
What version of AppleWin are you using?
Thanks.

**Comment by tomcw** [comment]
I found v12.82 here:
ftp://ftp.apple.asimov.net/pub/apple_II/images/productivity/graphics/graphics_magician/graphics_magician.dsk

In the same folder I also found graphicsmagicianiie.dsk. This has an explicit option for (M)ouse support.

**Comment by tomcw** [comment]
The web-client JS emulator uses the mouse to emulate the joystick, which is why it appears that the mouse is supported. To mimic this behaviour in AppleWin, then:
* uncheck "Mouse interface in slot 4" (Config -> Input tab)
* set Joystick 1 = Mouse (Config -> Input tab)

**Comment by tomcw** [comment]
Closing this issue, as it's expected behaviour.

**Comment by johnnystarr** [comment]
I see now, thank you sir.

**Comment by sicklittlemonkey** [comment]
Johnny. If you're interested in alpha-testing AppleWin's "virtual touch
tablet" (via Android phone or tablet) to do graphics, send me a personal
email.

Cheers,
Nick.
