### ISSUE TITLE
Pravets 8 emulation applies 65C02 instead of 6502.

### ISSUE THREAD

**Issue by CM630** [AppleWin/AppleWin#307]
Pravets 8 emulation applies 65C02 instead of 6502. This coses some compatibility problems.
A patch fixing the issue is attached.

[Pravets8 CPU.cpp.patch.txt](https://github.com/AppleWin/AppleWin/files/33314/Pravets8.CPU.cpp.patch.txt)

**Comment by tomcw** [comment]
Thanks for the patch. I'll make sure it's applied for the next release (no schedule for this at the moment).

**Comment by tomcw** [comment]
Patch:
```
 static DWORD InternalCpuExecute (DWORD uTotalCycles)
 {
-	if (IS_APPLE2 || (g_Apple2Type == A2TYPE_APPLE2E))
-		return Cpu6502(uTotalCycles);	// Apple ][, ][+, //e
+	if (IS_APPLE2 ||  (g_Apple2Type == A2TYPE_APPLE2E) || (g_Apple2Type == A2TYPE_PRAVETS82) ||  (g_Apple2Type == A2TYPE_PRAVETS8M) || (g_Apple2Type == A2TYPE_PRAVETS8A))
+		return Cpu6502(uTotalCycles);	// Apple ][, ][+, //e, Pravets 8x
 	else
 		return Cpu65C02(uTotalCycles);	// Enhanced Apple //e
 }
```

This patch indicates that A2TYPE_PRAVETS8A uses the 6502 CPU, but in AppleWin 1.26.0.3 I have the Pravets 82 as an Enhanced Apple //e clone, ie, using the 65C02.

Can you confirm that Pravets 82 is just an (standard) Apple //e clone, using the 6502?

**Comment by tomcw** [comment]
Actually I'm wrong... AppleWin 1.26.0.x correctly emulates all Pravets 82,8M,8A with a 6502.
Closing as fixed.
