### ISSUE TITLE
Ctrl-C not always being trapped properly in the emulator?

### ISSUE THREAD

**Issue by QuantumReality** [AppleWin/AppleWin#310]
I loaded up a standard DOS 3.3 disk, booted off it in AppleWin, and issued a CATALOG command. The usual behavior is to pause for keyboard input after ~20 lines then every 23 lines after. Ctrl-C should, on a real //e, immediately break from "pause for input" and return to the Applesoft or Integer prompt. In the latest AppleWin, it does not do so.

Ctrl-C will issue a proper "break from action" almost anywhere else, however - such as in LISTing a long Applesoft program.

**Comment by tomcw** [comment]
For ProDOS, CTRL-C certainly interrupts the CATALOG listing (at any point).
I don't have a real Apple II at hand to try this on, but I'd say it's unlikely that AppleWin is wrong.
Perhaps you are getting confused with another variant of DOS3.3 or even ProDOS?

**Comment by QuantumReality** [comment]
Nope, it's definitely reproducible on the DOS 3.3 System Master Disk issued by Apple itself. Such an image can be found here: ftp://ftp.apple.asimov.net/pub/apple_II/images/masters/Apple%20DOS%203.3%20January%201983.dsk

Boot up, issue a CATALOG command, hit ctrl-C at the blinking cursor, Instead of terminating at BOOT13 it will then list out SLOT# and only then terminate. Then try CATALOGing something like this:
ftp://ftp.apple.asimov.net/pub/apple_II/images/disk_utils/Beagle%20Bros%20-%20Utility%20City%20(July%2016%201982%20rev).dsk

ctrl-C will fail to break from the CATALOG even if you press it several times.

**Comment by sicklittlemonkey** [comment]
Both disks you linked to ignore the value of the keypress DOS gets. (Ctrl-C
does the same thing that any other key would do.)

Cheers,
Nick.

**Comment by QuantumReality** [comment]
Hm! You're right. I went to check the actual DOS 3.3 internals, and the JSR to the keypress is to RDKEY ($FD0C) which does nothing except grab a keypress and doesn't trap for a Ctrl-C. So that's my bad for not checking first.

**Comment by Michaelangel007** [comment]
I just booted up my real Apple //e with these disks:

OS | Result
---|---
DOS 3.3 | Ctrl-C is ignored,and catalog continued.
ProntoDOS | Ctrl-C (silently) breaks out of the catalog.

**Comment by tomcw** [comment]
Thanks for everyone's input on confirming that AppleWin has correct behaviour.
I will close this as spec.
