### ISSUE TITLE
[AppleWin 1.26a] : AND absolute bad timing cycles

### ISSUE THREAD

**Issue by Archange427** [AppleWin/AppleWin#313]
Dunno why (probably typo) but AND abs is 2 cycles only (normally 4).
see : CPU6502.h

**Comment by sicklittlemonkey** [comment]
I went through with a fine tooth comb and reported this last year.
https://github.com/AppleWin/AppleWin/issues/292

Looks fine in master.

Cheers,
Nick.

**Comment by Archange427** [comment]
Thank you Nick. 
In fact other timing bugs  (DEC/INC/ASL/...) are still present in AppleWin 1.26a (but corrected in master).
I did not notice (until now) because I used my own patched version of the 1.26a.
So no AppleWin versions (all branches included) run French Touch's demos (in which timing is important) correctly.

The most accurate is 1.26a but with cycling issues corrected.

**Comment by tomcw** [comment]
I hope to do a new release build next month - this will be from master, so will include these 6502/65C02 timing fixes amongst other things.

**Comment by tomcw** [comment]
Closing as a duplicate.
