### ISSUE TITLE
Empty Help file

### ISSUE THREAD

**Issue by cbeust** [AppleWin/AppleWin#314]
My help file seems to be empty:

![image](https://cloud.githubusercontent.com/assets/92322/12634218/6f533520-c52c-11e5-9434-4bdfefcc755b.png)

No matter which section I click on, I get an empty pane on the right hand side.

Besides this, is there an up to date help online? I found a couple but they are for older versions. In particular, they don't mention watch points. I was able to use those but I was wondering if it's possible to watch a range of memory instead of just one address?

Thanks for AppleWin, it's a pleasure to use. Based on the commits, it doesn't look like you're working much on it any more and I totally understand, so I don't really expect an answer but I thought it wouldn't hurt to ask :-)

**Comment by tomcw** [comment]
Hi,

Thanks for your feedback. The most up-to-date help file (AppleWin.chm) is in the [1.24.0.4 release](https://github.com/AppleWin/AppleWin/releases/download/v1.25.0.4/AppleWin1.25.0.4.zip).

re. Set a breakpoint on a memory range (aka watchpoint):
`BPM <address>,<length>`

re. Empty help file
Which version of AppleWin did you get the AppleWin.chm from?
Which version of Windows are you using?

Maybe try this:
- On Windows XP, Windows 7, etc you can simply right-click on the CHM file, select "Properties", and click on the "Unblock" button
- Click "Apply" and the content should be visible.

https://www.jeff.wilcox.name/2008/11/unblock-chm

**Comment by cbeust** [comment]
"Unblocking" the `.chm` file worked, thanks! I had no idea there was such a thing.

`BPM` is also working great.

Thanks again for this awesome emulator, which only lacks support for `.edd` or `.fdi` to be perfect in my book :-)

Closing this issue.
