### ISSUE TITLE
[Disk] Only mounts version 1 .2mg not version 0

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#317]
From: comp.sys.apple2
https://groups.google.com/forum/#!topic/comp.sys.apple2/75jHbY1aSs0

File: [DiskImageHelper.cpp](https://raw.githubusercontent.com/AppleWin/AppleWin/master/source/DiskImageHelper.cpp)
Function: C2IMGHelper::DetectHdr(LPBYTE& pImage, DWORD& dwImageSize, DWORD& dwOffset)

```
1044        if (pHdr->Version != 1) 
1045                return eMismatch; 
```

**Comment by sicklittlemonkey** [comment]
The creator signature of the problem file is "RVLW", which matches this:
http://mirrors.apple2.org.za/apple.cabi.net/GS.Emulators/XGS.DOS.rvlw020.zip.INFO.txt

So the following software created the image:
Revival - a 2IMG image utility for Windows 95, by Thomas Fok
<thomas@glink.net.hk> (2IMG format not compatible with XGS versions prior
to 0.48)
http://www.glink.net.hk/~thomas/revival.htm
(The link is dead ; - )

I was peripherally involved in the 2IMG format spec in the early 90's but I
can't recall if 0 was a valid value or not. 1 sounds more reasonable as I
don't recall the format changing.

Anyway, we should change the condition to > 1.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
http://web.archive.org/web/19981206023530/http://www.magnet.ch/emutech/Tech/


"+10  word16  version;
The version number of this header. We're at version 1 at this moment."

So the version was 1 in 1998. Pretty sure the 0 is a bug in revival.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,
In that csa2 thread, @fadden says:

> CiderPress will reject an image with a version > 1, but does nothing special for version 0. 

Shouldn't AppleWin match this, just so that between the (few) tools that support .2mg we have consistency? But on the other hand, there is just this single example of a non-compliant .2mg file, which can be fixed (by a binary edit), so we should just apply your fix (above).

**Comment by Michaelangel007** [comment]
It is unfortunate that some implementations of the .2mg spec don't implement it correctly.  In the sake of User Experience we should siliently work regardless.

Fixed in branch `NTSC_PreMerge` with commit  8a1d39104b3887a3d998749640b3badc3906397a

**Comment by Michaelangel007** [comment]
@sicklittlemonkey Thanks for the history & confirmation of the bug work-around Nick!

**Comment by Michaelangel007** [comment]
Do we want/need to cherry-pick and merge into [AppleWin/Applewin/tree/master](https://github.com/AppleWin/AppleWin/tree/master)?

**Comment by tomcw** [comment]
Hi Michael, yes if you could cherry-pick into master that'd be helpful. Thanks.
