### ISSUE TITLE
smartport return address wrong when crossing page

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#319]
08fd: jsr $c70d
returns to $803 instead of $903 because of a missing adc #0.

**Comment by tomcw** [comment]
I see, in `hddrvr.a65`, here:
```
; Pre: C=0
SmartPort
 pla
 sta $46
 pla
 sta $47		; ($47) = &cmd_hdr. NB. This comment should be ($46)
 pha
 lda $46
 adc #3			; Pre: C=0, Post: assume C=0
 pha			; (sp).w += 3
 ...
```
Size = 12 bytes

The code could be re-jigged as:
```
SmartPort
 pla
 sta $46
 adc #3			; Pre: C=0, Post: C=0 or 1
 tay
 pla
 sta $47		; ($46) = &cmd_hdr
 adc #0
 pha
 tya
 pha			; (sp).w += 3
 ...
```
Size = 14 bytes

NB. Increasing by 2 bytes is fine, since there are 2 unused bytes at the end  of `SmartPort`.

**Comment by peterferrie** [comment]
lines 103 and 106 can be removed to save two bytes and zero cost.

**Comment by tomcw** [comment]
Here's the code  in question:

```
102  lda hd_error
103  clc
104  cmp #1
105  bne noerr0
106  sec
107 noerr0
```

You are right, but let me demonstrate this:

- `hd_error` can be 0 or 1 (from HardDisk.cpp)
- `CMP #1` sets C = (hd_error >= 1) ? 1 : 0
  - A==1 means C=1
  - A==0 means C=0
- if `CMP #1` takes the BNE branch then A==0, and so  C=0 (from the CMP)
- if `CMP #0` doesn't take the BNE branch then A==1, and so C=1 (from the CMP)

Thanks!

**Comment by peterferrie** [comment]
> Here's the code  in question:
>
> ```
> 102  lda hd_error
> 103  clc
> 104  cmp #1
> 105  bne noerr0
> 106  sec
> 107 noerr0
> ```
>
> You are right, but let me demonstrate this:
>
> - `hd_error` can be 0 or 1 (from HardDisk.cpp)
> - `CMP #1` sets C = (hd_error >= 1) ? 1 : 0
>   - A==1 means C=1
>   - A==0 means C=0
> - if `CMP #1` takes the BNE branch then A==0, and so  C=0 (from the CMP)
> - if `CMP #0` doesn't take the BNE branch then A==1, and so C=1 (from the
> CMP)

The CMP overrides the CLC, so the CLC can be removed, and the SEC can
be removed because it is reached only when carry is set already.
In fact, the branch can be removed, too.

**Comment by sicklittlemonkey** [comment]
So unless you need to return A, and only C matters, that code can be:

lda hd_error
ror

Cheers,
Nick.

**Comment by peterferrie** [comment]
The page-crossing bug remains active.  I just hit it again today.

**Comment by tomcw** [comment]
Apologies. This fell off the radar along time ago :-/
I'll ensure it gets into the next (imminent) release.

**Comment by peterferrie** [comment]
Thanks.  I have reworked my code and avoided it as a side-effect, but
an official fix would avoid being surprised for a third time. :-)

**Comment by tomcw** [comment]
re.

```
lda hd_error
ror
```

In the end, I could reduce to just `ror hd_error`, which I could apply in 2 places.

NB. The `ror <abs16>` is read-modify-write, but on this I/O addr ($C0F1) the write is ignored. Also the value of hd_error is always guaranteed to be 0x00 or 0x01.

**Comment by tomcw** [comment]
Regression test added here: https://github.com/AppleWin/AppleWin-Test/commit/21cf71596bd418c8ef538aee1b71978456bc432f

**Comment by tomcw** [comment]
AppleWin 1.29.3.0 release [here ](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0)- please try it and confirm this all works for you.

**Comment by tomcw** [comment]
From the release note (History.txt:

> NB. Old save-states where the 6502's PC is in the old firmware now can't be loaded. (AppleWin will show an error)

IE. 6502 PC is in the $C7nn range.

If you get this error, then:
- load the save-state into the old AppleWin 1.29.2.0 (at the AppleWin start-up logo)
- then from the debugger (F7), step until you are out of the $C7nn firmware
- save the state (F11)
- then load this new state into the new AppleWin 1.29.3.0

**Comment by peterferrie** [comment]
Confirmed fixed.
Thanks.

**Comment by tomcw** [comment]
More extensive regression test added here: https://github.com/AppleWin/AppleWin-Test/commit/bed3b3ee17cb8b7316075c920ed19aa40fe5fe41
