### ISSUE TITLE
Can't skip HD boot

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#323]
Bug/Feature:
- [ ] Can't skip boot with HD in Slot 7 enabled (must manually via Ctrl-Reset, `PR#6`)

Source:

Apple II Pascal and harddisk support in emulators
https://groups.google.com/forum/#!topic/comp.sys.apple2.programmer/3eNWUV5-aow

**Comment by sicklittlemonkey** [comment]
That's how real hardware behaves.

Usually you'd have a program selector (E.g. Prosel) or startup program give
the option.

If you wanted to fix the "bug" in AppleWin you'd have to pause the boot and
check for a key held down (e.g. 6) in either AppleWin or the HD firmware.

Cheers,
Nick.

**Comment by tomcw** [comment]
Closing as invalid & removing Bug / Enhancement labels.

**Comment by tomcw** [comment]
Reopening as PR #370 checks for Open-Apple in order to skip HDD boot and instead jump to $C600.

**Comment by tomcw** [comment]
Merged in 4ac8bb3
