### ISSUE TITLE
Phasor questions

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#328]
Some Phasor-related questions have come up, so I'm tracking them in this issue.

> AppleWin defaults the Phasor mode to be Mockingboard mode (ie. as if the DIP SW is set to Mockingboard mode). So at Apple //e power on, reset (eg. change of h/w state) or CTRL+RESET, then the Phasor will switch back to Mockingboard mode.
> This means that initially there will always be a 6522 at $C400.

Is that this is the behaviour of a real Phasor?

> Here is some parts of the code from TEST.BAS. TEST.BAS uses BIN.SOUNDS to play samples demo, voice tests, etc.

```
1200 REM PHASOR SLOT FINDER
1210 S = 7
1220 A = 49168 + 256 * S: IF PEEK (A + 1) = PEEK (A + 15) AND PEEK (A
+ 14) = 128 THEN 1240
1230 IF S > 0 THEN S = S - 1: GOTO 1220
1240 POKE 769,S: IF PEEK (768) > 1 THEN POKE 768,1
1250 IF S = 0 THEN TEXT : HOME : VTAB 10: PRINT "THE PHASOR IS NOT
INSTALLED, PLEASE INSTALL BEFORE RUNNING PROGRAM.": END
1260 RETURN

1300 REM CHECK FOR PHASOR MODE
1310 MC = 49280 + PEEK (769) * 16: POKE MC + 13,0:A = 49152 + PEEK
(769) * 256:I = 0
1320 IF I > 3 AND I < 10 THEN 1340
1330 IF PEEK (A + I) < > PEEK (A + I + 16) THEN 1350
1340 IF I < 16 THEN I = I + 1: GOTO 1320
1350 POKE MC + 8,0
1360 IF I = 16 THEN TEXT : HOME : VTAB 10: PRINT " THE PHASOR IN SLOT
" PEEK (769)" MUST HAVE ITS DIP SWITCHES 1 AND 2 CLOSED!": END
1370 RETURN
```

The 1st subroutine "PHASOR SLOT FINDER" looks for a Phasor by doing this (for slot-4):
- if (peek($C411) == peek($C41F)) && (peek($C41E) == 0x80) then FOUND
- NB. No initial access to $C0Cn to select Phasor native/Mockingboard mode

This implies that this code works in either Phasor native or Mockingboard modes. Unless the Phasor always comes up in a fixed mode after power on or reset (regardless of the DIP SW settings) ...since maybe this code is only run when booting the phasor1.dsk?

The 2nd subroutine "CHECK FOR PHASOR MODE" is interesting too:
- poke $C0CD,0  // low address bits: b#1101 - selects Phasor native mode (but why is bit3=1?)
- it then compares 6522 values at offsets {0,1,2,3 and A,B,C,D,E,F} between $C40n and $C41n
- poke $C0C8,0  // low address bits: b#1000 - selects Mockingboard mode (but why is bit3=1?)
- if the complete set of 6522 values are the same then print "THE PHASOR IN SLOT 4 MUST HAVE ITS DIP SWITCHES 1 AND 2 CLOSED!"

So this implies 2 things:
1. DIP SW settings can override the Phasor mode
2. When in Phasor native mode then 6522's don't appear at both $C400 and $C410

**Comment by tomcw** [comment]
>Is that this is the behaviour of a real Phasor?

Yes, after a reset, there will always be a 6522 at $Cn00, because in native Phasor mode (SW1=CLOSED), after power on/reset it starts in Mockingboard mode.

>This implies that this code works in either Phasor native or Mockingboard modes.

For both MB and Phasor cards in slot-n, regardless of DIP SW settings or software selected mode, there's always a 6522 at $Cn10. (For MB mode, the 6522 repeats throught I/O memory, and for s/w selected Phasor mode the 6522 is mapped at $Cn10.)

>So this implies 2 things:
>1. DIP SW settings can override the Phasor mode

Yes.

>2. When in Phasor native mode then 6522's don't appear at both $C400 and $C410

Correct... when in s/w selected Phasor mode, there's floating bus at $Cn00 and 6522 at $Cn10.

See #777.

**Comment by tomcw** [comment]
@Archange427 - it was you that was asking about Phasor back in 2016.
This related to your [Test Lab 2](http://fr3nch.t0uch.free.fr/TLB2/TLB2.html) musidisk, which was for 2x Mockingboard or 1x Phasor card.

You also asked about the clock for the AY-3-8913. Just to clear this up:
- Mockingboard clocks the AY-3-8913 at 1MHz
- Phasor in Mockingboard mode clocks the AY-3-8913 at 1MHz
  - but in this mode you only get access to 2x AY-3-8913
- Phasor in Phasor native mode clocks the AY-3-8913 at **2MHz**
  - in this mode you only get access to **all 4x AY-3-8913**

So this means to support 2x Mockingboard cards or 1x Phasor card, you would need to adjust the tone & envelope periods for each card's respective clock frequency.

**Comment by Fr3nchT0uch** [comment]
Thank you for that!
I didn't remember that question actually, but here's a very interesting piece of information!

**Comment by Archange427** [comment]
Thank you for that!
I didn't remember that question actually, but here's a very interesting piece of information!
