### ISSUE TITLE
Keyboard: Any Key Down (AKD) not working

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#330]
From Michael Mahon via email:

> I was recently checking the behavior of the Any Key Down status on a IIc+ (which is identical to //e and IIc), and I found a discrepancy between what real hardware does and what AppleWin does.
> 
> When polling $C010, real hardware delivers the key code and a high order 1 bit when a key is depressed.  Then when another key is depressed while holding the first key down, the high bit stays on (of course) and the ASCII key code changes to reflect the latest keypress.
> When the second key is then released, nothing changes as long as the first key remains down.
> 
> AppleWin turns off the high bit as soon as the second key is released, even though the first key is still down--violating the "any key down" definition.

Minified Applesoft repro:

```
NEW
1 K=12*4096+16
2 ? PEEK(K): GOTO 2
RUN
```

Steps to Reproduce:
1. Press and hold first key (such as `ESC`)
2. Press and hold second key (such as `A`)
3. Release second key
4. Release first key

Expected Behavior on real hardware:
1. Output = 155
2. Output = 193
3. Output **stays** at 193.
4. Output = 65

Actual behavior on emulator (AppleWin 1.25):
1. Output = 155
2. Output = 193
3. Output = 65 <-- **FAIL**
4. Output = 65 (n/a)

Related:
- https://github.com/AppleWin/AppleWin/issues/116

**Comment by tomcw** [comment]
NB, there's some simple test code here: https://github.com/AppleWin/AppleWin/issues/556#issuecomment-392551888

**Comment by tomcw** [comment]
NB. On a PC's keyboard, AFAICT there's no way to distinguish between RETURN (main keyboard) and ENTER (numpad) - for the WM_KEYDOWN message, both send a VK_RETURN.

This means that RETURN, then ENTER, then releasing (eg) only ENTER will not have the AKD bit set.

I suppose we could count WM_KEYDOWN/UP's for VK_RETURN - ie. reference count just this key.

IMO life's too short for adding support for this edge case, so I'll keep this issue closed!

**Comment by tomcw** [comment]
Ah, thanks Nick - you are right:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms646267(v=vs.85).aspx

Extended-Key Flag

The extended-key flag indicates whether the keystroke message originated from one of the additional keys on the enhanced keyboard. The extended keys consist of the ALT and CTRL keys on the right-hand side of the keyboard; the INS, DEL, HOME, END, PAGE UP, PAGE DOWN, and arrow keys in the clusters to the left of the numeric keypad; the NUM LOCK key; the BREAK (CTRL+PAUSE) key; the PRINT SCRN key; and the divide (/) and ENTER keys in the numeric keypad. The extended-key flag is set if the key is an extended key.

**Comment by tomcw** [comment]
Thanks again Nick - AKD for Return+Enter is now fixed.
