### ISSUE TITLE
Mouse tracking is off

### ISSUE THREAD

**Issue by wirehead** [AppleWin/AppleWin#333]
I was trying to use the mouse in AppleWin and the tracking is off.

To reproduce, I move my mouse the same approximate distance from left to right where the mouse crosses the emulated window, then move it down so that it's solely going across the desktop.

For most emulators that are grabbing the mouse (VirtualBox, DOSBox), it's about equivalent.  But for AppleWin, the mouse rate speeds way up as it crosses the AppleWin window.

**Comment by tomcw** [comment]
Hi,
What software (application) are you running on the Apple II to experience this?
In all likelihood it will how the Apple software has configured the Apple II's mouse resolution. Some software (eg. Fantavision) can be close to the Windows mouse speed, whereas others (eg. GEOS) can be very different.

**Comment by tomcw** [comment]
Setting as 'invalid' and closing (as not enough info to take further).
Will reopen if there's more info provided.
