### ISSUE TITLE
FullScreen mode and Buttons on right hand side.

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#335]
I'm trying to figure out if this is working correctly or not.

I start AppleWin and before booting a disk, I click the "FullScreen" button(F6).  The entire computer screen is taken up with the emulator and I can move the mouse to the right hand side and while it is stopped there I will see the button underneath it.  If I move the mouse up or down the screen the old button is hidden and a new button is shown.  This is working the way I would expect it to.

From fullscreen mode, I then boot a disk (DOS in this case).  Once again the whole screen is occupied by the AppleWin display.  Now when I move the mouse to the right edge of the screen, I see the button for a fraction of a second and then it disappears.  I assume this is working as it should, but I'm not sure.  But if I move the mouse up and down the screen, even if I stop it on what should be the next button, the button is almost never displayed even for that fraction of a second.   If I pass over 5 or 6 buttons, maybe one will display briefly.  However, if I move the mouse to the left (away from the button area) and then move it to the right edge, the button displays for that fraction of a second so that I can see if I am on the right one.  I've also tried moving the mouse very quickly up and down (but still over the middle buttons) and the faster I move the mouse the greater the probability of seeing a glimpse of a button.

Q:  In fullscreen mode with a disk booted, when slowly moving the mouse up-and-down over the various buttons, shouldn't each button be displayed for at least a fraction of a second?

Tommy

**Comment by Michaelangel007** [comment]
Tommy, I'm away for business this week, but thanks for the bug report!

I've noticed the flickering behavior in full screen too, but didn't thoroughly investigate it like you have since I don't use full screen mode (much). Thanks for the details!

I think this has been been a bug for quite a while now.  I guess the next order of business it to track down if 

a) Has AppleWin done this in old versions?
b) Is this a new bug?

Once I'm back home next week I'll go through my archived versions and post an update.

**Comment by tomcw** [comment]
Hi,
This is covered by #211, so I will close this as a duplicate.
btw. we have a WIP version (in a branch) that has a better full-screen implementation which resolves this issue (and other issues too). I'll be looking to merge into the master branch soon.

**Comment by Michaelangel007** [comment]
Thanks for the update Tom and the earlier bug #211 link.
