### ISSUE TITLE
Ultima I Disk Drive speed error

### ISSUE THREAD

**Issue by BPaden** [AppleWin/AppleWin#338]
I'm not hugely experienced with the Apple II, so this could be a user error. I'm also running this with wine, so this could be a bug in wine. But when I boot up Ultima I - The First Age of Darkness and try to format a player disk, I get a `Disk drive speed error`. I've tried with the Apple II+ and the Apple IIe (the game doesn't seem to work at all with the original apple II), and I have tried using the authentic disk access speed, all to no effect.

**Comment by TommyGH** [comment]
This is similar to:
  Cannot format Pascal Disk #196

In #196 the error message is:  
  Drive speed is too slow.

Fyi,
Tommy

**Comment by tomcw** [comment]
From PR #507:
 .dsk & .nib images now format OK for both authentic/enhanced disk access speeds.
(.nib needs a zero-length image to be initialised with alternating values, eg. 0x80,0x81.)

Just like #196, before calling the formatter routine, it will try to determine if the disk is already formatted and has a subroutine (albeit slightly different to #196) that reads the drive latch until the nibble changes:

```
D4DA:A6 3E                LDX $3E    
D4DC:A0 00                LDY #$00   
D4DE:BD 8C C0             LDA $C08C,X
D4E1:20 F0 D4             JSR $D4F0   ;  12cy / RTS
D4E4:48                   PHA         ;  3
D4E5:68                   PLA         ;  4
D4E6:DD 8C C0             CMP $C08C,X ;  4
                                      ;  = 23 cycles
D4E9:D0 05                BNE $D4F0  
D4EB:A9 28                LDA #$28   
D4ED:88                   DEY        
D4EE:D0 EE                BNE $D4DE  
D4F0:60                   RTS        
```

(Again the delay between LDA and CMP is 23 cycles.)

NB. The formatter routine is just the standard ProDOS formatter routine (see my analysis in #125), with just this difference:
- code org'ed at $A800-$AC1E; data $AC1F-$AC39

**Comment by tomcw** [comment]
From the file: "Beneath Apple ProDOS 8 - Supplement for Version 1.1.1.pdf", page 67:

![prodos-datachanging](https://user-images.githubusercontent.com/6696896/32752992-251fff00-c8c3-11e7-842d-87b48a85ede2.PNG)

**Comment by tomcw** [comment]
Closing as work is complete.
