### ISSUE TITLE
NTSC (color and B&W) appear misaligned relative to the other video modes

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#341]
Here's a small bit of code that will intercept CTRL+CURSOR_KEYS to do pixel adjustment for the VT_COLOR_TV mode:

Frame.cpp (global scope)

```
int g_DbgXSrc=0, g_DbgYSrc=0;
```

Frame.cpp`FrameWndProc()

```
               if (g_bCtrlKey && wparam >= VK_LEFT && wparam <= VK_DOWN)
               {
                       if (wparam == VK_RIGHT) g_DbgXSrc--;
                       if (wparam == VK_LEFT)  g_DbgXSrc++;
                       if (wparam == VK_DOWN)  g_DbgYSrc--;
                       if (wparam == VK_UP)    g_DbgYSrc++;
               }
```

Video.cpp`VideoRefreshScreen()

```
                       if (g_eVideoType == VT_COLOR_TV)
                       {
                               extern int g_DbgXSrc;
                               extern int g_DbgYSrc;
                               xSrc += g_DbgXSrc;
                               ySrc += g_DbgYSrc;
                        }
```

In the end either ySrc -= 1 or ySrc -= 0 is best (leaving xSrc +=2), but I couldn't decide which one was _the_ best for ySrc.

**Comment by tomcw** [comment]
Also VT_COLOR_MONITOR looks like it needs the same xSrc+=2 correction for HGR, but seems well aligned for TEXT.

And if you have a colour video mode selected, press pause, then F7 to enter the debugger. The TEXT command will render the text screen with color burst on (F9, then CTRL+F9 will re-render with color burst off). But if the above xSrc+=2 correction is applied then the TEXT screen will be drawn misaligned relative to the other video modes.

**Comment by tomcw** [comment]
From cea2, "AppleWin 1.26.0 pre-release" thread:

**Comment by tomcw** [comment]
My repro:
```
 10  HGR2 
 100 I = 1
 200  HCOLOR= I
 210  HPLOT 0,0 TO 279,0 TO 279,191 TO 0,191 TO 0,0
 220  GET A$
 230 I = I + 1
 240  IF I = 4 THEN I = 5
 250  IF I = 8 THEN I = 1
 300  GOTO 200
```

**Comment by tomcw** [comment]
It's easy to correct in HIRES or MIXED modes: just change `void VideoRefreshScreen()` to adjust `xSrc` for `VT_COLOR_MONITOR` too:
```
	if (g_eVideoType == VT_COLOR_MONITOR || g_eVideoType == VT_MONO_TV || g_eVideoType == VT_COLOR_TV)
	{
		// Adjust the src locations for the NTSC video modes
		xSrc += 2;
	}
```

But for TEXT-only mode, this video mode is now wrong. Try pressing F9 to cycle through the modes.
NB. without the above `xSrc+=2` change, the TEXT-only mode is correctly aligned.

**Comment by tomcw** [comment]
Similar repro to above, but stop after drawing frame in white.
Then use `GOTO 1000` to run the 2nd part.

NB. In "Color Monitor" mode it switches between no color burst (in TEXT-only) and color burst (in MIXED). This is the only video mode where you can see a difference in the x-pos when holding a key down (for this 2nd part).

```
 10  HGR 
 100 I = 1
 200  HCOLOR= I
 210  HPLOT 0,0 TO 279,0 TO 279,191 TO 0,191 TO 0,0
 220  GET A$
 230 I = I + 1
 240  IF I < 4 THEN  GOTO 200 
 300  END
 1000 A = 49232
 1005 B =  PEEK (A + 7): REM  HIRES ON
 1006 B =  PEEK (A + 3): REM  MIXED ON
 1010 B =  PEEK (A)
 1020  GET A$
 1030 B =  PEEK (A + 1)
 1040  GET A$
 1050  GOTO 1000
```

**Comment by tomcw** [comment]
NB.  3e51f2f was to fix an occasional shimmering occurring during ANSI STORY's end credits:
When the TEXT80 part of the scanline was active during `void VideoRefreshScreen()`, then it wouldn't do the `xSrc += 2` adjustment... so the extended fix uses the color-burst signal instead.

**Comment by Michaelangel007** [comment]
I ran into this bug on [v1.26.03](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.0.3) with my game mod and was about to log a new bug _"HGR orange end scanline cutoff"_ when I decided to verify the status on:

* [v1.26.2.1](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.1)
* [v1.26.0.6](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.0.6)

Which I'm happy to see fixed in 1.26.0.6 onwards.

Simple repro. that I was using:

```
HGR
CALL-151
2001:D5 N 2027:D5 N 2401:95 N 2427:95
```

The first group of pixels in column 1 is just to provide a reference for the end scanline bytes -- `D5` and `95`

**Comment by Michaelangel007** [comment]
Reference pictures:

* Working 1.25.03 (pre-NTSC)
![orange_1 25 0 3](https://cloud.githubusercontent.com/assets/7876796/25043403/9a5a34f8-20d4-11e7-8c41-2c2ae9766710.png)

* Broken 1.26.0.3
![orange_1 26 0 3](https://cloud.githubusercontent.com/assets/7876796/25043410/a0c2a2b2-20d4-11e7-9213-32d2849e5c01.png)

* Fixed 1.26.06
![orange_1 26 0 6](https://cloud.githubusercontent.com/assets/7876796/25043432/c358641a-20d4-11e7-8302-fe834bf2a8ad.png)

* Jace
![orange_jace](https://cloud.githubusercontent.com/assets/7876796/25043417/ad23e91c-20d4-11e7-8d02-a891a2913ae0.png)

**Comment by tomcw** [comment]
There's a .dsk in the AppleWin-Test repo which includes a test for this bug, [here](https://github.com/AppleWin/AppleWin-Test/commits/master/v2/Tests-Various.dsk).
See [this index file](https://github.com/AppleWin/AppleWin-Test/blob/master/test%20index.txt) for a list of tests.

**Comment by tomcw** [comment]
Closing this old bug.
