### ISSUE TITLE
AZTEC.DSK boot time

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#347]
I'm interested in the timings you get for AZTEC.DSK (from boot to when it says "Press any key").

For 1.26.0.1:
- On my desktop PC (Win7-64, AMD Phenom II dual-core @3GHz) it takes 32s(!)
- But on my VAIO laptop (Win7-64, Intel Corei7 quad-core-HT @2.20GHz) it takes 6-7s.

For 1.25.0.3:
- Desktop: 2-3s
- VAIO: 4-5s

Clearly something is going badly wrong with this build on for my desktop PC.
NB. 1.25 was built with VS2005, 1.26 is built with VS2008.

Also use the -log argument to get AppleWin to automatically log the time for AZTEC from boot to "Press any key", eg look for:

> Time from emulation reboot until first $C000 access: 33758 msec

**Comment by sicklittlemonkey** [comment]
Hi Tom.​

With my desktop (i5, quad-core, 3.2GHz) I just used a stopwatch a few times
from F2 to seeing "PRESS ANY KEY".
1.26(.0.1): around 4s.
1.25(.0.3): around 2s.

So even on my machine it's noticeable, and I loves me a performance problem
to solve! ; - )

The VS profiler is useless as usual, so I started up the Very Sleepy
profiler, and the difference is obvious but then a bit of a puzzle.

Top of the list by exclusive time in 1.26:
CreatePalette 14.07s 14.07s 31.06% 31.06% GDI32 [unknown] 0 0x7617707c
(For me - might be different for others depending on graphics hardware and
driver.)

Whereas in 1.25 it's way down the list:
CreatePalette 0.03s 0.03s 0.11% 0.11% GDI32 [unknown] 0 0x7617711c

The puzzle is that we don't call CreatePalette - so something outside our
code is. However putting breakpoints on the WOW64 CreatePalette entry point
doesn't catch anything, and the profiling call stacks don't show the
culprit, which means it's being called from within another Win32 API. I
haven't delved into the 64->32 bit thunking layer, and didn't bother: it's
pretty obvious it can only be StretchBlt.

So adding some code to count StretchBlt calls gives me the following counts
per period from F2 to "PRESS ANY KEY":
1.26: around 12000 calls
1.25: around 10 calls

The difference must come down to this:
if (hFrameDC && anydirty)

When there are no changes to the frame buffer, builds <1.26 don't call
StretchBlt, and are much faster.

The difference between your two PCs would be the graphics hardware or
driver implementation.
Some feature used by StretchBlt is probably being emulated in software on
your desktop.

Now that the graphics are being generated line by line in 1.26, there are a
couple of ways to track frame buffer changes. I've tried both in the past.
1. Set a flag for the screen (or line or block etc) when the change is made
like builds <1.26 do. This is probably the most efficient, but probably
more places in the code to change because of the way emulators usually
break out each video mode.
2. Keep a copy of all the bytes fed for each line through the video
generator . Compare each new byte to the old byte as it's fed through to
detect a change. Centralised, so less code, but more CPU intensive than 1.
Avoids the StretchBlt penalty though.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
Just FYI, since it annoyed me I checked the addresses in the call stacks from Very Sleepy.

CreatePalette	GDI32	[unknown]	0	0x7617730c

Very Sleepy didn't show it, but going to the disassembly finds the 64-bit thunk for StretchBlt, as expected - that address is the instruction after the call:
```
_NtGdiStretchBlt@48:
76177300  mov         eax,1034h  
76177305  mov         edx,offset _Wow64SystemServiceCall@0 (7617BCB0h)  
7617730A  call        edx  
7617730C  ret         30h  
7617730F  nop
```

**Comment by tomcw** [comment]
Great detective work! I'll have to start using Very Sleepy!

Now that you've isolated StretchBlt() as the culprit, I made a small fix to the main loop, from:

```
	if (g_bFullSpeed)
		VideoRedrawScreenDuringFullSpeed(g_dwCyclesThisFrame);
	VideoRefreshScreen(0); // Just copy the output of our Apple framebuffer to the system Back Buffer
```

to:

```
	if (g_bFullSpeed)
		VideoRedrawScreenDuringFullSpeed(g_dwCyclesThisFrame);
	else
		VideoRefreshScreen(0); // Just copy the output of our Apple framebuffer to the system Back Buffer
```

This results in these better numbers:
- Desktop PC (AMD Phenom II): 2.5s
- Laptop (Intel core-i7): 3s

btw. you said:
> Now that the graphics are being generated line by line in 1.26 ...

Actually in **full-speed** mode, I disable the per-opcode video update (eg. in 65C02.cpp, `Cpu65C02()`). Instead every >=17030 cycles (ie. Apple II video frame), I update the whole screen, but only if any data has changed in that video mode's RAM.

Thinking about it, this will be wasteful too, since full-speed may run at 100x (of an Apple II), so in a real PC 60Hz frame I only need to update once, not 100 times.

**Comment by tomcw** [comment]
I've built, tested and uploaded a new pre-release here:
https://github.com/AppleWin/AppleWin/releases/tag/v1.26.0.2

I am going to leave this issue open for now, as I want to do my own analysis (eg. count calls to StretchBlt, and do additional timing on other machines).

**Comment by Michaelangel007** [comment]
Did we want to let comp.emulators.apple2 know about the pre-release for testing?

Speaking of Usenet ...

https://groups.google.com/d/msg/comp.sys.apple2/xSgkd5MeKfM/iduAocz1EwAJ

```
> On an non-enhanced Apple IIe (tested with AppleWin), if i quit from 
> BASIC.system with the 80-column firmware engaged, i get a beep instead 
> of the file list.  A reset, at this point, returns things to normal. 

sigh.  Yes, I see it.  The firmware isn't 100% register-compatible. 
3 bytes penalty to fix.
```

**Comment by Michaelangel007** [comment]
Tom, which [Aztec](ftp://ftp.apple.asimov.net/pub/apple_II/images/games/action/aztec) DSK image you using?

**Comment by Michaelangel007** [comment]
Using the .zip image:

|Computer| Time |
|:---|:---|
|i7 4770K & 3.5 GHz,, GTX 980 Ti| 2,6 sec |
|AMD Phenom II 955BE @ 4GHz | 3.6 sec |

**Comment by Michaelangel007** [comment]
OK, timings updated. :-)

**Comment by Michaelangel007** [comment]
Whoops, Tom, I edited one of your comments, instead of replying ...

**Comment by Michaelangel007** [comment]
> Actually in **full-speed** mode, I disable the per-opcode video update (eg. in 65C02.cpp, `Cpu65C02()`). Instead every >=17030 cycles (ie. Apple II video frame), I update the whole screen, but only if any data has changed in that video mode's RAM.

I'm assuming cpu65C02.h, lines 325-331  ?

https://github.com/AppleWin/AppleWin/blob/5fdc879a05abdbc59590f23954268c2a1448dc6d/source/CPU/cpu65C02.h#L325-L331

**Comment by sicklittlemonkey** [comment]
> > On an non-enhanced Apple IIe (tested with AppleWin), if i quit from
> > BASIC.system with the 80-column firmware engaged, i get a beep instead
> > of the file list.  A reset, at this point, returns things to normal.
>
> sigh.  Yes, I see it.  The firmware isn't 100% register-compatible.
> 3 bytes penalty to fix.

I believe this is talking about compatibility between the enhanced and
un-enhanced //e ROM.

Nothing for us to do.

**Comment by tomcw** [comment]
Hi Michael,
>> Actually in full-speed mode, I disable the per-opcode video update...

> I'm assuming cpu65C02.h, lines 325-331 ?

Yes, that's it (and the same for cpu6502.h and your debug cpu65d02.h too).

> Using the .zip image, Manual and `-log` timing:

I used the unzipped image (ie. AZTEC.DSK) just in case the zip support code was interfering with timings. I've now added it to the test repo, here: https://github.com/AppleWin/AppleWin-Test.

re. AppleWin -log, this is slightly broken... the initial value is wrong when you F2 from the AppleWin start-up screen (which is why the values you reported are so much bigger). Hitting F2 again will reset the timers correctly. I'll fix this.

**Comment by Michaelangel007** [comment]
@sicklittlemonkey Thanks for the confirmation Nick.  I was worried we weren't emulating the firmware correctly.

**Comment by Michaelangel007** [comment]
@tomcw Thanks for adding `AZTEC.DSK` to our sister repo. (I keep forgetting about it -- I've starred it now in GitHub.)

**Comment by tomcw** [comment]
Timings for a desktop Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz:
- 1.25.0.4: ~2s
- 1.26.0.3: 1.9s (using -log to get accurate timing)

(NB. 1.26.0.3 fixes the "slightly broken" -log switch as reported above, so the AZTEC timings are now correct for the 'launch AppleWin & F2' case.)

Ultimately, the only reason why 1.26.0 should be slower (in **full-speed mode**) than 1.25.0 is due to the whole-screen redraw... oh and that check each time round the 6502 opcode emulation loop to check for full-speed.

We could duplicate the 6502 opcode emu function: 1 for full-speed, and 1 for normal-speed, so that the 1000x 6502 cycles per emulation slice (= 400 opcodes?) don't need to check `g_bFullSpeed` for each opcode.

And the whole-screen redraw could be moved to another CPU core (for full-speed mode), but given that the timings (1.25 vs 1.26) have parity (...well for this specific case), then I don't see the need to further complicate the code.

**Comment by sicklittlemonkey** [comment]
On 19 September 2016 at 02:49, TomCh <notifications@github.com> wrote:

> Actually in full-speed mode, I disable the per-opcode video update (eg.
in 65C02.cpp, Cpu65C02()). Instead every >=17030 cycles (ie. Apple II video
frame), I update the whole screen, but only if any data has changed in that
video mode's RAM.
>
> Thinking about it, this will be wasteful too, since full-speed may run at
100x (of an Apple II), so in a real PC 60Hz frame I only need to update
once, not 100 times.

Tom, did you fix the above? Refresh based on time rather than cycle count?
I think it's a good idea.

Cheers,
Nick.

**Comment by tomcw** [comment]
Not yet. I'll try it and report back here with my results. . .

**Comment by tomcw** [comment]
**Desktop PC (AMD Phenom II)**

During AZTEC boot to "PRESS ANY KEY":
- VideoRedrawScreenDuringFullSpeed(UINT,false) called 0x2fd9 times with 0x89 calls to VideoRedrawScreen()
- Time = 2667ms

Then I changed the code to only update every 16ms (for a continuous full-speed period):
- VideoRedrawScreenDuringFullSpeed(UINT,false) called 0x26 times with 0x26 calls to VideoRedrawScreen()
- Time = 2402ms

So only a 260ms time saving for AZTEC, mainly doing much less memcmp()/memcpy() and 0x63 less VideoRedrawScreen() calls.

(NB. VideoRedrawScreenDuringFullSpeed(UINT,**true**) is essentially zero work, and is for the full-speed to normal-speed transition case to invalidate the video memory caches - which is why I've not included counts for it.)

**Comment by tomcw** [comment]
But this 'update every 16ms of real-time' works very well for #351 :)

**Comment by tomcw** [comment]
FYI, from AppleWin 1.26.1.1 to 1.26.2.0, I'm seeing a 16% speed-up for the AZTEC.DSK boot time:
- 1.26.1.1: 2.34s
- 1.26.2.0: 1.95s

Using my desktop PC (Win7-64, AMD Phenom II dual-core @3GHz).

The reason for this speed-up is the removal of the debug breakpoint support during the normal 6502 emulation loop. Ref: #217, #291, #384.

For the debug (MODE_STEPPING) timings see: #383.

**Comment by tomcw** [comment]
Closing this as there's nothing more to do.

NB. It's included in the AppleWin-Test repo, so AZTEC boot timings get checked each release when I run all those tests.

**Comment by sicklittlemonkey** [comment]
I haven't had time to look at the test repo yet, but that is great news!
Good on you for setting up a test suite. One of the few genuinely
progressive changes in modern dev.

Cheers,
Nick.

**Comment by tomcw** [comment]
>I haven't had time to look at the test repo yet

It's dead simple. Just a BAT file with a list of save-state files to run. (Actually 2 BAT files: one for v1 save-states, and then the main one for v2 save-states.)

Currently you have to manually kill AppleWin (ALT+F4) to move to the next test. And there's lots of things missing, but having a consistent set of tests (that is gradually growing) means I have increased confidence when doing a release.

Also when bugs are reported, then I will try to add a new test (when the bug is fixed), to try to stop regressions.

An obvious deficiency is testing the debugger - current tests just tests emulator functionality. But very recently I have added a 2nd "micro" unit-test for the debugger (VS2008 only at the moment), These unit-tests get run every time you build AppleWin. The 1st "micro" unit-test was "TestCPU6502" which tests all the 6502/65C02 opcodes function and cycle timings.

Anyway, all this is very much work in progress!

**Comment by sicklittlemonkey** [comment]
Sounds good.

> Currently you have to manually kill AppleWin (ALT+F4) to move to the next
test.

If you use PowerShell you can send a keypress to a Window. I mean, you can
do almost anything since you have the full .NET runtime at your disposal.
Of course there are probably command line apps you could use, or AutoHotKey
etc.

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
> Currently you have to manually kill AppleWin (ALT+F4) to move to the next test. 

Can we automate this ? i.e. Debugger `quit`, etc.  How do Windows (GUI) programs intercept "pipe" output anyways?

**Comment by Michaelangel007** [comment]
> If you use PowerShell 

Powershell. Bah, Humbug. 

Should be able to use a .vbs to do this ... which I seem to recall I've done.

* [Sending Keystrokes to a Program](https://technet.microsoft.com/en-us/library/ee156592.aspx])

```
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.AppActivate "AppleWin"
objShell.SendKeys "%{F4}"
```

And to run: `start close_applewin.vbs`

**Comment by tomcw** [comment]
>Currently you have to manually kill AppleWin (ALT+F4) to move to the next

The problem isn't simply being able to send a keystroke to the running AppleWin, but knowing what to observe and how long to wait before hitting ALT+F4.

EG. Some tests will start midway through a game (or productivity s/w) and expect you to interact with it (eg. play Arkanoid, in Dazzle Draw to use the mouse to draw a line or listen to the music in the Phasor / Mockingboard tests).

It's not simple to solve, so I've just opted for the easy manual approach.
