### ISSUE TITLE
Full-speed in mixed mode results in flickery video

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#352]
Steve Nickolas reported this on cea2, in the "AppleWin 1.26.0 (pre-release)" thread:

> Let's say I'm in split HGR mode and I BSAVE a file, A8192,L8192... 
> 
> While the drive's operating, the screen becomes a flickery mess, 
> constantly changing video modes between full text and full graphics... 

I've verified (in both GR and HGR mixed modes), and check 1.25.0 which doesn't not exhibit this behaviour.

**Comment by sicklittlemonkey** [comment]
​Just FYI, I did a quick few checks:
- BSAVE doesn't access C055
- This happens even in Apple II+ mode and in monochrome screen modes.
- Trying to debug in 1.26.0.3 is screwy. After (g)o it shows the Apple II
screen but says [stepping] in the window title bar, and the screen isn't
updated although text entry is working behind the scenes - having
breakpoints seems to prevent screen updates.

Cheers,
Nick.

**Comment by tomcw** [comment]
The problem is in full-speed mode, (enabled when drive is on, ie. during BSAVE):

`VideoRefreshScreen(int, UINT)` calls:
- `NTSC_VideoUpdateCycles( VIDEO_SCANNER_6502_CYCLES )`

This calls this function pointer: g_pFuncUpdateGraphicsScreen( cycles6502 ), with cycles6502 = VIDEO_SCANNER_6502_CYCLES, ie, calls `updateScreenSingleLores40( cycles6502 )`:

```
void updateScreenSingleLores40 (long cycles6502)
{
	if (g_nVideoMixed && g_nVideoClockVert >= VIDEO_SCANNER_Y_MIXED)
	{
		g_pFuncUpdateTextScreen( cycles6502 );
		return;
	}

	// otherwise update for LORES-40
```

So depending on g_nVideoClockVert (which in full-speed mode is effectively random), then either the whole screen will be updated as TEXT or GR (never MIXED).

We probably need a new function just for the `VideoRefreshScreen(int, UINT)` case.

**Comment by tomcw** [comment]
btw. a simpler repro is:
`]GR`
then repeatedly tap Scroll Lock key.
(with Config->Input: "[] Scroll Lock acts as toggle for full-speed CPU" **unchecked**)

**Comment by tomcw** [comment]
NB. 700a9e9 was another regression: on loading Ansi-Story (save-state during split-video mode) the V/H position was being reset to (0,0) breaking the split-video effect. But preserving the V/H position around the screen update caused the line-0 corruption (in 5f0ccfc)!
