### ISSUE TITLE
Split screen (TEXT/GR) doesn't look right for //e

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#359]
From cea2, "Any pointers on emulating an Apple IIe (enhanced) in Mame on Mac OS X?", Zellyn posted a link to his dsk image:

> If you want to try at home, the disk image is floatbus.dsk here: 
> https://github.com/zellyn/a2audit/tree/master/floatbus

Nick, you said:

> So yeah, OE is showing the correct behaviour for an analog monitor.
> AppleWin shows the same but in colour.

From the code (a2audit in GitHub), it seems that the 2nd half of the screen should remain in GR mode until the last line at $7D0, which is all $A0's.

But this is what I'm seeing with 1.26.0.5:
(And with prior 1.26.0.n versions and with Sheldon's AppleWin-NTSC-05 version too)

![applewin_screenshot_000000000](https://cloud.githubusercontent.com/assets/6696896/19356963/7bb2690a-9167-11e6-9c08-c45f50bb5b77.png)

**Comment by sicklittlemonkey** [comment]
Apologies Tom, I just replied in the thread now to clarify.

OE emulates the Apple II, not the Apple //e, and the Apple Split routine
was written by Bob Bishop for the Apple II.

The image above is what you get with AppleWin //e scanning. The AppleWin
Apple II scanning looks better - exactly like OE.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,
So it does! Thanks for pointing that out.

btw. In AppleWin's Debug.cpp, go to line 7719 to enable this macro:
`#define TRACELINE_WITH_VIDEO_SCANNER_POS 1`

Now when you use the built-in AppleWin debugger, and use the "tf" command (TraceFile) you get additional vpos & hpos video scanning positions. It's been in the code for some months now. I should really make it a real feature in AppleWin.

Here's where the Apple Split code gets the wrong $A0 sync (for the //e):

```
text
line   Vpos
-----------
11   -  88	````````
11.5 -  92  green line
12   -  96  black line
12.5 - 100  multi-coloured line
13   - 104  U&7...

Vert Horz A: X: Y: SP:  Flags     Addr:Opcode    Mnemonic
0065 0040 A0 04 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 0003 A0 04 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C	; Vpos=102
0066 0005 A0 04 00 01EE ..RB.IZC  6053:CA        DEX 
0066 0007 A0 03 00 01EE ..RB.I.C  6054:D0 F8     BNE $604E
0066 000A A0 03 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 000E A0 03 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 0010 A0 03 00 01EE ..RB.IZC  6053:CA        DEX 
0066 0012 A0 02 00 01EE ..RB.I.C  6054:D0 F8     BNE $604E
0066 0015 A0 02 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 0019 A0 02 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 001B A0 02 00 01EE ..RB.IZC  6053:CA        DEX 
0066 001D A0 01 00 01EE ..RB.I.C  6054:D0 F8     BNE $604E
0066 0020 A0 01 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 0024 A0 01 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 0026 A0 01 00 01EE ..RB.IZC  6053:CA        DEX 
0066 0028 A0 00 00 01EE ..RB.IZC  6054:D0 F8     BNE $604E
0066 002A A0 00 00 01EE ..RB.IZC  6056:8D 51 C0  STA $C051	; Vpos=102, Hpos=42 (~half way through line)
```

So it has done 4 consecutive successful CMP $C050, reading $A0 each time: at Hpos: $40,$0A,$15,$20
But the video starts at Hpos=25=$19, so I don't understand why the CMP $C050 at Hpos=32=$20 is reading $A0.

**Comment by sicklittlemonkey** [comment]
Nice logging. : - )

I don't have time to look in detail right now, but it's best to read the
section starting at page 5-40 in Sather's Understanding the Apple //e.

Eg:
Programs written for the Apple II may well not
perform correctly on the Apple lIe because of
differences in scanning during HBL. In the
Apple II. HBL scanned memory was separate
from other display memory in TEXT/LORES
scanning. In the Apple lIe. HBL scanned memory
overlaps other scanned memory in TEXT/
LORES scanning in similar fashion to HIRES
scanning.

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
Gentlemen,

This may be of interest / help:

File: [NTSC.cpp](https://github.com/AppleWin/AppleWin/blob/master/source/NTSC.cpp), 

* [APPLE_IIP_HORZ_CLOCK_OFFSET](https://github.com/AppleWin/AppleWin/blob/master/source/NTSC.cpp#L230) 

* [APPLE_IIE_HORZ_CLOCK_OFFSET](https://github.com/AppleWin/AppleWin/blob/master/source/NTSC.cpp#L278)

**Comment by tomcw** [comment]
[Have an Apple Split, by Bob Bishop, Softalk, October 1982](http://rich12345.tripod.com/aiivideo/softalk.html)

> a complete sixty-five-cycle scan line consists of sixty-five consecutive bytes of display buffer memory that starts twenty-five bytes prior to the actual data to be displayed.

On the Apple //e, something different happens during HBL.
(And above, Nick quotes this HBL difference from Sather's UTAIIe book)

>Another subtlety in the example program lies in our choice of $A0 and $E0 as tag bytes. While any values could have been used as tags, the values $A0 and $E0 are especially useful because they both appear as blanks on a text screen. On a lo-res graphics screen they appear (in our example) as a row of black (or blank) over a row of color.

But on the Apple //e, $E0 is a ` char.

**Comment by tomcw** [comment]
An updated trace to include video-scanner addr & floating bus data, for Apple //e:
```
Vert Horz Addr Data A: X: Y: SP:  Flags     Addr:Opcode    Mnemonic
0065 0040 064D   A0 A0 04 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 0003 0610   A0 A0 04 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 0005 0612   A0 A0 04 00 01EE ..RB.IZC  6053:CA        DEX 
0066 0007 0614   A0 A0 03 00 01EE ..RB.I.C  6054:D0 F8     BNE $604E
0066 000A 0617   A0 A0 03 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 000E 061B   A0 A0 03 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 0010 061D   A0 A0 03 00 01EE ..RB.IZC  6053:CA        DEX 
0066 0012 061F   A0 A0 02 00 01EE ..RB.I.C  6054:D0 F8     BNE $604E
0066 0015 0622   A0 A0 02 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 0019 0626   A0 A0 02 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 001B 0628   50 A0 02 00 01EE ..RB.IZC  6053:CA        DEX 
0066 001D 062A   70 A0 01 00 01EE ..RB.I.C  6054:D0 F8     BNE $604E
0066 0020 062D   A0 A0 01 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
0066 0024 0631   E0 A0 01 00 01EE ..RB.IZC  6051:D0 F9     BNE $604C
0066 0026 0633   00 A0 01 00 01EE ..RB.IZC  6053:CA        DEX 
0066 0028 0635   20 A0 00 00 01EE ..RB.IZC  6054:D0 F8     BNE $604E
0066 002A 0637   40 A0 00 00 01EE ..RB.IZC  6056:8D 51 C0  STA $C051
```

This func calcs the video-scanner addr:
```
INLINE uint16_t updateVideoScannerAddressTXT()
	g_aHorzClockMemAddress[ g_nVideoClockHorz ] = 
		g_aClockVertOffsetsTXT[g_nVideoClockVert/8] + 
		g_pHorzClockOffset[g_nVideoClockVert/64][g_nVideoClockHorz] + 0x400;
```

For addr: V=$65,H=$40
. IIP: 0x200 + 0x004F + 0x400 = 0x064F
. IIE: 0x200 + 0x004F + 0x400 = 0x064F

NB. IIP & IIE are always the same addr for visible parts of hline.
NB. NTSC_VideoGetScannerAddress() adjusts hclk by -2 (so addr= 0x64D).

At $64D there is a $A0 char, this is the start of the $A vertical GR line, with the $0 being for the horizontal black GR line above.

For addr: V=$66,H=$0A
. IIP: 0x200 + 0x1019 + 0x400 = 0x1619
. IIE: 0x200 + 0x0019 + 0x400 = 0x0619

NB. $617 (or  $619-2) is located in the top TEXT part which is all $A0 chars.
Whereas for the IIP, the hblank fetch occurs from $1617, which isn't a $A0 char.

So the IIP fetches HBl data from outside TEXT1 & TEXT2 memory, whereas the IIE fetches HBl data from within TEXT1 memory. This explains why the IIE is getting an early sync on 4x $A0 values.

**Comment by sicklittlemonkey** [comment]
Thanks Tom. That logging will be really handy.

Cheers,
Nick.

**Comment by tomcw** [comment]
NB. The Apple Split code doesn't initialise the $1600..16FF range, so on an A][+ prefilling with $A0 gives you a similar result to an A//e:

```
]BLOAD BHELLO
]CALL -151
*1600:A0
*1601<1600.16FFM
*6000G
```
![applewin_screenshot_000000000](https://cloud.githubusercontent.com/assets/6696896/20075222/47f407a4-a52b-11e6-98eb-a19105ef025e.png)

**Comment by tomcw** [comment]
>Now when you use the built-in AppleWin debugger, and use the "tf" command (TraceFile) you get additional vpos & hpos video scanning positions. It's been in the code for some months now. I should really make it a real feature in AppleWin.

This is now done (074acce):
```
tf "<file.txt>" [v]
```

With this extension you now get: vpos, hpos, video scanner addr, video data on bus + the original CPU state, eg:
```
Vert Horz Addr Data A: X: Y: SP:  Flags     Addr:Opcode    Mnemonic
0065 0040 064D A0   A0 04 00 01EE ..RB.I.C  604E:CD 50 C0  CMP $C050
```
