### ISSUE TITLE
Feature suggestion: report volume number

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#360]
I know the .dsk format doesn't support Volume numbers. And most emulators don't either. But would it be feasible to have the Applewin "report" a Volume number of our choosing for programs that want a specific number?

Like how Sierra games want 000, 001, 002, and so on? And this would be useful for testing out DOS 3.3 HDD programs and patches.

**Comment by sicklittlemonkey** [comment]
Those images should be wrapped into 2MG files and have a volume number set.
(Ciderpress can do this.)

AppleWin will then use the correct volume number.

**Comment by Keatah** [comment]
Applewin doesn't support drag'n'drop of 2mg files does it?

**Comment by sicklittlemonkey** [comment]
Did you try this before asking? ; - )

Yes, it does support 2MG drag and drop - to the main windows and to the
drive.

It doesn't claim the filetype so you can't double click a 2MG file by
default.

Perhaps that should be a feature request.

**Comment by Keatah** [comment]
I see what's happening now. I tried several 2mg images from asimov. Basically Applewin says to mount them as an HDD. Then they work. They were 801kb in size. The 141kb sized 2mg (wrapper) images drag-n-drop ok.

I think I understand why it works that way. Just that as an end user I would expect all images to be drag'n'drop capable.

I suppose the documentation in ciderpress/applewin explains everything. It's just that with so many commercial products being dumbed down with closed eco-systems and cryptic icons, I've lost faith in documentation these days. The same goes for error messages too sometimes. So used to meaningless dialog that states the obvious.

**Comment by sicklittlemonkey** [comment]
Yes, unfortunately 3.5 inch or HD image drag and drop is not supported.

(The volume number has no meaning for those.)

**Comment by tomcw** [comment]
Closing this as "won't fix", but I've spun off the UX improvements here: #361
