### ISSUE TITLE
ImageOpen using CDiskImageHelper instead of CHardDiskImageHelper when called from HD_Insert

### ISSUE THREAD

**Issue by rhoem1** [AppleWin/AppleWin#368]
I've got a few .hdv files that are between 800 * 1024 + 64 + 128 and 32 * 1024 * 1024 + 128.  When I try to mount one, the code flows into a call to ImageOpen which ends up using CDiskImageHelper::GetMaxImageSize() instead of CHardDiskImageHelper::GetMaxImageSize() via sg_DiskImageHelper.Open()

This causes Open() to return eIMAGE_ERROR_BAD_SIZE for any .hdv larger than an 800k floppy.

I think passing in the disk image helper needed to ImageOpen is likely the best solution.

Originally, .hdv's were designed to start at 0 bytes and grow to 32mb.

**Comment by tomcw** [comment]
Isn't this (a duplicate and) fixed by #348 ?

**Comment by rhoem1** [comment]
I apparently have 1.26.0.1, so  yes.  nevermind then.
