### ISSUE TITLE
Question about 80STORE flag

### ISSUE THREAD

**Issue by allender** [AppleWin/AppleWin#378]
I have been working on my own apple 2 emulator, and AppleWin has been an incredible reference.  Thanks for continuing to improve AppleWin.  It's been awesome having such a great resource.

 In looking over some of the code, I have a question about the 80STORE flag in the video section.  There are these lines in video.cpp: 1314

```
	// Apple IIe, Technical Notes, #3: Double High-Resolution Graphics
	// 80STORE must be OFF to display page 2
	if (SW_80STORE)
		g_uVideoMode &= ~VF_PAGE2;
```

I read through the technical note referenced in the comment, and I do not read the information in the technical note in the same way as is documented in this comment.  In particular, the technical note says:

"The PAGE2 switch normally selects the display page, in either graphics or text mode, from either page 1 or page 2 of the motherboard memory.  However, it does so only when the 80STORE switch is off."

I read this comment to mean that the page2 switch only selects page 1 or page 2 from main ram with the 80store switch is off.  I do not read it that the page2 switch should be turned _off_ when the 80STORE switch is active.  I was hoping you could help clarify for me your interpretation of these lines of code, or why this code is present in AppleWin.  Having worked with your emulator a bunch, I haven't run across errors, but in doing my own work, this code seems to be unnecessary and in fact a potential bug (that might be corrected for elsewhere in your code).  Thanks.

Thanks

**Comment by tomcw** [comment]
Hi Mark,

Thanks for the positive comments.

My understanding is 80STORE is used to allow faster update to 80-column text (generated from page1 from both main & aux memory) by changing the behaviour of the PAGE2 soft switch:
. 80STORE=0: PAGE2 selects between main memory's page1 or page2
. 80STORE=1: PAGE2 selects between main & aux memory's page1

So from the video generator's point of view if 80STORE=1 and PAGE2=1 then the video generator will not fetch video data from page2 (ie. 80STORE=1 tells the video generator to ignore PAGE2).

Given this, then I think the comment is correct.

>I read this comment to mean that the page2 switch only selects page 1 or page 2 from main ram with the 80store switch is off.

Yes this is my understanding too.

**Comment by allender** [comment]
Tom - Thanks for your response.  I realize why I thought this code was incorrect.  You are duplicating PAGE2 (and other flags) between video and memory subsystems.  I read the code as if it might be turning off the PAGE2 flag for the memory system as well (since I share flags in my code), but since the memory system has it's own flag. 

I appreciate the response.

**Comment by sicklittlemonkey** [comment]
Mark, Tom is correct. Also I would refer to Sathers books rather than
anything by Apple.

**Comment by allender** [comment]
Right.  My confusion resulted from the fact that the code in question looked like it was turing off the PAGE2 flag (which it is).  I incorrectly thought that it was turning off that flag for the memory system, while it's turning it off for the video system.  I was confused because if my (incorrect) assumption had been right, then I couldn't understand how the 80 column mode was working.

Thanks for the pointer to Sather's books.  I have mainly been using those as my reference actually so it's good to get confirmation about them.  I had followed the technote based on the comment in the code, but typically do use his books for references.

Thanks for your reply.
