### ISSUE TITLE
save state inside mouse code can cause hang

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#381]
The current bank for the mouse card is apparently not saved in the save-state file (or at least, it's not restored).
If the state was saved while the alt code is banked in, then loading that state will execute the wrong code because the unbanked code will run instead.

**Comment by tomcw** [comment]
Thanks for reporting this. I'll take a look.

Are you using AppleWin 1.26.0.x or an older version?

**Comment by tomcw** [comment]
Ignore me - it must be AppleWin 1.26.0.x, as the Mouse interface state wasn't saved previously.

And I think I see the problem: it appears the loading of the state isn't restoring the $Cn00 ROM.

**Comment by tomcw** [comment]
OK, I've tried a few things but I can't get this fail.

Here's what I've tried, all save-state files with PC in the range [$C400..FF]:

1) Apple //e (enhanced), Dazzle Draw, using mouse:
 - save-state: mouse-card's ROM at offset $000 banked in at $C400
 - save-state: mouse-card's ROM at offset $600 banked in at $C400
2) Apple //e (non-enhanced), mouse-card inserted. From monitor select internal ROM (C007:0) then jump into self-test  (C401G):
 - save-state: internal ROM switched in at $C400

I can successfully load these save-states with AppleWin 1.26.0.6.

NB. It's quite tricky to generate save-states with the PC in this range, so I built a special version of AppleWin that posted a WM_KEYDOWN message of F11 (ie. save-state) when it detected the PC in the range [$C400..FF] during the main `ContinueExecution()` loop.

Can you send or attach (just rename to have a .txt extension) your yaml save-state file. Can you also describe what you were doing and what game/software you were running?

Thanks.

**Comment by peterferrie** [comment]
> OK, I've tried a few things but I can't get this fail.
>
> Here's what I've tried, all save-state files with PC in the range
> [$C400..FF]:
>
> 1) Apple //e (enhanced), Dazzle Draw, using mouse:
>  - save-state: mouse-card's ROM at offset $000 banked in at $C400
>  - save-state: mouse-card's ROM at offset $600 banked in at $C400
> 2) Apple //e (non-enhanced), mouse-card inserted. From monitor select
> internal ROM (C007:0) then jump into self-test  (C401G):
>  - save-state: internal ROM switched in at $C400
>
> I can successfully load these save-states with AppleWin 1.26.0.6.
>
> NB. It's quite tricky to generate save-states with the PC in this range, so
> I built a special version of AppleWin that posted a WM_KEYDOWN message of
> F11 (ie. save-state) when it detected the PC in the range [$C400..FF] during
> the main `ContinueExecution()` loop.

Sorry, I just checked my version - 1.25.0.4.  Maybe that's the problem
after all.
I didn't upgrade because of the debugger/screen refresh issue in the
1.26 release version.
It sounds like I need to switch.

**Comment by tomcw** [comment]
Right, #363. I will try to put out an interim build with this (+ a few other fixes for reported bugs) soon.

**Comment by tomcw** [comment]
NB. I have added these save-states as new tests here:
"Add tests for internal & external ROMs when PC is in range [C400..FF]"
https://github.com/AppleWin/AppleWin-Test/commit/57c1a348c24bdec8e0f73a04ed9f6a1423aa6cb6

**Comment by tomcw** [comment]
Closing.

**Comment by tomcw** [comment]
> Right, #363. I will try to put out an interim build with this (+ a few other fixes for reported bugs) soon.
FYI: Fixed in release 1.26.1.0.
