### ISSUE TITLE
Reset not resetting the 40/80-col text mode for mixed-mode rendering

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#382]
Reported by Steve Nickolas on cea2.

A bug in AppleWin's video reset routine that's not resetting 40/80-col text mode for mixed-mode rendering.

So if you were in 80-col mode (eg. boot to AppleSoft, and do PR#3), then boot his basic80.dsk, and issue GR; then you will see this problem.

**Comment by sicklittlemonkey** [comment]
​Hi Tom.

Have you verified this on a physical machine?

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,

Specifically the problem is to do with the new NTSC backend. There's some replication of state between Video.cpp and NTSC.cpp.

When NTSC is rendering is mixed mode, then there is a dedicated function pointer for lines [160...191] to update the text part (it either points to a 40-col or 80-col text rendering function). This isn't getting correctly re-init'ed (when the A//e machine gets reset). It should be reset to the 40-col rendering function.

**Comment by sicklittlemonkey** [comment]
I see. Even after reading the thread I wasn't sure exactly what the problem
was. ; - )

Cheers,
Nick.

**Comment by tomcw** [comment]
Simple repro:
* Boot to AppleSoft
* PR#3
* GR
* CTRL+RESET
* GR

**Comment by tomcw** [comment]
Fixed in 1.26.1.1
