### ISSUE TITLE
"Enhanced disk speed" is very slow when debugger is active (1.26.1.0)

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#383]

**Comment by tomcw** [comment]
Hi Peter,

Can you describe the steps that demonstrate this?

When debugging is active (eg. a breakpoint is set, or running in "g" (go) mode) then emulation will run at full speed (aka unthrottled). But debugging is implemented as a single-step mode, ie. one opcode is emulated, then debug checks are carried out (eg. check if any breakpoint has been hit). This single-step mode is naturally slower then normal emulation.

When in normal emulation mode (debugger not active), _if the drive motor is on_, then "enhanced disk" runs emulation at full speed (aka unthrottled).

NB. There's a bit about the differences between enhanced vs authentic disk speed in #202.

**Comment by peterferrie** [comment]
Hi Tom,

> Can you describe the steps that demonstrate this?

I'll try again.  As you can see from the edit history, it took me
several attempts just to get the issue opened. :-/  Stupid machine.

> When debugging is active (eg. a breakpoint is set, or running in "g" (go)
> mode) then emulation will run at full speed (aka unthrottled). But debugging
> is implemented as a single-step mode, ie. one opcode is emulated, then debug
> checks are carried out (eg. check if any breakpoint has been hit). This
> single-step mode is naturally slower then normal emulation.
>
> When in normal emulation mode (debugger not active), _if the drive motor is
> on_, then "enhanced disk" runs emulation at full speed (aka unthrottled).
>
> NB. There's a bit about the differences between enhanced vs authentic disk
> speed in #202.

I start AppleWin, enter the debugger, and then use "g address" to set
a breakpoint and resume execution, such as booting a floppy.  At that
point, I find that the disk drive is equally slow in authentic or
enhanced speed, and in fact slower to access the disk than on the
Apple II real hardware.

The 1.26.0 version of AppleWin did not exhibit this behavior.

**Comment by tomcw** [comment]
FYI, Aztec load times running with debugger active (from power-on to "Press any key"):
> g 435	; 435: bit $c000

1.26.1.1: 36s
1.26.0.6: 32s    ; NB. #363 meant that the screen wasn't updated (fixed at 1.26.1.0)
1.25.0.4: 10s

NB, my comment about this in #363 was:
> NB. With AppleWin 1.26, the video is updated after every debug single-step operation. This gives a cycle accurate video display, but means that the debugger's `g` command runs much slower than in 1.25. We should probably offer a way for the debugger to ena/disable the cycle-accurate video when debugging (NB. debug single-step is used by more than just `g` command, eg. `tf` too).

**Comment by peterferrie** [comment]
> FYI, Aztec load times running with debugger active (from power-on to "Press
> any key"):
>> g 435	; 435: bit $c000
>
> 1.26.1.1: 36s
> 1.26.0.6: 32s    ; NB. #363 meant that the screen wasn't updated (fixed at
> 1.26.1.0)
> 1.25.0.4: 10s
>
> NB, my comment about this in #363 was:
>> NB. With AppleWin 1.26, the video is updated after every debug single-step
>> operation. This gives a cycle accurate video display, but means that the
>> debugger's `g` command runs much slower than in 1.25. We should probably
>> offer a way for the debugger to ena/disable the cycle-accurate video when
>> debugging (NB. debug single-step is used by more than just `g` command,
>> eg. `tf` too).

Thanks, I must have missed or forgotten about that comment.
It's exactly what I'm seeing, and yes, it would help greatly to have
an option to reduce and/or turn off screen updating during 'g'.
Perhaps a typeable command within the debugger itself - "screen
fast/screen off/screen normal", etc.

**Comment by tomcw** [comment]
Updated timings after fixes for #217, #291, #384.

On my desktop PC (AMD Phenom II), AZTEC.DSK boot time: (cf. #347)
- Normal: 2s
- Debugger, gg cmd: 15.5s
- Debugger, g cmd: 17s

**Comment by tomcw** [comment]
I've built an experiment (pre-release) 1.26.2.0 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.0).

**Comment by tomcw** [comment]
Confirmed by Peter in #389:
>Thanks, that solves the write-protect and **speed issue**

**Comment by Michaelangel007** [comment]
>    Normal: 2s
>    Debugger, gg cmd: 15.5s
>    Debugger, g cmd: 17s

WHOA -- that's a huge performance hit.  AH, timing discussion moved to #347.

**Comment by tomcw** [comment]
Yeah (from above) for the **full-speed** debug (MODE_STEPPING) case, we have gone from:

- 1.25.0.4: 10s
- 1.26.2.1: 15.5s

ie. a 50% slow down for the AZTEC.DSK boot-up time.

TBH, I didn't put any effort into optimising this MODE_STEPPING code-path. My priority was to simplify the MODE_RUNNING case (#347), with the nice side-effect of a small ~16% speed-up for the MODE_RUNNING case.

As you say in #217, having a dedicated 6502/65C02 emulation path for the debug (MODE_STEPPING) case is probably more optimal than hijacking the normal (MODE_RUNNING) emulation path.
