### ISSUE TITLE
g_bDebugNormalSpeedBreakpoints - what is the use-case?

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#384]
Hi Michael,

If you exit the built-in AppleWin debugger using SHIFT+F7 (where F7 is for the Debug button on the UI), then this sets `g_bDebugNormalSpeedBreakpoints = true`.

The associated comment in Frame.cpp says:

```
\\ MODE_RUNNING \\ Normal Speed Breakpoints: Shift-F7 exit debugger, keep breakpoints active, enter run state at NORMAL speed
```

This flag looks to only be used in the core cpu6502.h / cpu65C02.h emulation loops, ie:
```
	if( IsDebugBreakpointHit() )
		break;
```

Where this function is defined as:
```
	inline int IsDebugBreakpointHit()
	{
		if ( !g_bDebugNormalSpeedBreakpoints )
			return false;
		return _IsDebugBreakpointHit();
	}
```

Anyway, my question is what is the use-case for this (undocumented) feature?
Since it is undocumented, then maybe it was just added as an internal development aid, and I can remove it. What do you think?

**Comment by sicklittlemonkey** [comment]
Hmm, this is a feature I would like. In fact I would prefer this (running
debug with breakpoints at normal speed) to be the default for "g(o)", and a
modifier of different command (e.g. gg) to run debug mode at top speed.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,

Cross-referencing this issue with #383, then here's an draft spec:

command | run at normal speed | run at full speed | video quality
--|--|--|--
g(o) | yes | only if disk active, etc | precise(*)
gg | no | always | periodic

Video quality: (*)
- When running with g(o)
  - (normal speed), then it's assume there's enough PC time to render the video per 6502 cycle.
  - (full speed), then use periodic video update.
- When running with gg (full speed), then use periodic video update.

How does this sound?

**Comment by sicklittlemonkey** [comment]
That sounds great!

**Comment by Michaelangel007** [comment]
Hey, Tom

Sorry was away last week for business.  Let me take a look later this week and provide my thoughts on why this exists.

**Comment by tomcw** [comment]
Hi Michael,

I've removed `g_bDebugNormalSpeedBreakpoints` now at 743add80f0b6bf7498581a5d5a6a77e0e84894d8.

Basically I've reworked things so that in MODE_STEPPING, the debugger calls into the regular `ContinueExecution()` function one opcode at a time. This allows for normal speed (1MHz) emulation (with correct speaker sound & precise video rendering) coupled with all the debugger checks for breakpoints.

Since it's the regular `ContinueExecution()` function then (for example) you boost emulation speed by pressing the Scroll-Lock key.

Tom

**Comment by sicklittlemonkey** [comment]
> Since it's the regular ContinueExecution() function then (for example)
you boost emulation speed by pressing the Scroll-Lock key.

Ah, that's the missing ingredient!

Cheers,
Nick.

**Comment by tomcw** [comment]
I see that there's another part to checking for debug BPs - specifically "break on opcode", referenced in #291. I'll see if I can move this into the debugger-only (single-step / MODE_STEPPING) code path.

I also see that Nick requested G(o) at 1MHz in #217, so I'll use that for further discussion etc.

Anyway, the original point of this issue was to better understand the use-case for this (undocumented) feature... which I do now. So I'm going to close this.

**Comment by Michaelangel007** [comment]
Whoops, I never answered this.

I believe this is what the intended usage was:

* F7 exit debugger (but active), running full-speed
* Shift-F7 exit debugger (but active), normal-speed

Thinking about it now, I think usages are reversed.  We should open up a new feature request to swap the behavior of these keys.

**Comment by tomcw** [comment]
How do you exit the debugger (ie. switch to MODE_RUNNING)?

The g/gg cmds are trivially simple to type, so probably simpler to leave as-it (also less confusing for the end user... and F7 to enter/exit the debugger is nicely symmetrical).

**Comment by Michaelangel007** [comment]
Well, I'm a heavy user of function keys so I'd like to see them. ;-)

Am I missing something or will these work?

* F7 - Enter/Exit Debugger, running normal-speed
* Shift-F7 - Enter/Exit Debugger, running full-speed

**Comment by tomcw** [comment]
Just to expand on what you are proposing:

1. I'm in normal emulation mode, MODE_RUNNING
2. I press F7 which enters debugger (ie. show debugger's monitor view, and enters MODE_DEBUG)
3. I press F7 which exits debugger in `g` mode (ie. running normal-speed, but in MODE_STEPPING)

But how do I exit MODE_DEBUG or MODE_STEPPING and get back to MODE_RUNNING?

**Comment by sicklittlemonkey** [comment]
Yeah, this is what i was asking in the other thread.

If I enter the debugger with F7 and set some breakpoints, I would prefer to
need to use commnds (g, gg) to hit them,

To me it seems more intuitive that F7 turns off the debugger.

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
Thanks for the clarification and patience guys. :-)  I finally understand that we have 3 states and only 1 key!

I propose the following:

|Key     |Debugger Active?|Old Mode      |New Mode      | Effect        |Debug Speed |
|:------:|:--------------:|:-------------|:-------------|:--------------|:-----------|
| F7     | No             |MODE_RUNNING  |MODE_STEPPING | Enter debugger| n/a        |
| F7     | No             |MODE_STEPPING |MODE_STEPPING | Enter Debuger | n/a        |
| F7     | No             |MODE_DEBUG    |MODE_DEBUG    | Enter Debugger| n/a        |
| F7     | Yes            |n/a           |MODE_RUNNING  | Exit Debugger |disabled    |
|Shift-F7| Yes            |n/a           |MODE_STEPPING | Exit Debugger |normal speed|
|Ctrl-F7 | Yes            |n/a           |MODE_DEBUG    | Exit Debugger |full speed  |


Notes:

* Shift-F7 is an alias for g
* Ctrl-F7 is an alias for gg

I guess this might finally be motivation for custom keys -- as I would greatly prefer F7 to return to MODE_STEPPING -- but I think Nick has a point so I'll consent to that.

Now to retrain my brain to get used to Shift-F7 to exit the debugger ... :-)

**Comment by sicklittlemonkey** [comment]
Michael, sounds good, though I agree the change might be jarring, and
configurable keys would be great.

For instance it would be nice to be able to use the Visual Studio keys for
stepping etc - which would interfere with the existing function keys, but I
almost never use those from the debugger.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Michael,

These extensions for F7-modifiers seems fine to me, since there's no change to existing behaviour (I'm discounting the old SHIFT+F7 behaviour as that was never documented, so no one except you(!) knew about it).

**Comment by sicklittlemonkey** [comment]
On 16 April 2017 at 06:03, Michaelangel007 <notifications@github.com> wrote:
> Shift-F7 Yes n/a MODE_STEPPING Exit Debugger normal speed
> Ctrl-F7 Yes n/a MODE_DEBUG Exit Debugger full speed

One last thing - any chance of switching Ctrl and Shift around?

> Now to retrain my brain to get used to Shift-F7 to exit the debugger ...
:-)

Because I'm more likely to want to turn off the debugger (F7) or exit the
debugger at normal speed - like you prefer.
And Ctrl-F7 is "easier" to type than Shift-F7. ; - )

Cheers,
Nick.
