### ISSUE TITLE
support 40 tracks of .nib files

### ISSUE THREAD

**Issue by Andyeung** [AppleWin/AppleWin#387]
Anyone can help for modify a source (DiskImageHelper.cpp) to make AppleWin support up to 40 tracks .nib file? Thank you.
line 717:
from 		if (dwImageSize != NIB1_TRACK_SIZE*TRACKS_STANDARD)
to 		if (dwImageSize < NIB1_TRACK_SIZE*TRACKS_STANDARD || dwImageSize % NIB1_TRACK_SIZE != 0 || dwImageSize > NIB1_TRACK_SIZE*TRACKS_MAX)
and line 720:
from 				m_uNumTracksInImage = TRACKS_STANDARD;
to		m_uNumTracksInImage = dwImageSize / NIB1_TRACK_SIZE;

**Comment by tomcw** [comment]
Hi,
Can you point me to some links of 40-track .nib images?
I'll need these to test your pull-request.

**Comment by Andyeung** [comment]
https://mega.nz/#!twJSjCaQ!F7GnvEeN6cp46nl4ExUjC5Ud0amhKv6LeQPyW19BArc
This link has 36 tracks .nib file which has copy protection in that software. So it must use .nib format  without crack it.

**Comment by tomcw** [comment]
Can you tell me how I can use the 2nd disk -"supchisys36fontsA(40).po" ?
