### ISSUE TITLE
AppleWin 1.26.1.1 write-protect detection misreporting

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#389]
Booting Gemstone Warrior from Asimov, the disk is being reported as write-protected even though it isn't.
The detection routine is at $575E, it's returning #$AA constantly, which the game interprets as protection enabled.

**Comment by tomcw** [comment]
Any idea if this is a regression at 1.26.1.1?
Or if the same problem occurs for older versions of AppleWin?

**Comment by peterferrie** [comment]
> Any idea if this is a regression at 1.26.1.1?
> Or if the same problem occurs for older versions of AppleWin?

1.26.0.6 is affected similarly.
1.25.0.4 and earlier that I just tested are not affected, so it was
introduced with 1.26.

**Comment by sicklittlemonkey** [comment]
Interesting. I'll have a look tonight.

Cheers,
Nick.

**Comment by tomcw** [comment]
I've built an experiment (pre-release) 1.26.2.0 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.0).

**Comment by peterferrie** [comment]
> I've built an experiment (pre-release) 1.26.2.0 version
> [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.0).

Thanks, that solves the write-protect and speed issue, but now the LC
behavior is improper.  I will open a new issue.

**Comment by tomcw** [comment]
NB. Add regression test [here](https://github.com/AppleWin/AppleWin-Test/commit/c169891a54bce2fbf31f199d0b867c86c344561d).
