### ISSUE TITLE
VS2017 support

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#391]
Spun off from  #390.

Nick said:

> Also, I tried building with VS 2017 the other night and got errors about
> auto_ptr which is deprecated.
> 
> At a glance VS 2017 doesn't seem to support any C++ below C++14 It would be
> nice to see if another ptr type can be used for all solutions.

Require mods for unsupported std::auto_ptr<> in VS2017.
Require a new vcxproj & sln - but see this PR #339, which contains some VS2017 patches.

**Comment by Michaelangel007** [comment]
Also see https://github.com/AppleWin/AppleWin/pull/410

**Comment by tomcw** [comment]
Fixed in b02c7ff and 4222267.
