### ISSUE TITLE
a2audit errors

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#392]
Ref: [a2audit](https://github.com/zellyn/a2audit) repo, [a2audio.dsk](https://github.com/zellyn/a2audit/commit/c5e87ab55dd5be16f9c37147560fc85f2de5905e)

Fails with these errors:

```
APPLE II AUDIT
MEMORY:128K
APPLE IIE (ENHANCED)
TESTING LANGUAGE CARD
AFTER SEQUENCE OF:
LDA $C080
LDA $C081
INC $D17B
INC $FE1F
EXPECTED $D17B IN RAM BANK 2 TO CONTAIN $22, GOT $54
DATA-DRIVEN TEST FAILED
ZELLYN.COM/A2AUDIT/V0#E0007
TESTING AUX MEM
LC FAILED BEFORE:SKIPPING AUXMEM LC
AFTER SEQUENCE
- LDA   #$15
WANT:
- C100-C2FF: ?
- C300-C3FF: ROM
- C400-C7FF: ?
- C800-CFFE: ?
GOT:
- C100-C2FF: ?
- C300-C3FF: ROM
- C400-C7FF: ?
- C800-CFFE: ROM
CXXX ROM TEST FAILED
ZELLYN.COM/A2AUDIT/V0#E000B
TESTING SOFTSWITCHES
SOFTSWITCH TESTS SUCCEEDED
PRESS 'Y', 'N', SPACE, OR ESC
```

NB. To dump the above text:
- pass -speech as an arg
- in `CPU.cpp`, `Fetch()`, change `PC == COUT`to `PC == 0x6c98`

**Comment by sicklittlemonkey** [comment]
IIRC AppleWin doesn't properly emulate the two accesses needed to write
enable high RAM.

This doesn't usually cause any problems, though.

Cheers,
Nick.

**Comment by tomcw** [comment]
Yes, that's it!

After fixing that, there's a 2nd failure for this sequence:

```
LDA $C080
LDA $C081
STA $C081
LDA $C081
```

Where the STA $C081 clears the 1st LDA $C081, so the net result is read-only.

**Comment by tomcw** [comment]
NB. There's still this historic comment in `MemSetPaging()` for $C08n accesses:

``` C++
//	g_bLastWriteRam = 1; // note: because diags.do doesn't set switches twice!
```

I searched Asimov ftp site-index for "diags" and couldn't find any matches (although there are diagnostics disks, none are called "diags.do").

**Comment by sicklittlemonkey** [comment]
Maybe from a confusion about writing the same address twice? It doesn't
have to be the same address. Table 5.5 in Understanding the Apple //e.

Hard to say without the exact disk.

Cheers,
Nick.

**Comment by tomcw** [comment]
OK, I'm going to the remove that comment then.

**Comment by tomcw** [comment]
The complete audit.dsk is now working for the 4 Apple models (II, II+, //e, Enhanced //e).
But none of the clones (Pravets x3 and TK3000) work - probably because the ROM doesn't match the Apple ROMs.
