### ISSUE TITLE
-d1 not working through launchbox

### ISSUE THREAD

**Issue by Massatomic** [AppleWin/AppleWin#393]
using current version AppleWin1.26.1.1 I cannot get Launchbox (v7.7)to utilise the -d1 command line parameter to have the .dsk file load into disk slot 1 on launch.

For me the program is loading to a black screen with apple //e across the top

Using Win 10 64bit

**Comment by tomcw** [comment]
Does this work from a regular cmd prompt?

I tried on Win7-64 and Win10-64 from a cmd.exe DOS bos, eg:
> applewin -d1 "c:\work\Images\aztec.dsk"
> applewin -d1 c:\work\Images\aztec.dsk

And it all works fine for me (with and without quotes).

Try specifying the -log switch too, eg:
> applewin -log -d1 c:\work\Images\aztec.dsk

This line indicates whether the -d1 switch succeeded (res=1) or failed (res=0):
```
Init: DoDiskInsert(D1), res=0
```

When it fails you do just get "a black screen with apple //e across the top".

**Comment by tomcw** [comment]
I just tried LaunchBox 7.7, and AppleWin 1.26.1.1 worked fine for me.

**Comment by Massatomic** [comment]
Thanks Tom, i have been called away for work and have not been able to follow up on your suggestions, i will try when I get home,

I must be doing something stupid, i tried I felt every combination and after a couple of hours I gave up and raised this issue

**Comment by tomcw** [comment]
These are the 3 dialogs that I edited to setup AppleWin and add one game (Archon_I.dsk):

![1 - edit emulator - emulator details](https://cloud.githubusercontent.com/assets/6696896/24071623/db924f0c-0bce-11e7-9cba-db86a414373d.png)

![2 - edit emulator - associated platforms](https://cloud.githubusercontent.com/assets/6696896/24071626/dfd8cb90-0bce-11e7-917e-4fa80ad5e4dc.png)

![3 - edit game - launcher](https://cloud.githubusercontent.com/assets/6696896/24071628/e21e4a38-0bce-11e7-871d-1fc0f132e1fd.png)
NB. For this last one, I didn't change anything in the "Emulation" sub-tab.

**Comment by Massatomic** [comment]
sorry for talking so long to get back to you tom, I checked that I had everything setup like your pictures and I did, still didn't work for me so I deleted everything and re setup from scratch and now its working. I have no idea what changed...

thanks very much for your help

**Comment by tomcw** [comment]
Thanks for confirming. Closing.
