### ISSUE TITLE
LC write-enabled state is not maintained correctly (1.26.2.0)

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#395]
Booting Gemstone Warrior, it claims to need 64kb of RAM.
The game performs two reads of $C081 which should write-enable LC, and later performs four STA $C083s (which should cause LC to remain write-enabled) and then writes to LC.  Only pre-write should be disabled by the STA - no effect on write-protection - but the LC becomes write-protected instead.

**Comment by tomcw** [comment]
Thanks for the quick check & report about this.

Ironically I broke this AppleWin LC support when I added support for the a2audit.dsk (#392).

I'll feedback this back to Zellyn so that his $C08n LC test can catch this.

**Comment by peterferrie** [comment]
> Thanks for the quick check & report about this.
>
> Ironically I broke this AppleWin LC support when I added support for the
> a2audit.dsk (#392).
>
> I'll feedback this back to Zellyn so that his $C08n LC test can catch this.

I did that already, so you don't need to.

**Comment by tomcw** [comment]
NB. Add regression test [here](https://github.com/AppleWin/AppleWin-Test/commit/c169891a54bce2fbf31f199d0b867c86c344561d).

**Comment by tomcw** [comment]
Hi Peter,

I've built a new experiment (pre-release) 1.26.2.1 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.1).

Gemstone Warrior now boots correctly. But let me know if you notice any other LC-related issues.

Thanks.

**Comment by peterferrie** [comment]
Hi Tom,

> I've built a new experiment (pre-release) 1.26.2.1 version
> [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.1).
>
> Gemstone Warrior now boots correctly. But let me know if you notice any
> other LC-related issues.

It looks good to me.  I believe that this one can be closed now.  Thanks.

**Comment by tomcw** [comment]
Thanks for confirming.
