### ISSUE TITLE
Debugger Custom Keys

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#396]
The debugger's hotkeys are currently hard-coded.

We should have a dialog where users can customize all the keys used.

[c.e.a2 source](https://groups.google.com/d/msg/comp.emulators.apple2/lqqjBTFWsGM/85-0lDVmBQAJ)

> would it be possible for you to update the control scheme to allow  WASD or arrow keys with either the space bar or enter as action? the current controls are awful and in archons case, the mouse doesn't work properly

**Comment by tomcw** [comment]
Thanks for logging this, but I don't think he was referring to the debugger though.

**Comment by tomcw** [comment]
I'm closing this as my understanding of the request was for better joystick support via WASD or Cursor keys. Cursor key support was added in 2014 (v1.24.0), so I guess in 2017 the OP just missed that we actually supported this.

Closing as invalid.
