### ISSUE TITLE
additional command-line options for specifying HDDs

### ISSUE THREAD

**Issue by EndeavourAccuracy** [AppleWin/AppleWin#398]
I suggest adding...

Command-line options:
-h1 &lt;pathname&gt;
Start with an image in HDD 1
-h2 &lt;pathname&gt;
Start with an image in HDD 2

And perhaps also:
-run
Start the emulated machine.

**Comment by tomcw** [comment]
Thanks. These -h1,-h2 switches sound sensible.

I'm not sure about -run, Wouldn't you just want the emulator to run automatically? (Certainly for the -h1 case).
NB. for -d1 this already runs automatically, so we need to consider consistency.

Maybe we also need a switch to skip the HDD boot, eg. for the case where there's a mix of -d1 and -h1.
See #323.

**Comment by sicklittlemonkey** [comment]
Yeah, I like more options.

If the existing default behaviour for d1 is to run, then the new h1 should run too by default.

Maybe have a -dontrun switch? ; - )

**Comment by EndeavourAccuracy** [comment]
It's mostly -h1 and -h2 that would be useful to have. I'm using AppleWin with [leapop](http://www.popot.org/level_editors.php?editor=leapop), and it would be more user-friendly if users didn't have to manually add the HDD disk image.

The reason I suggested -run is that your documentation says, for instance, that -f will "Start in full-screen mode". It "start"s the program AppleWin in full screen mode, it doesn't run the image. And it says that -d1 will "Start with a disk in drive-1", but it also runs the image. Instead of adding -run you could modify the description for -d1 and -d2 to say something like "Start with a disk in drive-# and run the disk".

**Comment by bsturk** [comment]
I'd like to see a command line argument to hide the mouse pointer when running full screen.  A *long* time ago I patched this functionality in, but I have no idea if it would work with the current source code.

**Comment by tomcw** [comment]
What about if AppleWin just hid the mouse pointer (in full screen) after a few seconds of it not being moved?

If you moved the mouse, then it would reappear (and then be hidden again after another few seconds of inactivity).

**Comment by bsturk** [comment]
Yes, that would work as well.  It's probably a better solution as well.

**Comment by tomcw** [comment]
Spun off (the idea of hiding the mouse pointer in full-screen) into #504.

**Comment by EndeavourAccuracy** [comment]
Giving this a one-year (passed since ticket creation) bump. ;)

**Comment by tomcw** [comment]
Thanks for the ping, I'll try to take a look soon.

**Comment by tomcw** [comment]
To do:
- [ ] add some tests for -h1, -h2
- [ ] add some tests for -d1, -d2

**Comment by tomcw** [comment]
Added -s7 empty in 419238bb5402dac9008de438c2a96a907522dbc3.

Added tests for new cmd-line options in https://github.com/AppleWin/AppleWin-Test/commit/54626d6f790d58a0d8e3171dabe2f17aa5534469

**Comment by tomcw** [comment]
@EndeavourAccuracy - can you test this [new 1.27.1 version](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.1.0).

**Comment by EndeavourAccuracy** [comment]
Thanks; works.
This will be useful.

**Comment by tomcw** [comment]
Thanks for confirming.
