### ISSUE TITLE
Screenshots missing top of top line of pixels?

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#403]
Screenshots missing top of top line of pixels?

Seems screenshots scrunch or remove half of the top line of pixels. I noticed it when making a shot of Star Blazer. You have to do a side-by-side comparison of the game in play and the screenshot. It isn't unique to any one title.

Hope I explained that alright.

**Comment by tomcw** [comment]
Yes, you're right! In "B&W TV" and "Color TV" modes (50% only?) then top half line is missing (and there's an extra half line at the bottom).

**Comment by tomcw** [comment]
Fixed & closing.

**Comment by tomcw** [comment]
I've built, tested and pre-released a new AppleWin 1.26.2.3 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.3).
