### ISSUE TITLE
Screen flicker in full-speed mode

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#405]
From cea2, James Davis, "AppleWin 1.26.1.1 Screen Flicker", (22 Apr '17):

I keep having to go back to AppleWin 1.25.0.4 because the last couple of times I downloaded newer versions like the latest stable release 1.26.1.1, I get some kind of HiRes flicker on the upper portion of the 40 column text screen.  I am running it on a Microsoft Windows 7/64 PC.  Will this bug be corrected in the next stable release?

> (Tom) Please can you give precise repro steps so that we can investigate this? 

I would have to reinstall that newer version to be exact, but from recollection, I just boot-up (slot 7) ProDOS and System Utilities, then drop out into Applesoft and press any key and it starts flickering from where a typed to the left and above randomly.  I usually run at max speed, too; but I am not sure if the flicker does not happen at normal speed, also.  I am usually trying to type CATALOG, first.  I just stop right there and reinstall the old version. 

I am running AppleWin as an Enhanced Apple IIe.  Nothing added, no additional cards in any other slots than what comes standard with AppleWin.  I have the Hard Disk Drive in slot 7 enabled, the 5.25" Floppy Disk Drive in slot 6, and the Printer in slot 1.  I think there is a /RAM/ disk, but it does not seem to work.  I do not know how to add slot cards to AppleWin, nor how to modify it in any way other than the configuration control-panel that it comes with.  [It is not like AGAT in that sense.  But, AGAT does not work with standard disk images, so AGAT is not a good emulator because of that.]  I do not use the sound features at all.  AppleWin does not sound right at high speed, and I do not want to hear anything from it, anyway.  I would like to know how to make AppleWin emulate exactly my real Enhanced Apple IIe hardware, but I do not know how.

**Comment by tomcw** [comment]
I think I am able to reproduce this by simply:
- Config: Machine = Enhanced Apple //e
- Config: CPU speed = max
- Boot `Tests-Various.dsk` (from the AppleWin-Test repo)
- CTRL+C and LIST
- then just watching and every ~1 second there will be a single glitched horizontal line

**Comment by tomcw** [comment]
The problem is when in full-speed mode, the display is updated every ~17ms. The V/H video scanner position is recalculated just before the whole screen update is done (based on `dwCyclesThisFrame`), but this new V/H pos won't be a continuation from the previous V/H pos. The horizontal glitch is the result of the V/H pos being wrong for the initial line.

So `NTSC_VideoRedrawWholeScreen()` needs fixing so that the redraw occurs from the start of the line & reinits the line vars.

Here's a screenshot of a glitch (V=54, H=2)
![tests-various_000000050](https://cloud.githubusercontent.com/assets/6696896/25317068/5ee70454-2869-11e7-9960-14ed2140ab48.png)

**Comment by tomcw** [comment]
In `VideoRedrawScreenDuringFullSpeed()` the screen only gets redrawn if the Apple II's video memory has changed. 

Another repro: From 40-col, issuing a PR# 3 command will clear the screen, but sometime a (glitched) horizontal line can get left. If there's no further change to this video memory (eg. no key is pressed) then this line remains there.

It's simpler to just remove the code to check for video memory changes.

And on doing this, the timings(*) for AZTEC.DSK boot times remain the same (cf #345):
- TV Color = ~1950ms
- Mono Amber = ~1900ms

(*) Using my desktop PC (Win7-64, AMD Phenom II dual-core @3GHz).

**Comment by sicklittlemonkey** [comment]
Thanks for the details, Tom. I tried to repro but couldn't - until you
mentioned 80-column mode. I can sometimes see it with that enabled.

Eventually I found a way to repro in 40-column-mode: with the text screen
full of data (e.g. from LIST) just hold down Scroll-Lock. Flickering
appears, especially top-right. Interestingly I don't see this if I set the
machine speed to full.

In regards to fixing it, I don't know the video code that well, but your
solution sounds OK - except for cases where screen updates aren't
hardware-accelerated. I.e. this would probably be worse for WINE.

Perhaps in full-speed mode we can update the screen less often. I notice
there's a flash bug (flash slows down when holding Scroll-Lock) and this
"BUG: In unthrottled CPU mode, flash rate should not be affected"
in updateFlashRate().

Ideally in full-speed mode the display would be updated often enough to
change flash at the normal rate - Sather says 3.74 alternations per second
(UTA2E page 8-13) - but not too much more. This would also reduce the load
in systems without hardware-acceleration.

Oh, I also looked into alternatives for StretchBlt, It seems Direct2D might
be one way, but that's on Vista up, though WINE has it and it's
hardware-accelerated. Michael has mentioned SDL though, so I'll probably
leave it alone.

Cheers,
Nick.

**Comment by tomcw** [comment]
I've built, tested and pre-released a new AppleWin 1.26.2.3 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.3).

**Comment by tomcw** [comment]
On cea2, James Davis confirmed this version fixes the issue:
> OK, the screen flicker is gone

Closing.

**Comment by sicklittlemonkey** [comment]
I know this issue is closed, but I want to close a tab I've had open for
ages, so I'll save it here. ; - )
It was when I was searching for Direct2D alternatives to GDI's StretchBlt,
and it also might improve performance.
https://stackoverflow.com/questions/26153633/windows-stretchblt-api-performance

Cheers,
Nick.
