### ISSUE TITLE
Debugger: Support LC status and memory

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#406]
John Public in cea2 "AppleWin's Debugger is still crap ... how do we fix it?", (21st May 2016) said:

> I'd still like to see an indicator to show whether you're in MAIN or AUX 
> memory. I was reading one of the apple 2 books and it says when the computer 
> starts up, you're in LCBANK2, so I'd like to see an indicator for that as well. (Yes, I'm still messing with Diversi-Dial). :) 
> 
> --Deeply Shrouded & Quiet 
> --Central Control! D-Dial # 49

**Comment by tomcw** [comment]
(Michael's reply to cea2)

1. Yup, that's been a wishlist of mine too! There is just enough room to squeeze in a few more modes: 

http://michael.peopleofhonoronly.com/dev/applewin/debugger/debugger_all_registers.png 

Considering there a dozen soft switches for memory management which are the (2) most important ones that people want displayed?  I'm thinking the abbreviations ... 

02:RM/X 
04:WM/X 

... instead of the more common verbose RAMDRON, RAMDROFF.  I see these are Appple's "official" names (from ProDOS sources): 

ramin    equ $c08b 
ramin2   equ $c083 
romin    equ $c082 ;swap rom in, write protect ram 
romin1   equ $c081 ;swap rom in w/o w-prot ram 
slot3rom equ $c00b ;write location to switch in slot 3 rom 
read3rom equ $c017 ; bit 7 =1 if slot space 3 enabled 
int3rom  equ $c00a ;write location to switch in internal 3 

I have to admit I've never done any Aux. memory programming (yet) so feedback would be appreciated! 


2. I also need to show the Language Card read/write bank state. How should this be compactly shown?   

The $C080 .. $0C08F area is a bit of a clusterfrack. :-/ The ancient "Language Card Crack" technique (C081 C081 D000<D000.FFFFM FA62:4C 59 FF C080) should be visible: 

80:LC2/ROM R/W+ 
88:LC1/ROM R/W+ 
^  ^       ^ 
|  |       Language Card State: Read, Write Enable, Write Protect 
|  Read from ROM or Language Card 
Address 

Reference; more for my sake so I don't have to track these down again :-) 

MEMORY MANAGEMENT SOFT SWITCHES 
$C000 W 80STOREOFF Allow page2 to switch video page1 page2 
$C001 W 80STOREON Allow page2 to switch main & aux video memory 
$C002 W RAMRDOFF Read enable main memory from $0200-$BFFF 
$C003 W RAMDRON Read enable aux memory from $0200-$BFFF 
$C004 W RAMWRTOFF Write enable main memory from $0200-$BFFF 
$C005 W RAMWRTON Write enable aux memory from $0200-$BFFF 
$C006 W INTCXROMOFF Enable slot ROM from $C100-$CFFF 
$C007 W INTCXROMON Enable main ROM from $C100-$CFFF 
$C008 W ALZTPOFF Enable main memory from $0000-$01FF & avl BSR 
$C009 W ALTZPON Enable aux memory from $0000-$01FF & avl BSR 
$C00A W SLOTC3ROMOFF Enable main ROM from $C300-$C3FF 
$C00B W SLOTC3ROMON Enable slot ROM from $C300-$C3FF 

http://mirrors.apple2.org.za/apple.cabi.net/Languages.Programming/MemoryMap.IIe.64K.128K.txt 

For WR-enable LC RAM, the softswitch REQUIRES two successive reads 

                        $C080                ;RD LC RAM bank2, WR-protect LC RAM 
ROMIN           =        $C081                ;RD ROM, WR-enable LC RAM 
                        $C082                ;RD ROM, WR-protect LC RAM 
LCBANK2         =        $C083                ;RD LC RAM bank2, WR-enable LC RAM 

                        $C084                ;RD LC RAM bank2, WR-protect LC RAM 
                        $C085                ;RD ROM, WR-enable LC RAM 
                        $C086                ;RD ROM, WR-protect LC RAM 
                        $C087                ;RD LC RAM bank2, WR-enable LC RAM 

                        $C088                ;RD LC RAM bank1, WR-protect LC RAM 
                        $C089                ;RD ROM, WR-enable LC RAM 
                        $C08A                ;RD ROM, WR-protect LC RAM 
LCBANK1         =        $C08B                ;RD LC RAM bank1, WR-enable LC RAM 

                        $C08C                ;RD LC RAM bank1, WR-protect LC RAM 
                        $C08D                ;RD ROM, WR-enable LC RAM 
                        $C08E                ;RD ROM, WR-protect LC RAM 
                        $C08F                ;RD LC RAM bank1, WR-enable LC RAM

**Comment by tomcw** [comment]
(Tom's reply to cea2)

On Saturday, May 28, 2016 at 5:57:04 PM UTC+1, Michael AppleWin Debugger Dev wrote: 
> 1. Yup, that's been a wishlist of mine too! There is just enough room to squeeze in a few more modes: 

Random thought, but you could toggle (via keyboard or mouse click) the video mode part and instead show the MMU config. (That's 10 lines of 12 chars!) 

You'd also need the current Aux 64K bank, eg. RAMworks cards can support up to 127 x 64K aux banks.

**Comment by Michaelangel007** [comment]
OK, I finally decoded and exported these obtuse flags in Memory.cpp. Looks like no one ever used MF_HIGHRAM ... at least it was set. :-)

```c
	// DETERMINE THE NEW MEMORY PAGING MODE.
	if ((address >= 0x80) && (address <= 0x8F))
	{
		SetMemMode(memmode & ~(MF_BANK2 | MF_HIGHRAM));

		if (!(address & 8))
			SetMemMode(memmode | MF_BANK2);

		if (((address & 2) >> 1) == (address & 1))
			SetMemMode(memmode | MF_HIGHRAM);

		if (address & 1)	// GH#392
		{
			if (!write && g_bLastWriteRam)
			{
				SetMemMode(memmode | MF_WRITERAM); // UTAIIe:5-23
			}
		}
		else
		{
			SetMemMode(memmode & ~(MF_WRITERAM)); // UTAIIe:5-23
		}
		g_bLastWriteRam = (address & 1) && (!write); // UTAIIe:5-23
	}
```

| Name | Function |
|:--:|:---|
| MF_HIGHRAM | Language Card $D000..$FFFF is active|
| MF_BANK2 | Bank 2 of Language Card active |
| MF_WRITERAM | Write-enable Language Card |


This is now implemented with commit 18fd4205c966a3c49b25994d35aaee35ef467c0f and 5cc4cbd26c1ae55454b516f1f876278290ed2b32.

**Comment by Michaelangel007** [comment]
I guess there is probably no need to show the R/W status twice ...

* $C081 Lang Card Off

![1_lang_card_off](https://cloud.githubusercontent.com/assets/7876796/25500388/bdd6ef6a-2b43-11e7-82cd-fd7911d3e734.png)

* $C080

![2_lang_card_c080](https://cloud.githubusercontent.com/assets/7876796/25500405/cc11dbc6-2b43-11e7-9639-d691aa43300f.png)

* $C083
![3_lang_card_c083](https://cloud.githubusercontent.com/assets/7876796/25500412/d0d434c4-2b43-11e7-9c28-bed3c0db6f08.png)

**Comment by Michaelangel007** [comment]
Tom

Is zero a valid value for RAMWorks `g_uActiveBank ` ?
Is it possible to use RAMWorks on a //e ?

**Comment by tomcw** [comment]
>Is zero a valid value for RAMWorks  `g_uActiveBank` ?

Yes. It takes values [0..0x7E].

**Comment by tomcw** [comment]
>Is it possible to use RAMWorks on a //e ?

Yes.

**Comment by Michaelangel007** [comment]
Thanks for the info Tom.

The reason I was asking was that I was trying to determine if the RAMWORKS card had been "installed." I ended up adding a new Language Card memory type, `g_eMemType ` for the various Language Cards -- since we need to support the Saturn as well.

It is being used by the debugger to show if a RAMWORKS or SATURN is active in [DrawSoftSwitches()](https://github.com/AppleWin/AppleWin/blob/master/source/Debugger/Debugger_Display.cpp#L2988-L2999}

Do you see any potential problems with this?

Thanks

**Comment by Michaelangel007** [comment]
Front-end UI is hooked up, just need the back-end support.

$C08F with command-line: `-saturn 128`

![5_lang_card_saturn_bank_7](https://cloud.githubusercontent.com/assets/7876796/25507031/8dbcd946-2b5e-11e7-838e-13b3712c5622.png)

**Comment by Michaelangel007** [comment]
_"Alrighty then"_ the debugger sucks a little less now with commit d243425c. :-)

* Read/Write for Main/Aux is now shown
* I've cleaned up the order of the IO softswitches for memory
* All memory status have a slightly darker background to distinguish it from the graphics switches.

![4_aux_mem_status](https://cloud.githubusercontent.com/assets/7876796/25509762/276a317c-2b70-11e7-82cb-5305222afcf8.png)

**Comment by tomcw** [comment]
>Do you see any potential problems with this?

This looks OK to me.

But a word on `_DrawSoftSwitchLanguageCardBank()`, in Debugger_Display.cpp:
The argument `extraBank` has the value `g_eMemType` encoded in bits 8 and higher. But if the enum were to change (such that the Ramworks or Saturn type has value 0) then this code would break:
``` C++
	if (extraBank > 0 )
	{
		// ...
```

Why not pass g_eMemType as an argument? Or just use it directly (since you made it global).

**Comment by Michaelangel007** [comment]
Thanks for the feedback Tom -- I'll get that fixed later this week.

**Comment by Michaelangel007** [comment]
Should "L1" and "L2" labels be switched to "B1" and "B2" for Bank?

I abbreviated LC1/LC2 as "L1" and "L2" but that may not be obvious they are banks?

**Comment by Michaelangel007** [comment]
This still needs more work. 

The problem is that _both_ L1 (or L2) and M are highlighted at the _same_ time.  This gives a contradictory view of which memory is actually active -- the LC has priority.

There are three display states. Using `[]` as notation for the highlighted banked area:

|80:|88:|Notes|
|:---:|:--:|:---|
|[L2]/M|L1/[M]| Bank 2 Active |
|L2/[M]|[L1]/M| Bank 1 Active |
|L2/[M]|L1/[M]| Main memory active |

Instead, this should be displayed as:

|80:|88:|Notes|
|:---:|:--:|:---|
|[L2]/M|L1/M| Bank 2 Active |
|L2/M|[L1]/M| Bank 1 Active |
|L2/[M]|L1/[M]| Main memory active |

Using a pivot table:

| -- |State 1|State 2|State 3|
|:--:|:-----:|:-----:|:-----:|
|80: |[L2]/M | L2/[M]|L1/[M] |
|88: | L1/[M]|[L1]/M |L2/[M] |


Line [#2823](https://github.com/AppleWin/AppleWin/blob/master/source/Debugger/Debugger_Display.cpp#L2823) of Debugger_Display needs to have additional conditional logic:

```
	_DrawSoftSwitch( rect, nAddress, bBankOn, NULL, sOn, "M", " ", bg_default );
```

**Comment by Michaelangel007** [comment]
* Inactive Bank now grayed out
* Only last activated bank shows `M`

![image](https://cloud.githubusercontent.com/assets/7876796/25910753/59fcff70-3566-11e7-9623-cb4605b493a0.png)

**Comment by tomcw** [comment]
Hi Michael,

I'm not quite following the notation. Here's what I (partially) understand - but please correct me!
Like you, I will use `[]` to indicate what it highlighted.

[B2] = LC 4K RAM Bank2 is enabled at $D000-DFFF.
[B1] = LC 4K RAM Bank1 is enabled at $D000-DFFF.
B2 && B1 = 12K ROM is enabled at $D000-FFFF.

[M] = ?
M = ?

[R] = LC 12K RAM at $D000-FFFF
R = LC 12K ROM at $D000-FFFF

[W] = LC 12K RAM at $D000-FFFF is write enabled
W = LC 12K RAM at $D000-FFFF is write protected

**Comment by Michaelangel007** [comment]
``
M = Main Memory
```

Is there another 1 character abbreviation for main memory that is clearer?

**Comment by tomcw** [comment]
>Is there another 1 character abbreviation for main memory that is clearer?

The problem with calling it "memory" is that both RAM and ROM is memory.
What about: `I` for Internal ROM?

It's tricky with just one character!

**Comment by sicklittlemonkey** [comment]
I'm not following this thread closely, but it's clear we're pushing the
limits of using so few characters in this small space.

**Comment by Michaelangel007** [comment]
Great point about "memory" being too generic Tom!

Normally the LC is ROM but can become RAM.  This is taken care of the `R/W` display.

However, what we are really trying to show is the _usage_ of the: `16K / 48K` memory split -- specifically _how_ is the 16K allocated?

Not counting the 2 character address, we have a total of 8 chars on the bottom line.  

My first choice takes up 11 characters :-/

```
80:LC2/LC1/ROM
   12345678901
```

Unfortunately my second choice takes up 9 characters:

```
80:B2/B1/ROM
   12345678    
```

One option might be to get rid of the forward slashes `/` but that is inconsistent with the rest of the `switch` display -- everything runs together.  We can mitigate that by using lowercase but that looks goofy/dumb:

```
80:b2b1rom
   12345678
```

Instead we can get rid of the `Bank` and abbreviate it like this:

```
80:2/1/ROM
   12345678
```

This a total of 7 characters -- which just fits. :+1:   The trade-off is that we lose the _visual_ mapping of c088 for bank 1 -- but considering the only people (probably ) looking at the debugger _already_ know the Apple's IO soft-switches -- I'm OK with this trade-off.

I'll have to move the R/W down to the next line -- it may look a little funny without the address but here is a screenshot of that so we can compare/contrast.

![image](https://cloud.githubusercontent.com/assets/7876796/26067568/866ff700-394f-11e7-816c-f71668d9db96.png)

Thoughts?

**Comment by Michaelangel007** [comment]
Add new branch: `langcard_status`

**Comment by Michaelangel007** [comment]
Since we now have extra space on the bottom ... we could better utilize the 3 character `address :` space a little better:

If the RamWorks card is enabled `-r 128`:

```
00:RWrk R/W
   12345678
```

If the Saturn memory card is enabled `-saturn 128`:

```
00:Sat  R/W
   12345678
```

**Comment by Michaelangel007** [comment]
Visual montage / comparison of latest lang. card status.

* Ramworks/Saturn page number is shown in yellow.  If the langauage card is writeable then the page number is shown in red.

![lang_card_status_new](https://cloud.githubusercontent.com/assets/7876796/26114764/0f30e0d6-3a13-11e7-98eb-09f794777325.png)

**Comment by Michaelangel007** [comment]
@sicklittlemonkey The `I` is not a bad idea. What would allow 80:2/1/IR/W to fit on a single line -- albeit without any spacing before R/W. I'm going to go with `ROM` for now since we have the extra line.

**Comment by Michaelangel007** [comment]
Full context using Ramworks as an example:

![9a_lang_card_mem_ramworks_read](https://cloud.githubusercontent.com/assets/7876796/26115019/bdcc996e-3a13-11e7-9b7c-cbc34db69f01.png)
![9b_lang_card_mem_ramworks_write](https://cloud.githubusercontent.com/assets/7876796/26115020/bdd2c50a-3a13-11e7-91fe-962de3a936ad.png)

**Comment by tomcw** [comment]
Hi Michael,

This looks fine for the last 2 lines:
```
80:2/1/ROM
00RWrk R/W
```

Can you provide a cheat-sheet for the `02:Rm/xWm/x` line too?

Does it cover the state of these 4 soft switches:
```
$C002 W RAMRDOFF Read enable main memory from $0200-$BFFF 
$C003 W RAMDRON Read enable aux memory from $0200-$BFFF 
$C004 W RAMWRTOFF Write enable main memory from $0200-$BFFF 
$C005 W RAMWRTON Write enable aux memory from $0200-$BFFF 
```
?

**Comment by Michaelangel007** [comment]
Sorry Tom for the delay. Now that Diablo 3 Season 10 on the PS4 is over and dealing with my father passing is (mostly) over, I can get back to Language Card work.

> Can you provide a cheat-sheet for the 02:Rm/xWm/x line too?

You just did. ;-) But I'll provide another variation:

```
   Rm Read from main mem for $0200-$BFFF; Use OUT C002 to enable
   Rw Read from aux  mem for $0200-$BFFF; Use OUT C003 to enable
   Wm Write to main  mem for $0200-$BFFF; Use OUT C004 to enable
   WX Write to aux   mem for $0200-$BFFF; Use OUT C005 to enable
```

I've updated docs/debugger_changelog.txt with the above with commit c863741cf81e4eaa4eafa03c4776b7b72a13dad5.

> $C002 W RAMRDOFF Read enable main memory from $0200-$BFFF 
> $C003 W RAMDRON Read enable aux memory from $0200-$BFFF 
> $C004 W RAMWRTOFF Write enable main memory from $0200-$BFFF 
> $C005 W RAMWRTON Write enable aux memory from $0200-$BFFF 

Correct, it displays those locations:

```
_DrawSoftSwitchMainAuxBanks()

	int  nAddress  = 0xC002;
	bool bMainRead = (memmode & MF_AUXREAD)  ? true : false;
	bool bAuxWrite = (memmode & MF_AUXWRITE) ? true : false;
```

**Comment by tomcw** [comment]
Michael - sorry to hear about your father.

I can't remember where we got to on this thread. From a quick scan, I think we may nearly be done? There's just the html doc to update. (Assigned to self)

**Comment by Michaelangel007** [comment]
Thanks Nick.  Funeral is this Monday, July 31, so it is _almost_ over.

I don't believe there is any more work to be done.  Tom did mention that you should be able to (mouse) click on them to change status -- I've raised a new enhancement #447

I need to do some more testing. i.e. checkout master, cherrypick this branch. before I feel happy with this patch.

Thanks for taking care of the docs Nick.

**Comment by tomcw** [comment]
>Tom did mention that you should be able to (mouse) click on them to change status -- I've raised a new enhancement #447

Actually I said:
>Random thought, but you could toggle (via keyboard or mouse click) the video mode part and instead show the MMU config. (That's 10 lines of 12 chars!)

So not toggle the soft-switches, but toggle what is being displayed: video or MMU state (to give you more screen real-estate to play with).

**Comment by tomcw** [comment]
Outstanding:
- [ ] html help doc to update
