### ISSUE TITLE
AppleWorks 5.1 flickers during boot

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#409]
Repro: 
- Use AppleWorks 5.1 (Quality Software) as a HDD image, downloaded from here:
  - https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/integrated/appleworks/v5.1/AppleWorks%205.1%20Program.2mg
- applewin.exe -r 127

For AppleWin 1.25.0.4 there's little to no flicker for alternate 80-column text chars during boot.
But for AppleWin 1.26 (1.26.0.1 to 1.26.2.3) there's lots of 80-col flicker.

I guess this is something to do with the new 1.26 video rendering.
Perhaps 80STORE? Perhaps to do with determining the amount of extra RAM?

Here's a screenshot of the 80-col display when it flickers:

![appleworks5 1-boot](https://cloud.githubusercontent.com/assets/6696896/25567388/5b359dc2-2de4-11e7-80a8-264f85e0a3ea.png)

Is this a video rendering bug?

EDIT: NB. With 1.25.0.4 you sometimes see the same image (as above), but it doesn't flicker, instead it will be visible for a longer time (and only once).

Also note that unlike floppy disk access, HDD access doesn't enable full-speed mode. So the Apple II video rendering during loading from HDD will still do cycle-accurate NTSC video rendering.

**Comment by Keatah** [comment]
I think this relates to the entry I made a while back. #297

**Comment by tomcw** [comment]
@Keatah - yes, I think you are correct. Thanks for the reminder about this related issue.
