### ISSUE TITLE
Applewin Printing

### ISSUE THREAD

**Issue by pschnob** [AppleWin/AppleWin#416]
Hi,
I'm trying to print out some old apple II stories & programs.  Printing to a text file is fine so I installed a print to text printer and tested it and it's working fine in Windows.  However I've set Applewin to use that printer but nothing happens when I enter the print command?  

Ctrl+PrintScrn button also does nothing (would it print the whole program or just the portion visible on the screen?)

The help file says I can use the command line command "-use-real-printer" but I don't know how to do that (the 'magnifying glass' window prompt doesn't accept this command).

I've looked through the instructions but can't find any further info about how to 'print' 'out' of the emulator.  Is there a special key or command or ?  

Please advise.  Thank you!
Best Regards,
Pete

**Comment by sicklittlemonkey** [comment]
The printing in AppleWin is very basic. It can currently only handle
printing text to the emulated parallel card in slot 1. The output is saved
as a text file.

See the Advanced settings tab, including the following items (from the
manual)


*Printer dump filename:*Data sent to the printer is stored in a text file.
Use this setting to select its location.


*Terminate printing after idle:*
When printing is started, a printer file is created and it is closed either
after the specified time expires, or when the emulator is reset. This
setting is emulation speed dependent.

Cheers,
Nick.

**Comment by pschnob** [comment]
Hi Nick,
Thx for the reply! ...but I've tried all that and it's not doing anything?

I've set the output printer file location to: D:\AppleWinOutput.txt and the idle time to 600 but when I type PRINT in the emulator no .txt file is generated in that location?

**Comment by sicklittlemonkey** [comment]
Please refer to Apple II manuals or books about printing.

From a BASIC prompt in general you would use PR#1 to starting printing and
PR#0 to finish.

Cheers,
Nick.

**Comment by pschnob** [comment]
Thanks that worked fine!  Guess it's been a few decades too many since I actually printed...didn't recall the PR#1 command at all!  Thx again.
Best,
Pete
