### ISSUE TITLE
AppleWin.chm help: typos on Uthernet page

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#417]
Via private email, James Davis reported this:

There are two instances on the Uthernet page of your AppleWin Help file that use the word "then" where it should be the word "than"!  I have marked them below with "then <-- sic: should be "than"!>" so you can find them and correct them in future releases of AppleWin Help.  (These are the only two such errors currently in the AppleWin Help file.)

Yours truly, 

James Davis

==============================​==============================​==========
Uthernet network card
------------------------------​------------------------------​----------
Overview: 
. . . 
Acknowledgment: 
. . . 
Details: 
. . . 
 
An Alternative to downloading WinPcap is to get the Ethereal package which includes WinPcap along with Ethereal network analyzer code. To use Ethereal to capture traffic (other then <-- sic: should be "than"!> your own) you must be plugged into a shared hub vs a switch. If you plan on doing any network programming ethereal is a definite must have. 
. . . 
If you have more then <-- sic: should be "than"!> one interface you may need to select them in turn in order to get the text description for each interface vs what WinPcap likes to use for a reference. Select Ok. and then close AppleWin. *Note:* Wireless does not work with WinPcap. 
. . . 
Troubleshooting: 
. . . 
==============================​==============================​==========

**Comment by Michaelangel007** [comment]
I didn't write this but `then` and `than` _still_ trip me up as a native speaker! I found this [Oatmeal's cheat sheet](http://theoatmeal.com/comics/misspelling) helps to sort out which is what:

# TL:DR; 

* Than -- used for object comparison
* Then -- used for time

**Comment by sicklittlemonkey** [comment]
I notice Americans often do this. Then again, we all have our own little
tics in language.
