### ISSUE TITLE
Code refactor: Rename and convert SLOTCXROM to INTCXROM

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#419]
Sather uses INTCXROM instead of SLOTCXROM' (NB. the latter has a prime).

He even has a footnote about this in UTAIIe:5-28. And explains that the Apple //e Tech Ref Manuals use SLOTCXROM when it means the opposite!

NB. AppleWin uses SLOTCXROM to correctly mean INTCXROM' (again, note the prime). So AppleWin is correct, but is unconventional.

Anyway, since UTAIIe is the reference for most (all?) of the logic that we implement in the emulator, IMO it would make better sense to adopt Sather's name for this signal. Also it would simplify some of the AppleWin comments (eg. 52450aa) where they reference both the AppleWin signal (SLOTCXROM) and the equivalent UTAIIe signal (INTCXROM').

@sicklittlemonkey - I assume you'll be OK with this change?

**Comment by sicklittlemonkey** [comment]
Heh, sounds good.

Probably worth keeping a note somewhere (or even maybe at each usage) as to
the difference from Apple's nomenclature.

Cheers,
Nick.
