### ISSUE TITLE
Crusade In Europe Joystick And Controller Issue

### ISSUE THREAD

**Issue by bdjphotoman590** [AppleWin/AppleWin#432]
Hi, When I play Crusade In Europe, the computer controller can be used but is incredibly slow in moving the cursor around the map.  I can use keyboard for now.  Thanks, bdjphotoman590.

**Comment by tomcw** [comment]
I expect this is just how the game was implemented for joystick vs keyboard.

NB. I tried the game with a mousecard in slot-4, but it wasn't recognised - the input options were still only joystick or keyboard.

Closing, as AFAICT there's nothing wrong with the emulation.

**Comment by sicklittlemonkey** [comment]
You can always choose a higher emulator speed.
