### ISSUE TITLE
Choosing Thumbstick #2 causes crash in older AppleWin's

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#434]
PR #428 extends Joystick 2 to use "Joystick 1's second thumbstick".

If you select this option (saved to the Registry: Joystick1 Emu Type = 5), switch back to an older AppleWin (eg. 1.26.2.4), bring up the Config->Input property sheet and OK; then this results in a crash.

Problems:
- there's no bounds checking in `JoySetJoyType(UINT num, DWORD type)` for `type`.
  - so at start-up, it reads type=5 from the Registry and sets `joytype[1] = 5` (when the max is 4).
- when you open Config->Input, `CPageInput::InitJoystickChoices()` populates the joysticks' combo boxes.
  - this completes things by calling `JoyGetJoyType()` to get `type==5`
  - this is passed to `CPropertySheetHelper::FillComboBox(..., int currentchoice)` as `currentchoice`, to set the combo cursor to `currentchoice`.
  - `SendMessage(combowindow, CB_SETCURSEL, currentchoice, 0)` returns -1, but this isn't checked.
- Clicking "OK" calls `CPageInput::DlgOK()`.
  - this sets `uNewJoyType1 = SendDlgItemMessage(hWnd, IDC_JOYSTICK1, CB_GETCURSEL, 0, 0)`
  - now `uNewJoyType1==-1`
- Just below this, `m_nJoy1ChoiceTranlationTbl[uNewJoyType1]` will then crash.

We can make fixes to the current code to improve checking return results and doing more bounds checking.

We obviously can't fix the released AppleWin, so we need some way to remedy this in the unreleased "joystick 1 - thumbstick 2" support.

One idea is to change the Registry key (again), eg. from:
```
#define  REGVALUE_JOYSTICK0_EMU_TYPE	"Joystick0 Emu Type"
#define  REGVALUE_JOYSTICK1_EMU_TYPE	"Joystick1 Emu Type"
```
to:
```
#define  REGVALUE_JOYSTICK0_EMU_TYPE	"Joystick0 Emu Type(2)"
#define  REGVALUE_JOYSTICK1_EMU_TYPE	"Joystick1 Emu Type(2)"`
```

**Comment by tomcw** [comment]
(cont)

And support both new and old Registry keys.

NB. There's precedent for this already: In `LoadConfiguration()`, the code will try to use the new Registry keys, but if these fail then it will fall back to the old keys by calling `LoadConfigOldJoystick()`.

Support for old Registry key support is required when upgrading from AppleWin version N to N+1 (where N uses the old keys, and N+1 uses the new keys).

**Comment by sicklittlemonkey** [comment]
​Thanks Tom!
