### ISSUE TITLE
Applewin doesn't show all available COM ports.

### ISSUE THREAD

**Issue by theunixguy** [AppleWin/AppleWin#435]
![screenshot 120](https://user-images.githubusercontent.com/22863659/28191728-1aed1712-6800-11e7-8a3b-f15de091dcb4.png)
![screenshot 119](https://user-images.githubusercontent.com/22863659/28191744-3f009106-6800-11e7-8590-9879196d6adc.png)

Applewin doesn't show all available COM ports.

**Comment by tomcw** [comment]
AppleWin will scan ports COM1,...,COM31.

I stepped the code and it generates the correct COMx names including double-digit COM10.

I then made the code ignore the "failed to open" cases, and the Config UI correctly showed all 31 COMx names in the drop-down combo control.

I'll have to think more about this, but for now avoid "serial port - 4" / COM10.

**Comment by tomcw** [comment]
btw. what version of AppleWin are you using? And what version of Windows?

**Comment by tomcw** [comment]
Fixed in d23d091 (see #707).
