### ISSUE TITLE
Help file (AppleWin.chm) not displayed properly

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#436]
Today I downloaded AppleWin1.26.1.1 ZIP from GITHUB, and I'm having problems with the Help file.

I created a folder ("C:\Program Files (x86)\AppleWin\AppleWin1.26.1.1") and extracted the files to it.

I double-click AppleWin.chm (Creation date:  9/18/2016 5:10:22 PM) and the 2 pane help window (Microsoft HTML Help Executable program) is displayed, with the left side populated with an expandable list headed by "Table of Contents".  I expand the link and see additional links ("AppleWin Team", "Acknowledgements", etc.).

I click (or double-click) an entry in the left pane ("AppleWin Team") and expect to see the appropriate help information displayed in the right hand pane, but that pane remains blank.

I've tried this from within AppleWin1.26.1.1 and it behaves the same.

It also behaves this way with my 1.25.0.3.exe version as well.

However, I do have a version 1.25.0.4 in "C:\Users\TOM\Documents\Visual Studio 2015\Projects\AppleWinTommyGH\Release\AppleWin.chm"  The creation timestamp on that file is 8/22/2016 6:13:00 PM.   That help file DOES properly display as I would expect.

What do I have to do to get the CHM file to display properly?

**Comment by sicklittlemonkey** [comment]
Are you on Windows 7?
https://stackoverflow.com/questions/11438634/opening-a-
chm-file-produces-navigation-to-the-webpage-was-canceled

Cheers,
Nick.

**Comment by TommyGH** [comment]
Windows 10.
Solution:
   Right click on CHM file and select UNBLOCK.

Windows 10 protecting me from myself again.

**Comment by sicklittlemonkey** [comment]
Thanks Tommy. Yeah this has come up a few times recently.

Tom, maybe we should consider moving to a different help format. What do you think?

Cheers,
Nick.

**Comment by tomcw** [comment]
>Tom, maybe we should consider moving to a different help format. What do you think?

Yes. Perhaps the simplest thing to do is just ship the html (and png) files and for the Help button (F1) to just open the toc.html in a browser.

I'll spin this off into a dedicated issue.

**Comment by tomcw** [comment]
Closing since I've spun off to #437.
