### ISSUE TITLE
Adjust video scaling in Windowed mode?

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#44]
**BerliOS Feature Request #3272**

**Date:** 2007-March-23 22:18
**Submitted By:** tomch
**Category:** User Interface
**Assigned To:** tomch
**Priority:** 5
# 

Date: 2007-Mar-23 22:18
Sender: tomch
Logged In: YES 
user_id=25188
Browser: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.8.0.11) Gecko/20070312
Firefox/1.5.0.11

[From Javik on Open Discussion forum]

Would it be possible to permit the window size to be
scaled? At the moment I'm using a laptop at 1920x1200
and AppleWin is very tiny indeed.

As screen resolutions continue to increase, it would be
nice to be able to scale the window from 1x up to 4x
without having to resort to full-screen mode.

**Comment by SEGStriker** [comment]
For some reason 2x windowed mode doesn't work on some (if not all) Windows 10 laptops.
I tried several laptops with Windows 10 x64, different video cards, from Intel 4000 HD (inside the CPU) to Geforce onboard and add-on cards - same result. When trying to switch to 2x, it just flashes for a moment and stays 1x. Full screen mode works.

**Comment by tomcw** [comment]
If the resolution isn't high enough to support 2x windowed mode, then AppleWin will refuse to switch.

The base resolution of 560x384.
So this means for x2 mode, you need at least: 1120 x 768

**Comment by SEGStriker** [comment]
Current environment:

BitsPerPixel : 32
Bounds       : {X=0,Y=0,Width=1366,Height=768}
DeviceName   : \\.\DISPLAY1
Primary      : True
WorkingArea  : {X=0,Y=0,Width=1366,Height=728}

BitsPerPixel : 32
Bounds       : {X=1366,Y=0,Width=1920,Height=1080}
DeviceName   : \\.\DISPLAY2
Primary      : False
WorkingArea  : {X=1366,Y=0,Width=1920,Height=1080}

Video card: Intel HD 4400

Doesn't work on each display,

Also doesn't work on another laptop - IdealPad with single display, resolution is also higher than what you proposed.

**Comment by tomcw** [comment]
This isn't correct...
>So this means for x2 mode, you need at least: 1120 x 768

...as it doesn't account for the **window's border/frame**.

These are the actual minimum dimensions for 2x windowed mode:
- Win7: 1181 x 806
- Win10 (1909): 1181 x 818

**Comment by tomcw** [comment]
btw - Update AppleWin.chm (help doc): b6f51bde9fcc44858723a844d9096a1a78d900e8

**Comment by SEGStriker** [comment]
But my second display (external one) is 1920x1080 so it should work there.
BTW, it is working on my desktop PC which still has 4:3 monitor (old style but much better for me) - with 1280x1024 max resolution. And sometimes I use 1024x768, still works.
