### ISSUE TITLE
Space Raiders V2 doesn't work with Applewin

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#444]
Space Raiders V2 doesn't work. You cannot really get past the point where it asks you to enter your name. You type a letter and it repeats a symbol over and over again. However, version 1 works just fine.

V2
ftp://ftp.apple.asimov.com/pub/apple_II/unsorted/space%20raiders%209k%20file%20PRODOS%20(san%20inc%20crack).dsk

V1
ftp://ftp.apple.asimov.com/pub/apple_II/images/games/file_based/Othello_Eliminator_Galaxian_TailGunner_SpaceRaiders.zip

**Comment by MarcoVerpelli** [comment]
Do not blame AppleWin for this.
54C0: 20 1D FD  shoud be 20 0C FD.
You should know that qkumba compresses all the files, so it's impossible (at least for me) to tell where to apply the change on the disk image.
Try to contact qkumba on Twitter or comp.sys.apple2

**Comment by Keatah** [comment]
Yes of course. Thanks for the insight and patch I sent off a tweet to qkumba to see if we can get a //e version or something..

I checked against my real hardware and AppleWin matches it. Sometimes it's all to easy to forget that not everything works on the //e, and that a little change in settings is all it takes.

**Comment by sicklittlemonkey** [comment]
The original game was not //e-compatible. There's a new //e-compatible version in asimov's incoming from qkumba.

Closing as not a problem with AppleWin.
