### ISSUE TITLE
Sending open-apple or closed-apple commands to the emulated machine?

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#448]
Sending open-apple or closed-apple commands to the emulated machine? Can this be done? If so, how?

WordBench from Addison-Wesley requires you to press Closed Apple + Enter to finish entering the date. But that key combo toggles full-screen or window. And as a result the program can't continue.

**Comment by tomcw** [comment]
Open Apple = PC's LEFT ALT
Closed Apple = PC's RIGHT ALT
Are these not working?

If not then an obvious(?) but **poor** workaround is to use an emulated joystick and press button#1 instead of Closed Apple (ie. RIGHT ALT key).

**Comment by Keatah** [comment]
Applewin treats a left/right alt key AND the <enter> key, TOGETHER, as the command to maximize the Applewin window. It doesn't send <alt> + <enter> to the program. Which is what the program needs.

The joystick work-around works if I use a real joystick. The emulated joystick through the keyboard does not work. It does the full-screen thing.

**Comment by sicklittlemonkey** [comment]
> Applewin treats a left/right alt key AND the key, TOGETHER, as the
command to maximize the Applewin window. It doesn't send + to the program.
Which is what the program needs.

Hmm, this is new behaviour.

> The joystick work-around works if I use a real joystick. The emulated
joystick through the keyboard does not work. It does the full-screen thing.

The emulated joystick workaround should work. Note that button 0 (Open
Apple) is the Keypad 0 (zero) key, not the Keypad Enter key.

Cheers,
Nick.

**Comment by Keatah** [comment]
OK. The numeric pad 0 works.

**Comment by tomcw** [comment]
NB. New switch added:
-alt-enter=<open-apple-enter|toggle-full-screen>

Closing as all work complete in #556.
