### ISSUE TITLE
A keypress is lost after entering debugger:  Boot DOS disk, F7, set brkpt, F7, Press a key

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#454]
Emulator:  1.26.2.4
Debugger: 2.9.0.8

To recreate:

1. Boot a DOS disk
2. F7
3. bpr pc=0
4. F7
5. CATALOG

?SYNTAX ERROR

The "C" was not accepted into the emulator.

This bug exists in previous versions of AppleWin too.

Pressing F7 to enter the debugger, and then pressing F7 (with no breakpoints set) and the problem does not exist.

**Comment by tomcw** [comment]
This was fixed just after the 1.26.2.4 version in 0257492209c974c8fa857378c174b9262c170d78.
I'll do a new build very soon to include this (and other small fixes).

**Comment by tomcw** [comment]
Here's a new build, [1.26.3.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.0), which should fix this issue.

**Comment by TommyGH** [comment]
AppleWin 1.26.3.0 has fixed this issue (from my limited testing).
