### ISSUE TITLE
Strange speaker clicks while changing configuration

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#456]
AppleWin 1.26.3.0
AppleDebugger 2.9.0.8

1. Start AppleWin in AppleII mode (Original).
Authentic Disk speed, Authentic CPU speed, no disks in drives.
2. F2 to start emulation.  See the "*" prompt.
3. F7 to enter debugger.
4. F8 to change configuration.
5. Choose APPLEII+ and select OK.
6. OK to "Confirm" dialog.
7. OK to "Are you sure" dialog.

AppleWin restarts, but I hear a series of about 15 to 20 strange speaker clicks.  The pattern of clicks seems to be identical each time I've tried this.

I will also note that I have the "Confirm reboot" checkbox clear, yet I still see two(!) dialog boxes after selecting the new configuration.  What does "Confirm reboot" not being checked mean?

And I will also note, but have not reproduced, that at one point during the switching debugger on/off I thought I lost a character when typing input to the emulator.  I reported a separate issue about this against an earlier level of AppleWin and it was fixed in this level.  It "usually" seems fixed, but on this one occasion it seemed to not be fixed.

**Comment by TommyGH** [comment]
I have just reproduced this on 1.25.0.3 as well.

**Comment by tomcw** [comment]
>AppleWin restarts, but I hear a series of about 15 to 20 strange speaker clicks. The pattern of clicks seems to be identical each time I've tried this.

Reproduced (1.26.3.0).
NB. You must be in the debugger and then change the computer type (just changing the computer type is not enough).

**Comment by tomcw** [comment]
>I will also note that I have the "Confirm reboot" checkbox clear, yet I still see two(!) dialog boxes after selecting the new configuration. What does "Confirm reboot" not being checked mean?

This is for the F2 / "Apple logo" button. If you uncheck "Confirm reboot" (as you have done) then you don't get this confirmation dialog. I like having the confirmation dialog, as IMO it's far too easy to accidently hit F2 and lose all your work!

**Comment by tomcw** [comment]
>And I will also note, but have not reproduced, that at one point during the switching debugger on/off I thought I lost a character...

This should not happen now (with 1.26.3.0 or above). Keep an eye on this, and report it here if it reoccurs.

**Comment by tomcw** [comment]
FYI, new experimental release build 1.26.3.1 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.1), which includes this fix.
