### ISSUE TITLE
Disappearing Addresses, Colon, and OP codes on the debugger code display

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#462]
With the click of a mouse button, the addresses disappear.
With another click of the mouse button, the colons (":") change to spaces (" ").
With another click of the mouse button, the OP codes disappear.

![noaddresses2](https://user-images.githubusercontent.com/7924807/29327248-28cbe2be-81b4-11e7-9ca3-5b471b5a5a6f.jpg)

![noaddresses5](https://user-images.githubusercontent.com/7924807/29327712-ab4aaf6c-81b5-11e7-9473-a07e19efc140.jpg)

For the life of me I could not figure out why sometimes my disassembly view in the debugger would change. And it took me awhile to figure out how to get some of them back to normal ("disasm OPCODE 1", "disasm COLON 1").  But when the addresses disappeared, I thought the only way to get them back was to restart AppleWin.

Today I discovered the undocumented(?) feature.  See the attached images.  The "hot spot" is on the left of the screen.

![noaddresses4](https://user-images.githubusercontent.com/7924807/29327597-52f91d08-81b5-11e7-908d-659fdee2292d.jpg)

To someone unfamiliar with this feature, it is EXTREMELY difficult to understand why all of a sudden your display has changed.  I usually have multiple windows open at the same time, and I sometimes misclick the mouse button where I should not.  Perhaps I'm trying to resize another applications window by dragging it's edge, and I misclick by a few pixels and hit the "hot spot" instead.  BAM!! there go my opcodes.

I also imagine more than once I tried to "copy" some text from the "hot spot" of the window, and once again, BAM! there goes my display.

Now that I know about it, I think it is a GREAT feature!!!

But to the unsuspecting user it is BAD! BAD! BAD!

**Comment by Michaelangel007** [comment]
Yes, this feature is intentional.

There are a couple of action items that need to be done:

* [ ] We could change it to `Shift-Click` so the user can't accidentally do this.
* [ ] Update the debugger help to document this.

**Comment by Michaelangel007** [comment]
Status:

* [ ] `WM_LBUTTONDOWN` needs to call `KeybUpdateCtrlShiftStatus();`
* [ ] Add logic in `DebuggerMouseClick()` to check Alt, Ctrl, Shift with "disasm click"
  * g_bAltKey
  * g_bCtrlKey
  * g_bShiftKey

Add debugger config support for:

* [ ] `disasm click 0` // No Alt, Ctrl, Shift
* [ ] `disasm click 1`
* [ ] `disasm click 2`
* [ ] `disasm click 3`
* [ ] `disasm click 4`
* [ ] `disasm click 5`
* [ ] `disasm click 6`
* [ ] `disasm click 7`

**Comment by Michaelangel007** [comment]
NOTE: Need to merge #480 before we can bump debugger version & update docs/Debugger_Changelog.txt

**Comment by Michaelangel007** [comment]
Tommy, another Quality-of-Life feature is #483

**Comment by tomcw** [comment]
When I start AppleWin, enter debugger (F7) and query the disasm config:
`disasm`
then it reports
`Click: 0 = Left click`

**Comment by tomcw** [comment]
OK, changed default to Shift+Click.

**Comment by tomcw** [comment]
@Michaelangel007 - I'll let you complete this issue. You just need to:
Update the debugger help to document this new behaviour.

**Comment by tomcw** [comment]
Bumped debugger version (2.9.0.12) & updated docs/Debugger_Changelog.txt.
