### ISSUE TITLE
Apple ][ (original) not booting

### ISSUE THREAD

**Issue by NixieLake** [AppleWin/AppleWin#465]
I can't seem to get the Apple ][ (orig.) model to get past the garbled text phase of boot-up. I don't know if it's a ROM issue or something else, but the other models work fine.

Windows 10, Acer Aspire F 15 laptop using Intel i5-7200 2.gGHz (7th Gen)

**Comment by sicklittlemonkey** [comment]
I think you're describing normal behaviour.

The original Apple II ROM did not boot anything and just stopped at the
Monitor (asterisk) prompt.

In order to automatically boot a drive you had to have an Autostart ROM,
which is what the II+ had.

Cheers,
Nick.

**Comment by NixieLake** [comment]
Thanks for the info. I was looking forever for the solution and after you pointed me in the right direction I was able to get programs running properly on it. I just didn't realize it was the Monitor program running rather than Applesoft or Integer BASIC.
