### ISSUE TITLE
Add cmd line switch to stop PrintScreen key from being registered

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#469]
Reason: It's occasionally useful to be able to run AppleWin with Windows' default PrintScreen support, eg. for the screen grabs I did in #464, I had to set a breakpoint and skip over `AppleWin_RegisterHotKeys()`.

**Comment by Michaelangel007** [comment]
This is a good idea.

Recommend: `-noprintscreen`

**Comment by Michaelangel007** [comment]
This needs to be added to `doc/History.txt` for 1.27

```
. [Bug #469] Added new command line to disable the PrintScreen key from being registered: -no-printscreen-key
```

**Comment by Michaelangel007** [comment]
Not closing until above added to history.txt
