### ISSUE TITLE
Long output lines in full console window.  Two problems.

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#476]
In this first image, look at the line starting with "Dup Symbol Name" in the lower half of screen.
Look all the way to the right at the name "A2_USER1.SYM".  It would seem the "R" character was dropped as it isn't on the next line either.

![screen1](https://user-images.githubusercontent.com/7924807/29490927-7acca386-8511-11e7-9d1f-88acc576a69d.jpg)

I next did a Ctrl/PrintScrn to capture this as text, and pasted it into Notepad.  On the longer lines, after 50 characters are shown, the next character is an inserted space " ".  See for example, "A2 _USER1.SYM".  I will note that I think 50 is the maximum number of characters in the disassembly window, and the maximum number of characters that are displayed using ECHO from a script.

![screen2](https://user-images.githubusercontent.com/7924807/29490958-1c7c7e4a-8512-11e7-82da-23c5f1763b66.jpg)

**Comment by Michaelangel007** [comment]
```
	char sText[ CONSOLE_WIDTH * 3 ];
```

[Debugger_Symbols.cpp, Line 701](https://github.com/AppleWin/AppleWin/blob/master/source/Debugger/Debugger_Symbols.cpp#L701)

```
					ConsolePrintFormat( sText, " %sDup Symbol Name%s (%s%s%s) %s"
						, CHC_ERROR
						, CHC_DEFAULT
						, CHC_STRING
						, g_aSymbolTableNames[ iTable ]
						, CHC_DEFAULT
						, pPathFileName
```

**Comment by Michaelangel007** [comment]
Repro.:

```
ConsolePrintFormat( sText, " 23456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789ABC" );
```

Bug in `ConsolePrint()`

**Comment by Michaelangel007** [comment]
Note: Can NOT use `echo` for testing:

```
echo " 23456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789ABC"
```

**Comment by Michaelangel007** [comment]
Tommy, please log a **new** bug for `echo`:

i.e. "(Debugger) ECHO is limited to 55 chars"

**Comment by Michaelangel007** [comment]
NOTE: Need to merge #480 before we can pump debugger version & update docs/Debugger_Changelog.txt

**Comment by tomcw** [comment]
Bumped debugger version (2.9.0.12) & updated docs/Debugger_Changelog.txt.
