### ISSUE TITLE
Help doc: Document behaviour of video emulation when in full-speed mode

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#477]
Need to document:
- Full speed mode favours speed over video accuracy
  - Video only updated periodically (once a wall-clock 60Hz frame) instead of each opcode
- In full speed, timing loops won't work correctly (eg. ANSI Story)
- In full speed, card detection routines (that rely on floating bus) won't work correctly (eg. Ankh, #474)

Also worth stating how to enter full-speed mode:
- Implicitly: drive motor on (and enhanced drive mode enabled), etc.
- Explicitly: ScrollLock key, `gg` from debugger, etc.

**Comment by tomcw** [comment]
Also from #508:
- In full speed, Apple II+ VBL detection routines won't work (so the code will just hang)

**Comment by tomcw** [comment]
Also from #4:
- In full speed, Drol didn't work

IIRC there's some video-scanner sync'ing going on in this game, so again won't work with 1.26 in full speed mode.

**Comment by sicklittlemonkey** [comment]
Yeah, from what I recall, it's to smooth the animation at the completion of
a round (i.e after completing all 3 levels).

I don't think it's during disk access, so there's no reason to run this
part of the game at full-speed ... Hmm, except to skip it I suppose. It's a
shame it doesn't work at full-speed considering that it could (though it
would slow things down).

Cheers,
Nick.

**Comment by tomcw** [comment]
>It's a shame it doesn't work at full-speed...

Yes, I agree. Not the best user experience.

We could have the emulator detect II+ VBL detection, eg:
-LDA $C050
 BNE -

This check could be done periodically, eg. at the start of the next batch of 6502 emulation, in `CpuExecute()`.

I'll spin this discussion out into a dedicated issue.
