### ISSUE TITLE
Screen partly corrupted using DEBUGGER. "111111111111" outside disassembly window.

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#479]
This is a bit of a weird one.  I was using the down arrow on my keyboard to scroll through some code in the disassembly pane.  All of a sudden 2 characters to the right of the disassembly pane (is it called the "info panel"?) were corrupted.  Each time I pressed the down arrow key, another " 1" appeared.  See attached screen captures.

It doesn't seem to be directly related to WM_PAINT, as I could move another application window over the corrupted window, then move it off again, and I could still see the corruption.  However, if I minimized AppleWin and then restored Applewin, the window was displayed without the corruption.

The problem is repeatable.  I could close Applewin, then restart it, and scroll through this same sequence of code and it would corrupt in the same manner.  There seems to be more than one place in the code that causes this corruption.

AppleWin:  1.26.3.0
Debugger:  2.9.0.8

I was using the enclosed DEBUG.TXT script and the enclosed A2_USER1.SYM.  I booted DOS(1983) (January) Master disk first before F7 and RUN DEBUG.TXT.

Corrupt Screen:
![corruptpaintjob](https://user-images.githubusercontent.com/7924807/29644516-672ac1e0-883c-11e7-8683-d18fa13e7c9b.jpg)

Good Screen:
![goodscreen](https://user-images.githubusercontent.com/7924807/29644545-9de1bb08-883c-11e7-92e9-75f7be3b6388.jpg)

First sign of corruption:
![firstsignofcorruption](https://user-images.githubusercontent.com/7924807/29644551-a68be0d0-883c-11e7-8c87-3e915fab61e8.jpg)

[debug.txt](https://github.com/AppleWin/AppleWin/files/1247425/debug.txt)

[A2_USER1.SYM.txt](https://github.com/AppleWin/AppleWin/files/1247426/A2_USER1.SYM.txt)

**Comment by Michaelangel007** [comment]
Repro.:

1. Rename `a2_user1.sym.txt` to `a2_user1.sym` to auto-load symbols at boot
2. Start AppleWin
3. Boot: ` Apple DOS 3.3 January 1983.dsk`
4. `F7`
5. `run debug.txt`
6. `Down arrow` until `BD81`

**Comment by Michaelangel007** [comment]
Trace:

* `CmdCursorLineDown()`

**Comment by Michaelangel007** [comment]
Also, $BD7F and $BD81 are showing a few pixels of the background outside the disassembly pane.

**Comment by Michaelangel007** [comment]
![outside_bd7c](https://user-images.githubusercontent.com/7876796/29672389-f2dec9ac-88a0-11e7-8da2-1074dd4fd74f.png)

**Comment by Michaelangel007** [comment]
Bug lies past line 2042

i.e. Replace line 2042 with, and no bug.
```
return nOpbyte; // ********************************************************************************************
```

**Comment by Michaelangel007** [comment]
Bisect: 2042,2293

**Comment by Michaelangel007** [comment]
![outside_bd7c_2](https://user-images.githubusercontent.com/7876796/29672985-af558d0e-88a2-11e7-960c-dfe882fc6759.png)

**Comment by Michaelangel007** [comment]
Shorter repro.:

1. Applewin
2. `F2`
3. `F7`
4. `ESC`
4. `run debug.txt`
5. `ESC`
6. `u bd28`
7. `Down` -- bug shows at $BD7C

**Comment by Michaelangel007** [comment]
pTarget: `DRV2EN.LCBANK1.ENABLE2`

**Comment by Michaelangel007** [comment]
Repro.:

1. `F7`

```
sym DRV2EN.LCBANK1.ENABLE2 = C08B
300:BD 8B C0
u 300
```

**Comment by Michaelangel007** [comment]
Tommy,

/Oblg.

* Patient: _"Doctor, it hurts when I do this."_
* Doctor: _"Don't do that then!"_

Until the debugger gets fixed here is a work-around in `A2_USER1.SYM`

C08B	DRV2EN.LC.BANK2

The _cause_ is that **long symbol names** are not being clipped.  I attempted to fix this in the past but looks like I forgot a few cases (indirect mode, etc.)

On my end there are a few things that need to be done:

* [ ] Change `Warning` for symbol aliases to `Info:`
* [ ] Add `Warning:` when importing symbols > 20 characters
* [ ] Fix DrawDisassemblyLine, line 2124 to account for index mode

**Comment by Michaelangel007** [comment]
Need to account for:

* Branch != 0
* , X
* ,Y
* ,X)
* ),Y

**Comment by Michaelangel007** [comment]
@tomcw Total of 3 commits need a quick review:

* a276bef
* 975230b
* eed603f

Thanks.

**Comment by Michaelangel007** [comment]
Ah, GitHub shows/treats issue 480 as a pull request.  Neat.

OK, enough "spam" for now. :-)

**Comment by tomcw** [comment]
Merged and deleted PR #480.

**Comment by tomcw** [comment]
Tested OK with [1st ](https://github.com/AppleWin/AppleWin/issues/479#issuecomment-324646332) and [3rd](https://github.com/AppleWin/AppleWin/issues/479#issuecomment-324674192) repros above.

**Comment by tomcw** [comment]
Closing.
