### ISSUE TITLE
(Debugger) Click on Status register binary bits to toggle

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#483]
While working on #462 would like to be able to use the mouse to toggle the status bits.

`DebuggerMouseClick()`, when cy =4 or 5

| cx | Flag |
|:-:|:--|
| 53 | `N` |
| 54 | `V` |
| 55 | `R` -- reserved, can't toggle |
| 56 | `B` |
| 57 | `D` |
| 58 | `I` |
| 59 | `Z` |
| 60 |  `C` |

**Comment by Michaelangel007** [comment]
NOTE: Need to merge #480 before we can bump debugger version & update docs/Debugger_Changelog.txt

**Comment by tomcw** [comment]
@Michaelangel007 - your current implementation does allow you to toggle the R flag.

**Comment by tomcw** [comment]
Bumped debugger version (2.9.0.12) & updated docs/Debugger_Changelog.txt.
