### ISSUE TITLE
APPLE2E.SYM; Corrections/questions/comments about a few definitions

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#484]
1.  0032 INVFLG/PROMPT

Shouldn't this be:

 0032 INVFLG
 0033 PROMPT

2. 0044 A5L/MACSTAT

Not a big deal, but if you know, what is MACSTAT?  I've never seen it before.

3. 002E MASK/TEMPOP

Once again, not a big deal, but what is TEMPOP?

The MONITOR ROM defines:
  002E MASK
  002E CHKSUM
  002E FORMAT

4. 
0028 BASL
0029 BAS2L
002B BAS2H

Here there is a problem.  BASH is not defined, and BAS2L is wrongly defined.  These should be:

0028 BASL
0029 BASH
002A BAS2L
002B BAS2H

5.  I was looking at the definitions after $C600 and the comment ";Disk Drive".  To me it looks like none of the definitions in this range ($C600..$C6FF) have anything to do with a disk drive controller.

Not a big deal, but any idea what they are?

In addition, I expected to see some of the following defined:

  C600
  C65C
  C683
  C6A6

That's it for now.

**Comment by Michaelangel007** [comment]
Thanks for the bug report Tommy.

I don't know who compiled that initial APPLE2E.SYM file but yes there are clearly some wrong entry points listed there:

* [ ] `INVFLG/PROMPT`

```
                44   INVFLG   EQU   $32
                45   PROMPT   EQU   $33
```

**Comment by Michaelangel007** [comment]
I'm also not familiar with MACSTAT but a little bit of _google-fu_ reveals: _Machine State_

[The Apple //c Reference Manual Vol. 2](http://www.applelogic.org/files/IICREFV2.pdf), Appendix I, Page 127

```
67 * Note: In Apple II, //e, both interrupts and BRK destroyed 
68 * location $45. Now only BRK destroys $45 (ACC) and it 
69 * also destroys $44 (MACSTAT). 
70 * 
71 MACSTAT EQU $44 ;Machine state after BRK 
```

**Comment by Michaelangel007** [comment]
Consolidated list for (easier) reading ...

* [ ] 0032 INVFLG/PROMPT
* [ ] 0044 A5L/MACSTAT
* [ ] 002E MASK/TEMPOP
* [ ] BASH, BAS2L
* Disk Drives
 * [ ] C600
 * [ ] C65C
 * [ ] C683
 * [ ] C6A6

**Comment by Michaelangel007** [comment]
* [ ] MASK/TEMPOP

I've asked in [c.s.a2.p](https://groups.google.com/forum/m/#!topic/comp.sys.apple2.programmer/ZcPSNsKIOqU): `Origin of TEMPOP $2E ?

This might be our only clue ...
`
> As far as I can tell it looks like someone was trying to describe FORMAT from Apple //c Reference Manual Vol 2 
> 42 FORMAT EQU $2E ;temp for opcode decode 
> 43 LENGTH EQU $2F ;temp for opcode decode 

We should rename the symbol to be:

`002E F8.MASK/F8.FORMAT`

**Comment by Michaelangel007** [comment]
Disk Drive Symbols in question:

```
; Disk Drive
C603 TSTZPG
C607 ZP1
C610 ZP2
C623 ZP3
C628 ZPERROR
C62E TSTMEM
C638 MEM1
C63A MEM2
C655 MEM3
C657 MEM4
C65C MEM5
C667 MEM6
C670 MEM7
C688 MEM8
C68A MEM9
C68F MEMA
C69E MEMB
C6AD MEMC
C6BE SWCHTST1
C6CC MEMERROR
C6CD BADBITS
C6D7 BBITS1
C6DB CLRSTS
C6EB CLRS
```

**Comment by Michaelangel007** [comment]
Also see #425 for Drive IO soft switches revamp.

**Comment by Michaelangel007** [comment]
The disk drive symbols **are correct.** -- the comment is misleading though!  They come from the Jan. 1987(*) [IIe Technical Reference Manual](ftp://ftp.apple.asimov.net/pub/apple_II/documentation/hardware/machines/Apple%20IIe%20Technical%20Reference%20Manual.pdf) (216 MB), Page 317  (PDF Page 345) when the Built-In Memory Test is run $C3XX ROM space.

<img width="750" alt="c300_1" src="https://user-images.githubusercontent.com/7876796/29779774-6fe15c7e-8bc8-11e7-8d6e-57b8564b48dd.png">

<img width="725" alt="c300_2" src="https://user-images.githubusercontent.com/7876796/29779786-74eb94aa-8bc8-11e7-9d7f-a1adb6a5c2c3.png">

(*) **Note:** There are TWO versions of the IIe TRM, 1985 and 1987.

**Comment by Michaelangel007** [comment]
Tagging as 1.27 as a reminder that [docs/Debugger_Changelog.txt](https://github.com/AppleWin/AppleWin/blob/master/docs/Debugger_Changelog.txt) needs to be updated when #480 is merged.

**Comment by Michaelangel007** [comment]
Tommy,

Here is the latest [APPLE2E.SYM](https://github.com/AppleWin/AppleWin/blob/master/bin/APPLE2E.SYM) that you can use until the next version of AppleWin is released.

**Comment by tomcw** [comment]
>If anyone wants the actual $C600 Drive Symbols they can create a new issue (Feature Request Enhancement.)

These symbols would be a property of the card itself, so this feature is already covered by this issue+comment: https://github.com/AppleWin/AppleWin/issues/425#issue-232095356

**Comment by tomcw** [comment]
Bumped debugger version (2.9.0.12) & updated docs/Debugger_Changelog.txt.
