### ISSUE TITLE
Apple win doesn't show the right accumulator values

### ISSUE THREAD

**Issue by marcover** [AppleWin/AppleWin#490]
Hi,
I wrote this simple program: 
300: A9 05 69 03 FF FF 00 00

when I ran it (300G), the program executes and then it brakes

the values of the accumulator showed is not precise - every time I ran the program I don't get 8 but a random value like

309- A=01 X=00 Y=00 P=31 S=E4

that makes very difficult to debug programs

Thanks
Marco

![acc](https://user-images.githubusercontent.com/26029604/31057467-1d9130ee-a698-11e7-9baf-c1c4b2645222.jpg)
![acc](https://user-images.githubusercontent.com/26029604/31057469-24e299d2-a698-11e7-9689-687f7ca72326.jpg)

**Comment by tomcw** [comment]
You are running with emulated mode: Apple //e, which has a NMOS 6502 CPU. Therefore, opcode FF is the undocumented opcode INS, which affect the accumulator.

Either try switching to an Enhanced Apple //e (CMOS 6502, where opcode FF is just a NOP); or don't use the FF opcode.

btw. also you are not setting the C (carry) or D (decimal) flags, both of which have an affect on ADC.

**Comment by tomcw** [comment]
Closing as invalid.
