### ISSUE TITLE
Mouse not working in GEOS

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#497]
I have tried to use the geos HD from here

ftp://ftp.apple.asimov.net/pub/apple_II/images/misc/hdv_images/geos.hdv

With a mouse card in slot 4 but the mouse does not work.
In the same setup I can use Apple II Desktop and the mouse works as expected.

Version 1.14.2.0 has this line in the history

Mouse support for Contiki v1.3, Blazing Paddles & GEOS

**Comment by tomcw** [comment]
OK, I'll take a look.

btw. this  floppy version works:
ftp://ftp.apple.asimov.net/pub/apple_II/images/masters/other_os/gui/geos/geosd1s1.dsk

**Comment by audetto** [comment]
Yes it does.
But I found this strange effect that after using GEOS I need 2 reboots to use the mouse in Apple II Desktop.

1) Start AppleWin with the GEOS disk in the drive and mouse card
2) wait for it to boot
3) insert MDESK.PO in the HD
4) Reboot F2
5) Mouse does not work
6) Reboot again F2
7) Mouse works

At step 2 it does not matter if one uses the mouse or not in GEOS.

**Comment by tomcw** [comment]
Thanks for the extra issue report. I guess some (mouse-card) state isn't being reset correctly.

**Comment by tomcw** [comment]
According to CiderPress, this .hdv image file contains damaged files:

> - WARNING: ProDOS filesystem blockcount (65535) exceeds disk image blocks (1375).
> - 760 blocks are marked used but not part of any file.
> - WARNING: Blocks past the end of the disk are marked 'in use' in the volume bitmap.
> - WARNING: One or more files are damaged.

Also the .hdv file is 687 KB (704,000 bytes) in size.
Which is exactly 1375 blocks.

**Comment by tomcw** [comment]
If you start GEOS without a mousecard, then it complains "No interrupt source found.":

![nointerruptsourcefound](https://user-images.githubusercontent.com/6696896/33230157-3efcb28a-d1d6-11e7-9e4e-9ffd3745d897.png)

I can see the mousecard being used to generate VBL interrupts **_only_**.
(btw. the GEOS interrupt handler is ~2100 cycles on average!)

You can use keyboard input to move the GEOS desktop cursor:
- Open Apple + cursor keys
- Open Apple + UIO, JKL, M,. (where it's like a matrix for up/down/left/right/diagonals and OA+K=select)

You can see what Input Devices are available:
- Select the 'options' menu item
- And pick 'select input' (Closed Apple + I: doesn't seem to work)

Only Keyboard Input is available. This is way the mouse isn't working. You need to have a mouse device available and to pick that.

![selectinputdevice](https://user-images.githubusercontent.com/6696896/33230227-4d3a33da-d1d7-11e7-8e3d-471e7f685c8e.png)

**Comment by tomcw** [comment]
NB. I have another GEOS hdv image (called "GEOS-mouse supported by APPLEWIN.hdv" - but I don't know where it came from).

This offers Joystick, Keyboard & Mouse input devices:

![selectinputdevice2](https://user-images.githubusercontent.com/6696896/33230256-d56bd984-d1d7-11e7-92cf-42bd1044aaf2.png)

Perhaps you can try using appls->DISK MAKER, and Install ("GEOS on a large-capacity device such as a hard disk")?

**Comment by tomcw** [comment]
I tried appls->DISK MAKER and Install (on hard disk).

This allows you to configure the drivers for various things: input device (eg. mouse), printer, printer interface, clock and ramdisk.

So to me it's clear that `geos.hdv` just wasn't configured to have the mouse as the input device.

I'm closing this, as it's not an emulation problem.
