### ISSUE TITLE
Does Bxx taken need an extra cycle penalty for this special end of page case?

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#503]
On csa2, "Cycles question" qkumba said on Oct 25, 2017:

> To summarise, the one-cycle penalty comes from either fetching absolutely across a page boundary (5 cycles):
> 
...
> 
> or taking a branch with a prefetch across a page boundary (4 cycles):
> 
> 2A0:
> LABEL
> ...
> 2FD: SEC
> 2FE: BCS LABEL
> 300: NOP
> 
> That last one is special.  That penalty comes from the prefetcher assuming that the branch isn't taken, and then fetching from the next page. 

AppleWin only adds an extra cycles, when:
- branch is taken: +1
- branch is taken and page-crossing: +2

In the qkumba case above, the page doesn't change, so AppleWin only emulates a +1 cycle penalty.

Need to check on real 6502 and 65C02.

**Comment by sicklittlemonkey** [comment]
At a glance I think the BRANCH_TAKEN code in AppleWin looks ok:

static __forceinline void Fetch(BYTE& iOpcode, ULONG uExecutedCycles)
has
regs.pc++;

and so does REL:
#define REL addr = (signed char)*(mem+regs.pc++);

Because of the above regs.pc is pointing to the next instruction (e.g. 300
in qkumba's example) so BRANCH_TAKEN is comparing the correct addresses to
determine if the branch taken crosses a page.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick, yes you're right - I should have checked it properly.

This little program demonstrates it:
20FC:60 38 B0 FC
20FDG

I stepped the x86 asm for the emulated BCS opcode, and yes, `uExtraCycles`=2.

Still worth checking on real 6502 h/w the next time I have it set up.
NB. I'll just use the simple Mockingboard 6522 timer to count the cycles.

**Comment by tomcw** [comment]
Verify on real h/w:

20F6:AE 4 C4 0 38 AD 4 C4 B0 F6
20FAG

```
.ORG $20F6
 LDX $C404
 BRK
 SEC
 LDA $C404
 BCS $20F6
```

NB. Below, delta = (A-X) - 4 cycles for the LDX $C404

AppleWin 1.26.3.5:
- Original Apple //e: delta = 4
- Enhanced Apple //e: delta = 4

Real h/w:
- Original Apple //e: delta = 4

NB. A check sanity check is to move the code down by 1 byte to $20F5. Now on both emulator and real h/w the delta=3.

I'm closing this (even though I've only checked on NMOS 6502, not CMOS 65C02).
