### ISSUE TITLE
Full-screen: hide mouse pointer after a short period of inactivity and show again if moved

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#504]
From #398, @bsturk said:
> I'd like to see a command line argument to hide the mouse pointer when running full screen.  A _long_ time ago I patched this functionality in, but I have no idea if it would work with the current source code.

@tomcw:
>What about if AppleWin just hid the mouse pointer (in full screen) after a few seconds of it not being moved?
If you moved the mouse, then it would reappear (and then be hidden again after another few seconds of inactivity).

@bsturk:
>Yes, that would work as well. It's probably a better solution as well.

**Comment by tomcw** [comment]
@bsturk: There's a new experiment build of 1.26.3.4 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.4), which includes support for this. Can you give it a try and let me know what you think?

**Comment by bsturk** [comment]
@tomcw Perfect!  Even better than what I suggested for a change.

thank you

**Comment by tomcw** [comment]
Thanks for the feedback.
(Closing)
