### ISSUE TITLE
Canyon Climber hangs when accelerated via GG

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#508]
It's performing II+ style VBL detection this way:
-LDA $C050
BNE -
and the value never changes in that case.
It's fine when run at regular speed.

**Comment by tomcw** [comment]
Hi Peter,

This (believe it or not) is the current "spec" for this `gg` cmd.

From the [release note](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.2) (or History.txt) there's a little table describing g vs gg commands.

For `gg`, 'run at normal speed'=no and 'video quality'=periodic.  
The rationale being that when you run at full speed, then you don't care about cycle-accurate video display... except in cases like yours when the code is doing a VBL sync.

I'll have a think about how this can be improved.

For now your best option is to use `g` instead, and set the 'Emulation Speed Control' to one notch less than full speed via the main Config page (F8). The CPU speed will be 3.9MHz.

**Comment by peterferrie** [comment]
Hi Tom.

> This (believe it or not) is the current "spec" for this `gg` cmd.

Then please close this as "by design".  I accept that.

> From the [release
> note](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.2) (or
> History.txt) there's a little table describing g vs gg commands.
>
> For `gg`, 'run at normal speed'=no and 'video quality'=periodic.
> The rationale being that when you run at full speed, then you don't care
> about cycle-accurate video display... except in cases like yours when the
> code is doing a VBL sync.

I didn't understand the implications of the periodic video aspect, but now I do.

> I'll have a think about how this can be improved.

No need.  It's fine this way.
Thanks.

**Comment by tomcw** [comment]
>I didn't understand the implications of the periodic video aspect, but now I do.

At the very least I'll improve the rel notes & documentation about this command (eg. to include your case).

**Comment by tomcw** [comment]
> At the very least I'll improve the rel notes & documentation about this command (eg. to include your case).

This is covered by #477, so I will close this as "won't fix".
