### ISSUE TITLE
How can I extract the soft switch states from save-state?

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#509]
Private email from Mark to Michael:

> Hi Michael,
> 
> I'm a newbie to using the state file and have a question for you. 
> Is it possible to tell from the AppleWIN saved state file the equivalent of the info provided by these soft switches?
> 
> LDA $C016 ;MAIN/AUX ZPAGE & BSR) (bit7 = 1: AUX, bit7=0 MAIN)
> LDA $C012 ;ROM/BSR soft-switch flag (bit7 = 1: BSR, bit7=0 ROM)
> LDA $C011 ;BANK1/BANK2 soft-switch flag (bit7 = 1: BANK2, bit7=0 BANK1)
> 
> Thanks!
> Mark

**Comment by tomcw** [comment]
In the save-state file (.aws.yaml) there's this line (around line 36)

```
    Memory:
      Memory Mode: 0x00000010
```

This is just the global variable (bitfield) `memmode` defined in memory.cpp/h:

Memory.h
```
#define  MF_80STORE    0x00000001
#define  MF_ALTZP      0x00000002
#define  MF_AUXREAD    0x00000004	// RAMRD
#define  MF_AUXWRITE   0x00000008	// RAMWRT
#define  MF_BANK2      0x00000010   // Language Card Bank 2 $D000..$DFFF
#define  MF_HIGHRAM    0x00000020   // Language Card RAM is active $D000..$DFFF
#define  MF_HIRES      0x00000040
#define  MF_PAGE2      0x00000080
#define  MF_SLOTC3ROM  0x00000100
#define  MF_SLOTCXROM  0x00000200
#define  MF_WRITERAM   0x00000400   // Language Card RAM is Write Enabled
```

Memory.cpp
```
#define  SW_80STORE    (memmode & MF_80STORE)
#define  SW_ALTZP      (memmode & MF_ALTZP)
#define  SW_AUXREAD    (memmode & MF_AUXREAD)
#define  SW_AUXWRITE   (memmode & MF_AUXWRITE)
#define  SW_BANK2      (memmode & MF_BANK2)
#define  SW_HIGHRAM    (memmode & MF_HIGHRAM)
#define  SW_HIRES      (memmode & MF_HIRES)
#define  SW_PAGE2      (memmode & MF_PAGE2)
#define  SW_SLOTC3ROM  (memmode & MF_SLOTC3ROM)
#define  SW_SLOTCXROM  (memmode & MF_SLOTCXROM)
#define  SW_WRITERAM   (memmode & MF_WRITERAM)
```

So for your questions: (see function `MemCheckPaging()`)
- $C016: SW_ALTZP (memmode & 0x00000002)
- $C012: SW_HIGHRAM (memmode & 0x00000020)
- $C011: SW_BANK2 (memmode & 0x00000010)

Does that make sense?

**Comment by 6502-workshop** [comment]
Yes, thank you!

**Comment by tomcw** [comment]
Great - I'll close for now, but re-open if you need more info.
