### ISSUE TITLE
Disappearing 5.25" disk images in AppleWin (tested in v1.26.3.4)

### ISSUE THREAD

**Issue by alupin65** [AppleWin/AppleWin#511]
1. My disk setup: 2 disk images in both 5.25" drives and one is from, say, directory .\A1 and the other from .\B.  2 HD's in Slot 7.
2. Boot AppleWin from HD in S7,D1 ("applewin -r 64"). Do something and quite AppleWin altogether.
3. Start AppleWin again with the same command.  Now you will find S6,D2 empty but the diskette in S6,D1 is still there.
4. If you put the original diskette in S6,D2 and repeat 2-3, you will find S6,D1 now empty instead. S6,D2 still has the right image.

**Comment by tomcw** [comment]
Quick triage:
The last drive that has a disk inserted will set this Registry value:
HKEY_CURRENT_USER\Software\AppleWin\CurrentVersion\Preferences -> "Starting Directory"

Similarly for HDD images, there's only one Registry value:
HKEY_CURRENT_USER\Software\AppleWin\CurrentVersion\Preferences -> "HDV Starting Directory"

So having floppy of HDD images in different directories means that only those images in the "\[HDV\] Starting Directory" will be inserted (or plugged in) on an AppleWin restart.

NB. For save-state files (from the AppleWin.chm):
>Note: Only the file names of the disk images are stored in the .yaml file (not the full path). This allows you to move your disk image around or distribute them. If AppleWin can't locate the disk image(s), then it will prompt for the new location.

**Comment by tomcw** [comment]
This got fixed in #960 - AppleWin v1.30.4.0:

>Floppy image names are now stored in Registry (or conf.ini) with their full path.

Closing.
