### ISSUE TITLE
Apple /// emulation

### ISSUE THREAD

**Issue by SEGStriker** [AppleWin/AppleWin#513]
I think it is about time to add emulation of Apple /// (3) to this great emulator.
Also 3.5 FDD controller (requests 5747, 4879 - my first request about this) . It is truly needed by lot people.

**Comment by tomcw** [comment]
>Also 3.5 FDD controller (requests 5747, 4879 - my first request about this) .

berlios requests 4879 = #104 
berlios requests 5747 = #195 (closed as a dup of #104)

**Comment by SEGStriker** [comment]
I think Apple /// emulation will be really good to have. As you probably know, there is only one partly working emulator and it is not for PC but for Mac - Sara. Of course, MESS has unfinished emulation that isn't working correctly (at least it wasn't last time I checked). So it is surely good to have finally emulator that is working on PC.

**Comment by sicklittlemonkey** [comment]
I would vote against this proposed enhancement. My reasoning is:

1. The Apple /// is a very different and more complicated machine compared
to others in the Apple II series - offering only very limited
compatibility. The hardware is about as different as the IIgs, but probably
not as well documented.
2. The Apple /// sold poorly and had very little software released for it,
so the userbase would be a small niche compared to the Apple II enthusiasts
we currently appeal to.
3. Following from the above, it would take a large effort to implement, and
very few of our existing users would benefit. Development time is better
spent on existing Apple II feature requests.

Of course, I'm not arguing against the need for Apple /// emulation. The
existing emulators should be enhanced and ported to desired platforms. But
I see no benefit in tacking it onto AppleWin.

Cheers,
Nick.

**Comment by tomcw** [comment]
I'm in general agreement with Nick's reasons, especially this point:
>Development time is better spent on existing Apple II feature requests.

So setting to: Won't Fix.
