### ISSUE TITLE
After using GEOS, I need 2 reboots to use the mouse in Apple II Desktop

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#514]
Spun off from #497:

Using: ftp://ftp.apple.asimov.net/pub/apple_II/images/masters/other_os/gui/geos/geosd1s1.dsk

@audetto reported:
But I found this strange effect that after using GEOS I need 2 reboots to use the mouse in Apple II Desktop.

1. Start AppleWin with the GEOS disk in the drive and mouse card
2. wait for it to boot
3. insert MDESK.PO in the HD
4. Reboot F2
5. Mouse does not work
6. Reboot again F2
7. Mouse works

At step 2 it does not matter if one uses the mouse or not in GEOS.

**Comment by tomcw** [comment]
@audetto: can you provide a link to MDESK.PO?

**Comment by audetto** [comment]
http://apple2online.com/web_documents/MDESK.zip

**Comment by tomcw** [comment]
Hmm... I can't reproduce this (using both 1.26.3.1 and the latest 1.26.3.4).
The mouse always works first time after rebooting from GEOS to Apple II Desktop.

I followed your steps exactly.
Also I tried these simplified steps...

1. Start with geosd1s1.dsk in drive-1 **and** MDESK.PO as HDD-1.
2. Hold down Open-Apple, and then press F2 (Open-Apple tells the HDD firmware to boot from floppy)
3. Wait for GEOS to boot
4. Reboot with F2
5. Apple II Desktop boots & mouse is working

Do you have any extra hardware enabled? EG. RAMworks? A card in slot-5?

**Comment by audetto** [comment]
To me it still happens.
Used 1.26.3.4 (in wine) Tomorrow I try in windows.
Here are the 3 save state

[states.zip](https://github.com/AppleWin/AppleWin/files/1504193/states.zip)

**Comment by tomcw** [comment]
OK, thanks - I can reproduce this now.
For some reason it's the enabling of the HDD card (not the plugging in of the HDD into the card) that is causing the issue.

**Comment by tomcw** [comment]
This is a bug in the emulator's restart code that wasn't resetting the mousecard state.
(And h/w reconfig is enough to cause a restart... and trigger this bug)

There was a pending mousecard interrupt (VBL) from the old GEOS session, and on re-enabling the card for A2 Desktop, the interrupt fired. IRQ fetched 0x0000 from 0xFFFE, vectored to 0x0000, which was a BRK, and an infinite loop ensued!

**Comment by tomcw** [comment]
Can you try [AppleWin v1.26.3.5](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.5) and let me know how you get on?

**Comment by audetto** [comment]
It does work now.

**Comment by tomcw** [comment]
Thanks for confirming.
