### ISSUE TITLE
Apple Win problem with Double Lores and Aux-Move

### ISSUE THREAD

**Issue by naspitelabs** [AppleWin/AppleWin#516]
When one has a Double Lores image on the screen, and then you do an aux move (The direction I usually go in is from Main to Aux memory), it will switch the onscreen display from DBLORES pg1 to DBLORES pg2.  On real hardware it will do this switch (On a IIE Plat and GSSport works)... but in Apple WIN it does not do this (Its sort of a reverse glitch).  Once I do aux-move, I perform POKE 49152,0:POKE 49236,0 to change it back to the original screen, so I think these memory locations are (NOT) changed with applewin to create hardware like conditions.      ((((-As a side note, Apple WIN 1.25.0.3 is great for programming with its display mode in COLOR-TV, and i know the color is slightly off in comparison to the newer version.. but the new one is so hard to use on a daily basis for programming and has a fuzzy display.  Regardless, AppleWIN is fantastic software, thank your for making it!)

**Comment by tomcw** [comment]
>As a side note, Apple WIN 1.25.0.3 is great for programming with its display mode in COLOR-TV, and i know the color is slightly off in comparison to the newer version.. but the new one is so hard to use on a daily basis for programming and has a fuzzy display.

Another vote for #357. But duly noted.

>Regardless, AppleWIN is fantastic software, thank your for making it!

Thanks for the feedback! :)

**Comment by tomcw** [comment]
>When one has a Double Lores image on the screen, and then you do an aux move (The direction I usually go in is from Main to Aux memory), it will switch the onscreen display from DBLORES pg1 to DBLORES pg2.

You say you are using AppleWin 1.25.0.3.
Does this also occur with [AppleWin 1.26.3.4](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.4) too?

**Comment by naspitelabs** [comment]
Yes, when the issue was first discovered, I went to download the latest version (1.26.xx something) and the same issue existed.. its a pain switching between GSSport and AppleWin to determine exactly what the issue (minimum code is)... i'm trying to get you a disk image... when run on real hardware it will glitch on the screen, in AppleWin, everything seems normal... very deceiving!

**Comment by naspitelabs** [comment]
https://www.dropbox.com/s/uvhmyf32ikevvjr/DLORES%20GLITCH.dsk?dl=0
This file... TEST1 will produce graphic glitch in GSSport and IIE Plat (*This is what its suppose to do), but will be fine in AppleWin.   Test2 will be fine in all cases.   Note line 199 is what I did to 'correct' the issue, it pretty much reactivates pg1 of double lores after an aux move operation.      CALL 36600 activates double-lores... 37190 is the double lores page mover...  you can again place it in a new statement like 407 (407 call 36600:call 37190) if you want to see the second image, but is not needed for the glitch to occur.

**Comment by tomcw** [comment]
Thanks for the repro. This bug has been latent for many years.
I'll rebuild and get you to verify the fix...

**Comment by tomcw** [comment]
Can you try [AppleWin v1.26.3.5](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.5) and let me know how you get on?

Note to self: "a2audit 1.04" noticeably more flickery now, but otherwise all tests appear fine.

**Comment by tomcw** [comment]
@naspitelabs - please let me know if [AppleWin v1.26.3.5](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.5) fixes the issue? Thanks.

**Comment by naspitelabs** [comment]
Hi Tom.. 
The newer version of AppleWin seems to be acting more like the original iie... So I'd say the issue is fixed!
Thanks for checking back...  Tom P.

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 13, 2017 at 5:22 PM, TomCh<notifications@github.com> wrote:   
@naspitelabs - please let me know if AppleWin v1.26.3.5 fixes the issue? Thanks.

**Comment by tomcw** [comment]
Thanks for confirming.
