### ISSUE TITLE
Full-speed: prevent hangs when games uses II+ video sync

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#519]
(Spun off from #477)

>>It's a shame it doesn't work at full-speed...
> 
> Yes, I agree. It's not the best user experience.
> 
> We could have the emulator detect II+ VBL detection, eg:
>  -LDA $C050
>  BNE -
> 
> This check could be done periodically, eg. at the start of the next batch of 6502 emulation, in `CpuExecute()`.

If we document the kinds of II+ video sync routines that are being used then we could think about a solution. These games use II+ video sync (but of course there are others):
- #4, Drol
- #508, Canyon Climber

EG, some generalised solution of the form:
- _if full-speed && bytes at 6502.PC == {AD 5x C0 D0 FB} then 6502.PC+=5_

(We need the $C05x access to occur, so perhaps advance the PC on the 2nd occurrence?)

Video rendering will still be imprecise in full-speed mode (which is fine) - we are just trying to prevent the game from hanging.

NB. For //e VBL detection, it reads from $C019
This works in full-speed, as `VideoCheckVbl()` calls `VideoGetVblBar()` which checks the v-position based on `g_dwCyclesThisFrame`, this variable is correct regardless of full-speed mode.

**Comment by tomcw** [comment]
NB. #532 is a //e game which doesn't boot in full-speed mode.

For full-speed mode, why not just update the video scanner h/v position whenever the floating-bus is required.

Then the call to `NTSC_VideoGetScannerAddress()` will return the correct value.
NB. This gets called by `MemReadFloatingBus()` and `IO_Null()`.

**Comment by tomcw** [comment]
I tested AZTEC boot times before and after this patch (2c8f5ce), and times remain the same (~1981ms).

**Comment by tomcw** [comment]
Fixed, so closing.

**Comment by sicklittlemonkey** [comment]
Nice one!

I hoped it wouldn't be too hard to plumb the old behaviour back in
somewhere.
​
Cheers,
Nick.

**Comment by tomcw** [comment]
Yeah, it was kind of obvious once I had to consider more cases (eg. like #532).
