### ISSUE TITLE
SSC: Support ACIA's TX Register Empty interrupt

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#522]
Request from #308, where @burniouf said:
>any chance TX register empty IRQ implemented ?

**Comment by tomcw** [comment]
Should be pretty simple.
NB. Need to support both COM and TCP modes.

**Comment by burniouf** [comment]
great! let me know if a build is to be tested.
Would you like me to provide test cases based on a A2osX media ?

**Comment by tomcw** [comment]
Yes, if you have Apple II software that I can use to test this, then that'd be very useful.

**Comment by tomcw** [comment]
Added test here: https://github.com/AppleWin/AppleWin-Test/commit/39e4de05b5b5b20f76a226eb1a04d92bc1bfcf55

**Comment by tomcw** [comment]
New AppleWin 1.27.2.0 build [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.2.0).
