### ISSUE TITLE
drive head can be moved while drive turned off (1.26.3.6)

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#525]
In AppleWin, it is possible to perform a seek even while the drive is turned off.
On real hardware, the request is ignored, and the current track remains current.

(There's a secondary issue but it requires support for spin-up/spin-down, so it might be considered future work: on hardware, if the drive is not fully spun up, then a "long" (say, more than a couple of tracks) seek will not reach the requested track).

**Comment by tomcw** [comment]
@peterferrie - is this issue (and the secondary issue) related to your comment on the csa2 news-group, in thread "Gumball" [here](https://groups.google.com/d/msg/comp.sys.apple2/DM_h7hkaUmA/bcLz_IOqDQAJ)?

**Comment by peterferrie** [comment]
Hi Tom,

> @peterferrie - is this issue (and the secondary issue) related to your
> comment on the csa2 news-group, in thread "Gumball"
> [here](https://groups.google.com/d/msg/comp.sys.apple2/DM_h7hkaUmA/bcLz_IOqDQAJ)?

The issue is what hid until now the cause of the current Gumball issue.
Had I tried an emulator with the correct behaviour, then I would have
found it sooner. :-)

The secondary issue was the cause of an earlier problem in Gumball,
since solved by waiting longer.  It's a very hardware-specific
problem.

**Comment by sicklittlemonkey** [comment]
Hi guys.

Sorry for the delayed response ... been painting fences and wiping bottoms
this weekend. : - /

I believe the head stepping is possible during the 1 second drive off delay
- similar to how Sherwood Forest etc read the drive with the motor off.

As long as you turn it back on within 1 second it's like it was never
turned off.

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick - OK, I've add support to allow head stepping during this 1s (actually 1.25s in AppleWin) "motor off, but still spinning" period.

**Comment by peterferrie** [comment]
Yes, that's true, and leads into the spin-up/down secondary case.  You
can't seek reliably during either of those events.
However, in the case of Gumball, the drive was fully off at the time
(specifically, for the entire duration of the active level).
I should have been more specific.
