### ISSUE TITLE
I cannot type lowercase with AppleWin and Win10.

### ISSUE THREAD

**Issue by Wizardling** [AppleWin/AppleWin#528]
But have no problem doing so with an emulator like https://www.scullinsteel.com/apple2/

However, in AppleWin caps lock and shift have zero effect on case.

**Comment by tomcw** [comment]
Here's what to do:

1. On start-up, AppleWin always begins with the Apple II's Caps Lock enabled, regardless of the current state of the PC's Caps Lock key.
2. When you press the PC's Caps Lock key the 1st time, this will actually enable the PC's lock, and AppleWin will see this but remain in the Caps Lock _enabled_ state.
3. Finally press the PC's Caps Lock key a 2nd time, and now AppleWin will disable Caps Lock and allow lower-case to be used.
4. ...and subsequent toggling of the PC's Caps Lock key will continue to be replicated by AppleWin.

**Comment by Wizardling** [comment]
Nope, sorry, that did not work. I tried turning capslock off and on many times yesterday and again after your reply today. Nothing changes inside AppleWin. It's uppercase all the way, regardless.

Plus now I'm getting some error about being unable to capture the PrintScreen key. Not that I care much about that. But I really do need a way to type lowercase in order to use this emulator.

**Comment by tomcw** [comment]
I'll check tomorrow on a Win10 machine.

>Plus now I'm getting some error about being unable to capture the PrintScreen key.
Either you are running more than one instance of AppleWin, or some other program has registered for the PrintScreen key before AppleWin.

**Comment by Wizardling** [comment]
Cheers, I appreciate you looking into it. As for PrintScreen - only one instance of AppleWin is running, and all that changed was I restarted my PC this morning *shrug*

**Comment by sicklittlemonkey** [comment]
As Tom said, another program has captured the Print Screen key. E.g. if you have One Drive installed you need to disable the "Automatically save screenshots" feature.

![image](https://user-images.githubusercontent.com/4393005/35015470-65992974-fb79-11e7-9bcc-660c92cbef90.png)

If you're using a laptop you might get some advice on seeing whether Caps Lock presses are registered with the advice here:
http://windowsreport.com/caps-lock-indicator-not-working-windows-10/

Cheers,
Nick.

**Comment by Wizardling** [comment]
I do have One Drive installed, but I never turned on its automatic screenshot saving, nor that of any other app, at least knowingly.

My keyboard's capslock works as expected outside of AppleWin. It does seem to be an issue peculiar to just this one app, so far as I can tell.

Huh, I tried pressing PrintScreen inside of AppleWin just now, then restarted the app. No more warning. Odd, but at least that minor issue has now departed.

I wonder: what is the next best Apple II emulator for Windows, after AppleWin (in case a fix or just understanding what is going wrong takes a while)? Up till last year my primary machine had been a Mac for a couple decades (though I've always used many OSes), and that is where I did my emulation. So I'm not fully conversant with the state of retro emulation under Windows.

**Comment by sicklittlemonkey** [comment]
OneDrive has the feature enabled by default. I had to disable it - I put a
pic of the setting here:
https://user-images.githubusercontent.com/4393005/35015470-65992974-fb79-11e7-9bcc-660c92cbef90.png

For emulator recommendations you should probably ask on comp.sys.apple2 or
the Facebook Apple II Enthusiasts Group.

Cheers,
Nick.

**Comment by Wizardling** [comment]
No, I have checked, and it isn't enabled, nor in DropBox, or anywhere else knowingly. But as I say, simply pressing PrintScreen while in AppleWin seems to have resolved that issue for now. Why? I can't tell you :-D

It has been a while since I frequented that Usenet group, but I shall stop by again. AppleWin does seem nice enough, though. Certainly, it is top-ranked in Google. It is only the lack of lowercase that is a sticking point.

**Comment by sicklittlemonkey** [comment]
AppleWin is very convenient and has most things you'd need, including a
debugger.

I've never had any problems with Caps Lock in AppleWin in any version of
Windows, including 10, so this is a strange case.

Can you give us any more info on your keyboard, and Windows 10 build number
please?

Cheers,
Nick.

**Comment by Wizardling** [comment]
Problem solved... sort of. It turns out AppleWin changed (reverted?) settings to the II+ instead of IIe enhanced which I had set. So it wasn't actually the problem I thought. I know I had setup the emulator as a IIe enhanced at least, as one of the first apps I ran the other day required it. But today when I carefully reviewed all settings, wondering if I'd missed something... there it was: I was on a virtual II+. I'd have noticed eventually when I went back to an app requiring a newer model. But weird that my earlier setup was changed. Is this a known issue? Or am I missing something that configuration is tied too?

Anyway, my sincere apologies for not doublechecking my settings before posting, and wasting some of your time. But unless I'm experiencing early onset dementia, I knowI had taken care of setup, and the evidence of my own actions backs me on that :-)

**Comment by sicklittlemonkey** [comment]
It remembers the last configuration you used. It also puts the model name
in the title bar of the Window so you can never be confused. ; - )

Anyway, relieved to hear there's no problem then.

Cheers,
Nick.

**Comment by Wizardling** [comment]
Well, I can only say something went screwy with remembering my setup. Unless something went screwy with me, heh.

I see that the model is in the title bar, yeah. But I was going full screen for a more immersive experience :-)

**Comment by tomcw** [comment]
I can't explain this either (ie. AppleWin erroneously switching to a II+ model).
FTR, what version of AppleWin are you using?

**Comment by Keatah** [comment]
Butting my nose in here.. I've not ever seen AppleWin switch machines unless I asked it to.

**Comment by Wizardling** [comment]
v1.26.1.1

Well, trust me to find the weird problem :-D Is there any kind of verbose logging I can turn on to see what's going on if I can catch it again? Maybe I've got a dodgy SSD that isn't accepting writes properly... *shrug* My file storage SSD (on which I have my emulators and images) is quite old, though the boot NVME SSD is brand new.

I won't worry too much because for now I'm having too much fun. Switching systems and emulators with the resulting testing has got me re-playing some older games again. I need to buy an old CRT for extra retro fun, since my modern graphics system has an old VGA port included...

**Comment by tomcw** [comment]
There is logging, but it doesn't include configuration changes. I'll extend it to include this.

FYI, to enable logging use -l or -log switch:
```
> applewin.exe -l
```

This will create (or append to) an AppleWin.log file.

**Comment by tomcw** [comment]
More logging for when Apple2 Type changes (added at b324f43).

**Comment by tomcw** [comment]
Closing this old issue.
