### ISSUE TITLE
Is there a way to turn filters off?

### ISSUE THREAD

**Issue by ckeech** [AppleWin/AppleWin#530]
I used to use an older version and I like the pixelated non softened look. I've tried all the new filters and none of them seem to have the unfiltered look. I'd love to have this option.

Thanks :)

**Comment by tomcw** [comment]
I think this is a duplicate of #357 - can you confirm this is what you are asking?

**Comment by ckeech** [comment]
Yes tomcw, that's the same thing. Thanks :)
