### ISSUE TITLE
DOS 3.2 - INIT gives an I/O ERROR

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#537]
Officially there's no support for DOS 3.2 in AppleWin (eg. there's no mention of DOS 3.2 in the docs, and .d13 disk images have never been supported).

To reproduce this using AppleWin 1.27.0:

- From a system master disk (eg. "Apple DOS 3.3 January 1983.dsk"), RUN START13, and then insert "Apple DOS 3.2.1 Standard.nib" in drive-1 and hit return to boot it.
- Insert a new/blank .nib into drive-2 (eg. just type the name of a file that doesn't exist, but with a .nib extension).
- Now `INIT HELLO,D2` will quickly give an I/O ERROR.

NB. AppleWin 1.25.0.4 completes the INIT without error. But if you try to open the .nib with CiderPress, then it prompts with Filesystem=Unknown filesystem. Selecting "DOS sector ordering" and "DOS 3.2" gives the error:

> Unable to access disk image using selected parameters.  Error: specified filesystem not found.

**Comment by tomcw** [comment]
The difference between 1.25.0.4 and 1.27.0 is how the disk's write-protect state is returned.

For DOS 3.2.1, after INIT writes a track, it'll attempt to read it (eg. to check that the gaps aren't too big and no sectors have been overwritten).

Here's the code to read the disk's write-protect state and set read mode:

```
bf7b:
 lda $c0ed,x	; DiskLoadWriteProtect()
				; - but floppywritemode==1, so this is no-op
				; - ie. floppylatch is unaffected (remains 0xff)
				; - when floppylatch.b7 should've been cleared
 lda $c08e,x	; DiskSetReadMode()
				; Sets floppywritemode:=0 and returns floppylatch
 bmi bfb5
 ...

bfb5:
 lda #$40	; I/O Error?
 jmp be39

be39:
 sec
 ldy #$0d
 sta ($48),y	; b7f5
 lda $c088.x	; Motor off
 rts
```

For AppleWin 1.27.0, because floppywritemode==1, then the write protect state isn't written to the latch (bit7), and the latch value remains at 0xFF. So the INIT fails. See `DiskLoadWriteProtect()`.

Is this a bug? Or a difference between the 13-sector and 16-sector Disk II interface controller cards?

**Comment by tomcw** [comment]
In `DiskLoadWriteProtect()`, if I comment out this line then the INIT completes (just like 1.25.0.4):

```
	if (!floppywritemode)
```

@sicklittlemonkey - Nick: you did the improvements and changes in this area. Do you have thoughts about this?

**Comment by sicklittlemonkey** [comment]
Interesting. I'm currently packing my life away into boxes, but this isn't
obvious at a glance when looking at the sequencer programs on 9-19 of
Sather's Understanding the Apple //e.

As usual, though, Sather is nothing if not thorough!
Read page 9-21 from the paragraph starting:
"If for some reason the above write protect check
were entered with the READ/WRITE switch in
WRITE, the write protect switch would still be read
correctly."

So we can just remove the surrounding "if (!floppywritemode)" block.

Nice find!

Cheers,
Nick.

**Comment by tomcw** [comment]
Nick: thanks for the quick Sather reference (that's fixed and committed now).

I'm leaving this issue open for now, as there are a few DEBUG asserts to tidy up (due to 13 sectors), and it would be nice to understand why CiderPress doesn't like these DOS 3.2 .nib's that AppleWin is creating.

**Comment by tomcw** [comment]
Added test for DOS 3.2.1 INIT (https://github.com/AppleWin/AppleWin-Test/commit/21185bd1b2cb597081c63dcbf1194143aefbe953)

**Comment by tomcw** [comment]
>it would be nice to understand why CiderPress doesn't like these DOS 3.2 .nib's that AppleWin is creating.

There's a subtle bug in CP:
https://github.com/fadden/ciderpress/issues/30
