### ISSUE TITLE
Support Apple // Extended Debugging Monitor ROM

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#545]
(Email from Nick, 15/3/2017)

Has anyone ever asked for the EDM? JACE supports it.
http://www.jamtronix.com/blog/2007/05/24/apple-extended-debugging-monitor/

Obviously it's not really needed since AppleWin has a debugger, but pretty it's cool to be able to use what the Apple firmware developers used.

The most notable inclusion is assembling and disassembling 65C02 opcodes, which the //c got but the //e missed out on. I verified that when answering here:
http://retrocomputing.stackexchange.com/questions/2477/did-the-apple-iie-platinum-include-all-feature-enhancements-from-the-apple-ii-li

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
Already logged as issue #394.

Cheers,
Nick.

**Comment by tomcw** [comment]
Duplicate - closing.
