### ISSUE TITLE
False "Unable to capture PrintScreen key" warning suddenly happening every launch.

### ISSUE THREAD

**Issue by Wizardling** [AppleWin/AppleWin#547]
Okay... after restarting Windows 10 this morning, I now get this false warning and PrtScn saves a screenshot of AppleWin's screen just fine, regardless. Onedrive, Dropbox, etc all still have automatic screenshot saving turned off.

**Comment by tomcw** [comment]
I've checked AppleWin's code, specifically this function: `AppleWin_RegisterHotKeys()` which registers for these 3 hot-keys:

1. PrintScreen (for 560 pixel screenshot)
2. Shift+PrintScreen (for 280 pixel screenshot)
3. Ctrl+PrintScreen (copy current TEXT40/TEXT80/debugger screen to clipboard)

It will try to register for all 3. If any fail then you'll get the message: `Unable to capture PrintScreen key`, but it will always try to register for all 3, irrespective of any of them failing.

Currently there's no logging for any failures.

So it could be that only the Ctrl+PrintScreen registration has failed, but the other 2 are fine, and will work within AppleWin.

Can you try doing Shift+PrintScreen and Ctrl+PrintScreen to determine if these work/don't work?

**Comment by Wizardling** [comment]
Okay, it _was_ Dropbox which despite no input from me, had taken over Control-PrScrn and for some reason decided not to display sreenshot sharing as checked, until I used that key combo. Windows software in general seems to have a very bad habit of occasionally randomly changing prefs when Windows 10 is restarted.

**Comment by tomcw** [comment]
OK, thanks for confirming this.

>Currently there's no logging for any failures.

I'll leave this issue open to improve logging for this.
Also the Message Box could be more specific about what failed.

**Comment by tomcw** [comment]
@Wizardling - FYI, a [new 1.27.1 version](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.1.0) with improved UI and logging when PrintScreen key fails to register.

**Comment by Wizardling** [comment]
Cheers, will try out immediately!
