### ISSUE TITLE
ClosedApple + <key> is not working (when using right ALT key)

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#558]
The right ALT key (aka Alt Gr) works, but the key it's combined with (eg. "A") is not made available to $C000 / $C010.

This isn't a regression (I went as far back as 1.13.1) - it appears never to have worked!

NB. The erroneous way that AKD works (#330) means that if I press "A", followed by right ALT + "A", then $C010 (AKD) will go high. (EDIT: but only for this "A" key, not for any other keys.)

**Comment by tomcw** [comment]
At 1.27.5.0, then (when right ALT is down) the internal `keycode` doesn't get updated when any keys are pressed. So if keycode=13, then (when right ALT is down), any key press (eg. "A") will cause AKD/$C010 to return 141 (ie. 13+128).

**Comment by tomcw** [comment]
Some logging showing the difference in Windows message received for left vs right ALT:
(ext = lparam.KF_EXTENDED, joy = JoyProcessKey() indicated that the key-press was for a joystick input)

```
Left ALT+A
WM_KEYDOWN = 0x12, ext=0, joy=1
WM_KEYDOWN = 0x41, ext=0, joy=0
WM_CHAR    = 0x61

Right ALT+A
WM_KEYDOWN = 0x11, ext=0, joy=0
WM_KEYDOWN = 0x12, ext=1, joy=1
WM_KEYDOWN = 0x41, ext=0, joy=0
WM_CHAR    = 0xE1

Right ALT+B
WM_KEYDOWN = 0x11, ext=0, joy=0
WM_KEYDOWN = 0x12, ext=1, joy=1
WM_KEYDOWN = 0x42, ext=0, joy=0

Right ALT+C
WM_KEYDOWN = 0x11, ext=0, joy=0
WM_KEYDOWN = 0x12, ext=1, joy=1
WM_KEYDOWN = 0x43, ext=0, joy=0
```

So when right ALT is pressed, then in general WM_CHAR is not sent.
In fact WM_CHAR is only sent for these right ALT+\<key\> key-strokes:

Keyboard key | WM_CHAR wparam | Character in Notepad+
--|--|--
` | 0xA6 | ¦
A | 0xE1 | á
E | 0xE9 | é
I | 0xED | í
O | 0xF3 | ó
U | 0xFA | ú
$/4 | 0x80 | €

**Comment by sicklittlemonkey** [comment]
Heh, it's been a long time since I looked at this kind of stuff. Windows
does a bit of pre-processing.
There are some interesting blog posts if you google around:
https://blog.keyman.com/2008/06/robust-key-mess/
https://handmade.network/forums/t/2011-keyboard_inputs_-_scancodes,_raw_input,_text_input,_key_names

Cheers,
Nick.

**Comment by tomcw** [comment]
Hi Nick,
Thanks for those links.
The [first one](https://blog.keyman.com/2008/06/robust-key-mess/) is interesting:
> Don’t reinvent the wheel: avoid the temptation to use the keyboard information functions (MapVirtualKeyEx and related functions) to reimplement the WM_KEYDOWN -> WM_CHAR translation.

Since AltGr doesn't generate a WM_CHAR message, then there has to be some manual translation to convert an AltGr-generated WM_KEYDOWN (+ SHIFT) to an ascii value. Since we now have to do this, then we could ditch support for the WM_CHAR message in AppleWin, and just _always_ manually translate WM_KEYDOWN.

**Comment by sicklittlemonkey** [comment]
Yeah. One possible downside would be that I presume you couldn't use
automation software that sends WM_CHAR - in the very unlikely case anyone
is doing that. ; - )

Cheers,
Nick.

**Comment by tomcw** [comment]
Heeding the "don't reinvent the wheel" advice, I will try posting a WM_KEYDOWN message without the extended (AltGr) flag set, so that TranslateMessage() will post a WM_CHAR. This seems like a simpler approach.

Another reason is that in Keyboard.cpp, for the TK3000e machine, there's support for accented chars (ie. wparam>127). If I were ditching WM_CHAR then (after switching it to WM_KEYDOWN) I'd need to test this code, but I don't want the time sync of having to go near this code!

**Comment by tomcw** [comment]
> I will try posting a WM_KEYDOWN message without the extended (AltGr) flag set, so that TranslateMessage() will post a WM_CHAR.

This didn't work - no WM_CHAR message was generated.

So instead I manually post a WM_CHAR message, on getting WM_KEYDOWN for ascii keys (accounting for shift, control & caps lock).

Also pressing Alt Gr sends WM_KEYDOWN messages for VK_LCONTROL and VK_RMENU. This fake VK_LCONTROL masks whether Control is really being pressed or not. So I'm suppressing this fake VK_LCONTROL in the keyboard hook filter.

**Comment by tomcw** [comment]
Merge PR #573 / 6ed354714

**Comment by tomcw** [comment]
In #570, Marco reported that on his Italian(?) keyboard, AltGr+\<key\> is used to type #, @, [ , ] keys. And Wikipedia shows this too, [here](https://en.wikipedia.org/wiki/AltGr_key#Italian).

I said:
>There isn't much demand for ClosedApple+<key>, so maybe I'll provide a GUI option for opting in to this new 1.27.6 behaviour, and revert so that the default is like 1.27.5 (and earlier).

**Comment by tomcw** [comment]
There's a new 1.27.7 release [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.7.0) with the hooked ALT GR fake LCONTROL**reverted**.
Use `-hook-altgr-control` if you really need to do Closed Apple+CTRL+\<key\>!

**Comment by tomcw** [comment]
A summary of what changed at 1.27.7:
(NB. Before 1.27.7, for Closed Apple + \<key\>, the \<key\> wasn't visible via $C000 or $C010.)

- Closed Apple + \<key\> now working for both $C000 and $C010 (AKD).
- Closed Apple +CTRL +  \<key\> only working if you use `-hook-altgr-control`.
- Open Apple + Closed Apple +CTRL +  \<key\> only **partially** working if you use `-hook-altgr-control`.
  - Workaround: use NumPad  '0' + '.'
- Open Apple + \<system key\> working (may need to use a cmd line switch) - see #556.

**Comment by tomcw** [comment]
Closing this issue, since the current (1.27.7) support for Closed Apple + \<key\> is probably good enough.

**Comment by tomcw** [comment]
At 1.28.3, I changed the behaviour so that WM_CHAR is only posted when using switch: -altgr-sends-wmchar
