### ISSUE TITLE
Drop support for VS2010 and VS2012?

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#559]
In PR #339, [here](https://github.com/AppleWin/AppleWin/pull/339#issuecomment-285855059), I considered which versions of VS support which OS's:

---

I'm considering VS from the point of view of AppleWin supporting older Windows OS versions.
(Not that I do any testing on OS's older than Win7-64, but rely on end-user feedback to highlight issues.)

VS2005 - last VS version to support Win98/ME
VS2008 - last VS version to support Win2000: [ref](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#2008)
VS2010 - supports WinXP and above
VS2012 - dropped support for WinXP
VS2012-update1 added support back in for WinXP
VS2013/15/17 - do these still include support for WinXP targets?

At AppleWin 1.26 we moved from VS2005 to VS2008, and so dropping support for Win98/ME.

I'm fine with sticking with VS2008 (for the official release build) for now, but it's useful to understand the implications of moving to a newer VS version.

If in the future we moved to a newer VS, then implicitly that means Win2000 is no longer supported by AppleWin (probably fine, but we should ask on the cea2 newsgroup). Now WinXP becomes the new base OS, so what is the minimum VS version that still supports WinXP?

---

Yes, VS2013/15/17 does have XP support. (Never used myself though.)
The corresponding Platform toolset settings are v120_xp, v140_xp, and v141_xp.
For comparison, the default settings without XP support are v120, v140, and v141.

---

"Configuring Programs for Windows XP" https://msdn.microsoft.com/en-us/library/jj851139.aspx

That's for 2015 but 2017 still has the same option. BTW, they've optimized 2017 to load quicker than 2015.

**Comment by tomcw** [comment]
Anyway, VS2012 hasn't been updated for 3 years (May 2015).

But I can see that Michael still updates VS2010 periodically. NB. I don't since I don't have it installed (and have no desire to install it!).

I propose we drop VS2012 from the repo.
And also VS2010 too... but this is up to Michael, who looks to still be using it.

**Comment by tomcw** [comment]
@Michaelangel007 - can we drop VS2010 support yet?

...and close PR #442 too (which is for V2010).

**Comment by tomcw** [comment]
NB. I've moved all VS2005 & VS2012 proj & sln files.
Just VS2010 still to decide on. . .

**Comment by tomcw** [comment]
VS2019 was released earlier this week, but I don't know if it has a Platform toolset for XP.

We should consider building the release version of AppleWin with a newer version of Visual Studio. The benefits are the obvious ones with moving to a more modern IDE, dev tools + compiler (including more modern C++).

If we can jump to VS2019 then why not? Otherwise VS2017.

Moving to anything after VS2008 means that Windows XP becomes the oldest theoretically supported platform that AppleWin will run on. (I say "theoretically supported", but I don't plan on actually testing on this OS.) I'll post this to the cea2 mailing list to gauge opinion, and then perhaps look to make the switch in a few months' time.

NB. When switching I'll also coordinate so that the AplpeWin version changes at the same time, eg. from 1.28 to 1.29.

**Comment by rzumer** [comment]
VS2019 plans to drop XP support, currently I believe it is still included with the VS2017 toolkit (v141) but marked as deprecated.

**Comment by Michaelangel007** [comment]
I haven't forgotten about this.

Moving this month but downloading and installing the VS2019 Preview on my Win7 box.  I checked the v141 relevant stuff (command line, etc.)  Download was fast ~2 GB (took about a minute.)  Installing is slow -- even on an SSD.

We probably should have a dedicated `COMPILING.md` file with pictures so people can easily see what options they need due to all the crap included in the installer front-end now.

**Comment by Michaelangel007** [comment]
Installing 361 packages took about ~5 minutes.

Bloody MS.  Reboot required after installing VS2019 Preview so it can continue the installing. :-/

**Comment by rzumer** [comment]
There are already instructions linked in the readme and dependencies have not changed.

It's funny to me that you say downloading was fast but installation slow. 2019 and maybe 2017 can install while downloading so I can't imagine it's that bad when you are blessed with a fast Internet connection.

**Comment by Michaelangel007** [comment]
I have AppleWin compiling and running with MSVC 2019 (Visual Studio Community 2019 Preview) 16.2.0 Preview 4.0.  I was able to import the AppleWinExpress2017 solution without issue. (I forget the exact migration options picked.)  We'll need to create 2019 solution and project files.

Compiling I ran into two minor issues. Here are the solutions:

# MSVC 2019 Compiling Instructions

1. Error message: `Cannot open include file: 'stdio.h'`

* View > Solution Explorer > Properties > Configuration Properties > General > Windows SDK Version > 10.0.17763.0

The Windows 8.1 SDK is no longer available. :-/

2. Error message: ` Cannot open include file: 'stddef.h'`

* Tools > Get Tools and Features... > Individual components > Compilers, build tools and runtimes > [x] Windows Universal CRT SDK

**Comment by sicklittlemonkey** [comment]
Ah, I don't know if you were alerted, but I actually had this problem
building AppleWin last week with 2017 and added the Windows Universal CRT
to the build instructions on GitHub.

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
I missed that alert Nick.  Thanks for updating `docs/compiling.txt` !

Did we want to rename that file to be an `.md` so that the marked up links work?

**Comment by tomcw** [comment]
In https://github.com/AppleWin/AppleWin/pull/442#issuecomment-513924759, Michael said:
>Go ahead and drop support for 2010 since I have MSVC 2019 installed now.

**Comment by tomcw** [comment]
For reference, VS2019 still includes the old (VS2015) v140_xp Platform Toolset.

**Comment by tomcw** [comment]
>Moving to anything after VS2008 means that Windows XP becomes the oldest theoretically supported platform that AppleWin will run on. (I say "theoretically supported", but I don't plan on actually testing on this OS.) I'll post this to the cea2 mailing list to gauge opinion, and then perhaps look to make the switch in a few months' time.

Posted "AppleWin - change to minimum Windows version" to cea2 ML [here](https://groups.google.com/d/msg/comp.emulators.apple2/Gs1IOxdc8HU/jwLSitQnAQAJ).
