### ISSUE TITLE
Support UniDOS Plus

### ISSUE THREAD

**Issue by phed001** [AppleWin/AppleWin#563]
UniDOS is a modified DOS 3.3 which can read/write the 3.5" diskette. I tried to select a UniDOS disk image (.2mg) in slot 7 and boot the virtual machine, but it does not boot up.

**Comment by tomcw** [comment]
Can you give me a link to a .2mg image?

**Comment by phed001** [comment]
I do not have a link to a .2mg image, but what you can try is this:
[ftp://ftp.apple.asimov.net/pub/apple_II/images/masters/3rd_party_dos/Unidos%203.3%20Plus%20Version%202.0.1.po](url)

**Comment by tomcw** [comment]
With the 800K .po image plugged in as a HDD image, then AppleWin 1.27.4 boots to an Applesoft prompt (but the HDD light remains lit). CATALOG results in an I/O ERROR, but you can CATALOG,S6,D1 successfully (with a DOS 3.3 floppy in the drive).

CiderPress recognises this as: "UNIDOS (400K DOS x2)".

**Comment by tomcw** [comment]
Perhaps a similar issue to #88?

NB. @SEGStriker said:
>We have already 3.5" FDD controller requests. If added, it will solve all issues.

**Comment by harrisonpaulg** [comment]
I have checked into my fork of Applewin, preliminary support for a Liron-type controller in slot 5. This gives us FOUR 3.5"+ drives, Two in slot 5 and two in slot 2(under newer prodos versions, anyway). It boots Unidos 3.3 Plus just fine. I'll be happy to commit it here when it's completely working (save states don't work reliably yet

**Comment by SEGStriker** [comment]
It will be good because current 3.5"/HDD controller in slot 7 doesn't do the job for me...

**Comment by phed001** [comment]
If that could combined with the HDD controler in slot 7, that would be great.

**Comment by harrisonpaulg** [comment]
You can boot Unidos off the HDD in slot 7, but it loses connection during its setup phase, which is why it doesn't run HELLO. You can reconnect it by poke 47007,7.

**Comment by tomcw** [comment]
This is now booting correctly with AppleWin 1.30.19.0:

![Unidos 3 3 Plus Version 2 0 1](https://github.com/user-attachments/assets/fb18ac50-4faf-4494-95e3-057df079f665)

From a dump of the HDD cmds, it was the SmartPort STATUS command that was causing the issue:
```
 :
slot-7, HDD-0(00): Cmd=80 ST: 00
slot-7, HDD-0(70): Cmd=01 RD: 00000110
 :
```
