### ISSUE TITLE
AppleWin built with VS2015 has clipped window on right and bottom

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#571]
Both running on a Win10-64 machine:

(built using VS2015 on Win10-64):
![aw-1 27 5 0-built-with-vs2015](https://user-images.githubusercontent.com/6696896/42962282-2651dacc-8b89-11e8-8aeb-2ebb18f69dfb.png)

1.27.5.0 release build, (built using VS2008 on Win7-64):
![aw-1 27 5 0-release](https://user-images.githubusercontent.com/6696896/42962295-2e9c44ec-8b89-11e8-9d4a-be558903255c.png)

**Comment by tomcw** [comment]
Same result when building on Win7-64 (VAIO laptop): VS2008 vs VS2015.

**Comment by rzumer** [comment]
Two pixels missing in both directions, also affects VS2017. Can you check the macros used in `Frame.cpp:GetWidthHeight()` to see if they differ in the two environments (2008/2015)?

**Comment by tomcw** [comment]
All done on the same Win7-64 machine.

### VS2017:
```
g_nViewportCX                       = 560
VIEWPORTX                           = 5 (const)
BUTTONCX                            = 45 (const)
GetSystemMetrics(SM_CXFRAME)        = 4 (unused)
GetSystemMetrics(SM_CXFIXEDFRAME)   = 3
GetSystemMetrics(SM_CXBORDER)       = 1 (unused)
GetSystemMetrics(SM_CXPADDEDBORDER) = 4
nWidth                              = 629
g_nViewportCY                       = 384
VIEWPORTY                           = 5 (const)
GetSystemMetrics(SM_CYFRAME)        = 4 (unused)
GetSystemMetrics(SM_CYFIXEDFRAME)   = 3
GetSystemMetrics(SM_CYBORDER)       = 1 (unused)
GetSystemMetrics(SM_CYCAPTION)      = 22
nHeight                             = 430
```
NB. ALT+PRINTSCRN, then paste into Paint reports: 629 x 430px
ie. Both nWidth & nHeight are the same as what Paint reports.

### VS2008:
```
g_nViewportCX                       = 560
VIEWPORTX                           = 5 (const)
BUTTONCX                            = 45 (const)
GetSystemMetrics(SM_CXFRAME)        = 8 (unused)
GetSystemMetrics(SM_CXFIXEDFRAME)   = 3
GetSystemMetrics(SM_CXBORDER)       = 1 (unused)
GetSystemMetrics(SM_CXPADDEDBORDER) = 0
nWidth                              = 621
g_nViewportCY                       = 384
VIEWPORTY                           = 5 (const)
GetSystemMetrics(SM_CYFRAME)        = 8 (unused)
GetSystemMetrics(SM_CYFIXEDFRAME)   = 3
GetSystemMetrics(SM_CYBORDER)       = 1 (unused)
GetSystemMetrics(SM_CYCAPTION)      = 22
nHeight                             = 422
```

NB. ALT+PRINTSCRN, then paste into Paint reports: 631 x 432px
ie. Both nWidth & nHeight are 10px less than what Paint reports! Why?

For VS2008, because GetSystemMetrics(SM_CXPADDEDBORDER) returns 0 instead of 4, then the nWidth & nHeight values are 8 (=4x2) pixels less.

Even with all this info, I still don't understand.
Here's a possible "fix" for `Frame.cpp:GetWidthHeight()`:
```
	if (GetSystemMetrics(SM_CXPADDEDBORDER))
	{
		nWidth  += GetSystemMetrics(SM_CXBORDER)*2;
		nHeight += GetSystemMetrics(SM_CYBORDER)*2;
	}
```

**Comment by tomcw** [comment]
For reference, here are the changes to `Frame.cpp:GetWidthHeight()`:
- July 2014: PR #210
- Oct 2017: ba6a38d32532d7c4aa1744eeb98c310922884ef9

**Comment by inexorabletash** [comment]
Searching indicates this is a common problem affecting other Windows developers on toolchain updates, caused by a different manifest being used.

**Comment by rzumer** [comment]
> Even with all this info, I still don't understand.
> Here's a possible "fix" for `Frame.cpp:GetWidthHeight()`:
> 
> ```
> 	if (GetSystemMetrics(SM_CXPADDEDBORDER))
> 	{
> 		nWidth  += GetSystemMetrics(SM_CXBORDER)*2;
> 		nHeight += GetSystemMetrics(SM_CYBORDER)*2;
> 	}
> ```

I think it would be best to just do a +2 to the width and height based on the MSVC version, since it is not clear to me that `SM_C[X/Y]BORDER` is an appropriate constant to use (unless you have a reference that explains your use of it). It would be nice to have a more elegant solution that is compatible across all versions, but as a first step an `#if _MSC_VER >= 1900 ... #else` block defining different resolutions has no cost and is a safe and minimal change. Just need to double-check the minimum version that needs the fix.

**Comment by tomcw** [comment]
From that stackoverflow link, I made the change:
- Minimum Required Version = 5.01

>Yes, just change the minimum subsystem version to pre-Vista value, like 5.01 (for Windows XP 32-bit). For some reason, 5.1 will yield the same result too; the resulting EXE would be the same.
>
>**When Win32 Subsystem Version is 6.0 or above, there is a behavior change regarding the window border size.** Though I am not aware of where Microsoft has documented about this.

Now with VS2017 I get the same values as VS2008:
```
g_nViewportCX                       = 560
VIEWPORTX                           = 5 (const)
BUTTONCX                            = 45 (const)
GetSystemMetrics(SM_CXFRAME)        = 8 (unused)
GetSystemMetrics(SM_CXFIXEDFRAME)   = 3
GetSystemMetrics(SM_CXBORDER)       = 1 (unused)
GetSystemMetrics(SM_CXPADDEDBORDER) = 0
nWidth                              = 621
g_nViewportCY                       = 384
VIEWPORTY                           = 5 (const)
GetSystemMetrics(SM_CYFRAME)        = 8 (unused)
GetSystemMetrics(SM_CYFIXEDFRAME)   = 3
GetSystemMetrics(SM_CYBORDER)       = 1 (unused)
GetSystemMetrics(SM_CYCAPTION)      = 22
nHeight                             = 422
```

And the window is now no longer clipped:
![aw-vs2017](https://user-images.githubusercontent.com/6696896/52526762-da056480-2cb5-11e9-8182-24e54ba44092.png)

**Comment by rzumer** [comment]
Very strange behavior, but SGTM.
