### ISSUE TITLE
FRQ - Swap HDD button 

### ISSUE THREAD

**Issue by TedThompson** [AppleWin/AppleWin#585]
A swap HDD button would be nice, tho I expect it to be low priority.  Toolbar would be great, but if real estate is too limited, one in the disk dialog tab would be great.

**Comment by TedThompson** [comment]
Changing HDD images doesn't cause a reboot.  Enabling/disabling the HDD controller does, but I can trade HDD images all day long like I was swapping floppies.  That's partly what inspired the idea. (v1.27.8.0)

**Comment by tomcw** [comment]
Would you really hot-swap HDDs on a real, power-on machine?
Surely you'd power down the Apple II, swap HDDs, then power it up.

**Comment by inexorabletash** [comment]
Virtual II has the "OmniDisk" concept, a generic smartport drive that allows mounting anything but 5.25" disks, but with similar hot-swapping affordances. 

In real life, SCSI Zip Drives are probably the comparable device.

**Comment by TedThompson** [comment]
Hmm if you're talking about write caching you may have a point. I dont know. But from limited testing I can change images and move images with no ill effects. Prodos seems to simply view a volume as a volume and its either there or not. 

For instance I can have a volume called /foo/ in s6d1 and one called /bar/ in s6d2 and set the prefix to /foo/ and it doesn't care if I swap using the button. BUT! What I don't know is if the software plays any tricks informing the emulation that the "disks" have moved.

**Comment by tomcw** [comment]
Work complete. Closing.

**Comment by tomcw** [comment]
NB. Release of AppleWin 1.28.0 containing this feature is [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.28.0.0).

**Comment by sicklittlemonkey** [comment]
Perhaps Ctrl-F5 could be a shortcut for this.
