### ISSUE TITLE
cosmetic: debugger branch targets < $1000 are missing the leading '0'

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#587]
0FFE: B0 FE BCS $FFE
1000: B0 FE BCS $1000

and now the disassembly is misaligned.

**Comment by tomcw** [comment]
Thanks Peter. One of us will take a look and fix this for the next release.

**Comment by tomcw** [comment]
FYI, fixed in 1.27.10 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.27.10.0/AppleWin1.27.10.0.zip).
