### ISSUE TITLE
Apple II original: default to not having a LC installed

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#590]
Captain Goodnight is playable instead of displaying the 'M' and rebooting.

**Comment by tomcw** [comment]
Hi Peter,
The emulated Apple II has a 16K LC in slot-0 (but not the auto-start ROM).
Are you expecting only a 48K Apple II (ie. without LC)?

**Comment by peterferrie** [comment]
Hi Tom,

Yes, I was expecting a 48kb Apple II.
I'll hack around it.  No problem.

**Comment by tomcw** [comment]
I think an option to have no LC (ie. slot-0 empty) would be good here.

NB. The current emulated Apple II is a bit of a hybrid:
- 64K (48K + 16K LC)
- non-autostart F8 ROM

Strictly speaking, with an Apple 16K LC installed, the F8 ROM should be switched to the auto-start version. But [apparently](http://www.applelogic.org/PeripheralCards.html) the Microsoft version didn't replace the F8 ROM, so theoretically that is what AppleWin could be emulating.

**Comment by peterferrie** [comment]
It would be nice to have such a configuration, certainly, but then it becomes a request and not the "bug" that I reported.

**Comment by tomcw** [comment]
Hi Peter,
There's a new 1.27.10 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.27.10.0/AppleWin1.27.10.0.zip), which now defaults the original Apple II to 48K (no LC).

I tested with Captain Goodnight, and get the 'M' (both "Hot Rod" crack and the "san inc" crack).

Can you check it?

**Comment by peterferrie** [comment]
Thanks Tom, it's working well for me.

**Comment by tomcw** [comment]
Great - thanks for confirming.
