### ISSUE TITLE
Refuses to read player disks for Ultima I and II (Resolved - User Error)

### ISSUE THREAD

**Issue by NotStanley4330** [AppleWin/AppleWin#594]
I have tried several times to play Ultima I and II via the emulator, but every time I get to the insert player disk prompt and I insert a copied player disk it it refuses to budge. I hit every key on the leyboard and still nothing. This is for the original Ultima I and Ultima II. Maybe its just me. Here is the disks I am using.

(The names for U2 are misleading, disk 1 is the master)
![trying to get help](https://user-images.githubusercontent.com/44741162/48335042-6a79cd80-e611-11e8-969c-d1455d65f761.JPG)

[Ultima I and II disks.zip](https://github.com/AppleWin/AppleWin/files/2571106/Ultima.I.and.II.disks.zip)

**Comment by tomcw** [comment]
Hi,
What version of AppleWin are you using?
Also, any reason why you are emulating an Apple II+? Why not an enhanced //e?

**Comment by tomcw** [comment]
For Ultima I:
- boot with "Ultima I (1981)(California Pacific Computer)(Disk 1 of 2).dsk"
- type '0' for  2 drives
- put your "i wanna die.dsk" into drive-2
- type '1' to generate a new character
- at the "INSERT A NEW PLAYER DISK DRIVE 2" message, press ESC
- wait a few seconds for the drive green LED to turn off

**Comment by tomcw** [comment]
For Ultima II:
- boot with "Ultima II - Revenge of The Enchantress (1983)(On-Line)(Disk 1 of 4).dsk"
- put your "i wanna die.dsk" into drive-2
- type 'C' to create a new character
- at the "(INSERT A BLANK PLAYER DISK) message, press ESC
- voila!

**Comment by NotStanley4330** [comment]
i am using the most current downalod. What I have been told is that if you
emulate via the enhanced iie, the galaxy map will not work. I hva esince
resolved the problem howvere, your feedback and other helped. Thanks so
much. You can mark the querey as resolved.

**Comment by sicklittlemonkey** [comment]
Yes, there is a bug in the original Ultima I if you use a 65C02. I added it
to this wiki back in 2015:
http://wiki.ultimacodex.com/wiki/Bugs#Ultima_I

Cheers,
Nick.

**Comment by tomcw** [comment]
Thanks Nick for this useful info.

(Removing "invalid" tag, since the question was valid.)

Closing issue.
