### ISSUE TITLE
Strange TEXT effect with Enhanced //e

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#595]
Start AppleWin in Enhanced //e mode, drives empty:
. F2 to start
. CTRL+RESET
. CALL -151 `RETURN`
. 3CTRL+P `RETURN`
. C00C:0 `RETURN` ; ie. 80COL off
. 300L `RETURN`

I get a strangle animating effect where it's flipping between TEXT pages 1 & 2.
(Hit PAUSE to pause and just show TEXT page 1)

![applewin_screenshot_000000000](https://user-images.githubusercontent.com/6696896/48447833-06801200-e795-11e8-8c1d-c016e6b3b59d.png)

NB. I see this effect with AppleWin 1.26.0.1 (first NTSC version) & 1.27.10.0 (latest NTSC version).

Does a real Enhanced //e show the same behaviour?
And what's going on? Is it a bug in the ROM? The only way to do anything else is via CTRL+RESET.

Edit by Michael: Tom, I added explicit `RETURN`s since it wasn't clear if they were needed or not.

**Comment by Michaelangel007** [comment]
Wow! Just verified this DOES happens on real hardware with my Enhanced  //e !

Looks like maybe a bug in the 80-col firmware???

How the hell did you ever find this one!? :-)

**Comment by tomcw** [comment]
@Michaelangel007 - thanks for confirming on real Enhanced //e h/w.
I'll post about this to the csa2 ML - hopefully someone (with more time than me) will look in more detail at this.

**Comment by tomcw** [comment]
Closing, since the emulator is correct here.
