### ISSUE TITLE
Delay in typing from keyboard before it shows up in emulator. (But maybe because of Wine for Mac)

### ISSUE THREAD

**Issue by RobertMVelasquez1996** [AppleWin/AppleWin#598]
I am not sure why there is a delay in pressing the key and it showing up in the emulator when running under Wine for Mac. Because there was no delay when using AppleWin 1.27.10.0, which is very strange. Maybe the code is executed slower in recent versions when in Wine. I do not know, but any help would be appreciated.

**Comment by RobertMVelasquez1996** [comment]
Update, I found out why the delay happened, it was because I was using max speed before this, and I suddenly changed to authentic speed.

**Comment by tomcw** [comment]
OK, labeling as "Wine".
FYI, there's no official AppleWin support under Wine, but it's useful to record info about behaviour under Wine, as a number of users are using AppleWin+Wine.

**Comment by RobertMVelasquez1996** [comment]
Thanks Tom, I wrote that because I thought using it on wine was the problem, but it really was because of the speed of the emulator. Sorry about that.
