### ISSUE TITLE
Remove support for save-state v1

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#603]
Consider deprecating support for v1 .aws.

Current regression testing is very light: just 2 .aws files.

Over time, AppleWin gets refactored which can impact the loading save-state code (for v1 .aws). Given the light testing, then my confidence in it continuing to work well is low.
NB. There haven't been any bug reports about v1 support - so is anyone actually using it? (It's really only got limited save-state support anyway.)

The last version to save v1 .aws was 1.25.0.4 (Apr'15).
The first version to save v2 was 1.26.0.6 (Oct'16).

If it were dropped at AppleWin 1.28, then for someone to load a v1 .aws with AppleWin 1.28+, then they'd just need to convert using AppleWin 1.27:
- start AppleWin 1.27 at the logo screen
- load the v1 .aws state file
- save a new v2 state file

**Comment by sicklittlemonkey** [comment]
I don't use this much, and when I do it's temporary. Might there be any
people who maintain a large library of save states?

Assuming there's a way to give a load state on the command line, another
switch to automate saving it to v2 and exiting would provide a tool to
batch automate conversions.

Barring that unlikely case, people have had plenty of time to migrate, so I
support the deprecation.

Cheers,
Nick.

**Comment by tomcw** [comment]
>Barring that unlikely case, people have had plenty of time to migrate, so I support the deprecation.

Thanks Nick. I agree that it's pretty unlikely people will have a library of v1 save states (if they did, then they'd have surely reported lots of bugs by now!). I've now set the milestone to 1.28.

btw. there is a way to load a save-state from the command line (-load-state \<savestate\>).
