### ISSUE TITLE
Holding down F9 to cycle through the video modes results in occasional flicker with garbage

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#611]
Spun off from #357, where Nick said:
>One thing I happened to notice though - holding down F9 cycles through the modes, but occasionally a line will flicker with garbage - for just one frame I guess.

**Comment by tomcw** [comment]
Probably related to this issue...

From the start-up logo: set video mode = Color (NTSC Monitor), and then 'Benchmark Emulator'. On switching to HGR, the top line will appear shifted right by a 7M pixel.

The shift occurs for this initial/top line, because in `updateVideoScannerAddress()`, this condition is false:
```
g_eVideoType == VT_COLOR_MONITOR_NTSC && GetColorBurst()
```

ie. `GetColorBurst()` is false, and so the line offset isn't adjusted by -2.

NB. If you do the benchmark after starting normal emulation, then it won't be the top line that's shifted, but the current video scanner's vpos.

**Comment by tomcw** [comment]
NB. CTRL+F9 (which currently does nothing) will also cause some flicker.
In `FrameWndProc()`, this seeming no-op still calls:
- `VideoReinitialize()`
  - calls: `updateVideoScannerAddress()` which resets `g_pVideoAddress` to start of current line
- `VideoRefreshScreen()`

I tried a quick hack so that `updateVideoScannerAddress()` is not called during an F9+modified combo, and this seems to fix this glitching.

**Comment by sicklittlemonkey** [comment]
Looks good, thanks!

I mean, of course it wasn't when holding down F9 that it bothered me.
Just occasionally when I hit F9 to change the colour mode sometimes I would
catch a bad frame out of the corner of me eye. ; - )
Cheers,
Nick.
