### ISSUE TITLE
enhanced IIe IRQ servicing crash when SP < 4

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#619]
The Mockingboard IRQ handler code does not check if S wraps around when pushing the STA $C006/RTI code.
Example with S=#$01

LDA #$40
PHA ;S=00
LDA #$C0
PHA ;S=FF
LDA #$06
ADC #$00
PHA ;S=FE
LDA #$8D
PHA ;S=FD
...

So the code was written to $1FE-FF and $100-01, where it can't run anymore.
Perhaps the solution would be to have
$Cx9D: STA $C006 ;in banked RAM
$CxA0: RTI ;in main memory

and then no stack tricks are needed.

**Comment by tomcw** [comment]
Hi Peter - I'm a bit confused by this issue. Is it really for AppleWin, or should it have been for another project?

**Comment by peterferrie** [comment]
Hi Tom, it's really AppleWin.  When Mockingboard is enabled in AppleWin, then whenever an interrupt occurs, the Mockingboard-specific code runs, beginning at $Cx7C.
That code ends with the sequence above which contains the bug.

**Comment by tomcw** [comment]
>whenever an interrupt occurs, the Mockingboard-specific code runs, beginning at $Cx7C.

Sorry, I still don't follow this, as the Mockingboard doesn't have any firmware/ROM code. The I/O space at $Cn00 (n=slot) is just for the 6522 registers at $Cn00-1F and $Cn80-8F. The rest is just floating-bus.

So when a Mockingboard IRQ fires, then the 6502 will vector to the address at $FFFE,FFFF; which will jump into $Cxxx internal ROM space (for //e) and eventually callback to the user handler (vector stored at $3FE,3FF).

If you can point me at some specific code that does what you describe then I'm happy to take a look.

**Comment by tomcw** [comment]
FYI, here's the code I wrote for my Cybernoid music disk:
https://github.com/tomcw/Cybernoid/blob/master/Common/MB-Macros.a

`MB_Init2` sets up the Mockingboard's 6522 timer, and sets the user vector ($3FE/F).
`MB_ISR` is the user interrupt service routine.

**Comment by peterferrie** [comment]
Okay, I see my mistake.  It's not specific to the Mockingboard at all.
It just happens to be code running from $C4xx.
It's the internal ROM code that has the bug for any interrupt
servicing for any device.

When the interrupt fires in the enhanced IIe configuration, the
handler via $3FE is run, and then control is returned to $C3F4, which
jumps into ROM, which does a STA $C007 / JMP $C47C.  Then the code
flows into the stack trickery that demonstrates the bug.

**Comment by tomcw** [comment]
Crikey! I have a documented long standing MouseCard interrupt-related bug in Contiki 1.3... I wonder if this ROM bug explains it? I will have to check.

btw. are you happy for me to close this issue as invalid? (Since it's an enhanced //e  ROM bug)

**Comment by peterferrie** [comment]
And now I apologise because I see that it's not AppleWin's fault.  The internal ROM itself has the bug.

**Comment by tomcw** [comment]
Thanks!

**Comment by peterferrie** [comment]
Yes, please mark it as invalid.
