### ISSUE TITLE
Crash when entering debugger from logo screen

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#622]
In this function: `int GetDisassemblyLine ( WORD nBaseAddress, DisasmLine_t & line_ )`

When `nTargetPointer` == 0xFFFF && memmain and memaux are not consecutive, this line crashes:
```
	nTargetValue = *(LPWORD)(mem+nTargetPointer);
```

Replace with this:
```
	nTargetValue = *(mem + nTargetPointer) | (*(mem + ((nTargetPointer + 1) & 0xffff)) << 8);
```

**Comment by Michaelangel007** [comment]
Hey Tom, do you have a repo. for this?
i.e. I'm wondering how you found it?

Kind of makes me curious what other mem addressing bugs are lurking ...

Cheers

**Comment by tomcw** [comment]
Interestingly I could only repro this when building with VS2017 (debug configuration, run under the VS debugger).

NB. I ordinarily build with VS2008, and regularly enter the AppleWin debugger from the logo screen, and never see this crash.

I guess the way to guarantee the repro is force memmain to be non-contiguous with memaux (eg. alloc a 64KiB block between the memmain & memaux allocations).
