### ISSUE TITLE
Unable to type certain characters when AltGr is required on an international keyboard

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#625]
Spun off from #583, reported by @tilleul:

---

Sorry if it's not related to the issue I have but to me it's very similar. Using v1.28...
Using a french-keyboard, I'm unable to print characters like @ # { } in APPLESOFT ! ... these require ALT GR on a french keyboard ....

What is strange is that: printing [ ] work although they also require ALT GR
What's even stranger is that printing § or £ does not work either although it does NOT require ALT GR !

I don't have the problem with v1.26. Tested on 2 computers, same result.

I have tried using the -no-hook-alt ... it doesn't change anything ...

**Comment by tomcw** [comment]
>1.27.5 works.
>1.27.6 doesn't ...

Probably this commit 6ed354714e2ecdc1f3beb7e3b00794925c1ded85 is the problem, ie. for #558.

For reference, Alt Gr on a French keyboard: https://en.wikipedia.org/wiki/AltGr_key#French
EG. `AltGr+0 -> @`

I'll spin this off into a new issue, and maybe enable this behaviour only on a cmd-line switch - no one was asking for this anyway, it was just something I spotted.

**Comment by tilleul** [comment]
Thanks. I don't know if it has any impact for you or not but my keyboard is in fact Belgian :)
So for me it's ALTGR+2 -> @ and ALTGR+3 -> # but I suppose you'll find a fix common to all keyboards ?

**Comment by tomcw** [comment]
There's a new AppleWin 1.28.3 build [here](https://github.com/AppleWin/AppleWin/releases/download/v1.28.3.0/AppleWin1.28.3.0.zip).

I've reverted the behaviour so it should be like 1.27.5.
Can you confirm this is working for you?

NB. There's a new command line switch to enable the 1.27.6 AltGr+\<key\> behaviour (-altgr-sends-wmchar). I guess only use this for US or UK keyboards?

**Comment by tilleul** [comment]
It's working ! Thanks !

**Comment by tomcw** [comment]
Great! Thanks for confirming.
