### ISSUE TITLE
DHGR in 1.28.x.0

### ISSUE THREAD

**Issue by landloafer** [AppleWin/AppleWin#633]
Graphic issues with RGB Monitor mode since 1.28.2.0. Particularly related to DHGR.

![reg](https://user-images.githubusercontent.com/39210397/55057086-1d1f6980-50a3-11e9-9f1d-14d171986c8d.PNG)
Renegate - Screen defects

![drag2](https://user-images.githubusercontent.com/39210397/55057182-65d72280-50a3-11e9-9bc8-e62cf2b9adc1.PNG)
Dragon Wars - Mixed B&W Graphic and Color Text

**Comment by tomcw** [comment]
Renegade is "accidentally" enabling RGB 160x192 color mode (see #621):

All video soft-switches (excluding $C054/5) from boot:

```
Renegade:

$C056: PC=$FB36, VideoMode=00000040
$C051: PC=$FB3C, VideoMode=00000040
$C00E: PC=$CD8B, VideoMode=00000040
$C058: PC=$FA72, VideoMode=00000040 (not video)
$C05A: PC=$FA75, VideoMode=00000040 (not video)
$C05D: PC=$C2B8, VideoMode=00000040 (not video)
$C05F: PC=$C2BB, VideoMode=00000040 ; DHGR off
$C001: PC=$CA9C, VideoMode=00000048
$C000: PC=$CAB7, VideoMode=00000040
$C00C: PC=$25B7, VideoMode=00000040
$C000: PC=$25BA, VideoMode=00000040
$C056: PC=$FB36, VideoMode=00000040
$C051: PC=$FB3C, VideoMode=00000040
$C001: PC=$217E, VideoMode=00000048
$C000: PC=$219C, VideoMode=00000040
$C000: PC=$1E0D, VideoMode=00000040
$C050: PC=$1D16, VideoMode=00000000
$C057: PC=$1D19, VideoMode=00000004
$C052: PC=$1D1C, VideoMode=00000004
$C05E: PC=$1D1F, VideoMode=00000006 ; DHGR on
$C00D: PC=$1D22, VideoMode=00000007
$C000: PC=$1D25, VideoMode=00000007
$C000: PC=$1C20, VideoMode=00000027
$C000: PC=$1C20, VideoMode=00000027
$C000: PC=$1C20, VideoMode=00000027
$C000: PC=$1C20, VideoMode=00000027
$C00C: PC=$F23C, VideoMode=00000026
$C05F: PC=$F23F, VideoMode=00000024 ; DHGR off
$C000: PC=$F150, VideoMode=00000024
$C050: PC=$F25B, VideoMode=00000024
$C057: PC=$F25E, VideoMode=00000024
$C00D: PC=$F261, VideoMode=00000025
$C05E: PC=$F267, VideoMode=00000007 ; DHGR on
```

Is this what happens on a real Apple ColorCard?
Or is AppleWin's logic wrong?

NB. If you play the *HGR* game and die; then returning to the title screen, it's now in 560x192 B&W mode.

**Comment by tomcw** [comment]
Dragon Wars is odd... it sets DHGR Mixed mode, but bit7's meaning is inverted!

**Comment by tomcw** [comment]
re. Dragon Wars:
Back in 2006, Andrew Harvey noted that Dragon Wars (DW) was inverting bit7, [here](https://groups.google.com/d/topic/comp.emulators.apple2/6teL_vemtVA/discussion).
Although I don't agree with him that Dazzle Draw (DD) is too.

EG. Discussion between Nick (@sicklittlemonkey) and Andrew H:

> I must say I'm really surprised about how much software seems to use
> this different high bit for text areas. Does anyone know why this is
> the case? What year did the US card that supported this come out? How
> well was it known - or anticipated?

It is very weird that [King's Quest] KQ and DW/DD use the bit in the opposite way. Possible
explanations are:

1) There were multiple RGB cards with non-standard use of this bit
2) The programmers coded blind it and never actually saw the end result

Use of this bit may also be due theoretically to a common library of text
rendering code that just happened to (re-)set the bit on all text rendered.

**Comment by tomcw** [comment]
And also this interesting posting from Holgar from 2000(!) [here](https://groups.google.com/d/msg/comp.emulators.apple2/l_yFH3HIyQU/niZvAZ2M_icJ).

```
Hello,

(Uh, this is my very first posting to a newsgroup. Please have patience with me and my poor English.)

If I understood this thread right, there seems to have been the question whether the high-bit in double-hiresmode influences the output of the screen, either monochrome, colour or something inbetween. To find proof of such a behaviour I've programmed my emulator in such a way that it tells me the value of the high-bit. Then I took a look at some well-known programmes whether they keep the high-bit on or off.
Here are my findings:

Text        = Characters (should typically use monochrome mode for higher resolution)
Graphic     = Pictures, shapes etc (should typically use coulor mode)
BW = black characters on white background
WB = white characters on black background

                        Text               Graphic
Airheart                off                off
Battlechess             off                off
California Games        off                off
Dragon Wars             BW on              off
                        WB off
Maniac Mansion          off                on
                                        every fourth column off(?)
Might&Magic 2           off                off
                                        every fourth column on(?)
Neuromancer             BW on              background on
                        WB off             shapes off
Pirates                 on                 on
Rampage                 on                 on
Testdrive               off                off
                                        three bright columns on the car-select page
                                        have the high-bit set. Reason unknown.
Transylvania            off                on

Conclusion:
As you can see from this table, there doesn't seem to be any evidence of a systematic usage of the high-bit as a switch between different resolutions. Even if it was built into the hardware it was definitely not used by the programmers. 'Neuromancer' and 'Dragon Wars' show that the setting of the high-bit was rather influenced by the character set, not the resolution.
In addition, 'Neuromancer', 'Maniac Mansion', 'Might&Magic 2' and especially 'Testdrive' show that programmers even mixed both high-bit on and high-bit off within the same picture but without any relation to the actual content of the picture, only perhaps as a result of some programming algorithm (e.g. shapes).

Cheers

Holger
```

**Comment by inexorabletash** [comment]
Interesting that in Andrew Harvey's csa2e thread there's no discussion of actual RGB cards - it seems everything is theoretical. Also, my reading of Holger Picker's post doesn't indicate whether any of those enumerated games set mixed mode. 

Do we know yet if anything but DW both sets mixed mode _and_ has the high bit consistently inverted?

I could easily chalk one example up to Andrew's _"The programmers coded blind it and never actually saw the end result"_ explanation - lack of easy access to both information and hardware, but just speculating.

**Comment by tomcw** [comment]
Yes, I think both are theoretical.
I will dig into the video soft-switch access, especially in DW, to see how the DHGR mode is being setup.

I can't believe that "_The programmers coded blind_" - this is Interplay in 1989! Although right at the top of this issue there's an example of Taito (also in 1989) seemingly oblivious to the RGB ColorCard and these DHGR video modes. OTOH, Broderbund (again in 1989) coded Prince of Persia so it didn't inadvertently trigger the wrong DHGR mode.

**Comment by tomcw** [comment]
DW video soft-switch accesses (excluding $C054/55):

```
$C056: PC=$FB36, VideoMode=00000040
$C051: PC=$FB3C, VideoMode=00000040
$C00E: PC=$CD8B, VideoMode=00000040
$C058: PC=$FA72, VideoMode=00000040 (not video)
$C05A: PC=$FA75, VideoMode=00000040 (not video)
$C05D: PC=$C2B8, VideoMode=00000040 (not video)
$C05F: PC=$C2BB, VideoMode=00000040
$C001: PC=$CA9C, VideoMode=00000048
$C000: PC=$CAB7, VideoMode=00000040
$C00C: PC=$25BF, VideoMode=00000040
$C000: PC=$25C2, VideoMode=00000040
$C056: PC=$FB36, VideoMode=00000040
$C051: PC=$FB3C, VideoMode=00000040
$C001: PC=$2189, VideoMode=00000048
$C000: PC=$21A7, VideoMode=00000040
$C000: PC=$200B, VideoMode=00000040
$C00C: PC=$2014, VideoMode=00000040
$C00E: PC=$2017, VideoMode=00000040
$C056: PC=$FB36, VideoMode=00000040
$C051: PC=$FB3C, VideoMode=00000040
$C057: PC=$C496, VideoMode=00000044
$C052: PC=$C49C, VideoMode=00000044
$C050: PC=$C49F, VideoMode=00000004
$C051: PC=$C4E7, VideoMode=00000044
$C056: PC=$C4EA, VideoMode=00000040

=====

$C052: PC=$B20E, VideoMode=00000040
$C057: PC=$B211, VideoMode=00000044
$C050: PC=$B214, VideoMode=00000004
$C05C: PC=$B217, VideoMode=00000004 (not video)
$C00C: PC=$B21A, VideoMode=00000004
$C05E: PC=$B21D, VideoMode=00000006
$C05F: PC=$B220, VideoMode=00000004
$C00D: PC=$B223, VideoMode=00000005
$C05E: PC=$B226, VideoMode=00000007
$C05F: PC=$B229, VideoMode=00000005
$C05E: PC=$B22C, VideoMode=00000007
$C001: PC=$B2EC, VideoMode=0000000F

===== Showing title screen

$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F
$C000: PC=$ED0E, VideoMode=00000007
$C001: PC=$ED73, VideoMode=0000000F

===== Loaded game

$C057: PC=$F990, VideoMode=0000000F
$C057: PC=$F990, VideoMode=0000000F
$C057: PC=$F990, VideoMode=0000000F
   :                           :

```

NB. The access to $C05C to set AN2 (which the Apple //e clears at boot in ROM). Is this significant?

**Comment by tomcw** [comment]
There's a comment in JACE's [code](https://github.com/badvision/jace/blob/master/src/main/java/jace/apple2e/VideoNTSC.java) which says:

>A lot of programs are clueless about RGB modes so it's good to default to normal color mode

Renegade is definitely clueless (but IMO not Dragon Wars). I'll list others here as I find them.

**Comment by tomcw** [comment]
Hi Brendan / @badvision:
Do you have a list of programs clueless about the RGB modes?
Since `RESET` will reset the card back to regular DHGR 140-pixel color mode, then it's only those games that switch between DHGR and HGR (like Renegade, above). NB. Prince of Persia is RGB-mode-aware.

**Comment by tomcw** [comment]
>NB. The access to $C05C to set AN2 (which the Apple //e clears at boot in ROM). Is this significant?

Dazzle Draw also accesses AN2 via $C05C: (but uses bit7 the opposite polarity to Dragon Wars)

```
$C056: PC=$FB36, VideoMode=00000040
$C051: PC=$FB3C, VideoMode=00000040
$C00E: PC=$CD8B, VideoMode=00000040
$C058: PC=$FA72, VideoMode=00000040 (not video)
$C05A: PC=$FA75, VideoMode=00000040 (not video)
$C05D: PC=$C2B8, VideoMode=00000040 (not video)
$C05F: PC=$C2BB, VideoMode=00000040
$C001: PC=$CA9C, VideoMode=00000048
$C000: PC=$CAB7, VideoMode=00000040
$C052: PC=$640F, VideoMode=00000040
$C057: PC=$6412, VideoMode=00000044
$C001: PC=$6415, VideoMode=0000004C
$C050: PC=$6418, VideoMode=0000000C
$C05C: PC=$641B, VideoMode=0000000C (not video)
$C00C: PC=$641E, VideoMode=0000000C
$C05E: PC=$6421, VideoMode=0000000E
$C05F: PC=$6424, VideoMode=0000000C
$C00D: PC=$6427, VideoMode=0000000D
$C05E: PC=$642A, VideoMode=0000000F
$C05F: PC=$642D, VideoMode=0000000D
$C05E: PC=$6430, VideoMode=0000000F

; Dazzle Draw's title screen
```

**Comment by tomcw** [comment]
@landloafer : there's a new version of AppleWin 1.28.5.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.28.5.0):
- Renegade works correctly now
- Dragon Wars: start AppleWin with the new -rgb-card-invert-bit7 switch

**Comment by landloafer** [comment]
Installed the new Applewin. It works so good. Look forward to improving the detection algorithm, so that no need a soft switch.

**Comment by landloafer** [comment]
Using the soft switch, lots of DHGR games tested still work fine e.g. Prince of Persia, Last Ninja, Renegate etc.
It is understandable that some other games like Sierra's Space Quest I, II etc are wrong.

**Comment by tomcw** [comment]
Yes, using the -rgb-card-invert-bit7 switch, only DHGR MIX mode will be wrong, eg. Dazzle Draw. All the other DHGR modes (140-color, 160-color, B&W) are unaffected.

The only reason to use the switch is for Dragon Wars; and so far, for nothing else.

**Comment by tomcw** [comment]
>Look forward to improving the detection algorithm, so that no need a switch.

Closing, as #642 covers this request.

**Comment by tomcw** [comment]
From #631, @nicolho has a Le Chat Mauve adaptor for his //c ("partly an Apple product too, with reference A2M4020F"), and I asked him:

If possible could you also check these .dsk images too:
- Dragon Wars ([here](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/rpg/dragon_wars/dragon_war_a.dsk)): just boot to the title screen. Is it colour or B&W?
- Renegade ([here](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/Renegade%20Disk%201%20of%202%20%281989%29%28Taito%29%28Clean%20crack%29.dsk)): how does the title screen look?

**Comment by tomcw** [comment]
His reply:
---

Hi Tom, so the results are the same than with AppleWin :

- Dragon Wars's title screen is always B&W (looks like it is, like most DGHR games, intended to be seen in color on a NTSC display, but obviously unaware of any "DHGR 140 color mode" activation)

- Renegade displays its DHGR title screen in color after a cold start, like this :

![Renegade on Chat Mauve](https://user-images.githubusercontent.com/25092789/56842136-e354a500-6892-11e9-87a9-b758f65ab7fa.jpg)

...but not always ! :confused: and unlike AppleWin, after one reboot or more, it always shows up in B&W...

Sorry for my delayed response, I was intrigued and tried many things, but I haven't found any definitive "software" answer about it. And in this regard, my findings on //c could not be relevant with what happens with a real ][e...

(To know precisely how to deal with AN3 switching sequences will probably require a better understanding of the video circuitry and its digital logic's intricacies . Since I intend to dig more into it for my own research, I'll possibly report about it afterwards)

**Comment by tomcw** [comment]
Thanks very much @nicolho.

>Dragon Wars's title screen is always B&W

Interesting... actually Dragon Wars is aware of these DHGR modes, as the code is very clearly setting DHGR MIX mode (see [above](https://github.com/AppleWin/AppleWin/issues/633#issuecomment-478166320)). But it has bit7 = zero, meaning B&W mode.

Of course you have an adaptor for your //c, so this could be different from the //e behaviour.

> Renegade displays its DHGR title screen in color after a cold start
> ...but not always ! :confused: and unlike AppleWin, after one reboot or more, it always shows up in B&W...

Again this could be a difference between the //c adaptor and the //e card.
Also perhaps the //c adaptor doesn't support the DHGR 160-pixel color mode? (In which case, it would probably default to DHGR 140-pixel color, as in your screenshot.)

I don't know a lot about the //c, so can you explain how the //c "Le chat Mauve" adaptor works?
