### ISSUE TITLE
Release Build with MSVC 2019 do not work

### ISSUE THREAD

**Issue by jvernet** [AppleWin/AppleWin#638]
I'm trying to build AppleWin with my new PC with MSCV2019. Release build do not work (screen full of garbage), 

The Debug build work.

I tried remove optimisation, no way...

**Comment by jvernet** [comment]
Sorry... Debug version seems to start with Apple IIe mode, but Release in Apple ][ or something like that. Defined Apple//e emullation and it work.

**Comment by tomcw** [comment]
Marking as invalid.
(I don't have VS2019 installed so can't validate any of this.)
