### ISSUE TITLE
Minor 6522 issues

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#652]
Cross-referencing with 6522 datasheet:

1. TIMER2's mode is defined by ACR.bit5 (not bit7-6 like TIMER1).
2. TIMER2 modes are one-shot and counting pulses on PB6.
3. TIMER2 only has a low-order latch (T2L-L), unlike TIMER1 which has both high & low-order latches.
4. TIMER1/2 decrements. "Upon reaching zero, an interrupt flag is set ..."
   - so an interrupt is generated for a transition from 0x0001 -> 0x0000 (currently AppleWin does it on underflow from 0x0000 -> 0xFFFF).
   - but the timing diagram for one-shot mode (fig. 15) shows the interrupt generated after N+1.5 cycles or midway through 0xFFFF. (The timing diagram for free-run mode (fig. 16) doesn't show T1 values.)
   - so AppleWin accounts for the extra cycle (due to underflow at 0x0000 -> 0xFFFF), but should only generate the IRQ on 0x0001 -> 0x0000?
5. What if TIMER1 is loaded with 0x0000. Is this equivalent to 0x10000?

**Comment by Archange427** [comment]
Just my 2cents, very poor technically but could be related to your fourth point:
On the ORIC scene, they usually set a delay minus -2 to define a precise timing for interrupt.
You can find a reference to this here: 
http://forum.defence-force.org/viewtopic.php?f=25&t=1816&start=15#p17131
Ok it's just forum's gossip, with not technical reference...
I remember reading something about that behavior at the time but I can not find where anymore. 
And it's been several days that I'm looking for precisely (funny to see you're wondering about this particular point). Without success...
I'm pretty sure it came from Twilighte (a real genius on the ORIC scene). 
But impossible to find the reference for the time being.

You should maybe have a look at the source code of ORICUTRON, the best emulator. 
Maybe the part on the VIA would bring you information on this point (if it implements this "-2" behavior).

**Comment by Archange427** [comment]
Another thought:
can you test the program I sent you that display a visual use of the CPU during a PT3 track on a real machine ? (I am unfortunately no longer able to do)
If the start of the display is NOT stable but move forward or backward, it will probably mean that the delay I used is not good and therefore that the timing used by AppleWin to generate the IRQ is not the right one.
If the display is stable, either everything is OK or so delay and IRQ timing are both not good but neutralize  themselves ;)

**Comment by tomcw** [comment]
>can you test the program I sent you that display a visual use of the CPU during a PT3 track on a real machine ?

Yes, I want to (and will) do this.

**Comment by tomcw** [comment]
OK, I have tested this TEST_INT_SYNC.zip (test.dsk) on a real Apple IIe (6502, 50Hz PAL). NB. Not enhanced, so not 65C02.

You can see (from the attached pictures) that the interrupt is not sync'ed with the display and the white "interrupt time" gradually moves (slowly) down the screen. The fact that it moves slowly means that it's very close the correct interval.
![DSC00044](https://user-images.githubusercontent.com/6696896/59536198-fc6cf000-8eea-11e9-9fe7-115db0978f2f.png)

NB. I tried this same test.dsk on AiPC (v0.1.42.1, PAL/50Hz mode), and it is stable on that emulator... therefore the emulator is wrong!

So I hex-edited test.dsk and changed the PAL interval to 0x4F36 (was 0x4F38), and it's now stable on my PAL Apple IIe. (NB. I first tried 0x4F37 and that was not stable either.)

**Comment by tomcw** [comment]
>But why -2 ?!

If you look at the 6522 datasheet (mine is Rockwell), Fig.18 "Timer 2 one-shot mode timing" shows that !IRQ OUTPUT goes low (active) after N+1.5 cycles. Perhaps this is rounded up to 2?

>If interrupt in AppleWin really occurs between $0000 and $FFFF... why -2 more ?!!

Well I think AppleWin is wrong, and the interrupt should occur from a $0001 -> $0000 transition.

And then there's this extra 0.5 cycle from the 6522 datasheet.

btw. I can only tested on a PAL Apple IIe, but since it looks like this is an artifact of the 6522, then it should be true for NTSC Apple IIe too. But it would be good to ask someone with an NTSC Apple II + Mockingboard to verify this.

**Comment by tomcw** [comment]
@Archange427 - new AppleWin 1.28.7 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.28.7.0): fixes this issue where the 6522 TIMER's period is actually N+2 cycles (and also fixes Sather's "Little Text Windows").

Precise 6522 frame intervals are:
- NTSC: $4284
- PAL: $4F36 (verified on a real Apple IIe)

**Comment by tomcw** [comment]
>5. What if TIMER1 is loaded with 0x0000. Is this equivalent to 0x10000?

No. I checked this on a real (original) //e, and the T1 interrupt occurs immediately. And T1C=0xFFFF takes the longest time to underflow. This was for both FRT and one-shot modes.

**Comment by tomcw** [comment]
Some more (minor) issues:

6. The TIMER1 (or TIMER2) latch in one-shot mode after counting down to zero will continue to reload from latch
EG. setting the latch to 0x8000, then TIMER1 (or TIMER2) COUNT will count down as follows:
   - 0x8000 -> 0x0000
   - 0x8000 -> 0x0000

Currently AppleWin has a bug where it'll reload with 0xFFFF.

NB. An extreme version of this to set the latch to a very small value like 0x0001.
Then the counter (low) will only read as 0x00 or 0x01.
And a side-effect of this, is that Mockingboard detection that relies on reading T1C_L (eg. Skyfox) will fail! This is compounded by point 7, where only a power-cycle can "fix" this (or manually writing to T1C_H with a non-zero value).

7. On reset, 6522 registers are not initialised

Currently AppleWin has a bug where (on reset) it'll set all 6522 regs to 0x00.
NB. IER (Reg-E) always reads with bit7=1.

Probably at power-on, all the 6522 regs have random values.

What happens on reset if the 6522 has been configured with IER.TIMER1=1 (or TIMER2=1) and period timer mode has been set? Probably the reset will disable this in the 6522, so that it's not generating spurious interrupts!

8. What values does TIMER1 (or TIMER2) counter return during the 2 cycles after underflow?

From above: "6522 TIMER's period is actually N+2 cycles", ie:

   - 0x4F36 (PAL 50Hz period)
   - 0x4F35
   -  :
   - 0x0000
   - 0xFFFF
   - 0xFFFE -> TIMER1 reload from latch & IRQ asserted
   - 0x4F36 (PAL 50Hz period)
   - 0x4F35
   -  :

What does the 6522 return for T1C_L for those 2 cycles?

**Comment by tomcw** [comment]
> 7. On reset, 6522 registers are not initialised

From the Rockwell R6522 datasheet, on page-2:

RESET (!RES) clear all internal registers (except T1 and T2 counters and latches, and the Shift Register (SR)). In the !RES condition, ... Also, the Timers (T1 and T2), SR and interrupt logic are disabled from operation.

**Comment by tomcw** [comment]
> 8. What values does TIMER1 (or TIMER2) counter return during the 2 cycles after underflow?

```
loop
	lda		nextT1L_C			; {5,4,3,2,1}
	ldy		#SY6522_TIMER1L_COUNTER
	sta		(MBBase),y
	lda		#$00
	ldy		#SY6522_TIMER1H_COUNTER
	sta		(MBBase),y			; (and clears IFR.T1)

mb0	lda		$c400+SY6522_TIMER1L_COUNTER	; (4cy) (and clears IFR.T1)
```

Results from real h/w (Phasor):

| Initial T1C | LDA $C404 (T1C_L) |
-- | --
0x0005 | 0x02
0x0004 | 0x01
0x0003 | 0x00
0x0002 | 0xFF
0x0001 | 0x01

So for the final result, T1C_L is reloaded with 0x01 before the read occurs.
0x0001 > 0x0000 > 0xFFFF > 0x0001... so a 3 cycle period.

This is easy to see from the monitor:
`* C404: 1 0`	; T1C_L=0x01, T1C_H=0x00 (T1C=0x0001)
`* C400.C47F`
The reads of C4n4 will show values of 0x01, 0x00 and 0xFF.

**Comment by tomcw** [comment]
Fixed in:
- 776a48fc0176c0c503cd8acaaa49f0a57f4f88c8 (support T1 latch in one-shot mode, ie. 6 above)
- 4e881634308139403283456b7ada381f9e471916 (not all 6522 regs are initialised on a RESET, ie. 7 above)
- ff29b055ce789ff09d0861fed9f4a66ebdc8cf76 (T1 underflow with small latch)
- 84a705d20d19d6147bf44f257f75c4662cc1b56b (small T1 latch, eg. T1L=0x0001 above)
