### ISSUE TITLE
PAGE1/2 select occurring 1 cycle early

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#656]
Now that #654 delays the GR/TEXT ($C050/C051) mode switch by 1 cycle, @Archange427 noticed that PAGE1/2 ($C054/55) is wrong:

AppleWin 1.28.7.0:
![test-line(AppleWin)](https://user-images.githubusercontent.com/6696896/59981827-2f0c9c00-9601-11e9-806d-d9595e963dcd.png)

Real Apple IIe (PAL):
![DSC00042](https://user-images.githubusercontent.com/6696896/59981828-3633aa00-9601-11e9-9fd9-be1451ab3296.png)

**Comment by tomcw** [comment]
Based on Sather's precise VBL sync (UTA2e, 3-26), I wrote 3 similar tests:

Each test does a "Sather precise VBL sync"; waits 17 (or 18 or 19) cycles, then:
- line-0: LDA C055, LDA C054 (= 8 cycles)
- delay 7*65-8 cycles = 447 cycles
- line-7: LDA C050, LDA C051 (= 8 cycles)
- delay 20280-(8+447+8) = 19817 cycles
TOTAL = 20280 cycles

### Test-1:
![AppleWin-branch-GH648-50Hz](https://user-images.githubusercontent.com/6696896/59981883-1a7cd380-9602-11e9-9d6d-563668899ee2.png)

![DSC00052](https://user-images.githubusercontent.com/6696896/59981884-1cdf2d80-9602-11e9-981d-8486b1637403.png)

### Test-2:
![AppleWin-branch-GH648-50Hz](https://user-images.githubusercontent.com/6696896/59981896-3b452900-9602-11e9-902d-51f37895cfbc.png)

![DSC00053](https://user-images.githubusercontent.com/6696896/59981902-4f892600-9602-11e9-8361-b3e83303bbc5.png)

### Test-3:
![AppleWin-branch-GH648-50Hz](https://user-images.githubusercontent.com/6696896/59981907-5adc5180-9602-11e9-9aeb-eca2c9376440.png)

![DSC00058](https://user-images.githubusercontent.com/6696896/59981911-6e87b800-9602-11e9-8d7f-23aa2e229d40.png)

**Comment by tomcw** [comment]
So it appears that there's no delay for the PAGE1/PAGE2 switch!

**Side-note:** Is this the same behaviour on an Apple II+? And what about DGR/TEXT80? (eg. Ansi Story) And LORES/HIRES?

----

btw. that glitch (on line-7) switching from GR back to TEXT is explained in Don Lancaster's "Enhancing your Apple II & IIe, Volume 2", on page 221 it says:

_"Glitches are far simpler to manage on the lIe. Just exit from text on a space and exit from LORES black, and all lIe glitches should be invisible."_

And also see Volume 1, page 244:

_"Usually, there is no problem in going from TEXT to HIRES, from HIRES to TEXT, from LORES to HIRES, or from HIRES to LORES. But you can get glitches on a TEXT to LORES or a LORES to TEXT transition. Here's the rule to stomp these glitches ..."_

**Comment by tomcw** [comment]
Actually credit goes to @Archange427 for suggesting that PAGE1/PAGE2 doesn't have the 1 cycle delay, and for all his test dsk images & code he sent me to try and get to the bottom of this weird behaviour. Thanks!

**Comment by Archange427** [comment]
Thank you Tom but you had to sort through all the emails I sent you filled with crazy ideas and unclear theories ;)
Very good job, as usual!

**Comment by sicklittlemonkey** [comment]
Wow, interesting stuff! Breaking new ground here Tom!

**Comment by tomcw** [comment]
Hi Nick - my suspicion about this extra cycle for switching between TEXT and LORES is something funky going on with 7M and 14M clocks (maybe?).
- LORES->TEXT: If you look at the images above for the LORES line, there are 3 cycles of 14M, and then the last one looks like 7M (ie. each pixel is 2x 14M pixels).
- TEXT->LORES: If you look at the [images here](https://github.com/AppleWin/AppleWin/issues/654#issuecomment-505158241),  the "*" is ~1.5 6502 cycles wide, and is TEXT80.

So maybe 1 **extra** cycle for 7M/14M change?

Anyway, I don't think emulation of this "glitch" is important, but clearly the timing of it is.

**Comment by tomcw** [comment]
Fixed in AppleWin 1.28.8.0 ([here](https://github.com/AppleWin/AppleWin/releases/tag/v1.28.8.0)).

**Comment by tomcw** [comment]
btw, I spoke to John Brooks last week, and he knew about this, and it was already implemented in his VidHD HDMI video card!

**Comment by sicklittlemonkey** [comment]
Interesting. That guy knows way too much. ; - )

**Comment by tomcw** [comment]
**Update:**
>There is no delay except TXTCLR, TXTSET, MIXEDCLR, MIXEDSET

@sosaria7 explains this here https://github.com/sosaria7/appleinpc/issues/9#issuecomment-509728336.

**Comment by tomcw** [comment]
This commit also fixes Deater's "Cycle-count Megademo" ([here](http://www.deater.net/weave/vmwprod/megademo/)), where the vertical GR grey line shouldn't be visible between GR & HGR split video.
