### ISSUE TITLE
WOZ: Wizardry III copy-protection check fails on T$22 (T34)

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#662]
### Summary:
After the boot disk's title screen, press a key, and it will seek/read some data, eventually seeking to T$22. It does a copy-protection check which fails and then sits in an infinite (convoluted) loop.

### Details:
- read D5AA96 detected - Vol:50 Trk:22 Sec:0C Chk:7E
- $8c90 ; read 256 sector headers (16 revolutions), ending with:
  - read D5AA96 detected - Vol:50 Trk:22 Sec:0B Chk:79
- $8d5c ; high-level copy-protection check

```
8d5c:	;
		; attempts: 4
	lda 8d7c	; target sector (=0x0D)
	jsr 8d1a	; do protection check (AppleWin result: A=0x0E)
	cmp #$10
	bcc 8d77	; branch if A < 0x10
	cmp #$1C
	bcs 8d77	; branch if A >= 0x1C
	;
	lda 8d7d	; target sector (=0x0F)
	jsr 8d1a	; do protection check (AppleWin result: A=0x1B)
	cmp #$26
	bcc 8d77	; branch if A < 0x26
	cmp #$36
	rts
8d77:		; err
	sec
	rts
```
- $8d1a ; low-level copy-protection check

```
8d1a:
	jsr 8cf9		; wait until target sector
	jsr 8d3d		; wait D5AAAD
					; 12 cycles (bpl-not taken, cmp, bne-not-taken, rts)
	ldy #0			; 2
8d22:	jsr 8d78	; 12 jsr/rts delay
		jsr 8d78	; 12
		jsr 8d78	; 12
		dey			; 2
		bne 8d22	; 3 (taken)
					; SUB-TOTAL  = 41
					; LOOP TOTAL = 41 * 256 - 1 = 10495 cycles (2624-1 bitcells / 328-1 8-bit nibbles)
	lda $c08e,x		; 4 ($c0ee = set read mode)
					; TOTAL = 14 + 10495 + 4(C0EE) + 4(C0EC) = 10517
					; NB. AppleWin cycleDelta between latch accesses = 10517 + 3 extra cycles = 10520
-		lda $c08c,x		; read latch
		bpl -
		iny
		cmp #$DE
		bne -
	tya
	rts				; A=Y=0x0E

8d78:	rts
```

But there aren't enough WOZ bits (bitcells) between D5AADD and DE!

- Just after D5AAAD:
  - Bit Offset: 0x0000BD35 (NB. Track's bit Count: 0x0000C722)
  - Extra Cycles: 3.000000
- Just after DE:
  - Bit Offset: 0x000000D9
  - Extra Cycles: 0.000000

C722 - BD35 + D9 = AC6 (2758) bitcells = 2B18 (11032) cycles

To pass copy-protection check, as a minimum need 16 nibbles:
- ie. 15x 10-bit sync FF's and DE
- = 15 * 40cy + 32cy = 632cy
- = remaining cycles after the 768x JSR/RTS wait loop
- 11032 - 632 = 10400cy =  max time for the 768x JSR/RTS wait loop
- but "time for 768x JSR/RTS wait loop" (10520) > 10400

**So there's not enough WOZ bits (bitcells) between D5AADD and DE!**

Another thing is what is this copy-protection check actually checking for?
- My guess is that this sector is written (when mastered) at a slower speed
- this results in longer bitscells
- so after the 6502 completes the 768xJSR/RTS wait loop, there will be more bitcells (and so more nibbles) left to read, and so satisfying this protection check.

But the WOZ2 image has optimalBitTimings=0x20 for this disk... so nothing special here.
If I force optimalBitTiming = 0x21:
- 1st check passes with Y=0x16 (need 0x10 <= Y < 0x1C)
- 2nd check fails  with Y=0x23 (need 0x26 <= Y < 0x36)

And why does this WOZ image work with MAME?

**Comment by tomcw** [comment]
@kerthunk: any ideas about this?
Could the disk have been imaged and not have set "optimal bit timing" correctly?
But then why does it work with MAME? (This implies there's an issue with my AppleWin implementation... which is most likely.)
Perhaps there are other images like Wizardry that I could try?

**Comment by kerthunk** [comment]
Hmmm, not sure off hand. I just made a .woz file of it and it boots fine under MAME, OpenEmulator, and microM8. But it appears to fail the protection check under Virtual ][. This is using an optimalBitTiming of 0x20.  I have attached the .woz images that I tested with.

This appears to be the protection sector. There are 2 of them on track $22. The sectors are malformed and it is possible that they are different sizes.
![Screen Shot 2019-07-09 at 3 55 30 PM](https://user-images.githubusercontent.com/713994/60928391-15ef2680-a262-11e9-8fe6-031555328e6f.png)

[wizardry3.zip](https://github.com/AppleWin/AppleWin/files/3375061/wizardry3.zip)

**Comment by tomcw** [comment]
Thanks John - I can see this zip has a slightly different .woz to the one I downloaded from the woz-a-day collection (eg. a slightly different number of bits in T$22). Anyway, I tried with AppleWin 1.29.0.0, and I still get the same non-working behaviour.

FTR, the copy-protection tests at T$22/S$0D and T$22/S$0F yield nibble count results of 0x0E and 0x1B respectively (so same as the woz-a-day image). I need results of 0x10 and 0x26 - see 6502 code at $8d5c above.

Since these .woz images work in those other 3 emulators, this strongly suggests that AppleWin has the problem, so I'll investigate further on the AppleWin side.

btw. that's a really nice nibble representation (showing sync/fake bits under each nibble).

**Comment by peterferrie** [comment]
At $8D2E, LDA $C08E,X is returning the wrong nibble (#$AD instead of #$FF, and that #$FF should be about to be dropped).
At $8D31, LDA $C08C,X is returning #$FF immediately instead of starting a new read.

MAME sees counts of 0x18 and 0x30.  I haven't checked others yet.

**Comment by tomcw** [comment]
Thanks for providing that data.

>At $8D2E, LDA $C08E,X is returning the wrong nibble (#$AD instead of #$FF, and that #$FF should be about to be dropped).

OK, I'm only updating the latch for $C0EC. So this #$AD is from the previous $C0EC latch read, ie. when it read D5AAAD. But, yes, strictly speaking all latch reads (ie. $C0En even addresses) should update the latch. I'll fix that.

>At $8D31, LDA $C08C,X is returning #$FF immediately instead of starting a new read.

Yes - AppleWin is probably wrong, as the prior $C0EE access reads the latch (and advances the logic state sequencer?), then this $C0EC should probably start a new read.

But now AppleWin will read 1 less nibble... which is worse :-/

Assuming that MAME just uses the _unmodified_ .woz image's T$22 data, then it would be interesting to know the (bit) position in the track buffer's bit-stream, at key points like: just after reading D5AAAD and just after reading DE.

**Comment by peterferrie** [comment]
According to the picture that John posted, those FFs are 10 bits long.
They'll hang around longer than the 8-bit ones.  That might account
for the difference.

**Comment by tomcw** [comment]
For .woz images, AppleWin operates at the bitstream level, so for this image each "bitcell" is 4us.

There's a big discrepancy between AppleWin and MAME, with respective results of 0x0E and 0x18. This difference (0x18-0x0E) = 10 x 10-bit FFs = 100 bitcells.

I'm wondering if AppleWin is (somehow) at the wrong point in the bitstream, eg. it could be too close to the DE nibble (whereas MAME could be starting further back).

From John's image the (malformed) sector is 0xF (4&4 encoding has sector = AFAF). This is for the 2nd sector protection check (the first being for sector 0xD). I'll check AppleWin's bitstream-to-nibble output matches John's image...

**Comment by tomcw** [comment]
OK, I've figured it out.

And @peterferrie you were right when you said the 10-bit FFs hang around longer than the 8-bit ones.

Sometimes the bit-stream is aligned so that you can read the same value from the latch twice, even with this longish 13-cycle loop:
```
-		lda $c08c,x	; 4: read latch
		bpl -		; 2 (branch not taken)
		iny		; 2
		cmp #$DE	; 2
		bne -		; 3 (branch taken)
```

AppleWin was holding the value in the latch, but only for the 1st zero bit - so only a maximum hold for 11 cycles... too short for this loop.

The copy-protection works by having a sector full of 10 bit sync FFs. Then:
1. waiting ~10500 cycles so that the head is close to the end of this sector of sync FFs.
    - a copy (_without_ the zero sync bits) would overshoot the end of the sector.
2. then using the zero sync bits to allow the code to count the same nibble twice.
    - a copy (_without_ the zero sync bits) wouldn't hold the data in the latch long enough for it to be counted twice.

**Comment by tomcw** [comment]
There's a new 1.29.1.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.1.0/AppleWin1.29.1.0.zip), which includes a fix for this.

**Comment by tomcw** [comment]
For a bit more info on my debugging with MAME, here's a patched Wizardry III boot image:

[Wizardry III - Side B(patched).zip](https://github.com/AppleWin/AppleWin/files/3464337/Wizardry.III.-.Side.B.patched.zip)

I patched the 17th and 7th 10-bit FF _from the end_ of T$22/S$0D, with these hex edits, changing a 10-bit FF to a 10-bit D5 in each case:
- offset 37a00: 3F CF -> 35 4F
- offset 37a14: 3F CF -> 35 4F
- patch the crc32 in the woz header (MAME erroneously doesn't accept 0x00000000 meaning ignore checksum)

Dumping sector at the patch point:
```
Offset:  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F 10 11 12 13 14 15 16 17
Nibble: D5 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF D5 FF FF FF FF FF DE AA EB
```

NB. The 1st D5 (offset 1 above) gets skipped by the ~10500 delay, so I didn't need this patch.

In MAME, set a BP at 8D39 (ie. the `CMP #$DE`) and after 10 breakpoints you'll see the 2nd D5 (offset 0x11 above) read twice from the latch, eg:

```
MAME:
Y-reg:  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F 10 11 12 13 14 15
latch: ff ff ff ff ff ff ff ff ff D5 D5 ff ff ff ff ff ff ff ff ff de
```

For reference the MAME commands are:
- mame64 apple2ee -w -debug -flop1 image.woz
- bp 8d39
- g = go
- s = step
- out = step-out of subroutine

From more info, see [here](https://docs.mamedev.org/debugger/index.html).

**Comment by tomcw** [comment]
Closing, as this was fixed a while ago.
