### ISSUE TITLE
Mounting .woz file blocks writing to .dsk images as well.

### ISSUE THREAD

**Issue by NRS-NewRisingSun** [AppleWin/AppleWin#664]
Thank-you so much for adding .woz support!

I understand that writing to .woz image is not supported yet, but strangely enough, when a .woz image is mounted, writing to .dsk format files becomes unreliable as well. I noticed that when I tried Ultima III, I could not write to the .DSK-format "Player" diskette I had, nor could I use the DOS 3.3 "COPYA" utility to copy the .woz-format player master diskette to a blank .dsk-format diskette ("unable to write"). Playing the game using a .NIB-format "Player" diskette works, so I don't think I am using the program incorrectly.

Using version 1.29.0.0.

**Comment by sicklittlemonkey** [comment]
I'm having a look around for now, since the code has changed a lot, but I can repro this.

Also, I just hit this assert doing COPYA from DSK in drive 2 to WOZ in drive 1:
```
void Disk2InterfaceCard::UpdateBitStreamPosition(FloppyDisk& floppy, const ULONG bitCellDelta)
{
	_ASSERT(floppy.m_bitCount);	// Should never happen - ReadTrack() will handle this

```

**Comment by tomcw** [comment]
COPYA works fine for me...

Here's what I've tried:
- Boot "DOS 3.3 System Master.woz"
- RUN COPYA
- Accept the defaults, eg. Original S6D1, Duplicate S6D2
- Click on Drive-2, and insert & create a new .dsk by typing a new image name, eg. blank1.dsk
  - NB. this create a new blank1.dsk file with 143360 bytes of all zeros
- Press any key to start the copy... and this completes successfully.

I tried with both "Disk Access Speed" = Authentic and Enhanced. Both complete successfully.

NB. Currently for .WOZ images, the only difference between Authentic and Enhanced is that Enhanced switches to Full Speed emulation when the drive is on. So the accuracy is the same, but it just completes much quicker.

I also tried DOS3.3's INIT command (woz in D1, blank dsk in D2), and again this works fine for me.
NB. There is a bug in DOS3.3 which can yield an I/O ERROR - see [this comment](https://github.com/AppleWin/AppleWin/issues/125#issuecomment-346340739).

Please tell me your steps to repro the COPYA issue.

**Comment by tomcw** [comment]
OK, I get the COPYA error "Unable to write" when I have:
- S6D1 = Ultima III size B.woz
- S6D2 = blank.dsk

**Comment by tomcw** [comment]
Right, the problem with COPYA "Unable to write" is because "Ultima III side B.woz" uses sectors with Volume=$02. The .dsk format implicitly uses Volume=$FE. AppleWin decodes (denibblizes) the sector and drops the Vol=$02. Then when it nibblizes the sector (eg. to verify the write) it uses Vol=$FE, and so hence the COPYA error.

To successfully copy this, you need to use a .nib. You can easily do this with AppleWin by just clicking on the drive-2 button, and type a non-existing .nib, eg. blank.nib. Now use this for the COPYA.

**Comment by NRS-NewRisingSun** [comment]
Okay, so it seems to be something specific to that particular disk, and nothing to do with blocking write access to .dsk images when a .woz file is loaded. I was not aware of the importance of the "Volume" field before, but now I am.

So I should be getting the same error when copying from .nib to .dsk, and the general rule then is that one should never copy from .nib or .woz to .dsk, but always at least to .nib.

**Comment by tomcw** [comment]
>So I should be getting the same error when copying from .nib to .dsk,

Yes.

>and the general rule then is that one should never copy from .nib or .woz to .dsk, but always at least to .nib.

I don't know if you can truly apply a rule, as maybe some "scenario" or save disks (for a completely different game) may just use regular volume fields... and so .dsk will be fine. But in terms of accuracy, .woz is much better than .nib, which is better than .dsk.

**Comment by tomcw** [comment]
Tagging as invalid.
@sicklittlemonkey: if you can let me know how you triggered that assert then we can spin off a new  issue for that. (Random thought: did you use the 'Disk Swap' button?)

**Comment by sicklittlemonkey** [comment]
Sorry Tom, I tried for a few minutes but couldn't reproduce.
I should have made detailed notes at the time.

**Comment by tomcw** [comment]
Hi Nick ....and no problem, I know all too well about demonstrating an issue and then never being able to repro it! But there's definitely an ASSERT path through the code. Grab the callstack if you ever see it again as that'll narrow it down.
