### ISSUE TITLE
Debugger: support showing video v,h and beam position

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#666]
This request from @Archange427:
>PS: btw you did not answer me about the display of v / h in the debugger corresponding to the "real" position of the beam, what do you think?

me:
> I think it's more relevant to have the g_nVideoClockVert and g_nVideoClockHorz values, and not the real position of the beam. But you are the one writing the precise beam-position code, so can you explain why you think the real beam position is better information?

@Archange427:
In regards the debug hack to display V/H (or g_nVideoClockVert and g_nVideoClockHorz), I think our difference in perspective comes from a very simple thing. And it is very natural:

- you think like the developer of AppleWin, so you need the information from g_nVideoClockVert and g_nVideoClockHorz in case of bug or issue to analyze and understand what is wrong with AppleWin!
  - And I fully understand this point of view. And this need.

- I think more like a "developer" who work with an Apple II. I need something that represents what goes on the screen. On a real Apple II, they are 4 "blanks" all around the display (top/right/bottom/left).

I need values that represents that. As I code things going on during the display but during vblank and hblank too, I need to know precisely and in the most direct way where is the beam at a given time of the code.
Much more important, I need values that represents something logical.
We saw lately that with g_nVideoClockHorz = $41 (aka h=0 line 0), the VBL was still detected as we got with test_line program.
From an Apple II point of view, it's nonsense! While that makes perfect sense for AppleWin (and his developer ;)

I have trouble making myself understood I think because my English is too limited for some concepts a bit abstract.

I do not know if you will integrate the hack to a version of AppleWin but why not a debugger parameter  to satisfy everyone?
Like "vh0" to disable the display of v/h. "vh1" to display directly g_nVideoClockVert and g_nVideoClockHorz. And "vh2" to display to "the corrected" versions for the beam position?
Or something like that...

**Comment by Michaelangel007** [comment]
Tom, 

I have no issues if we add a new debugger command `videoclock` that displays both `g_nVideoClockVert` and `g_nVideoClockHorz` in the console.

If this is needed in the right "info. panel" then that's probably not going to work as we don't have any room for it. :-/

![All debugger registers](http://michael.peopleofhonoronly.com/dev/applewin/debugger/debugger_all_registers.png)

**Comment by tomcw** [comment]
IMO, we should have it available on the info.panel… we could lose those rows for Z7 and W7.

**Comment by tomcw** [comment]
@Archange427 emailed with a new patch, saying:
>I also removed my calculation concerning "v". I align myself with Jim Sather (!) and consider that the VBL high is from line 268 to 311 (PAL). So I leave "g_nVideoClockVert" untouched...
>
>If you want "h" (from g_nVideoClockHorz) untouched too, just remove the other calculation.
I personally prefer to have values that represent 'right' and 'left' HBL.

**Comment by tomcw** [comment]
@Archange427 - is there a Jim Sather reference (in his book, eg. page number) for your adjustment of: `g_nVideoClockHorz - 13` ?

I'll add a new debugger command `videoinfo` to:
- display in decimal (default) of hex
- and also do the -13 adjustment (default) or not.

In terms of displaying the values:
- show in red if the video position is not visible, and green if it's visible
- reduce watches from 8 to 6, which allows 4 rows for video info

**Comment by Archange427** [comment]
@tomcw : page 3.15/3.16 (table 3.2) shows left HBLANK is 12 cycles. And Right HBLANK is 13 cycles.
As AppleWin counts all the 25 HBL cycles at the beginning of each line, I just subtracted 13 cycles!
As already said, it's just a personal preference...  
I like having this representation of one left and one right horizontal blanking.
So, after the -13 adjustment, for the 65 cycles of one line:
<00  L-HBL   11><12         VISIBLE PART               51><52  R-HBL  64>

Btw I love your idea of red/green color if visible or not

**Comment by tomcw** [comment]
I might switch the defaults:
- hex - which is consistent with all other displayed data
- <25 HBL><40 VISIBLE> - as this is what Sather mainly uses

This means you'll have to either manually change to your preference... or you could run a debugger script (eg. `run script.txt`) with these commands. I think it's be nice if AppleWin automatically ran a script if it existed, eg. if `applewin_debugger_autoexec.txt` existed, then automatically run it.

**Comment by Archange427** [comment]
If we refer to Sather's cycles counting system for one line, we would rather have <40 VISIBLE><25 HBL>.
But the interest of this debugging option is precisely to display the position of the beam.
Two consecutive HBL during the 65 cycles of one same line is for me a nonsense.
But I'm probably stubborn ;)

Passing a debug script as a command line argument would be nice too.

**Comment by tomcw** [comment]
I've added the cycle count (truncated to 32-bit) below the vert/horz values:

![AW](https://user-images.githubusercontent.com/6696896/66607158-841def00-ebab-11e9-9b04-cd9d6964a1bf.png)

**Comment by tomcw** [comment]
I've made this the default:
- <25 HBL><40 VISIBLE> - as this is what Sather mainly uses

Because from Sather...

Woz set up the H counter to wrap at 0 at the end of the active display, so the 40 active positions are displayed on H ctr cycles 25-64 (64 is the stretched wrap-to-0-cycle).

Active scanlines are displayed on V ctr rows 256 to 256+191 for 14MHz modes.

>Passing a debug script as a command line argument would be nice too.

I'll add support for this, so that you can configure the display to your preference.

**Comment by tomcw** [comment]
If you have a file "DebuggerAutoRun.txt" in the same folder as AppleWin.exe, then this will be auto-run when AppleWin first starts.

In this txt file you can specify your default configuration eg:
```
videoinfo dec
videoinfo apple
```

You can also set breakpoints, mini-memory addresses (m1, ma2), watches etc.

**Comment by Archange427** [comment]
Great!
To add an option to use this cycle counting system [<00 L-HBL 11><12 VISIBLE PART 51><52 R-HBL 64>], is this still negotiable? ;)

**Comment by tomcw** [comment]
Yes, it's the `videoinfo real` command. (I meant to write that in the example above)

**Comment by Archange427** [comment]
Perfect! 
And btw thank you for adding this feature!

**Comment by tomcw** [comment]
No problem - hopefully it'll help me track down some bugs! ;-)

**Comment by tomcw** [comment]
AppleWin 1.29.3.0 release [here ](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0)- please try it and confirm this all works for you.

**Comment by Archange427** [comment]
I just tested (using the DebuggerAutoRun.txt file). And it seems to work properly. 
A note nevertheless but I already know that you will find that I am painful ;) :
I find that the red color used (especially with this background) is difficult to read in fact.
This probably comes from my configuration (Gfx card, monitor and settings) but I prefer to report it. 
See what others think...
But this is only a detail and it does not detract from the function itself which is excellent!

**Comment by tomcw** [comment]
Thanks... and I agreed that 'red text on green' doesn't work very well (see screenshot above, 3 days ago). The orange works better (and the yellow even better). Let me know if you have a preference.

**Comment by Archange427** [comment]
Haha! 
Actually I already built my "own" version from source code using... Y8 in "Debugger_Color.cpp".
And I tried COLOR_CUSTOM_04 (orange) too... But I much prefer yellow!
I also tried other RED versions but none had a good rendering with this background I think.
Yellow is by far the most readable!

**Comment by Michaelangel007** [comment]
Looks good Tom.  Nice work!

**Comment by tomcw** [comment]
OK, I've switched from red to yellow.
