### ISSUE TITLE
No command line "]"

### ISSUE THREAD

**Issue by eranfeit** [AppleWin/AppleWin#667]
Hello,
The " ] " does not exist , so I cannot write apple commands.
When i click the color apple button which reboot the emulator i see the "apple //e" above and nothing happens. 

If i "load a disc" , the reboot apple button wors fine and runs the rom file (means the reboot works) , but no " ] "  if there is no disc.

Thank you
Eran

**Comment by eranfeit** [comment]
Hello,
The " ] " does not exist , so I cannot write apple command.
When i click the color apple button which reboot the emulator i see the "apple //e" above and nothing happens. 

If i "load a disc" , the reboot apple button wors fine and runs the rom file (means the reboot works) , but no " ] "  if there is no disc.

Thank you
Eran

**Comment by eranfeit** [comment]
![IMG_7983](https://user-images.githubusercontent.com/18570737/61582088-f348f180-ab2e-11e9-93c2-25f5dafb991a.jpg)

I attched a photo of the screen

**Comment by Archange427** [comment]
@eranfeit: it's the normal operation of an Apple IIe. No disk doesn't mean no drive. 
Hit CTRL+ F2 to stop the reading attempt and find the prompt!

**Comment by eranfeit** [comment]
Thank you :)
