### ISSUE TITLE
WOZ: Seafox fails to boot

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#668]
From #661: @retrogear said:
>seafox.woz from wozaday collection hangs at track 32

I got seafox.woz from [here](https://archive.org/details/wozaday_Seafox_Broderbund).
For me, it gets to T$0B (T11) and then reboots.

I tried the Wizardry III extended latch fix (#662) and also changing the `significantBitCells` from 50 to `floppy.m_bitCount`, but neither help.

**Comment by peterferrie** [comment]
Two things: one, the game is hostile to a IIe or IIc machine.  You'll need Anti-M to run it there.
Two: the game has a bug in it which has nothing to do with .woz or not.  The protection code has a section where it reads a sector full of address+value sets and then stores the values at the addresses.  The bug is that one of the written addresses is $2B, which is supposed to hold the slot for the drive.  When the game tries later to read from the disk, it's hitting $C0A8, instead of $C0sC.  AppleWin doesn't return the floating-bus for $C0A8 so the game polls infinitely instead of timing out and continuing the boot.

**Comment by retrogear** [comment]
Would the $C0A8 be hitting the SSC in slot 2?

**Comment by peterferrie** [comment]
Ah, that seems to be the answer.
To get the game to boot might require that the SSC is removable, in that case.  All that's necessary for the boot to succeed is that a nibble with bit 7 set is returned, which currently doesn't ever happen.

**Comment by sicklittlemonkey** [comment]
It's always been a pipe dream of mine to add disk image metadata for this kind of stuff.
Flagging machines & ROM versions or disk write protect is easily done.
But requiring that certain slots are empty or contain no RAM cards would be useful.
And then of course there's preferred mono/colour mode, input devices, cards etc.

**Comment by tomcw** [comment]
Confirmed the following in order to successfully boot:

1. Need to set machine = Apple //e (ie. not Enhanced //e)
    - NB, since this is a WOZ v1 image, then it doesn't contain an extended (v2) INFO chunk about 'Compatible Hardware'.

2. Need so disable SSC in slot-2
    - I quickly tested this by getting reg-8 ($C0A8) to return floating bus (`IO_Null()`) on a read.

**Comment by tomcw** [comment]
Classifying as a "bug", since currently there's no way to remove the SSC in AppleWin.

**Comment by tomcw** [comment]
With the release of 1.29.3 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0), I'm closing this.

You can use cmd-line switches to run this .woz image:

`applewin.exe -s2 empty -model apple2e`

**Comment by retrogear** [comment]
One side effect of your changes with 1.29.3.0 is Legacy of the Ancients woz
image now boots.
You fixed an issue before I had a chance to report it :)

**Comment by tomcw** [comment]
Great stuff!
So what was the issue with 'Legacy of the Ancients'? Did that need the SSC removed from slot-2 too? (But there were a few other subtle WOZ-related changes as well.)

**Comment by retrogear** [comment]
Nothing to do with the SSC. It wasn't reading the non-standard epilog bytes
on track 0 (not sure which sector) it got sector 0 but that's about it.
Track 0 has 4x4 encoding like Wasteland (so says qkumba)

**Comment by tomcw** [comment]
@retrogear - actually I'm seeing a hang in LOA. See #739.
