### ISSUE TITLE
WOZ: Space Quest I does not boot reliably

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#669]
From #661: @landloafer said:
>Space Quest I test image : does not boot reliably. It will sometimes hang at "Please wait..." not passing through to joystick calibration screen.
[https://ia802804.us.archive.org/view_archive.php?archive=/30/items/woz_format_test_images_2018_05/woz-format-test-images-2018-05.zip](https://ia802804.us.archive.org/view_archive.php?archive=/30/items/woz_format_test_images_2018_05/woz-format-test-images-2018-05.zip)

Easy to reproduce.
I tried the Wizardry III extended latch fix (#662), and this seems to fix it.

**Comment by tomcw** [comment]
Hi @landloafer,
There's a new 1.29.1.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.1.0/AppleWin1.29.1.0.zip) - let me know if this fixes it.

**Comment by landloafer** [comment]
Thanks @tomcw,

It's fixed.

**Comment by tomcw** [comment]
Thanks for confirming.
