### ISSUE TITLE
AppleWin 1.29.0.0 page 2 display

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#670]
When booting the Spy vs Spy collection (I and II on the same disk), the boot-up switches to page 2 to display the menu, but it doesn't appear (sometimes it flashes but then returns to page 1).  Only by entering the debugger, then doing a reset, will subsequent boots show the screen.

**Comment by tomcw** [comment]
With AppleWin 1.29.0.0, I've tried this one here which shows the menu on PAGE2:
[https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/misc/dk_collection/439b%20-%20Spy%20vs.%20Spy%20I%20and%20II.dsk](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/misc/dk_collection/439b%20-%20Spy%20vs.%20Spy%20I%20and%20II.dsk)

Disk Access Speed:
- Authentic: OK
- Enhanced: NG

1.28.7.0: fine for both disk speeds.
1.28.8.0: NG as above... so a regression at this version.

**Comment by tomcw** [comment]
btw, on that .dsk image, 'Spy vs Spy I' crashes at the title screen (6502: hlt opcode, 65C02 an infinite loop running undefined opcodes/brk on the stack). 'Spy vs Spy II' seems to work OK.

**Comment by tomcw** [comment]
OK, this one works for both I and II:
[https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/spy_vs_spy/Spy%20vs%20Spy%201%20%26%202.dsk](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/spy_vs_spy/Spy%20vs%20Spy%201%20%26%202.dsk)

**Comment by tomcw** [comment]
Hi Peter,
There's a new AppleWin 1.29.1.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.1.0/AppleWin1.29.1.0.zip) - let me know if this fixes it.
