### ISSUE TITLE
load state discards pending interrupt

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#677]
If an interrupt was pending at the time when the state was saved (e.g. save state when PLP is about to execute), the interrupt does not fire when the state is reloaded (i.e. after PLP runs).

**Comment by tomcw** [comment]
Thanks Peter. I'll look into fixing this shortly.

**Comment by tomcw** [comment]
Commit 94bbc5ec3dd404fe050bc51f1b9c56f34496e1b2 fixes this.

Regression test added here: https://github.com/AppleWin/AppleWin-Test/commit/7ea40c3975f217e5e8ab8a53a1faf939bfa4514f

**Comment by peterferrie** [comment]
Thanks Tom, the change looks good.

**Comment by tomcw** [comment]
Peter - I assume you don't need a fix for this in any great hurry. So it'll just get included in the next release (which may happen in ~a few weeks' time).

**Comment by peterferrie** [comment]
No rush.  I'll be careful about when I save.  Thanks.

**Comment by sicklittlemonkey** [comment]
Only the finest bug reports from Peter!
This could have been painful to track down.

**Comment by tomcw** [comment]
Yep - I really appreciated bugs for these edge-cases being raised.

It was fiddly to repro, so in the end I just wrote this code:
https://github.com/AppleWin/AppleWin-Test/blob/master/Projects/GH677-IRQ-Pending/irq-pending.a
... then created a save-state at the point that CLI was about to be executed.

**Comment by tomcw** [comment]
FYI, new AppleWin build 1.29.2 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.2.0/AppleWin1.29.2.0.zip).

**Comment by tomcw** [comment]
Closing as fixed.
