### ISSUE TITLE
"Scroll Scroll Scroll" demo has tearing during the display of the big scroll

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#680]
Email from Arnaud on 17/8/2019:

Today while making screenshots of my "old" releases, I noticed a weird issue. On "Scroll Scroll Scroll", there is tearing during the display of the big scroll (the one with GR characters).

I check again the original video I made at the time (with my real hardware), no problem of course (but I was pretty sure of that, otherwise I will not have released! ).
I also check with last version of AIPC, no issue either!

I thought of a regression, so I tested with another AppleWin version. But same issue with older version...
Note that version prior to 1.26 have display problems (but paradoxically, the tearing does not seem to be present).

I send you the DSK file if you want to test by yourself (it's exactly the original version, I did not change anything)...
Do you also see tearing or is it a problem with my PC ?!

**Comment by tomcw** [comment]
Hi Arnaud,

I've tested this and what I see is not tearing, but juddery / jerky scrolling.

I'm using AIPC 0.1.42.1 and AppleWin both in 60Hz mode. (When I use AIPC in 50Hz, then it's jerky too.)

Also I see similar jerky scrolling (only for AppleWin, not AIPC) for Ansi Story, at the "Turn the disk over!" horizontal scrolling message.

I have seen this jerky (AppleWin) behaviour before, but hadn't raised it as an issue. I guess that AIPC is synchronising with the PC monitor's vsync, so that this jerky (or tearing) visual isn't visible?

NB. My PC monitor's refresh rate is 60Hz.

**Comment by tomcw** [comment]
Hmm... I've just upgraded to AIPC 0.1.45.1 and I'm now seeing bad tearing for Scroll Scroll Scroll (big GR scroller) in 60Hz mode! (And 50Hz too.)

What version of AIPC are using using? Are you running in 50 or 60Hz?

**Comment by Archange427** [comment]
Hello Tom, Thanks for your tests.
So I did new tests myself.

AIPC v0.1.45.1 (50Hz and 60Hz) : no tearing but sometimes some jerky scrolling (not all the time... in fact rather infrequently). Not as smooth as on a real machine (in my memories) but OK.

AW v1.28.8.0 (50Hz and 60Hz) : a lot of tearing. 
The first line, sometimes the second line (and sometimes more) of the "big letters" are displayed "shifted" compared to the others.
I tried to take screenshots to show a little what I see. This is not systematic all the time and is not regular... 
Sometimes the beginning of the scroll is OK and the "tearing" appears later. Sometimes, it's the opposite!

screenshots:
![2019-08-25_003357](https://user-images.githubusercontent.com/10745357/63643429-379c5400-c6d0-11e9-8701-8b9a0c22d4ae.jpg)
![2019-08-25_003416](https://user-images.githubusercontent.com/10745357/63643430-39661780-c6d0-11e9-8bc7-5102eeb86b60.jpg)

**Comment by Archange427** [comment]
OK, I have just done other tests on a real machine this time... 
(yes! I have one almost complete ... for the moment the image comes from the composite output to my TV and not a monitor) but the display is OK. 
And as I thought, the scrolling is smooth, no tearing nor jerking...

**Comment by tomcw** [comment]
Definitely this is because AppleWin isn't synchronising with the PC monitor's display. So some sort of WaitForVerticalBlank() is required. And maybe GDI double-buffering is needed too.

**Comment by tomcw** [comment]
Note to self: I added support (currently turned off) in e09cd21 for WaitForVerticalBlank() between the StretchBlt() & the GdiFlush(). This now just gives me the sort of tearing that Arnaud is seeing.

NB. WaitForVerticalBlank() is a heavyweight operation that busy-waits until VBL, so CPU usage is very high. See [here](https://www.codeproject.com/articles/4436/tearing-free-drawing-with-gdi) where someone's solution is to check the scanline via a timer event every 2ms. He uses the scanline to decide where it's time to draw.

**Comment by Archange427** [comment]
> NB. WaitForVerticalBlank() is a heavyweight operation that busy-waits until VBL, so CPU usage is very high. See [here](https://www.codeproject.com/articles/4436/tearing-free-drawing-with-gdi) where someone's solution is to check the scanline via a timer event every 2ms. He uses the scanline to decide where it's time to draw.

Very interesting reading, thank you for sharing the link!
And crazy to see that 16 years later, WaitForVerticalBlank is still so crappy ;)

**Comment by tomcw** [comment]
To simply prevent the tearing (that you have posted screenshots for) I just need to do the Windows video update during the Apple II VBL.

But this still gives juddery (jerky) scrolling :-/

I quickly tried using that heavyweight WaitForVerticalBlank(), but that didn't make much difference. Probably because I'm not updating the Windows display *every* 60Hz. I need to do further investigation here.

btw. great to hear you have an Apple II again!! :-)

**Comment by tomcw** [comment]
NB. I committed 4ad09233998869169ce7e0886702a804aabf86cf to fix the tearing.

**Comment by sicklittlemonkey** [comment]
> NB. I committed 4ad0923 to fix the tearing.

It makes sense that this fixed the issue.

The screenshots (from Windows) couldn't show an issue fixed by
WaitForVerticalBlank(). ; - )

**Comment by tomcw** [comment]
Tearing fixed, so closing this issue.
Jerky scrolling issue moved to #722.
