### ISSUE TITLE
Star Fleet I does not recognize side B woz image

### ISSUE THREAD

**Issue by txgx42** [AppleWin/AppleWin#686]
See attached zip file... Boot from side A woz image, then insert the side B woz when prompted and press a key. The game will not recognize that the correct disk has been inserted. It will work if you insert the dsk version of side B (which was converted from the woz file using the Applesauce client software)

Tested with AppleWin 1.29.1.0. The side B woz image works in Virtual II and MAME, so the images appear to be good.

[Star Fleet I - The War Begins v2.1 (Interstel).zip](https://github.com/AppleWin/AppleWin/files/3585335/Star.Fleet.I.-.The.War.Begins.v2.1.Interstel.zip)

**Comment by tomcw** [comment]
Thanks for reporting this - I've confirmed it's not working (as you reported).

**Comment by tomcw** [comment]
It's not working because AppleWin currently forces .woz images to be write-protected.

**Comment by tomcw** [comment]
@txgx42 - there's a new AppleWin 1.29.10.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.10.0), with woz write support.
