### ISSUE TITLE
CPU Setting

### ISSUE THREAD

**Issue by exoscoriae** [AppleWin/AppleWin#689]
I was hoping it might be possible to set the CPU speed via command line, that way when running disk images through a launcher, this can be defined at launch versus having to send edits to the registry.

**Comment by tomcw** [comment]
What granularity and range of speeds would you be after?
EG. 0.5, 1, 2, 3, 4 MHz?

**Comment by exoscoriae** [comment]
Those would be great. That covers the speeds I was looking into as well a few more.

**Comment by sicklittlemonkey** [comment]
Wouldn't it be easier to just pass the desired speed to the command line
switch in MHz or Hz?

**Comment by tomcw** [comment]
A few quick notes whilst I remember...

AppleWin's UI for CPU freq (ie. the 'Custom Speed' slider) is actually a multiplier for the base MHz frequency. Depending whether NTSC or PAL is selected, this base freq is very slightly different.

In general I don't think this is too important, as really the user just wants ~1MHz (or ~2MHz, etc), so if ~1MHz maps to 1.023MHz/NTSC or 1.016MHz/PAL, the user won't care.

Anyway, I think it's better to support passing the base multiplier, not the precise frequency.

**Comment by sicklittlemonkey** [comment]
From memory it changes the machine speed by a few percent. It would be nice
to set it in Hz and do the conversion, but I suppose then the slider should
be fixed too.

**Comment by tomcw** [comment]
>Also, I was curious. I read that the Apple 1, Apple II, and Apple IIe all ran at 1mhz, with the IIe capable of boosting to around 1.9mhz in some circumstances. If they all ran at 1mhz, then what options change in AppleWin when you change the "model" setting? I see it changes two things in the registry.

They all run at 1MHz.
The 2 things that change in the Registry are: Apple II model and CPU type.

Changing the Apple II model implicitly means using a different ROM, and also different memory model + supporting different video modes.

Some titles/images will only run only newer models, as they depend on certain memory or video requirements. And there are a (tiny) few older games that only run on older models.

**Comment by tomcw** [comment]
>However it is important for my purposes that this also sets the model type.

Perhaps just use MAME's definitions:
-apple2
-apple2p
-apple2e
-apple2ee

**Comment by tomcw** [comment]
Added 2 new switches:
- -clock-multiplier \<value\>
  - where `value` is a [0.5...3.9] base-clock multiplier (ie. same as the Config UI's slider)
- -model \<apple2|apple2p|apple2e|apple2ee\>

**Comment by tomcw** [comment]
AppleWin 1.29.3.0 release [here ](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0)- please try it and confirm this all works for you.

**Comment by exoscoriae** [comment]
thank you, we will.

**Comment by exoscoriae** [comment]
We can confirm these command line options work. Thank you!
