### ISSUE TITLE
HDV Dismount

### ISSUE THREAD

**Issue by Harbinger-365** [AppleWin/AppleWin#692]
Hi guys,

From what Ive figured out if I mount a HDV file via command line in a bat Applewin activates slot 7 and mounts the image, all good. However Applewin remembers the mounted HDV and it is still mounted after I close Applewin and I boot up another game via command line meaning it takes priority over the new floppy Ive specified to use. 

Ive gotten around this by having my bat rename the HDV file on exit so that when I load another game via command line it wont find the previous HDV image, and ive added the "-s7 empty" flag to all my non HDV bats. 

Am I missing something that is much simpler? And if im not is there the possibility for you to add the option to dismount the HDV and disable s7 on exit of Applewin (or another solution with the same result)?

Thanks for hearing me out, and thanks for Applewin!

**Comment by tomcw** [comment]
>Am I missing something that is much simpler?

No, there's currently no elegant way to do this.

Sounds pretty simple though, eg. just a a new switch:
`-s7-on-exit empty`

This would unplug the HDD controller card when you exit AppleWin.

**Comment by Harbinger-365** [comment]
Glad I didnt miss something, solution sounds great!

**Comment by tomcw** [comment]
Implemented: `-s7-empty-on-exit`

**Comment by tomcw** [comment]
AppleWin 1.29.3.0 release [here ](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0)- please try it and confirm this all works for you.

**Comment by Harbinger-365** [comment]
Tested and it looks good on my end, thank you for implementing this.
