### ISSUE TITLE
Build release AppleWin with VS2019 using v141_xp platform toolset

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#693]
As discussed in #559, switch to building the release AppleWin using v140_xp platform toolset.

Since VS2019 still supports v140_xp, then I can't see any issue with going directly to VS2019 (from VS2008!).

**Comment by tomcw** [comment]
@Michaelangel007 , @sicklittlemonkey , @audetto:

I propose we drop VS2013, VS0215 & VS2017 supported sln/vcproj files... this'll mean that you (and others) will need to switch to VS2019. Has anyone got any issues with this?

NB. I still use VS2008 for AppleWin releases(!) and this issues exists to transition to VS2019 v140_xp for building the releases at some point.

**Comment by sicklittlemonkey** [comment]
Sounds good. I presume that means it will be ok to use modern C++ features.

**Comment by tomcw** [comment]
From @audetto [here](https://github.com/AppleWin/AppleWin/pull/861#issuecomment-723579139) too:
>Sure, happy to move.

**Comment by Michaelangel007** [comment]
I have VS2019 installed on my Threadrippers so dropping support for old MSVC is fine.

**Comment by tomcw** [comment]
Changed title from v140_xp to v141_xp.
v140 was the toolset in VS2015, whereas v141 was the toolset in VS2017.

### C++ language features

Only C++ language features implemented in Visual Studio 2012 are supported in apps that use the v110_xp platform toolset. Only C++ language features implemented in Visual Studio 2013 are supported in apps that use the v120_xp platform toolset. Only C++ language features implemented in Visual Studio 2015 are supported in apps that use the v140_xp platform toolset. Only C++ language features implemented in Visual Studio 2017 are supported in apps that use the v141_xp platform toolset. Visual Studio uses the corresponding compiler when it builds using the older platform toolsets. Use the most recent Windows XP platform toolset to take advantage of additional C++ language features implemented in that version of the compiler.

Ref: https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-160

**Comment by tomcw** [comment]
Toolset v141_xp will use SDK 7.1A.

NB.
- 7.1 - "It is the latest version that officially supports Windows XP target."
- 7.1A - "Introduces the "v110_xp" platform toolset"

Ref: https://en.wikipedia.org/wiki/Microsoft_Windows_SDK

**Comment by tomcw** [comment]
Released [AppleWin 1.30.0.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.0.0(try2)), so closing this.

**Comment by tomcw** [comment]
NB, VS2022 has dropped the optional install of v141_xp ([ref](https://learn.microsoft.com/en-us/cpp/porting/features-deprecated-in-visual-studio?view=msvc-170)).

**Comment by tomcw** [comment]
I installed VS2019 v16.11.32 on a new PC, and got compilation errors for the two v141_xp configurations:

```
1>c:\program files (x86)\microsoft sdks\windows\v7.1a\include\objbase.h(239): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
```

And:

```
3>c:\program files (x86)\microsoft sdks\windows\v7.1a\include\sapi.h(11878): error C2440: 'default argument': cannot convert from 'const wchar_t [1]' to 'BSTR'
3>c:\program files (x86)\microsoft sdks\windows\v7.1a\include\sapi.h(11878): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)
...
```

To fix them, I had to drop the `/permissive-` compilation switch.
https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170

**Comment by audetto** [comment]
I don't know how it works, but version `v7.1a` is very very old; maybe a newer version can be compiled with VS2019 without dropping warning levels.

**Comment by tomcw** [comment]
Yes - definitely time to move to something more modern!
