### ISSUE TITLE
-Woverflow and RAND_MAX

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#697]
gcc tells me that

Building CXX object source/CMakeFiles/appleii.dir/Disk.cpp.o
/home/andrea/projects/cvs/A2E/source/Disk.cpp: In member function ‘void Disk2InterfaceCard::DataLatchReadWOZ(WORD, WORD, UINT)’:

/home/andrea/projects/cvs/A2E/source/Disk.cpp:1129:37: warning: integer overflow in expression of type ‘int’ results in ‘2147483645’ [-Woverflow]

 1129 |              : (rand() < ((RAND_MAX * 3) / 10)) ? 1 : 0; // ~30% chance of a 1 bit (Ref: WOZ-2.0)

Should the code be refactored to avoid the potential issue?

**Comment by tomcw** [comment]
This is a bug in the GCC headers, since rand() returns values in the range [0...0x7FFF].

See here for confirmation of this bug:
https://gcc-renesas.com/question/rand-return-max-32767-rand_max-defined-0x7fffffff/

They suggest the following:
>Please use the -I compiler option to specify the location of the optlib include files, as in: -I”\rx-elf\rx-elf/rx-elf/optlibinc”

Can you do this?

NB. With VC++ (VS2008), in stdlib.h the define is correct:
```
#define RAND_MAX 0x7fff
```

**Comment by audetto** [comment]
I am not sure there is a right / wrong question here, rather portability.

https://en.cppreference.com/w/c/numeric/random/RAND_MAX
http://www.cplusplus.com/reference/cstdlib/RAND_MAX/

32767 is the minimum valid RAND_MAX, so there could be different implementations where the value is bigger.

The current code is ok given the VS implementation which is acceptable.
gcc warning is valid as well.

I will patch the code in the linux branch.

**Comment by tomcw** [comment]
>I will patch the code in the linux branch.

OK, so I will close this issue.
