### ISSUE TITLE
Rescue Raiders hangs with Phasor enabled

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#698]
AppleWin 1.29.2.0 (and tested RRv1.3 all the way back to 1.25.0.4).
Phasor enabled in slot-4

Boot RR (v1.3/NIB or v1.4/WOZ) and after the title screen, press 's' to start.
It will display the first 4-5 chars of "Emergency" and then just hang.

With a Phasor/Mockingboard installed, the game is trying to use the card's speech. NB. Mockingboard works fine.

From a quick code inspection it looks to be stuck in an infinite IRQ loop:
IRQ -> not de-asserting the IRQ, so RTI -> IRQ...

**Comment by peterferrie** [comment]
Not a bug in AppleWin.  It's a bug in the game code.  It's expecting a Speech interrupt to occur while reading the text, but which never gets raised.  The Mockingboard Sound I and II had the same issue.

**Comment by tomcw** [comment]
OK... but why does it work with the Mockingboard C?

> The Mockingboard Sound I and II had the same issue.
These used the old SC-01 speech chip, whereas the MB-C and Phasor use the SSI263 speech chip. RR is implemented to support SSI263, so (in theory!) speech with the Phasor should work.

**Comment by peterferrie** [comment]
Ah, in that case, maybe a bug in AppleWin after all.
When the speech interrupt is requested, the Phasor stops signaling the
interrupt source ($C48D & 2 is never 2, and/or $C40D & #$40 is never
#$40).

**Comment by tomcw** [comment]
NB. This looks like a general ISR for both speed & timer1 ints:
- $C48D & 2 is never 2 => speech interrupt
- $C40D & #$40 => timer1 interrupt

Could be the real Phasor h/w behaves differently to the MB-C.
I will check with real h/w.

**Comment by tomcw** [comment]
RRv1.3 with real Phasor:
- SW1=OPEN (MB mode): speech works
- SW1=CLOSED (Phasor mode): speech works

(I don't think SW1 affects the speech in any way, but may as well check)

**Comment by tomcw** [comment]
@peterferrie - this is now fixed in AppleWin 1.29.12.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.12.0).
