### ISSUE TITLE
debugger: display LC aux state

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#702]
next to the "80" state, perhaps put an 'x' between the "B2/W" and "R/W", and highlight the 'x' if $C009 was used?  Currently, there's no way to see if aux LC (and zp/stack) is active or not.

**Comment by tomcw** [comment]
Sounds like a good idea to expose this.
Are there any other things like this missing?

We could introduce more rows in this "video/MMU info" block (at the expense of losing a of the ZP watch).

**Comment by peterferrie** [comment]
> Sounds like a good idea to expose this.
> Are there any other things like this missing?

I think that's the only one that I'm really missing.

There's a weird case of having aux hires memory in an executable state
while displaying main video memory, but I've only ever seen it in one
title (Bank Street Writer) that I don't consider it worth pursuing.

> We could introduce more rows in this "video/MMU info" block (at the expense
> of losing a of the ZP watch).

I'd like to avoid that if possible.

**Comment by tomcw** [comment]
Yep, that sounds pretty weird!

It's interesting to hear that someone is using the ZP watches.
Do you use the other data watches to the right of the ZP watches? (eg.  `wa 42`) As I've just sacrificed 2 of these so that I can show the video-scanner & cycle count.

**Comment by tomcw** [comment]
How's this...?
- ALTZP=on: red 'x'
- ALTZP=off: blank space (ie. same as current display)

![AltZP](https://user-images.githubusercontent.com/6696896/67158144-27999d00-f32c-11e9-8ec9-7284a737bf3d.png)

**Comment by peterferrie** [comment]
Thanks, that works for me.

**Comment by tomcw** [comment]
New AppleWin 1.29.4.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.4.0) containing this update.

**Comment by peterferrie** [comment]
Confirmed good.  Thanks.
