### ISSUE TITLE
Castle Wolfenstein re-release (WOZ) freezes while writing to disk

### ISSUE THREAD

**Issue by boweden** [AppleWin/AppleWin#704]
Hi, 
The program appears to freeze up while running the re-release version of Castle Wolfenstein in WOZ format.  It's stuck at the "Writing Disk File - Do not reset" screen.  I don't know if it's a problem with the disk image or with the emulator.

This does not happen with the original release of Castle Wolfensetein, though (also WOZ format).

Thanks for any assistance.

[edit]
It's this game - https://archive.org/details/wozaday_Castle_Wolfenstein_061984

**Comment by tomcw** [comment]
Currently .woz writing isn't supported, which will explain this.

**Comment by boweden** [comment]
I see.  Thanks for clarifying.  I didn't encounter this error with the other older version of Castle Wolfenstein or even on another WOZ emulator (microm8) so I assumed it was an bug.  It all makes sense now :)

**Comment by peterferrie** [comment]
Write errors might be ignored in the older version, so the game would be playable but you could never advance in rank nor save/resume.

**Comment by tomcw** [comment]
@bowden - there's a new AppleWin 1.29.10.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.10.0), with woz write support.
