### ISSUE TITLE
The Crack of Doom (WOZ) "I/O error" when swapping to side B

### ISSUE THREAD

**Issue by boweden** [AppleWin/AppleWin#705]
Tested the The Crack of Doom (Addison-Wesley) WOZ image files from: https://archive.org/details/ApplesauceFlux4

I'm getting a "I/O error" in the beginning of the game when the game prompts to flip disk over.

Applewin version:  1.29.2.0

**Comment by tomcw** [comment]
It gives the 'I/O error' because AppleWin currently forces .woz images to be write-protected.

**Comment by tomcw** [comment]
@boweden - there's a new AppleWin 1.29.10.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.10.0), with woz write support.
