### ISSUE TITLE
Saving & loading apple ii Basic code

### ISSUE THREAD

**Issue by eranfeit** [AppleWin/AppleWin#706]
Hi,
How do I save and load my Basic code written in the emulator ?

Thank you
Eran

**Comment by sicklittlemonkey** [comment]
This is more of an Apple II usage question. There are many documents
and books on the topic.

For instance, if you're using a DOS disk:
https://www.apple.asimov.net/documentation/programming/basic/Apple%20II%20DOS%20%26%20Commands%20FAQ.txt

There are more general programming guides for new users. This one is
from back in the day:
https://apple2online.com/web_documents/apple_iie_programmer__s_manual.pdf

This one is only a few years old. There's a sample chapter on writing
and saving your BASIC programs:
https://macgui.com/newa2guide/

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
AppleWin doesn't (yet!) support tape I/O emulation.

Did you start AppleWin with or without a disk? (If without, then the safest
way for now is to save the emulator state by pressing F11.)

AppleWin comes with a disk image file called MASTER.DSK.
If you double-click this it will boot to the Applesoft BASIC prompt with
DOS connected.
Then you can used the commands in the documents mentioned previously: SAVE
FILE, LOAD FILE, RUN FILE, CATALOG etc.

Cheers,
Nick.

**Comment by tomcw** [comment]
Closing old issue.
