### ISSUE TITLE
SSC: Applewin + ADTpro

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#707]
FWIW:

ADTpro is no longer able to transfer files or even read a directory FROM Applewin's simulated Apple II & SuperSerialCard THROUGH Com0Com's virtual serial port TO the locally hosted ADTpro server.

It of course works fine in older Applewin versions. Is it useful? For demonstration purposes, absolutely.

**Comment by tomcw** [comment]
Thanks. I wasn't aware of com0com before, but it sounds useful for testing too.

Can you let me know the latest working AppleWin?

Ref: http://com0com.sourceforge.net/com0com/ReadMe.txt

**Comment by Keatah** [comment]
Last working AppleWin version - 1.27.1.0

1.27.2.0 and later seem to fail. I am able call up a remote directory via ADTpro client running on AppleWin one single time. That's it. Never had the issue on real hardware or older pre-1.27.1.0 versions.

**Comment by tomcw** [comment]
Confirmed this issue using:
- com0com-3.0.0.0-i386-and-x64-signed.zip
  - gives me COM2 and COM11 (NB. AppleWin 1.29.4.0 or less, only works with COM1-COM9)
- ADTPro-2.0.3

And I confirmed that 1.27.1.0 works (eg. directory, transfer a disk from Apple to host PC), using the default 115200-8-N-1 SSC settings.

**Comment by tomcw** [comment]
Here's the SSC transmit function:

```
2B64:AD 00 C0  LDA KEYBOARD
2B67:C9 9B     CMP #$9B    
2B69:F0 3A     BEQ $2BA5   
2B6B:AD A9 C0  LDA $C0A9
2B6E:29 50     AND #$50    ; DSR|TX_EMPTY
2B70:C9 10     CMP #$10    ; TX_EMPTY (Nb. DSR low = ready)
2B72:D0 F0     BNE $2B64   
2B74:68        PLA         
2B75:8D A8 C0  STA $C0A8
2B78:60        RTS         
```

**Comment by tomcw** [comment]
1.27.1.0 vs 1.27.2.0:

1.27.1.0 has:
- UpdateCommState()
  - dcb.fDtrControl = 0 (or = m_uDTR but only if m_bCfgSupportDTR is true via cmd-line)
  - dcb.fRtsControl = 0
- STATUS reg
  - DCD = 0
  - DSR = 0
  - TX_EMPTY always = 1

Even 1.27.1.0 fails to (S)END (eg. TEST.DSK), failing on block 44/280. Strangely it works in debug-stepping `g` mode!

**Comment by sicklittlemonkey** [comment]
Nice. Concurrency issues are rare in this kind of app! ; - )

**Comment by tomcw** [comment]
Added specific test for SSC using COM port: https://github.com/AppleWin/AppleWin-Test/commit/02a11dc04a780fe54d235f66d6e31322ee66ed38

**Comment by tomcw** [comment]
Hi Nick - yeah, I guess the work I did around 1.27.1 was mainly tested on the TCP path (for SSC) and not the COM path. Also the old 1.27.1 code having hardcoded SSC.STATUS.TX_EMPTY=1 didn't help either! (as it masked this race-condition).

Anyway, I've added a new SSC COM-specific test now (using com0com virtual port pair).

**Comment by tomcw** [comment]
ADTPro is good for soak testing: sending a 32MB HDD image over the SSC at 115200 baud takes ~40mins! :-)

**Comment by tomcw** [comment]
@Keatah: This is fixed in AppleWin 1.29.6.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.6.0) - can you confirm?

**Comment by Keatah** [comment]
Seems to be working fine so far. Ran a few transfers and directory requests.

**Comment by tomcw** [comment]
Thanks for confirming. I'll close this issue.
