### ISSUE TITLE
Old version of AppleWin

### ISSUE THREAD

**Issue by jvernet** [AppleWin/AppleWin#717]
Hi,

It's not an issue, but a question: wich is the LAST version of AppleWin to run on a 486DX66/Wfw3.11/W32s ?
I'm playing with my old 486, found an 1.10 version of Applewin, tried to see if I can find more recent version. I found an 1.3 version that is running, but the 1.4 version complain about missing 65c02.dll (wich I have, in the same directory).

I read somewhere that later special W32s versions was built...
What was the developpement tools in these w3.1 area ?

**Comment by tomcw** [comment]
I think these 1.30 and 1.40 versions are from a different fork to this AppleWin.

This AppleWin is derived from 1.10.4, which was 32-bit Windows 95 only.

**Comment by tomcw** [comment]
@jvernet: do you have any more questions, or can I close this?

**Comment by jvernet** [comment]
I'm playing with the 1.30 version it's fine, you can close. I would like to know wich was the developpement tools used for these build ? BorlandC ? Microsoft ?

**Comment by tomcw** [comment]
I don't know since it's someone else's work.
I'd guess MSVC, since when the original AppleWin source was made public it was with a Visual Studio project.

**Comment by jvernet** [comment]
Visual C++ 4 doesn't build, or so mucj missing project parameters, so it may be a later Visual Studio project, maybe. No build instructions in the 1.10 sources I can find, no VC project .

**Comment by tomcw** [comment]
>No build instructions in the 1.10 sources I can find, no VS project .

I had a quick look. In the BUILD folder there's a "makefile" called WIN32.CS. This is used in conjunction with the custom make-like application called C.EXE. Anyway, from WIN32.CS you can see that it used cl.exe (to build C/C++) and ml.exe (for .asm)... and cl.exe is the MSVC compiler.

**Comment by tomcw** [comment]
I'm going to close this old issue now. Please re-open if you have more questions.
