### ISSUE TITLE
6502 emulation should delay 1 opcode after CLI before taking interrupt

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#718]
When I was testing the 6522 TIMER1 (on a real original //e), I noticed a curious thing when enabling the 6502 interrupts with CLI: it takes an opcode before the interrupt is taken.

EG:

- SEI
  - Set T1C = 0x0001
  - Enable TIMER1 interrupt
  - ;; at this point TIMER1 has underflowed, and the TIMER1 interrupt is pending
  - LDY #0
- CLI
- INY
- ;; interrupt occurs here! (In the interrupt handler, Y=1)

I discussed with @Archange427 and he provide these links & info:

https://nesdev.com/6502_cpu.txt
>The processor will usually wait for the current instruction to
     complete before executing the interrupt sequence. To process the
     interrupt before the next instruction, the interrupt must occur
     before the last cycle of the current instruction.

http://visual6502.org/wiki/index.php?title=6502_Timing_of_Interrupt_Handling
>Instructions such as SEI and CLI affect the status register during the following instruction, due the the 6502 pipelining. Therefore the masking of the interrupt does not take place until the following instruction is already underway. However, RTI restores the status register early, and so the restored I mask bit already is in effect for the next instruction. 

See also links in the "resources" part.
-> interesting thing to report also from these pages, an INT can still raise right after a SEI!

IMO this is really just a "curiosity" for now. (I wonder if the CMOS 65C02 behaves the same?) I have no plans to support this in AppleWin, so will close as "won't fix".

**Comment by tomcw** [comment]
Here's some reference code:
```
6000: 78 A9 01 8D 04 C4 A9 00
6008: 8D 05 C4 A9 40 8D 0B C4
6010: A9 C0 8D 0E C4 A9 31 8D
6018: FE 03 A9 60 8D FF 03 A9
6020: C8 8D 29 60 A0 00 A2 00
6028: 58 C8 D0 FD E8 D0 FA 00
6030: 60 A9 40 8D 0D C4 8D 0E
6038: C4 A9 00 8D 29 60 A5 45
6040: 40
```

**Comment by Archange427** [comment]
I think this issue is more general than with CLI only. 
Because the rule stated above ( from https://nesdev.com/6502_cpu.txt ) potentially applies to each opcode.
How does AppleWin currently behave when an interruption occurs? 
How many cycles are systematically counted?
Could be related with #711 and #699

**Comment by tomcw** [comment]
>I think this issue is more general than with CLI only.

SEI as well. Both are 2 cycles, and due to the pipelining of the 6502, then on the last cycle of any opcode, the next opcode is fetched. This is why CLI delays by 1 opcode.

On the other hand, RTI is 6 cycles, so the pop `status` occurs earlier than the last cycle (because pop `status` occurs before pop `return address`). Therefore any pending interrupt will occur immediately after RTI (assuming that pop `status` enables interrupts).

>How does AppleWin currently behave when an interruption occurs?

It does the following emulation loop:
- execute one opcode
- check interrupt sources (6522 Timer, Speech, Serial Card Rx/Tx, Mouse)
- if IRQ is asserted then take interrupt

You can see the emulation loop [here](https://github.com/AppleWin/AppleWin/blob/8aff6addff08d211632f6d4a12c05e4327323da9/source/CPU/cpu65C02.h#L324).

And the `IRQ()` function, [here](https://github.com/AppleWin/AppleWin/blob/8aff6addff08d211632f6d4a12c05e4327323da9/source/CPU.cpp#L406) - where it takes 7 cycles.

**Comment by Archange427** [comment]
So if I understand correctly, when an interrupt occurs during - let's say - a series of NOP and when the INT code begins (I mean the one defined in $FFFE/$FFFF)

- with a real APPLE II, we had already passed: 
2 (or 3) cycles => finishing the current NOP + next one (3) or finishing only the current (2)  
+ 7 cycles (6502 / IRQ internal fct)
= 9 (or 10) cycles  

- with APPLEWIN:
7 cycles (IRQ() function)
= 7 cycles "only"

AppleWin does not deal with the opcode during which the interrupt occurred?

**Comment by tomcw** [comment]
AppleWin does deal with opcode during which the INT occurred, eg:
- NOP => INT occurs on 1st or 2nd cycle
- `CheckInterruptSources()` asserts IRQ
- IRQ, so:
  - 1st cycle of NOP: 2+7 = 9 cycles since INT occurred.
  - 2nd cycle of NOP: 1+7 = 8 cycles since INT occurred.

But what you are saying is that if the INT occurs on the NOP's 2nd cycle, then the **next** NOP opcode will already be fetched (due to 6502 pipelining), so then there's an extra 2 cycles before the interrupt occurs, so: 1+2+7 = 10 cycles.

I think you are right.

**Comment by Archange427** [comment]
Yes! That's why I said that the CLI issue with AppleWin is, in fact, a more general issue.

And now, we find where one cycle is lost by AppleWin with MAD EFFECT 1and 2.
My code assumes that we have **at least** 2 + 7 cycles.
But in some cases with AppleWin, we have only 8 cycles at the beginning of the INT function...

**Comment by tomcw** [comment]
So in theory, this pseudo-code will take 1+6+7=14 cycles before the interrupt routine starts executing?
```
    CLI
    6522.ACR = 0    ; one-shot mode
    6522.IER = #$C0 ; enable Timer1 IRQ
    T1L=#$0001      ; set Timer1 Latch & Count
    NOP             ; 2 cycles, and INT occurs on last cycle
    ORA ($00,X)     ; 6 cycles
```

But with AppleWin, it'll just take 1+7=8 cycles.

Your interrupt handler then compensates for this with:
```
    SEC                                                             ; 2
    LDA IntL                                                        ; 3
    SBC $C404           ; get T1 lower value (counter never stop)   ; 4 
```

But since the counter never stops then why does it matter that AppleWin took less cycles before the INT occurred? Perhaps because your next instruction is:
```
    SBC #17             ; = [24-7] => get final value from 0-7      ; 2
```
And if AppleWin takes too few cycles, then this SBC will go negative!

**Comment by Archange427** [comment]
Yes... and crash occurs because the result of the SBC will be later the BVC value !
and if the value is not in the expected range.... boom! The code ends anywhere...

**Comment by tomcw** [comment]
Adding this, as some interesting analysis done by blargg:

>[blargg, Fri Jun 18, 2010] I've discovered that a taken non-page-crossing branch ignores IRQ/NMI during its last clock, so that next instruction executes before the IRQ. Other instructions would execute the NMI before the next instruction in this case. This doesn't occur for non-taken branch, or one that crosses a page. It also doesn't occur for JMP.

http://forums.nesdev.com/viewtopic.php?t=6510
