### ISSUE TITLE
How would you use OpenGL?

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#721]
If one wanted to render the A2 screen with calls to OpenGL, how would you structure it?

I know how to do triangles, textures and perspective, but I am not sure how I would approach this: why?

Basically we are drawing pixel by pixel, not like big objects like triangles which might involves transformation and maths calculations. How do I leverage the power of OpenGL?

1) text mode and low res: textures? one per character?
2) hi and double hi res: pixels? very small lines?

The way I draw the screen in QApple is very poor (uses QPixmap and QPainter). I thought I should do low level memcpy, but even better, use the GPU: just no idea where to start from.

**Comment by Michaelangel007** [comment]
One way would be to use a single full-screen quad using a dynamic texture that is uploaded every frame.

Also check out what OpenEmulator is doing, specifically [Video Rendering](https://github.com/openemulator/openemulator#video-rendering)

**Comment by Michaelangel007** [comment]
Another way would be to use several textures since screen updates tend to be minor and then composite them in layers based on the Video Scanner and what mode is set for each byte. e.g. Your emulator **should** be able to handle video modes switching **mid-scanline**

* Text40 Page1
* Text40 Page2
* Text80 Page1
* Text80 Page2
* HGR Page 1
* HGR Page 2
* DHGR Page 1
* DHGR Page 2

**Comment by audetto** [comment]
In the linux build targeting OpenGL ES 2 I settled for a GL texture which is updated from the AW memory buffer and displayed using relative open gl functions once per frame.

A more advanced usage could be to implement the different video modes as shaders, but I have not tried it.

**Comment by sicklittlemonkey** [comment]
I notice this issue didn't refer to Zellyn's WebGL (which is apparently
"OpenGL ES 2") port of the OpenEmulator shader:
https://zellyn.github.io/apple2shader/

This guy also had a crack:
https://www.shadertoy.com/view/llyGzR

**Comment by Michaelangel007** [comment]
Thanks for the links Nick!  Much appreciated.
