### ISSUE TITLE
6502 interrupt should delay 1 opcode when interrupt occurs on last cycle of opcode

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#724]
Spun off from #718.

Due to 6502 pipelining, on the last cycle of any opcode (other than completing the opcode), _additionally_ either:
- the next opcode will be decoded (having already been pre-fetched), **or**
- if IRQ is _previously_ asserted then the interrupt will be taken

So if IRQ is asserted on the last cycle, then the next opcode decode is is already happening, so the interrupt will be taken after the next opcode completes.

**Comment by Archange427** [comment]
Issues #699 and #711 are probably related to this one (at least partially).

**Comment by tomcw** [comment]
Closing as fixed in AppleWin 1.29.6.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.6.0).
