### ISSUE TITLE
More than two disk drives would be awesome

### ISSUE THREAD

**Issue by vromtramchick** [AppleWin/AppleWin#726]
Hi!

I love playing Wasteland on your emulator.  

Back in the day, I had 4 FDDs hooked up to my Apple IIe and would play Wasteland.  It would be awesome if you added the option to have more than 2 FDDs.

Thanks.

**Comment by tomcw** [comment]
It looks like Wasteland has 4 disks.
asimov link: https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/rpg/wasteland/
But perhaps there are extra disk(s) for saving progress etc?

If I provided a command line way to put a 2nd DiskII controller in slot-5, and then (again from the command line) insert disks into slot-5 drive 1&2; would that work for you?

NB. You would not be able to remove or change the disks in slot-5 drive 1&2. From AppleWin's GUI you'd only be able to manipulate the disks in slot-6 drive 1&2.

Adding a configuration GUI to support drives in a slot-5 DiskII card would be more work.

**Comment by vromtramchick** [comment]
I can't believe you responded so quickly.  I can't even believe you
responded at all!  I appreciate the prompt response, but I don't want you
to do any extra work.  At some point more than two drives would be great,
but please, I don't want you to put in extra effort.

Wasteland was the best game ever.  Being a fan of The Terminator (watched
it so much the tape in the VHS cassette snapped), Wasteland allowed you to
be exist in an apocalyptic world where the machines had taken over.  There
had been games like it, but none were as in depth or complicated.  Plus,
their anti-piracy technique was brilliant.  They used cutscenes.  Now,
cutscenes couldn't be visually presented, I don't think the concept of a
cutscene even existed at the time, but that's what they did - low tech.
They included a collection of paragraphs which you were instructed to read
as you progressed through the game.  Sure you could just read all the
paragraphs, but there were more fake paragraphs than paragraphs which
pertained to the game!  Plus if you didn't have the book of paragraphs, you
couldn't play the game.  You would miss out on too much information.

Wasteland's 4 disks were confusing at first because you didn't use them
like in a normal game.  First, you had make copies of all four.  You would
need the disk one master to boot the game (just as you are required to do
in your emulator), but you would play the game on the four copies you made,
swapping them out as your progressed through the different towns and
facilities.  When I was 14, I purchased my own apple IIe, and one summer, I
took the 2 drives off my dad's computer and attached them to mine, dropping
the second floppy drive card into, I believe, slot 7.  The game was
designed to be played this way!  When it prompted for a different disk, you
would direct it to the other floppy controller by hitting ctrl+s, and then
hitting 1 or 2 for the drive.  I had all four disks active at one time.
HDDs were only then being considered for home use, with the Apple IIGS just
released.  But there I was, running the game as if it were on a hard
drive.  It was quite the experience.

Then came another realization.  If I completed all the tasks on disk 3, I
could make another copy of disk 3 and go back and do it all again!  Having
characters who were now stronger, better equipped didn't reduce the
experience, it was still challenging and fun.

They did try for many years to make Wasteland 2, but the beauty and
ingenuity of the original wasn't there.  Fallout is considered to be the
"spiritual successor" to Wasteland, and references Wasteland (Fallout 2 has
more) but no game in my mind has ever met up to what you could do with
Wasteland.

Thanks for making the emulator it's wonderful.  At lease you made it with 2
drives!

Phil

**Comment by tomcw** [comment]
So it sounds like you insert the 4 (copies of the) disks into the 4 drives, and then you never have to swap them out during game play. This is the perfect use-case for a simple command-line-only support (as I described above).

TBH, much of the work has been done already to support a 2nd Disk II controller card instance. If enabled, then I'd just need to disable the GUI side that allows configuration of that slot. EG, if you set slot-5 to be the Disk II card, then I'd need to prevent the GUI from configuring slot-5 for CP/M, Mockingboard or SAM sound cards.

Actually setting slot-7 would be simpler, as it's just a case of disabling the HDD controller card. If I get some time I'll have a play with the code to gauge how easy this is to do.

Ultimately #155 is what's needed (but that's a lot more work).

**Comment by tomcw** [comment]
@vromtramchick: a new AppleWin 1.29.7.0 with this change is [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.7.0).

You will need to provide the follow command line though:
```
applewin.exe -s5 diskii -s5d1 copy3.dsk -s5d2 copy4.dsk -d1 master1.dsk -d2 copy2.dsk
```

You can use the regular AppleWin GUI to boot with master1.dsk in slot 6 drive 1, and then swap it for copy1.dsk at the title screen.

Since there's no GUI to support the 2 drives attached to the slot 5 card, you can't eject or insert disks into these drives. But as a confidence check, I extended the tooltip (when you hover the mouse over the drive 1 or drive 2 buttons) so you can see what is in all the drives.

NB. save-state (F11) works with this slot 5 card too, but saving the state doesn't persist the disk images (eg. copy1.dsk). Since these disks get written to during the game, then I wouldn't recommend using save-states, because if you load an old save-state, then it won't match the disks any more, and you'll likely get undefined (ie. odd) behaviour.

Let me know if anything is unclear.

**Comment by tomcw** [comment]
Hi Phil / @vromtramchick - have you had a chance to try this out yet?

**Comment by vromtramchick** [comment]
The season's had me hoppin'.  I am looking forward to trying it out.

Thank you for your hard work, I'll let you know how it goes.

**Comment by tomcw** [comment]
This has been supported for 6 months, so closing.
