### ISSUE TITLE
"Apple //e" text when starts

### ISSUE THREAD

**Issue by Nerun** [AppleWin/AppleWin#735]
Where is located the centralized-top text message that appears when you boot the machine? The "Apple //e" text? I want to change it to "TK3000 //e", a brazilian version of Apple IIe.

What file should i edit?

Would be interesting to be capable to change it in config file!

**Comment by sicklittlemonkey** [comment]
This is already supported.

Click the Configuration button (or press F8) then on the main Configuration
tab select "Clone" for the Model.
Click the Advanced tab and select "TK3000 //e" in the Clone drop-down menu.

Cheers,
Nick.

**Comment by Nerun** [comment]
Oh sweet! Thank you!
