### ISSUE TITLE
[Development] Discussion about g_bFullSpeed

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#736]
@audetto commented in #733 (so moving the discussion here):

> re. .nib: authentic vs enhanced - I've confirmed this issue.

This made me think about something I noticed while integrating the NTSC code in the Linux version (and which caused Karateka to hang).

When CpuExecute is called with bVideoUpdate = false, then g_bFullSpeed *must* be true, otherwise the vert and horiz clocks are not updated properly.

Even then, then calculation in the 2 cases in not exactly comparable and requires some digging to check if it is the same (which seems like it is).

So, I was thinking, rather than this and the fact it could break easily, why not calling a special version of NTSC_VideoUpdateCycles() which just advances the clock (in exactly the same way as the current one), without updating the framebuffer.

It might change nothing, but it would remove a chance of problems.

So then I checked where else the fullSpeed variable is used (to see if I had missed anything) and I found https://github.com/AppleWin/AppleWin/blob/91f12942206f317eff7e4aebc895722bae7be5c6/source/CPU.cpp#L466 but I have no idea of what it is about.

**Comment by tomcw** [comment]
>When CpuExecute is called with bVideoUpdate = false, then g_bFullSpeed must be true

Yes, I've been trying to reduce the global variables - and am slow replacing with accessor functions. I've not done this for `g_bFullSpeed` yet, but didn't want to add to the problem; so for this case of calling `CpuExecute()` that's why I passed by parameter.

**Comment by tomcw** [comment]
>So, I was thinking, rather than this and the fact it could break easily, why not calling a special version of NTSC_VideoUpdateCycles() which just advances the clock (in exactly the same way as the current one), without updating the framebuffer.

In FullSpeed mode (ie. `g_bFullSpeed == true`), `g_nVideoClockVert/Horz` are just-in-time updated whenever there's a floating-bus access in `NTSC_VideoGetScannerAddress()`.

**Comment by tomcw** [comment]
>So then I checked where else the fullSpeed variable is used (to see if I had missed anything) and I found https://github.com/AppleWin/AppleWin/blob/91f12942206f317eff7e4aebc895722bae7be5c6/source/CPU.cpp#L466 but I have no idea of what it is about.

This isn't a great solution. I added it so that the performance of full-speed wasn't impacted by checking interrupt sources every opcode... but there are now new (French Touch) demos that rely on cycle-accurate interrupts... meaning that the demos will crash if run at full-speed.

So I think I'll remove this and just treat full-speed like normal speed when checking interrupt sources.

**Comment by audetto** [comment]
I am happy with the explanations / understanding.

**Comment by tomcw** [comment]
btw, this old code `if (g_bFullSpeed && opcodesUntilInterrupt < IRQ_CHECK_OPCODE_FULL_SPEED)` got removed & improved when I added PR #841.

>I am happy with the explanations / understanding.

OK - closing.
