### ISSUE TITLE
Show "step" cycle count in debugger.  For profiling.

### ISSUE THREAD

**Issue by StewBC** [AppleWin/AppleWin#737]
Show the cycle count of the last "step" (space, CTRL-SPACE, CTRL-DOWN ARROW, etc).  This is very useful for profiling and saves having to note the pre- and post cycle counters and do the math.  I hacked it in locally in Debugger_Display.cpp - DrawVideoScannerInfo - using static variables and it works great.  Would be nice to have this as part of the official emulator, implemented correctly (whatever that means).

**Comment by tomcw** [comment]
I agree - this sounds useful.

**Comment by tomcw** [comment]
I've changed the absolute cumulative cycle count to now show a cycle delta since the last step/breakpoint etc.

A new AppleWin with this changed is [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.7.0).
