### ISSUE TITLE
Can not INIT disk image with a volume number other than 254

### ISSUE THREAD

**Issue by griffin9k** [AppleWin/AppleWin#738]
I happened to INIT a DOS 3.3 disk image using AppleWin 1.29.1.0 and specified a volume number 17,  then got "VOLUME MISMATCH" message (as the screenshot shows). but I can still INIT the disk image WITHOUT specifying a volume number. 
Furthermore, after I initialized the disk image with specifying a volume number other than 254, I found the disk image was destroyed by AppleWin, the CiderPress considers it as an invalid image, I checked the disk image again using Copy II Plus "Disk Mapping" and "Sector Editor" function as shown in the last two screenshots, the whole disk was filled with zero!
To verify the problem, I did the above operation again on a physical Apple IIe + 5.25 floppy drive, it is completely normal, I can specify the volume number arbitrarily when I initialize the floppy disk.
Any suggestion?
![2019-12-08_115131](https://user-images.githubusercontent.com/52750376/70385992-7c719f80-19ce-11ea-84d1-bbf5e6689596.png)
![2019-12-08_115239](https://user-images.githubusercontent.com/52750376/70385993-7d0a3600-19ce-11ea-91c6-6539d70cf442.png)
![2019-12-08_115517](https://user-images.githubusercontent.com/52750376/70385994-7d0a3600-19ce-11ea-84b9-95db39c8e674.png)
![2019-12-08_115604](https://user-images.githubusercontent.com/52750376/70385995-7da2cc80-19ce-11ea-9a05-63299b95e120.png)

**Comment by tomcw** [comment]
What is the name of your floppy disk image?
It's likely you are using a using a .dsk extension (eg. blank.dsk)
.dsk only supports volume 254.

Instead you need to use a .nib (*).
Just open the Drive-2 dialog (F4), then type a file name of a new (non-existent) .nib, eg. blank.nib.
You should then be able to INIT this with any volume number.

(*) .woz will eventually work, but currently AppleWin's support is read-only.

**Comment by griffin9k** [comment]
Thanks for your comment, it works, I can INIT the BLANK.NIB image file with specifying any volume numbers, but when I mount the BLANK.NIB file in the Floppy EMU, it seems to be locked, I can't write anything onto it, please see the photo attached. But the strange thing is that I can read and write on AppleWin, is this normal?
![nib locked](https://user-images.githubusercontent.com/52750376/70387635-58b85480-19e2-11ea-919b-36eaafc020db.jpg)

**Comment by tomcw** [comment]
I don't know anything about 'Floppy EMU'... maybe it doesn't support writing to .NIB images?

**Comment by tomcw** [comment]
From the FAQ, [here](https://www.bigmessowires.com/floppy-emu/), it doesn't support writing to NIB (or WOZ):

>Can I write to the emulated disk, as well as read from it?
Yes, for all but Apple II NIB and WOZ format images.

**Comment by griffin9k** [comment]
It seems that there is no perfect disk image format yet, but thank you for your help:)
