### ISSUE TITLE
(Debugger) (H)GR command does not honour mixed mode

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#740]
Both GR and HGR try to show the full screen when the corresponding command is used, even if mixed mode was active at the time.  It makes the last four lines of text screen unreadable.

**Comment by tomcw** [comment]
@peterferrie: a new AppleWin with this fixed is [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.7.0).
