### ISSUE TITLE
Remap Button 0 and Button 1

### ISSUE THREAD

**Issue by wyatt-wong** [AppleWin/AppleWin#743]
Is it possible to remap Button 0 and Button 1 to other keys instead of the default Left Alt and Right Alt key ?

When I use AppleWin to play Dino Eggs, I have to press Left Alt (Button 0) to jump and Right Alt (Button 1) to take/drop wood, dino eggs and setup dino cages. This is troublesome. Furthermore the Windows key is next to the Left Alt key and I could accidentally pressed the Windows key instead of Left Alt key.

**Comment by tomcw** [comment]
I don't know if this will help, but via Configuration (F8) -> "Input" tab, then select "Joystick 1" = "Keyboard (numpad)". Now (with Num-Lock enabled) you can use the numeric keypad's `0` and `.` for Button 0 and Button 1... but now the cursors keys can't be used for joystick inputs.

btw. What keys would you want to remap to?

**Comment by sicklittlemonkey** [comment]
Other options include using a physical joystick or remapping WIndows keys
with eg:
https://github.com/randyrants/sharpkeys

Cheers,
Nick.

**Comment by wyatt-wong** [comment]
> I don't know if this will help, but via Configuration (F8) -> "Input" tab, then select "Joystick 1" = "Keyboard (numpad)". Now (with Num-Lock enabled) you can use the numeric keypad's `0` and `.` for Button 0 and Button 1... but now the cursors keys can't be used for joystick inputs.
> 
> btw. What keys would you want to remap to?

I would like to use Right Alt and Right Ctrl keys for Button 0 and Button 1 as they are just next to the arrow keys.

**Comment by wyatt-wong** [comment]
> Other options include using a physical joystick or remapping WIndows keys with eg: https://github.com/randyrants/sharpkeys Cheers, Nick.

I don't want to remap the key for the whole Windows OS, just want to be able to map the button 0 and button 1.

**Comment by tomcw** [comment]
It was simple to add a command line option for this: `-right-alt-control-buttons`

**Caveat:** Right-Ctrl + F2 will do the //e self test, as it detects CTRL+SOLID APPLE+RESET, as Right-Ctrl is both CTRL and SOLID APPLE! Workaround is just to use the Left-Ctrl key.

I also added: `-left-control-alt-buttons`

**Caveat:** Left-Ctrl + F2 will do the //e CTRL+OPEN APPLE+RESET. Workaround is just to use the Right-Ctrl key.

And I added: `-swap-buttons`
Useful for (eg) Lode Runner, where button-1 digs left (and button 0 digs right).

**Comment by tomcw** [comment]
@wyatt-wong: there's a new version 1.29.8.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.8.0/AppleWin1.29.8.0.zip) with this supported.

Let me know if this works for you, so that I can close this issue.

**Comment by tomcw** [comment]
@wyatt-wong - I'm resolving this, but let me know if you have any further comments.

**Comment by xotmatrix** [comment]
The combination of `AppleWin.exe -left-alt-control-buttons -swap-buttons` does what you want.

> -left-alt-control-buttons
> Use Left Control & Left Alt for Open Apple & Solid Apple keys respectively.
> Caveat: Left Control + F2 will do the //e Ctrl+Open Apple+RESET (as Left Control is now both Ctrl and Open Apple!). A workaround is just to use the Right Control key.
> 
> -right-alt-control-buttons
> Use Right Alt (AltGr) & Right Control for Open Apple & Solid Apple keys respectively.
> Caveat: Right Control + F2 will do the //e self test (as Right Control is now both Ctrl and Solid Apple!). A workaround is just to use the Left Control key.
> 
> -swap-buttons
> Swap buttons 0 and 1 for all input devices.
> EG. the Windows keys used for Open Apple & Solid Apple keys, and the current device being used to emulate a joystick (keyboard, real joystick or mouse)
