### ISSUE TITLE
xbox wireless controller - windows

### ISSUE THREAD

**Issue by carlosdesedas** [AppleWin/AppleWin#744]
Hi all.  thanks for bringing back memories with this great emulator...

I have an xbox controller connected to my PC using the wireless dongle from microsoft for the controller...  it's recognized as a USB controller in windows 10 itself, but when trying to select it to be used for applewin, it's not recognized.  If I plug it to the PC via usb-cable, i can use it fine, but the PC is hidden from sight, thus making in it awkward....

Is there a way to have this type of controller recognized while in use with the wireless dongle?  thanks

**Comment by tomcw** [comment]
An alternative (assuming you have the right type of xbox controller) is to use a Bluetooth adapter: https://www.pcgamer.com/xbox-one-controller-on-pc/

Otherwise, I don't know, as I don't have an xbox controller (I guess it could be related to AppleWin not using XInput - see #101)

**Comment by carlosdesedas** [comment]
Thanks Tom... that did the trick!  Luckily I had the xbox one x type controller that allowed me to sue bluetooth also...

Best regards,

Carlos

**Comment by tomcw** [comment]
Great! I'll close this issue.
