### ISSUE TITLE
Minor screen refresh issue in debugger

### ISSUE THREAD

**Issue by fadden** [AppleWin/AppleWin#746]
Tested with v1.29.7.0.  Reproduction steps:

 - Start emulator.
 - Hit F7 to open the debugger.
 - Hit '\\' \<enter\> to view the current emulated screen.
 - Grab the window and drag it halfway off the bottom or side of the screen, then back where it was.

The part of the window that was off-screen is now showing the debugger contents rather than the emulated screen.

**Comment by tomcw** [comment]
Thanks Andy - that'll be fixed in the next point release.

**Comment by tomcw** [comment]
Hi Andy / @fadden - FYI, there's a new version 1.29.8.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.8.0/AppleWin1.29.8.0.zip) with this fixed.
