### ISSUE TITLE
Typing a # on french keyboard causes Applewin to switch to full speed

### ISSUE THREAD

**Issue by Mark-Five** [AppleWin/AppleWin#749]
When using Applewin on a french keyboard PC, it is required to use ALT-GR 3 to type a #. AppleWin sees that as a request to engage full speed emulation (ALT-GR is actually CTRL+ALT, IE CTRL ALT 3).
This is quite annoying as a PR#6 will always toggle full speed emulation.
The ALT key status should be checked before switching to full speed. If it is pressed, it should NOT toggle to full speed.

**Comment by tomcw** [comment]
Thanks for reporting this. I'll take a look.

**Comment by tomcw** [comment]
@Mark-Five: there's a new version 1.29.8.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.8.0/AppleWin1.29.8.0.zip) with this fixed.

**Comment by Mark-Five** [comment]
Great ! Will test it ASAP. Thank you for fast and efficient fix !

Cheers,
Pascal.

Le 19 janv. 2020 à 18:22, TomCh <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Mark-Five<https://github.com/Mark-Five>: there's a new version 1.29.8.0 here<https://github.com/AppleWin/AppleWin/releases/download/v1.29.8.0/AppleWin1.29.8.0.zip> with this fixed.
