### ISSUE TITLE
Ctrl-Alt-Break no longer reboots

### ISSUE THREAD

**Issue by robinhood2014** [AppleWin/AppleWin#752]
In AppleWin version 1.29.8.0, when I press Ctrl-Alt-Break, it no longer restarts the emulated computer via an Open Apple-Ctrl-Reset. Pressing Ctrl-Break still works like a Ctrl-Reset and drops me to, for example, the Applesoft BASIC "]" prompt, but the Ctrl-Alt-Break trap seems to be broken in the latest release.

**Comment by tomcw** [comment]
Oops! Yes, I also spotted this late last night, but thanks for raising this. It's definitely a regression!

**Comment by tomcw** [comment]
OK, this new [1.29.9.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.9.0) version fixes the issue.
