### ISSUE TITLE
Swap Joystick Buttons

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#759]
I'm using an Xbox 360 controller and sadly the physical joystick button layout doesn't always match up with games.

i.e. This patch for Lode Runner swaps button 1 and 2 so that the (A) button digs left, and (B) button digs right.

    6AD1:61
    6ADA:62

Instead of having to patch _every_ game we should have a checkbox in `Configuration > Input`:

`[x] Swap joystick buttons 1 and 2`

**Comment by Michaelangel007** [comment]
Closed as duplicate of #743 

Two solutions:
* command-line `-swap-buttons`
* UI: `Configuration` > `Input` > `[x] Swap 0/1`

**Comment by qtipbailey** [comment]
> I'm using an Xbox 360 controller and sadly the physical joystick button layout doesn't always match up with games.
> 
> i.e. This patch for Lode Runner swaps button 1 and 2 so that the (A) button digs left, and (B) button digs right.
> 
> ```
> 6AD1:61
> 6ADA:62
> ```
> 
> Instead of having to patch _every_ game we should have a checkbox in `Configuration > Input`:
> 
> `[x] Swap joystick buttons 1 and 2`

I'm interested in this. How do you do these patches of which you speak? Is there a discussion somewhere about them?
