### ISSUE TITLE
Lancaster (Total Replay) hangs when starting second game

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#765]
I have AppleWin set to Mockingboards in 4&5.
The first game plays properly with Mockingboard sound.
When starting the second game, Mockingboard interrupts start firing repeatedly.
It's not actually hanging, but running so slowly that it looks like it has.

**Comment by tomcw** [comment]
Thanks @peterferrie - confirmed as a bug.

It's this odd 6522 code sequence that is causing the problem:
```
173E: 
	lda #$fd	; 1111 1101 -> IER:=0x7d & start TIMER1 & TIMER2
	sta $C40e
	lda #$02	; 0000 0010 -> IER:=0x7d
	sta $C40e
```

This enables TIMER2 interrupt (as well as TIMER1, but that's ok).

TIMER2 runs in one-shot mode, but nothing ever clears this TIMER2 interrupt source (btw. the ISR is at $6600, but it only clears TIMER1).

I have a similar unexplained 6522 one-shot issue with Willy Byte (but this time on TIMER1).

I really need to investigate on real Mockingboard/6522 hardware.

**Comment by tomcw** [comment]
The 6522 bug was that the TIMER2 interrupt only fires if the T2C_H (reg 9, Timer2 counter-high) has been written to. Merely enabling the IER.T2 bit isn't enough for TIMER2 to fire (even though it is always counting down and underflowing every ~0x10000 cycles).

On a real Mockingboard (ReactiveMicro), the code at $173E also causes the CA2,CB1,CB2 interrupt flags to be set too (eg. IFR=0x99). But the Lancaster ISR will clear these when writing to ORB & ORA ...when it writes to the AY8910 regs. (AppleWin doesn't emulate this.)

**Comment by tomcw** [comment]
For the 6522 TIMER1 (ie. the Willy Byte case):
- SEI
- T1=0xFFFF
- ACR=0x40 (free-running timer1)
- IER=0xC0 (enable T1)
- Poll IFR.b6 for T1 interrupt
- ACR=0x00 (one-shot timer1)
- CLI

On real h/w, the above yields 2 T1 interrupts (1 pending, and 1 from the one-shot).

Then with my ISR still setup, and after IER=0xC0 (enable T1):
- ACR=0x40 (FRT)
  - T1 interrupts occur periodically
- T1C_H=FF  ; T1C_L doesn't start
- ACR=0x00 (one-shot)
  - T1 interrupts stop (as ISR clears IER.b6)

**Comment by tomcw** [comment]
Also (on real h/w), after the initial 2 T1 interrupts above (ie. stopped in ACR=0 state), then:
- IER=0xC0  ; no extra ints
- ACR=0x40 ; no extra ints
- IER=0xC0  ; no extra ints

Currently AppleWin erroneously generates ints:
- IER=0xC0  ; 1 extra ints
- ACR=0x40 ; no extra ints
- IER=0xC0  ; periodic ints

**Comment by tomcw** [comment]
Added 6522 tests here: https://github.com/AppleWin/AppleWin-Test/commit/77c15bd2371c7958525d6de6c40eacb9fef368d9

**Comment by tomcw** [comment]
Hi Peter,
Here's a new build of [AppleWin 1.29.11.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.11.0) that fixes this issue.

**Comment by peterferrie** [comment]
Confirmed.  Thanks Tom.

**Comment by tomcw** [comment]
Good stuff - closing.
