### ISSUE TITLE
corrupt .po file after bootup

### ISSUE THREAD

**Issue by blindphoneman** [AppleWin/AppleWin#766]
Hi:

I set up a 32 meg HD image in .po format and try to boot it in AppleWin 1.29.10 in slot 7.  It seems to boot, but, then nothing works correctly.  After I exit the emulator, CiderPress will no longer recognize the image.  If I write protect the image, AppleWin still has problems, but, after booting from slot 6, then going back to slot 7, things seem to work better.then going back to slot 7, it seems to work correctly.  I don't know if

**Comment by tomcw** [comment]
@blindphoneman - your comment ends with an unfinished sentence.

**Comment by tomcw** [comment]
Hi @blindphoneman -  your original comment (from 27 days ago) has an unfinished sentence. Is this still an issue for you?

**Comment by tomcw** [comment]
I'm closing this as invalid, as the initial comment isn't complete & no update in a month.
