### ISSUE TITLE
SHK File Type

### ISSUE THREAD

**Issue by DRSaylor** [AppleWin/AppleWin#768]
Can AppleWin use this ShrinkIt file type? I have a copy of Prodos that is in a shk file but I get a filetype not recognized by AppleWin. Do I need to do something first? I tried to bring the file into ShrinkIt but got the same error. Please Help.

**Comment by tomcw** [comment]
>Can AppleWin use this ShrinkIt file type?

No - there's no support for ShrinkIt files.

Try using CiderPress to extract the image first:
https://a2ciderpress.com/features.htm#shrinkit

**Comment by tomcw** [comment]
Closing
