### ISSUE TITLE
Add command line to load custom ROM

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#771]
From @Archange427, on 17/3/2020:

I'm working on a custom rom [...]

Would it be possible to add the option to load the "CD" and "EF" parts of the ROM with new parameters from the command line ?

This would also allow to use famous custom ROMs from 80s (such as the SeniorProm) with AppleWin!

I think -rom \<file\> option is the simplest and covers all cases.
And it is very simple to make a 16K bytes file from "CD" and "EF" parts.

And to allow 12K files would be a good idea too if older Apple II models are selected in configuration tab ( even if I admit that I don't really know/use "old" Apple IIs!)

**Comment by tomcw** [comment]
My quick spec for this:

- Add new -rom \<file\> command line switch
- Where file size is exactly 16KiB or 12KiB (for older Apple IIs)
- It's an error if you try to use both -rom and -f8rom
- Ideally support custom rom in save-state

**Comment by tomcw** [comment]
Tests:
1) 12K: Apple IIj+ ROM

```
AppleWin.exe -model apple2p -rom "D:\Apple][\AppleROMs\Apple IIj+ ROMs\IIJPLUS.ROM#062000" -videorom "D:\Apple][\AppleROMs\Apple IIj+ ROMs\JVIDEO.ROM#062000"
```

https://mirrors.apple2.org.za/ftp.apple.asimov.net/emulators/rom_images/Apple%20IIj%2B%20ROMs.zip

Extracted rom & video-rom from `IIJ ROMS DUMP.DSK`

2) 16K: Apple // Extended Debugging Monitor (#394)

```
AppleWin.exe -model apple2ee -rom "D:\Apple][\AppleROMs\Apple2e_EDM.rom"
```

**Comment by tomcw** [comment]
Added the above 2 tests: https://github.com/AppleWin/AppleWin-Test/commit/790b07d07d32cfedf81dcd01e80b2e526159cae2

**Comment by tomcw** [comment]
Hi @Archange427 - here's a new build of [AppleWin 1.29.11.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.11.0).

Just use the new `-rom <file>` switch with a 12KiB or 16KiB ROM file.

**Comment by Archange427** [comment]
I just tested and it works perfectly! 
I was able to fix easily the checksum byte for my ROM custom ;)
Thanks Tom!
Also glad to see that this feature allows new possibilities to AppleWin such as emulation of the Japanese Apple II or the use of special ROMs!

**Comment by tomcw** [comment]
Thanks for checking this - yes, this little feature has added some interesting possibilities!
(Closing.)

**Comment by Drakepirate** [comment]
My Base 64A Roms are 28K total ( D0:4K D8:4K E0:4K E8:4K F0:4K & F8:8K ) 
A reduced version of 12K cutting last 2k and 4k of last  of each bin file partialy works but have no Applesoft prompt.

[Ci Base-64A.zip](https://github.com/AppleWin/AppleWin/files/4845108/Ci.Base-64A.zip)

**Comment by tomcw** [comment]
NB. "Base 64A" is a Taiwanese Apple II clone:
https://en.wikipedia.org/wiki/List_of_Apple_II_clones#Taiwan

I guess that because you have truncated the ROM, then it's not working due to this missing ROM. The only way to access the ROM will be through unsupported I/O ROM bank-switching (I guess).

So the first step would be to provide documentation as to how the extended ROM is switched in.

Note: this topic should be spun out into a dedicated issue.

**Comment by Drakepirate** [comment]
Hi Tom
I have the manual and extracted the ROMS from my real machine,  also a friend made a discover of ROM mapping (Base has a text processor embedded) . May be Can be the next clone to be implemented in Applewin? 🙄
![27D170C2-000C-4A50-BE04-D014F7C51DD2](https://user-images.githubusercontent.com/47072448/86075673-1dcf5880-babb-11ea-899d-cc12fa3b6fd0.jpeg)
![0B83BD1B-09B7-4B62-9FD0-12AA5F08E472](https://user-images.githubusercontent.com/47072448/86075695-2a53b100-babb-11ea-8506-f7c03ded394b.jpeg)

**Comment by tomcw** [comment]
Hi @Drakepirate - I've moved this request over to #806

**Comment by Drakepirate** [comment]
Thanks Tom.
