### ISSUE TITLE
Applewin debugger and auxiliary memory view

### ISSUE THREAD

**Issue by riodice** [AppleWin/AppleWin#772]
Hello,
I am working on AUXMOVE and XFER routines and do not find how to see the auxiliar memory and is $0000 to $FFFF specific zone. 
Is it possible in Applewin ?
The tool is amazing and a big thanks to the developpers.
Regards
Eric

**Comment by tomcw** [comment]
Currently there's no way to view the physical memory eg. main or aux 64KB.

Instead what the debugger's memory views show is virtual memory, ie. the memory as seen after using the MMU's software switches.

AFAIK the only way to access the physical auxiliary memory is to use the debugger's `bsave` command, which will save it to a file - see #166.

**Comment by Archange427** [comment]
You can use the **OUT** command from the debugger to manually switch from MAIN to AUX (or to set another switches btw)
Concretely, type:
out c003  to "display" what is in AUX memory 
out c002  to come back to MAIN ram.

Actually - as Tom said - theses commands change what is displayed in the AppleWin's virtual memory.

**Warning**: you have to put the switches back in the state they were when entering the debugger, otherwise crash guaranteed when resuming the program!

**Comment by riodice** [comment]
Hello,
Thank you for you answers.
I use 1.29.10 version and try using the BSAVE solution... but all my attempt (below) fails with and Error opening file... (image attached)

BSAVE "test",6000,FF
BSAVE "test",6000:60FF
BSAVE "main.bin",0:6000
BSAVE "aux2.bin",1:6000
BSAVE "main.bin",0:6000:60FF
BSAVE "aux2.bin",1:6000:60FF
BSAVE "C:\Apple_II\Applewin\test.txt",0:0000:00FF
Would you have you an idea ?
Regards
Eric
![image](https://user-images.githubusercontent.com/46989060/77313453-3255c500-6d04-11ea-953b-8100a20a6ceb.png)

**Comment by tomcw** [comment]
Hmm... all these work for me, except `BSAVE "C:\Apple_II\Applewin\test.txt",0:0000:00FF` - as I don't have a folder "C:\Apple_II\Applewin".

btw. `BSAVE "main.bin",0:6000` looks like a minor bug - this saves $0000-$6000 inclusive.

Anyway, can you issue a `cd` command to show your current directory. Maybe it's a path which require elevated permissions?

**Comment by riodice** [comment]
Thank your for your help. I have installed a new Applewin in a new place and BSAVE works. ;-)
Again your tool is amazing ! Bravo for your work.

**Comment by tomcw** [comment]
Thanks for the positive feedback! (I'll close as invalid)
