### ISSUE TITLE
Add Apple II J-Plus support

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#773]
Now that custom ROMs can be loaded (#771), then I thought that J-Plus support (from the command line) was done, eg:

```
AppleWin.exe -model apple2p -rom IIJPLUS.ROM -videorom JVIDEO.ROM
```

But @sicklittlemonkey told me that the video rom (in AppleWin 1.29.11.0) isn't quite correct...

>I did give it a go, though I wonder where that ROM
collection came from. I wrote the text files, but those ones are
different from the ones I remember releasing, unless there were
multiple versions. The full versions are here:
https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Computers/Apple%20II/Apple%20II%20j-plus/Documentation/
>
>Searching around I did find a problem with what I've written, and the
j-plus video ROM doesn't behave exactly as I would expect in AppleWin:
https://mametesters.org/view.php?id=6175
>
>I don't have my original notes handy, but from memory I was going by
screenshots like the one at the link above (in fact possibly that
exact one) ...
>
>It would be nice to get this working as it should.

Here's what AppleWin 1.29.11.0 shows...
![IIj+_videorom](https://user-images.githubusercontent.com/6696896/77821653-c6000a80-70e3-11ea-995b-b0c6f43e47a3.png)

From Nick's notes:
```
Characters in ROM:
00-3F Katakana } 00-7F activated by access to $C05C (annunciator 2 off)
40-7F ASCII    }
80-BF ASCII    ] 80-FF activated by access to $C05D (annunciator 2 on, set after reset)
C0-FF ASCII    ]

Characters displayed onscreen with annunciator 2 off:
00-3F Katakana - normal
40-7F Katakana - flashing
80-BF ASCII    - normal
C0-FF ASCII    - normal

Characters displayed onscreen with annunciator 2 on:
00-3F ASCII    - inverse
40-7F ASCII    - flashing
80-BF ASCII    - normal
C0-FF ASCII    - normal
```

So AN2 controls what video rom chars are displayed for 00-7F.
**EDIT:** NB. there's no way to get INVERSE Katakana.

To do:
- [x] Add a new Apple II J-Plus model (apple2jp) to the code base
- [x] Support AN2 just for this apple2jp model
- [x] Expose this via cmd line & Config UI

**Comment by sicklittlemonkey** [comment]
Just a note that we verified the flashing behaviour. Here's a photo where it's caught changing.
![KatakanaFlash](https://user-images.githubusercontent.com/4393005/78201281-96327780-74d4-11ea-9576-c0d8dde8fbea.jpg)

**Comment by tomcw** [comment]
Added test: https://github.com/AppleWin/AppleWin-Test/commit/2de648b3d5622f81a1e6f90a09a7d0b76649506b

**Comment by tomcw** [comment]
Closing, as all complete with Help docs updated at db373c695555aded858042839d88125e702cce1e
