### ISSUE TITLE
GraFORTH woz don't boot (almost!)

### ISSUE THREAD

**Issue by MarcoVerpelli** [AppleWin/AppleWin#782]
1) download https://archive.org/details/wozaday_GraFORTH
2) put image in slot 6 drive 1
3) boot --> hangs at track 0 sector 0, read forever looking for a $D5 i.e.
LOOP    LDA DATASTROB,X
             BPL LOOP
             EOR #$D5
             BNE LOOP
4) put a master DOS 3.3 in slot 6 drive 1
5) boot --> OK I've no doubt ;)
6) swap disk with GRAForth
7) PR#6 --> It's alive! Shouted Dr. Frankenstein

I have tried several times and it seems to be consistent, not random.
The Apple model emulated or the speed of the disk doesn't seem to matter.

Marco

**Comment by tomcw** [comment]
Hi Marco,
Thanks for the report.

I checked the WOZ Info chunk, and the `bootSectorFormat` field reports the disk format as a 13-sector boot sector (2). But the disk is actually 16-sector!

Here's a dump of T$00: [T00.txt](https://github.com/AppleWin/AppleWin/files/4605529/T00.txt)

NB, it's not booting with AppleWin, as this field now configures AppleWin to use the 13-sector Disk II firmware.

So the WOZ Info field `bootSectorFormat` needs to be set to 1 (not 2).
@a2-4am: can you re-upload with this corrected?

**Comment by a2-4am** [comment]
Fixed and reuploaded, thank you.

**Comment by MarcoVerpelli** [comment]
Thank you and sorry for the inconvenience.
I don't know anything about the WOZ format.

Marco

**Comment by tomcw** [comment]
Thanks @a2-4am for the quick fix ...and thanks Marco (please keep reporting these issues!)
