### ISSUE TITLE
DOUBT: Total RAM

### ISSUE THREAD

**Issue by Nerun** [AppleWin/AppleWin#791]
JUST A DOUBT

What is the total RAM for the system? 64k, 128k? It's all the same for all systems? (Apple II, IIe, Enhanced etc)

**Comment by tomcw** [comment]
Firstly it depends on the model you select.
EG. Apple II is 48K, Apple II+ is 64K, //e is 128K

Then it depends on whether you have a RAM card installed.
EG. Apple II can have a 16K Language Card or 128K Saturn (Language) Card; //e can have a RamWorks card enabling up to 8MB.

NB. The Brazilian "TK3000 //e" is an enhanced //e clone, so by default it has 128K, but can also have the RamWorks card.
