### ISSUE TITLE
PR#0 doesn't work.

### ISSUE THREAD

**Issue by rdking** [AppleWin/AppleWin#792]
Many of the Apple //e soft switches are meant to trigger merely by reading them. Among them are all the display control switches.

Proof: Just try this
```
] PR #3

] PR #1 
```
That should send you into 80 column mode and then back to 40 column. However, ```PR #1``` doesn't work. The same is true for all of the other display soft switches, and may be true for several of the non-display soft-switches. I don't remember too clearly about the others.

**Comment by sicklittlemonkey** [comment]
I think perhaps you've forgotten some of your old Apple II knowledge.

PR#N activates the card in slot N. Traditionally slot 3 was used for
80-column cards, hence PR#3 activating 80-columns in AppleWin for machines
that support it (Apple //e).

PR#1 will activate the card in slot 1, which was usually a printer card, as
it is in AppleWin.

To turn off 80 columns you can use PR#0, which disconnects the 80-column
firmware, or you can use Esc 4 (for 40 columns) and Esc 8 will go back to
80-columns.

Cheers,
Nick.

**Comment by rdking** [comment]
@sicklittlemonkey Yeah, it's been 35+ years. I don't doubt that my info is rusty. However, even using PR#0 doesn't work. I'm still left behind in 80 column mode.

Then there's
```
] CALL -151

* C00C
C00C - 0D
* C00D
C00D - 0D
* C00C
```
This should also toggle between 80 and 40 column mode, but it doesn't work unless I write to the address.

**Comment by rdking** [comment]
There's one other thing. When using RGB mode, all of the video modes demoed on [this disk](ftp://ftp.apple.asimov.net/pub/apple_II/images/hardware/video/Video-7%20Apple%20II%20RGB%20Demo%20(Video-7,%20Inc.)(1984).dsk) should work properly. When I was a kid, I had a //e with the AppleColor card and monitor. I remember having fun playing around with all of those modes. I even ended up writing a GUI OS of sorts (slightly jealous of the IIgs at the time). Is it possible to get these working in AppleWin?

**Comment by sicklittlemonkey** [comment]
C00C/C00D (and some others) need writes to switch 40/80 columns. See
here: http://jamtronix.com/2007/06/11/apple-e-soft-switch-status-and-other-io-locations/

AppleWin has been carefully honed over more than 20 years, checking
not just documentation but also behaviour on real hardware. It's one
of the most accurate Apple II emulators.

Some AppleColor card behaviour is supported. There are multiple issues
tracking this. See https://github.com/AppleWin/AppleWin/issues/764

**Comment by sicklittlemonkey** [comment]
For instance, the Apple II DeskTop project uses the AppleColor DHR mono
mode - which works in AppleWin:  https://www.a2desktop.com/

**Comment by rdking** [comment]
It's good to know that you're working on all the extended display modes. As for my rusty memory. let's not rely on that at all. Apparently it's just been far too long since I last laid hands on the hardware. So let's reduce my statement to just this:

```PR#0``` does not successfully return to 40 column mode after ```PR#3```

**Comment by sicklittlemonkey** [comment]
Hmm, you're right for the standard //e. But Esc 4 works. For the enhanced
//e both work.

**Comment by tomcw** [comment]
I have a standard //e, and can confirm that AppleWin's behaviour is the same, ie. when you type `PR#0` you get this:
![PR#0](https://user-images.githubusercontent.com/6696896/83297979-880a8a00-a1eb-11ea-9b62-0df1e29529b7.png)

As Nick says, Esc 4 reverts to 40-col mode.
Additionally, Esc Ctrl-Q quits the 80-col firmware... so back to the checkerboard cursor.

**Comment by rdking** [comment]
Esc 4 doesn't disable the 80-column card. It only switches to a 80-column card driven 40 column mode. This is evidenced by the fact that the cursor is still solid. If the 80 column card were disabled, you'd get back the hashed block for a cursor.

As for the ```PR#0``` problem, I'm using the "Enhanced Apple //e" mode. ```PR#0``` does not take me out of 80-column mode. However, I just found part of the cause. If I boot with no disk and use Ctrl+Break, ```PR#0``` works correctly. If I boot from PRODOS+BASIC.SYSTEM, no such luck. Something about that causes ```PR#0``` to fail in a way my admittedly faulty memory doesn't recall.

If this is something that was common with ProDOS & Applesoft Basic, then we can close this issue as me being crotchety and senile.  :)

**Comment by tomcw** [comment]
Booting my standard //e with these, then `PR#3` followed by `PR#0`...

- "Apple DOS 3.3 January 1983.dsk"
- "ProDOS 1.1.1" (18-SEP-84)
- "ProDOS 1.9" (16-JUL-90)

...all produce is the same result as the non-DOS version above.

NB. I can't try newer (eg. ProDOS 2.0.3, 06-May-93) since it REQUIRES ENHANCED APPLE IIE OR LATER.

I don't have an Enhanced Apple //e to test this on, but I assume this is "spec".

You could try asking on the comp.sys.apple2 news-group.

**Comment by tomcw** [comment]
From AppleWin, in "Enhanced Apple //e" mode:
- No DOS: `PR#0` reverts to 40-col
- "Apple DOS 3.3 January 1983.dsk": `PR#0` reverts to 40-col

But...
- "ProDOS 1.1.1" (18-SEP-84): `PR#0` remains in 80-col
- "ProDOS 1.9" (16-JUL-90): `PR#0` remains in 80-col
- "ProDOS 2.0.3" (06-May-93): `PR#0` remains in 80-col
- "ProDOS 2.5.0a8" (02-Nov-2019): `PR#0` remains in 80-col

NB. `PR#n` is both an [Applesoft](http://www.landsnail.com/a2ref.htm) & [DOS](http://www.landsnail.com/a2ref3.htm)/ProDOS command.

**Comment by tomcw** [comment]
I'm sure this a non-issue, and just a quirk of how `PR#0` behaves under different DOS's and //e ROMs. Especially since I've validated this behaviour on real (unenhanced) //e hardware.

So I am going to close this as invalid.
