### ISSUE TITLE
Return of Heracles Crash

### ISSUE THREAD

**Issue by coreyemtp** [AppleWin/AppleWin#797]
I apologize if this is too little information, but Return of Heracles gets all the way through to the actual gameplay, then crashes and resets the emulator.

Using the latest 1.29 version.

**Comment by sicklittlemonkey** [comment]
From which disk image(s)?

**Comment by tomcw** [comment]
@coreyemtp - please provide the exact AppleWin version too, as 1.29.x spans a year and 14 releases.

**Comment by tomcw** [comment]
FWIW, woz version [here](https://archive.org/details/wozaday_Return_of_Heracles).
Using AppleWin 1.29.13.0 it appears to work fine, ie. game play starts and game can be played.

**Comment by tomcw** [comment]
@coreyemtp  - any progress / update on this?

**Comment by tomcw** [comment]
Closing this as invalid, since there's not enough information to go on (and the .woz image appears to work fine).
