### ISSUE TITLE
ATC issues in AppleWin Apple //e Emulator 

### ISSUE THREAD

**Issue by FlaJunkie** [AppleWin/AppleWin#798]
I bought the code rights for the Apple II version of **Air Traffic Controller** from David Mannering many years ago.

And up until a few years ago, it ran perfectly on the emulator. I must have played this game thousands of times; it is my favorite computer-based video game, ever.

The issue is the game changes sometimes and in an illogical way. Airplanes will just decide to turn on their own and fly somewhere else. As I said before, the game did not do this years ago. It happens near the end of the game in most cases.

I assumed it was a quirk with the emulator, but today, a conflict occurred with two aircraft that did not exist on the screen!

How do we get started fixing this? Or did a developer add this "quirk?"

**Comment by tomcw** [comment]
If you can identify which specific AppleWin version the quirk started happening in, then we can try to pin-point if anything changed in the emulator.

**Comment by FlaJunkie** [comment]
> 
> 
> If you can identify which specific AppleWin version the quirk started happening in, then we can try to pin-point if anything changed in the emulator.

I'll spend some time and go backwards to see. Thanks.

**Comment by tomcw** [comment]
@FlaJunkie - any progress / update on this?

**Comment by FlaJunkie** [comment]
I have been unable to duplicate it on some of the previous versions.

One day, when I have zero rabbit hole diversions, I'll have to learn the code!

**Comment by tomcw** [comment]
OK, so are you going to keep trying to narrow it down?

IMO, it's _unlikely_ to be a bug in the emulator (given how mature it is... but not impossible!).

Other possibilities are that it could be your emulator configuration, eg. perhaps for a game from ~1979 you should use the "Apple II+" model, as maybe there is some forward compatibility issue with newer Apple //e models. (*)

Or (again configuration) it could be a problem with the cards you have installed in the slots? EG. perhaps the game is reading an I/O location for a random number (aka floating bus), but a card is correctly returning a fixed value.

(*) NB. I don't know what configuration you have, so this idea may not be valid.

**Comment by tomcw** [comment]
Hi @FlaJunkie - can I check on the status of this issue?

**Comment by FlaJunkie** [comment]
Sure! I just figured out how to use Windows key plus G to record the game live. (I'm an old guy and I still learn but not as fast.) I should be able to verify my concern or prove I am wrong. Thanks for the reminder.

**Comment by tomcw** [comment]
Hi @FlaJunkie, not much progress on this issue. Can I close it?

**Comment by FlaJunkie** [comment]
Go ahead. I have been unable to spend the time to verify the error.

Thank you for contacting me, and keep up the great work!

FlaJunkie

**Comment by tomcw** [comment]
Thanks. If you get new information, then post here and we can always reopen this (if necessary).
