### ISSUE TITLE
Applewin

### ISSUE THREAD

**Issue by murat8** [AppleWin/AppleWin#804]

**Comment by tomcw** [comment]
@murat8 - do you realise that you've only created an empty issue?

**Comment by sicklittlemonkey** [comment]
I just reported this user for abuse:
New account with multiple nuisance actions:
- Empty issues raised on 15 repos
- Nonsense PR review

Look at his activity:
https://github.com/murat8

Cheers,
Nick.

**Comment by tomcw** [comment]
Ah, good point.
I'll close this issue, and I can also permanently delete it too.
