### ISSUE TITLE
A leak in RGBMonitor

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#809]
I have found a leak in RGBMonitor.

This line https://github.com/AppleWin/AppleWin/blob/master/source/RGBMonitor.cpp#L706 does not have a corresponding `delete []` and each time the emulator is restarted it allocates a new buffer.

**Comment by tomcw** [comment]
Thanks @audetto - one of the advantages of OSS: many eyes on the code! :-)

I could've added code in `VideoDestroy()` to call a destroy function in RGBMonitor.cpp, but currently there is no such destroy func, so it'd mean extending the RGBMonitor interface. Perhaps better to wrap it up as a class instead (see #808).

**Comment by fenarinarsa** [comment]
I also noted this missing delete [] in the class I made, and added it to the destroy function.
