### ISSUE TITLE
Mockingboard playback loop after entering debugger then config

### ISSUE THREAD

**Issue by roughana** [AppleWin/AppleWin#813]
I started Berzap from Total Replay 4 alpha image with Mockingboard Sound/Speech selected and Applewin configured with Mockingboard in slot 4&5. I entered debugger while music was playing - which stops mockingboard playback - 
then entered config from the debugger. Mockingboard playback commenced again in a short loop.
I would expect the mockingboard playback to remain stopped.
(When I exited debugger, Mockingboard playback continues ok.)

**Comment by tomcw** [comment]
Thanks @roughana for the report - my repro is:
- Berzap (or any MB tune playing)
- F7 (enter debugger)
- F8 (enter Configuration)
- `OK`... and you'll get a short repeated looping sound. (NB. Pressing `Cancel` doesn't repro this bug)

Another repro is:
- Berzap (or any MB tune playing)
- F8 (enter Configuration) - so no need to go via the debugger
- Change some config that requires a machine restart, eg. switch from MB to Phasor
- `OK`... and the MsgBox asking `Would you like to restart the emulator now?` will have the short repeated looping sound

**Comment by tomcw** [comment]
@roughana - there's a new AppleWin 1.29.14.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.14.0/AppleWin1.29.14.0.zip), which fixes this issue. Can you give it a try?

**Comment by tomcw** [comment]
Closing this old bug, since it's now fixed.
