### ISSUE TITLE
Request for keystroke

### ISSUE THREAD

**Issue by blindphoneman** [AppleWin/AppleWin#817]
Hi:

As a blind user, I appreciate the keystrokes provided for all the toolbar buttons.

One thing I do have trouble with is bringing up the context menu for the various drives.

A sighted user can simply right-click on the toolbar buttons for the various drives, but, this is not always easy.  Sometimes, my screen reader will not accurately report the drive correctly, so it is a kind-of hit-and-miss thing.

Would it be possible to add another keystroke to access those context menus?

Not a show stopper, but, just a suggestion.

**Comment by tomcw** [comment]
So some way to display the context menu for the Drive1 (F3) and Drive2 (F4) buttons... perhaps a key-modifier + F3/F4?
Then with the context menu displayed, you can use the cursor up/down to pick one of the 4 items.

**Comment by blindphoneman** [comment]
That should work just fine.

Any way to do something similar with the HD when activated?  Same problem--the screen reader sometimes does not focus properly on these either.

Thanks!

**Comment by tomcw** [comment]
re. HD
Currently there is context menu UI for harddisk. Instead:
- F8 to bring up the Configuration
- Control+Tab to cycle through the property sheet pages to select "Disk"
- Tab to cycle through all the tab-stop locations
- Space to select

Is this good enough?

**Comment by blindphoneman** [comment]
That should be fine.

After all hard disks are not swapped as much as Flappies.

Thanks for looking into it.

**Comment by blindphoneman** [comment]
Sorry I meant to say Floppies not Flappies
That’s what I get for trusting voice recognition software

**Comment by tomcw** [comment]
btw, on investigating the tab-stops for the "Disk" prop sheet page, the order (when tabbing) is a little haphazard, so I should straighten this out too.

**Comment by tomcw** [comment]
Hi @blindphoneman,
There's a new release of AppleWin 1.29.15.0 containing this update: [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.15.0/AppleWin1.29.15.0.zip).

**Comment by blindphoneman** [comment]
Hi: Neat!  I sure appreciate this. I’ll replace my current version. Thanks again! Sent from Mail for Windows 10 From: TomChSent: Sunday, October 25, 2020 3:10 PMTo: AppleWin/AppleWinCc: blindphoneman; MentionSubject: Re: [AppleWin/AppleWin] Request for keystroke (#817) Hi @blindphoneman,There's a new release of AppleWin 1.29.15.0 containing this update: here.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tomcw** [comment]
I updated the AppleWin.chm help file with info about Ctrl+F3 (or F4), here: 3045e77

btw, take care, as Control + F2 does a CONTROL RESET on the Apple II!

Closing this issue.
