### ISSUE TITLE
Update Uthernet card support to use Npcap for Win10

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#822]
AppleWin supports Uthernet by using WinPcap (wpcap.dll), but this doesn't work on Win10 1607+.

In cea2, "[GSPort, Uthernet and TreeHugger?](https://groups.google.com/d/topic/comp.emulators.apple2/vO5qSej9Wfw/discussion)" there's discussion around augmenting the WinPcap support to include Npcap, for Win10 support. Kelvin Sherlock said:
>https://nmap.org/npcap/guide/npcap-devguide.html#npcap-feature-native-dll
>Basically call SetDllDirectory("C:\\Windows\\System32\Npcap\\") so it will use the new wpcap.dll 

This change allows Npcap & WinPcap to coexist, but will make AppleWin load Npcap's DLL's first.

See also: https://nmap.org/npcap/windows-10.html, specifically:
>Windows 10 1607 also introduced strict driver-signing requirements that WinPcap can't meet. Npcap is fully compliant, with its drivers tested and co-signed by Microsoft.

**Comment by tomcw** [comment]
* test with just WinPcap installed:

'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\wpcap.dll'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\Packet.dll'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\winnsi.dll'
WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

* installed Npcap (but didn't uninstall WinPcap)

NB. the default is to uninstall WinPcap, but I unchecked this option:
![npcap-install-options](https://user-images.githubusercontent.com/6696896/90338712-76af6d80-dfe3-11ea-856b-b334f88854ce.png)

'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\wpcap.dll'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\Packet.dll'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\winnsi.dll'
WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

* contiki 1.3: can still use DHCP to req an ip addr

* updated AppleWin to SetDllDirectory() for Npcap (2252966)

'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\Npcap\wpcap.dll'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\Npcap\Packet.dll'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'
'AppleWin.exe': Loaded 'C:\Windows\SysWOW64\winnsi.dll'
Npcap version 0.9996, based on libpcap version 1.9.1

Successfully tested the Contiki web-browser at: http://info.cern.ch/

**Comment by sicklittlemonkey** [comment]
Nice one Tom! Thanks for updating and testing this. I haven't used it for
ages, but it's good to know that feature still works.

Cheers,
Nick.

**Comment by tomcw** [comment]
Yeah, good to get this updated, especially as it was lagging behind for Win10.

I still need to test on Win10 (the above was on Win7), and also try the support for wireless adapters, which WinPcap never supported.

Finally the AppleWin help docs (for Uthernet) need a small update too. (EG, I see that [Wireshark](https://www.wireshark.org/docs/wsug_html_chunked/ChBuildInstallWinInstall.html#ChBuildInstallWinComponents) now includes Npcap)

**Comment by tomcw** [comment]
It's a bit finicky... from the help doc:
>Note: Due to a current limitation you must exit AppleWin and re-run AppleWin for an ethernet interface change to take effect. 

If you are able to get Contiki's DHCP to request an IP address for you, then it should work from there.

**Comment by tomcw** [comment]
I was able to run Contiki (connected to info.cern.ch) via Npcap on Win10-1903, over a wired ethernet connection.

When I installed Npcap, I selected the "Support raw 802.11 traffic ... for wireless adapters", but I couldn't get it to work on my WLAN.

**Comment by tomcw** [comment]
Hmm... looks like Npcap's WiFi support depends on certain WiFI adapters: https://secwiki.org/w/Npcap/WiFi_adapters

**Comment by sicklittlemonkey** [comment]
Ah, yes I had restarted but not run the config to "request an IP
address". It's been a while! Working now.

**Comment by tomcw** [comment]
@sicklittlemonkey / Nick - FYI, there's a new AppleWin 1.29.14.0 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.29.14.0/AppleWin1.29.14.0.zip) which contains this update.

**Comment by sicklittlemonkey** [comment]
Thanks Tom, I tested it as soon as you released it. Working on my personal
Win 10 PC, but not my work PC. (Might be A/V etc. Some error about "TFE"
blah blah mentioning Vice.)

**Comment by tomcw** [comment]
I guess it's this error you are getting...?
https://github.com/AppleWin/AppleWin/blob/24e6b7c132711f22ad6fa2803bd881cd3c16ffb7/source/Configuration/PageConfigTfe.cpp#L257

Maybe worth stepping through the `CPageConfigTfe::gray_ungray_items()` code to see where it's failing.

FWIW the old VICE KB article is preserved here: https://github.com/AppleWin/AppleWin/blob/master/docs/VICE%20Knowledge%20Base%20-%20Article%2013-005.htm

**Comment by sicklittlemonkey** [comment]
It is that error, thanks. I didn't think to take a screenshot and I
uninstalled Npcap because it (maybe) affected the stability of my VPN.

I'll step through when I can install Npcap again - sometime on a weekend.
