### ISSUE TITLE
RGB Monitor mode: HIRES+AN3 bug

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#828]
Spun off from PR #826, @fenarinarsa said:

On the HIRES+AN3 bug in RGB, here's what should show Digidream in RGB mode on a late RGB card (Apple/Feline/IIc adapter):

https://www.youtube.com/watch?v=YdZJa8QPuUw

Currently in AW when it goes to B&W, it doesn't come back to color when AN3 is enabled again.
Also, as you can see, there is no pixel shift to the right. In RGB there's no half-pixel shift at all, in any mode.

**Comment by tomcw** [comment]
Triage & simple repro:
- set video mode = "Color (RGB Monitor)"
  - In `NTSC_SetVideoStyle()`, this sets `g_pFuncUpdateHuePixel = updatePixelBnWMonitorSingleScanline`
- boot to Applesoft, then switch to CALL -151
- `C050 N C057`  ; TEXT off, HIRES on
- `C05E N C05F N C05E N C05F` ; set FL1:FL0 = b#11 = 560 B&W mode
- `C05E` ; DHIRES on
- video goes B&W
  - In `NTSC_SetVideoMode()`, this sets `g_pFuncUpdateGraphicsScreen = updateScreenDoubleHires40` (*)
- `C05F` ; DHIRES off
- video remains B&W
  - In `NTSC_SetVideoMode()`, this sets `g_pFuncUpdateGraphicsScreen = updateScreenSingleHires40Simplified`
  - `RGB_Is560Mode() == true`, so updateScreenSingleHires40Simplified() renders in B&W

(*) NB. Unlike other modes, there is no implementation for a "updateScreenDoubleHires40Simplied()", so the update function uses this Color/B&W (NTSC) TV function instead.

The complete list of missing "RGB" (or simplified) functions are:
- updateScreenDoubleHires40Simplied()
- updateScreenDoubleLores40Simplied()

**Comment by fenarinarsa** [comment]
This issue is not about DHIRES but about HIRES in RGB on the Apple card and others like Le Chat Mauve, IIc RGB adapters

To reproduce :
* set video mode to "Color (RGB Monitor)"
* boot to Applesoft, swith to `CALL -151`
* `C050 N C057 N C053` - TEXT off, HIRES on, MIXED on
* HGR should appear in color
* `C05E` - AN3 off ("DHIRES on")
* HGR should appear in B&W
* `C05F` - AN3 on ("DHIRES off")
* HGR should appear in color again

**Comment by fenarinarsa** [comment]
(I deleted my comment since it's not relevant)

**Comment by tomcw** [comment]
NB. "Color (RGB Monitor)" has now been split into
1. "Color (Composite Idealized)"
2. "Color (RGB Card/Monitor)"

For (1), this commit (a3f598917659816cd61bc6570bf2191ca21a0bb9) now deals with the missing `updateScreenDoubleHires40Simplied()`, by handling both SingleHires40 & DoubleHires40 in `updateScreenHires40Simplified()`.

**Comment by tomcw** [comment]
Closing this issue, since it was opened for PR #826 (now merged to master) + commit a3f5989 fixes the case for the "Idealized" video mode.
