### ISSUE TITLE
New feaure: copy text buffer to clipboard

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#829]
playing a text adventure and thought that it would be useful to be able to copy the currently shown text screen to the windows clipboard.
I would like to save room descriptions to a text file and if I could just copy the current text screen, it would be really useful.

**Comment by tomcw** [comment]
Sounds useful. We could use `Ctrl+Insert` to do this (ie. mirroring bash `Ctrl+Insert`=Copy / `Shift+Insert`=Paste).

Or the built-in debugger already uses:
>Ctrl+PrintScrn: Copy the text screen (auto detect 40/80 columns) to the clipboard.

Perhaps switch the built-in debugger to use `Ctrl+Insert` too (for consistency) ?

**Comment by audetto** [comment]
Indeed, already implemented as `Ctrl-PrintScreen`
