### ISSUE TITLE
disk2 loads wrong sector after disk switch in "authentic speed"

### ISSUE THREAD

**Issue by deater** [AppleWin/AppleWin#831]
I noticed this with my Mist demake, but I've simplified it down to a simple test case.

step1:    code loads track0:sector0 of disk, loads properly.
step2:    switch to 2nd disk.
step3:    code loads track0:sector0,  **wrong sector is read**, it reads sector 14 instead?

if the code tries again to read track0:sector0, reads properly

this only happens with authentic speed, can't trigger with enhanced speed

I can reproduce this with 1.29.14.0 (running under Linux via wine if that matters)

simplified test case attached:
[disk_test.zip](https://github.com/AppleWin/AppleWin/files/5170444/disk_test.zip)

  boot disk 1, press keys until prompted to insert disk2, then press keys.

**Comment by deater** [comment]
sorry for the false alarm, turns out this was a bug in qkumba's qboot code

it's an oddly specific bug, I tried on various emulators and it only triggered on AppleWin

**Comment by tomcw** [comment]
Hi Vince - glad you got this sorted.
Arguably a bug in AppleWin if authentic vs enhanced is different behaviour.
I'll keep an eye on https://github.com/peterferrie/qboot for his fix!

**Comment by tomcw** [comment]
>Arguably a bug in AppleWin if authentic vs enhanced is different behaviour.

I checked which which of "authentic" code is causing this difference. It's in Disk2InterfaceCard::ReadWrite():
```
	if (!m_enhanceDisk && pDrive->m_spinning)
```
This code looks at the time between the previous & current r/w of the latch (eg. $C0EC), and advances the track's nibble pointer accordingly. It only does this for "authentic" disk speed.

I'd have to see the qboot bug to look at this further.

**Comment by deater** [comment]
The fix to the qboot bug is to change the first two lines of the "seek" routine from LDA/STA to LDX/STX

I'm under the impression it is a timing thing that was mostly working due to luck, but I don't know for sure.

Probably not related to this situation but there's an additional bug I managed to trigger in qboot if you start reading from a non-zero sector and wrap around to the next track.  qkumba also found and fixed that bug but not sure if/when he's going to update his git tree
