### ISSUE TITLE
Support non-English character sets

### ISSUE THREAD

**Issue by rzumer** [AppleWin/AppleWin#835]
Non-English software displays the wrong symbols for some characters depending on the script.

At least I would like to be able to select a character set (from a bitmap) at runtime, and, ideally, select from multiple built-in regional bitmaps from the settings. Allegedly Virtual II supports this.

I found a (reconstructed) bitmap for French systems [here](http://ctrl.pomme.reset.free.fr/index.php/des-caracteres-accentues-avec-applewin-oui-cest-possible/). The complete one is the link on "fichier" at the bottom of the article.

**Comment by tomcw** [comment]
Currently you can use the command line `applewin.exe -videorom <file>` to switch to alternative video ROMs. See AppleWin.chm for a few more details.

www.reactivemicro.com has many video roms (see ReActiveMicro Support Sites -> RM Downloads...)

**Comment by rzumer** [comment]
Thanks for the info, I hadn't noticed that setting.

**Comment by tomcw** [comment]
Closing, as question answered.
