### ISSUE TITLE
não esplica os comandos do software/sistema emulado   

### ISSUE THREAD

**Issue by code344** [AppleWin/AppleWin#836]
não esplica os comandos do software/sistema emulado   e não esplica como salval um codigo em BASIC em uma imagem dsk
para inicialisar ou dar boot

**Comment by sicklittlemonkey** [comment]
"does not explain the commands of the emulated software / system and does
not explain how to save a BASIC code in a dsk image to boot or boot"

The topic of how to use Applesoft Basic and Apple DOS are covered in many
books and other sources. Here is a summary of DOS 3.3 commands including
saving a Basic program and booting a disk:
https://apple2.org.za/gswv/a2zine/GS.WorldView/Resources/ARTICLES/DOS.MiniManual.html

**Comment by tomcw** [comment]
Closing as Nick answered the question.
