### ISSUE TITLE
Looking for 1.27.13 to change save state from v1 to v2

### ISSUE THREAD

**Issue by davidk64fnq** [AppleWin/AppleWin#839]
Per help in current version for save/load state:

"NB. Loading of the old v1 file format (.aws file) is no longer supported. Use AppleWin 1.27.13 to load it at the AppleWin start-up/logo screen, then immediately save it (and it'll be saved in the v2 format)."

Can somebody point me to download location for this version please?

Alternatively could you resave attached state file for me?
[Wizardry_Dragon.zip](https://github.com/AppleWin/AppleWin/files/5282195/Wizardry_Dragon.zip)

Thanks

**Comment by tomcw** [comment]
1.27.13.0 is here: https://github.com/AppleWin/AppleWin/releases/download/v1.27.13/AppleWin1.27.13.0.zip

As the help says: do the load->save conversion at the AppleWin start-up/logo screen.

**Comment by davidk64fnq** [comment]
That worked - many thanks. I can't believe I didn't see the releases link on right hand side of screen. I just scrolled down and saw only one previous release at bottom and couldn't see a link to releases across the menu bar at top. 

It happened because I started out using an older version then downloaded the newest one. Is it possible for other sites to hyperlink to the latest download version zip file and the link still works if a new release comes out? If so, what would the URL be?

**Comment by sicklittlemonkey** [comment]
I don't think that's possible because the asset name of the AppleWin ZIP
file includes the version number, but I might be wrong.
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/linking-to-releases

Cheers,
Nick.

**Comment by tomcw** [comment]
Perhaps get AppleWin to check for new updates?

**Comment by davidk64fnq** [comment]
If you check this page:

http://www.zimlab.com/wizardry/mods/dragonquest.htm

you'll see Eric (snafaru) has linked to github but hosted version 1.25.0.3. I downloaded that version and started playing before downloading the latest version. 

Yes getting AppleWin to check for new updates would have avoided the issue I encountered.

**Comment by tomcw** [comment]
Closing this issue, as I've created a new issue to track demand for AppleWin checking for updates.

**Comment by davidk64fnq** [comment]
Thanks for that!
    On Sunday, 18 October 2020, 09:15:08 pm AEST, TomCh <notifications@github.com> wrote:  
 
 


Closing this issue, as I've created a new issue to track demand for AppleWin checking for updates.
