### ISSUE TITLE
g_CardMgr and m_ConfigNew order of initialisation

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#843]
Hi,
I am constantly battling with the order of initialisation of these 2 global variables.
g_CardMgr must happen first as otherwise it generates a segfault.

VS for some reason seems to get it the "right" way, but there is no guarantee in the C linker for which happens first and sometimes gcc does it the "wrong" way.

If I replace g_CardMgr with a function like this, so it forces it to be initialised the first time is used:

.... get_card_manager() {
  static g_CardMgr;  // global card manager
  return g_CardMgr
}

would the patch be accepted?

**Comment by tomcw** [comment]
Hi @audetto:
Yes, this sounds good. I just need to merge in a pull-request first before making this change (to avoid a merge conflict).

---

My dev note:
```
applewin.h:

extern class CardManager& GetCardMgr(void);

applewin.cpp:

CardManager& GetCardMgr(void)
{
	static CardManager g_CardMgr;	// singleton
	return g_CardMgr;
}
```

**Comment by audetto** [comment]
Perfect
