### ISSUE TITLE
Default AppleColor RGB card is not working correctly.

### ISSUE THREAD

**Issue by xotmatrix** [AppleWin/AppleWin#851]
The default card is supposed to be the Extended 80-Column Text/AppleColor Adaptor Card. Whether set by default or explicitly through the command line with `-rgb-card-type apple` it doesn't work correctly.

1. Start the Apple //e emulator
2. Configure video to RGB Card/Monitor
3. Boot the Apple Extended 80-Column AppleColor demo disk linked below.
4. Right away during it's self-running demo you will see the problems like uncolored Apple logo, colored 560x192 text.
5. Hit ESC, select 5 for the Video Mode demo.
6. Demo 7 (16 color F/B 40-col text) doesn't work (ie. no color).
7. Demo 8 (16-color Low-Res w/ F/B text) doesn't work (ie. no color).
8. Demo 10 (16-color F/B High-Res) doesn't work (ie. no color).

As I understand it, AppleColor should support every mode the Video-7 does but I do not have either cards to confirm this. The demo disks for both cards are extremely similar. Running the AppleColor demos with the Video-7 shows it working better, though not without problems like those seen in #850. Regardless, one should expect the AppleColor demos to work with the AppleColor card.

Interestingly, the AppleColor card emulation can render the undocumented 16-color 160x192 mode of the Video-7 (as it should). Will Scullin has tested the 16x160x192 mode on his AppleColor card. @tomcw may recall that discussion from June on Apple2Infinitum. Maybe Will would be up for further tests.
![IMG_5147](https://user-images.githubusercontent.com/14209329/97123016-0bc79480-1700-11eb-9891-251b80531e5a.jpeg)

![Applewin_2020-10-25_20-13-14](https://user-images.githubusercontent.com/14209329/97122742-8a233700-16fe-11eb-91f4-db253487d889.png)
![Applewin_2020-10-25_20-13-39](https://user-images.githubusercontent.com/14209329/97122756-b63eb800-16fe-11eb-9067-478778b5798d.png)
![Applewin_2020-10-25_20-15-09](https://user-images.githubusercontent.com/14209329/97122781-cc4c7880-16fe-11eb-88f5-711f6eb60e71.png)
[Apple Ext80ColumnAppleColorCardHR Demo 1.zip](https://github.com/AppleWin/AppleWin/files/5436205/Apple.Ext80ColumnAppleColorCardHR.Demo.1.zip)

**Comment by tomcw** [comment]
Hi @xotmatrix - with this issue (and #850), it looks like we still have a bit more work to do, and then I need to add more tests to the suite.

Both me and/or @fenarinarsa will take a look.

**Comment by tomcw** [comment]
@fenarinarsa - I applied this patch (fb08716) but for this issue (using `-rgb-card-type apple`), I'm still only getting B&W images for the HIRES Apple logo and the HIRES text describing the 4 colours for text, ie:

![logo](https://user-images.githubusercontent.com/6696896/97784247-22a13780-1b95-11eb-98b7-ed84c9506d03.png)
![hires-text](https://user-images.githubusercontent.com/6696896/97784251-259c2800-1b95-11eb-9202-595dcb268132.png)

But if I use `-rgb-card-type sl7`, then they render correctly in colour:

![logo-colour](https://user-images.githubusercontent.com/6696896/97784300-6f850e00-1b95-11eb-9127-e75285ae3e99.png)
![hires-text-colour](https://user-images.githubusercontent.com/6696896/97784302-727ffe80-1b95-11eb-9252-3e4b2cedeb9f.png)

NB. This is Apple's disk (`Apple Ext80ColumnAppleColorCardHR Demo 1.dsk`) for their AppleColor card, so clearly the AppleColor card supports this HIRES Duochrome mode, just like Video7's SL7-RGB card.

So perhaps there isn't any difference between the AppleColor card and Video7's card?
IE. For `-rgb-card-type` is `apple` just an alias for `sl7`?

**Comment by xotmatrix** [comment]
I don't have great pictures but the hardware of the Video-7 RGB-SL7 and the Extended 80-Column Text/AppleColor look identical. The AppleColor also supports modes that are only documented with the RGB-SL7.

![EaFwyNVWAAAg_PG](https://user-images.githubusercontent.com/14209329/97784963-b0225e80-1b78-11eb-9a60-c42384929338.jpg)
![EaFzIbuWkAUd583](https://user-images.githubusercontent.com/14209329/97784969-b7e20300-1b78-11eb-8f1c-0dbf1a8505ff.jpg)

**Comment by fenarinarsa** [comment]
I found some other documentation about the "Apple Color" card:
http://www.txbobsc.com/aal/1986/aal8608.html#a6
It talks about the F/B HIRES mode and DHIRES 160 mode, which is a feature of the SL7.

However the SL7 doesn't support mixed DHIRES mode, so I thought this card doesn't either. I always read than the Apple "RGB" card was made under patent of Video-7.

What's strange is that the Apple RGB demo disk is different from the one you have (`AppleII80columnRGBColorCard-ProDOS.dsk`). It doesn't show all the SL7 video modes like the F/B HIRES.

On the other hand [the AppleColor manual](https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Interface%20Cards/Apple%20IIe/Apple%20IIe%20Extended%2080%20Column%20RGB%20Card/Manuals/) doesn't talk about all those extended modes. But you can see that the AppleColor card supports mixed DHIRES, which was not the case of the SL7.
Also, this manual doesn't list the 240x192 monochrome HIRES mode at all, so I guess it doesn't exist (it may be the F/B mode of the SL7). I always assumed than the original RGB implementation in AppleWin was based on an Apple RGB card. So maybe that mode was added on Le Chat Mauve cards?

Or maybe that 240x192 HIRES was added for all the various IIc adapters?

In addition I must also say that I read many times that the AppleColor card was a TTL card, so the colors may be different.

So far my guess is that the AppleColor is the same card than the SL7, with mixed DHIRES added, and Apple hid the old SL7's modes in the manuals.

I can't really guess more without having the actual cards to test.

**Comment by tomcw** [comment]
>What's strange is that the Apple RGB demo disk is different from the one you have (`AppleII80columnRGBColorCard-ProDOS.dsk`). It doesn't show all the SL7 video modes like the F/B HIRES.

From the downloaded images I have, I did a binary compare and:
- `Apple Ext80ColumnAppleColorCardHR Demo 1.dsk` == [AppleII80columnRGBColorCard-DOS.dsk](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/hardware/video/AppleII80columnRGBColorCard-DOS.dsk)
- `Apple Ext80ColumnAppleColorCardHR Demo 2.dsk` == [AppleII80columnRGBColorCard-ProDOS.dsk](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/hardware/video/AppleII80columnRGBColorCard-ProDOS.dsk)

NB, there's a bug in the Demo 1/DOS.dsk for option 3 'Art Show Case', where the BASIC code crashes to the AppleSoft prompt!
Here's a fixed image (by me): [Apple Ext80ColumnAppleColorCardHR Demo 1 - fix.zip](https://github.com/AppleWin/AppleWin/files/5471213/Apple.Ext80ColumnAppleColorCardHR.Demo.1.-.fix.zip)
And my patch to the `ART SHOW CASE` BASIC program: [ArtShowCase-patch.txt](https://github.com/AppleWin/AppleWin/files/5471221/ArtShowCase-patch.txt)

>But you can see that the AppleColor card supports mixed DHIRES, which was not the case of the SL7.

But from the disk: `Video-7 Apple II RGB Demo (Video-7, Inc.)(1984).dsk`:

![Video-7 Video Modes](https://user-images.githubusercontent.com/6696896/97807739-79bd1000-1c5a-11eb-8ec5-801fe22b248c.png)

Selecting 14...

![Video-7 Video Mode 14 - Mixed 140 and 560](https://user-images.githubusercontent.com/6696896/97807745-817cb480-1c5a-11eb-8886-418110c9c464.png)

This is what you mean by "mixed DHIRES", right?

>Also, this manual doesn't list the 240x192 monochrome HIRES mode at all

What do you mean by "240x192 monochrome HIRES" mode?

Anyway, for now I will assume that AppleColor card == Video7's RGB-SL7 card.
(If anyone discovers any differences then we can fix it in a later release)

**Comment by fenarinarsa** [comment]
> ![Video-7 Video Mode 14 - Mixed 140 and 560](https://user-images.githubusercontent.com/6696896/97807745-817cb480-1c5a-11eb-8886-418110c9c464.png)
> 
> This is what you mean by "mixed DHIRES", right?

I was completely wrong. Sorry. Of course it supports mixed DHIRES.

> 
> > Also, this manual doesn't list the 240x192 monochrome HIRES mode at all
> 
> What do you mean by "240x192 monochrome HIRES" mode?

The mode that you get when in HIRES you disable AN3. On SL7 it's F/B HIRES, and AppleWin previously implemented it as 280x192 monochrome (and not 240x192 sorry), so I thought it was a feature of the AppleColor.

It looks like it was introduced in later IIe RGB cards and maybe all IIc RGB adapters.

> 
> Anyway, for now I will assume that AppleColor card == Video7's RGB-SL7 card.
> (If anyone discovers any differences then we can fix it in a later release)

Indeed.

**Comment by tomcw** [comment]
>The mode that you get when in HIRES you disable AN3.

This is the composite video mode where in HIRES, bit7 (palette bit) is ignored, so HIRES colours are only: black, white, purple and green (ie. no orange/blue). And the effect was used in FT's DIGIDREAM demo.

>On SL7 it's F/B HIRES, and AppleWin previously implemented it as 280x192 monochrome (and not 240x192 sorry), so I thought it was a feature of the AppleColor.

Actually I think this is a edge-case mode (B&W 280x192 HIRES). I think you can display it by enabling B&W 560 DHIRES, and then switching to HIRES. Eg, in #631, this (French?) guy reported it for Mousepaint using Apple //e with Le Chat Mauve RGB card, where he says "For MousePaint 1.1: if launched via MouseDesk 2.0 1.1 French" and shows a photo of B&W Mousepaint.

Yes, AppleWin previously implemented this, but like I say it's an edge-case, so can probably be ignored. Perhaps it was only LCM that had support for this edge-case?

Also I know with LCM there are extra soft-switches in $C0Bx to set B&W mode.
(I see that [Apple II Desktop](https://github.com/a2stuff/a2d) will support this at v1.2)

**Comment by fenarinarsa** [comment]
> Yes, AppleWin previously implemented this, but like I say it's an edge-case, so can probably be ignored. Perhaps it was only LCM that had support for this edge-case?

I don't think this is an edge case. It's documented in the LCM Féline's manual, as it is in the LCM and Video-7's IIc adapters. It looks like it HGR + AN3 off was chosen to be the HGR B&W mode by later cards and adapters.

Féline (IIe):
![image](https://user-images.githubusercontent.com/17545417/97888530-8493a580-1d2b-11eb-8abf-253b58b4dd48.png)

Video-7 for Apple IIc:
![image](https://user-images.githubusercontent.com/17545417/97889225-65494800-1d2c-11eb-99d4-cbce7236d3da.png)

The Video-7 Apple II RGB demo disk, when ran from a IIc - you can also get this menu by breaking to AppleSoft while in the main menu and doing `RUN VIDEO MODES2C`:
![image](https://user-images.githubusercontent.com/17545417/97889352-932e8c80-1d2c-11eb-9aad-f6f75bbeda0d.png)


> 
> Also I know with LCM there are extra soft-switches in $C0Bx to set B&W mode.
> (I see that [Apple II Desktop](https://github.com/a2stuff/a2d) will support this at v1.2)

Yes, that's on the EVE card, which is older than Féline. You need to activate those switches to enable the HIRES B&W mode (and three other modes, actually).
EVE is even more complex because it spies on the bus for every write access to $0400-$07FF and $2000-$3FFF, in F/B TEXT and F/B HIRES mode, to write the soft-defined default F/B colors in AUX. It's the most complex RGB card I saw so far.

![image](https://user-images.githubusercontent.com/17545417/97889899-31baed80-1d2d-11eb-95f3-0b8b80e4939e.png)

**Comment by tomcw** [comment]
>I don't think this is an edge case. It's documented in the LCM Féline's manual, as it is in the LCM and Video-7's IIc adapters. It looks like it HGR + AN3 off was chosen to be the HGR B&W mode by later cards and adapters.

Ah, I didn't know this!
Thanks for sharing all these details directly here.

Since this doesn't relate to the //e RGB cards (AppleColor and Video7's RGB-SL7) then support for this "HGR + AN3 off" mode can be dealt with in another issue (eg. relating to LCM support).

**Comment by tomcw** [comment]
@xotmatrix - try this new build [AppleWin 1.29.16.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.16.0) - let us know how this goes.

**Comment by xotmatrix** [comment]
Looks good!

**Comment by tomcw** [comment]
Thanks for confirming. Closing.
