### ISSUE TITLE
Windows Mouse not supported

### ISSUE THREAD

**Issue by markem** [AppleWin/AppleWin#857]
I may be wrong but on my system the mouse does now work with AppleWin. This is VERY unfortunate because it means it will not work with Mouse Desktop (Apple Desktop). What is weird is the Agat emulator works with no problem. I have a standard Microsoft Mouse (Optical). Now - AppleWin will capture the mouse - but it will not use the mouse - even in Glen Bredon's ProSel. Ideas?

**Comment by tomcw** [comment]
Can you attach a zip of the save-state file and the disk image (during the emulation "not working" state)? and I can take a look.

**Comment by markem** [comment]
Sure. Hard drive is a PO file named HD1.PO. Here are the links:

https://www.dropbox.com/s/xc5bd9yzf8gpvy0/HD1.po?dl=0

https://www.dropbox.com/s/9p0t198gaf0nqlb/SaveState.aws.yaml?dl=0

**Comment by markem** [comment]
Might I suggest a feature? Put ALL option information into the INI file so people do not have to guess how to express options. For instance: In the documentation to mount a hard drive is the option "-h1" but in the INI file it is "Last Harddisk Image 1=". Should not the INI file's preferences be the same as the options? Or should the documentation be changed to refect the Preferences?

**Comment by tomcw** [comment]
I can see from your save-save that you have a Phasor card in slot-4, when you need a Mousecard in slot-4.
Use the Configuration UI (using both Sound & Input tabs) to (a) remove Phasor, and (b) add Mousecard.

**Comment by markem** [comment]
Done. Works.

Are there any other desk accessories available? Like change the background et al?

**Comment by tomcw** [comment]
Desk accessories for AppleWin? No, there's nothing AFAIK.

**Comment by markem** [comment]
All I know is that the //gs originally used Apple Desktop and used it as an 8-bit system. Looking for the original //gs software. Might have some items in it that can be used.

**Comment by tomcw** [comment]
>Should not the INI file's preferences be the same as the options? Or should the documentation be changed to refect the Preferences?

The INI file is just a mirror of what gets persisted to the Windows Registry (eg. if you want to have multiple copies of AppleWin with different configs, or don't want to use the Registry). It is not something we want to expose, as it's meant to be internal-only.

>All I know is that the //gs originally used Apple Desktop and used it as an 8-bit system. Looking for the original //gs software. Might have some items in it that can be used.

You could try asking these guys: https://github.com/a2stuff/a2d

**Comment by inexorabletash** [comment]
More end-user facing docs: https://a2desktop.com

**Comment by markem** [comment]
Thanks! :-)

**Comment by tomcw** [comment]
Resolved issue, so closing.
