### ISSUE TITLE
Include file normalisation

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#862]
Having played with AW in linux for different frontends I would like to simplify the usage of #include.

Header files are not "self contained" and must be included in a particular order.
I would like to propose a PR where each and every .h can be included without worrying about the order, only requiring "stdafx.h" before.

Would this be accepted?

**Comment by tomcw** [comment]
I guess this change will affect many (all?) files, but only at the top of each file (where the includes are).
>Would this be accepted?

Submit a PR, and let's have a look at how pervasive this change is.

**Comment by audetto** [comment]
https://github.com/AppleWin/AppleWin/pull/866

Now all .h can be included without special order requirements.

**Comment by tomcw** [comment]
Updated CodingConventions.txt in 8811651.
PR merged, so closing.
