### ISSUE TITLE
160KB DSK Image support

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#87]
**BerliOS Feature Request #4477**

**Date:** 2009-February-09 16:28
**Submitted By:** softgear
**Category:** none
**Assigned To:** tomch
**Priority:** 5
# 

Date: 2009-Feb-09 16:28
Sender: softgear
Logged In: YES 
user_id=50244
Browser: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; IPMS/284E807A-149901E6AAA;
Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; SLCC1; .NET CLR 2.0.50727;
.NET CLR 3.0.04506; InfoPath.2)

I have some .DSK images which has 160KB size 
instead of 140KB. This has just a extended track. 
The format of these images are the same to the 
format of normal 140KB images.
But, AppleWin couldn't read these images.
Please, Modify AppleWin to support them.

**Comment by ngchungtak** [comment]
Please, Modify AppleWin II e emulator to support to 42 tracks version. It will be easily for me to crack game.
