### ISSUE TITLE
Starting up windowed mode & fullscreen mode.

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#876]
Is there a way to start Applewin in windowed mode while still specifying -fs-height=768 on the command line?

I most always want to start in windowed mode, but occasionally switch to fullscreen and have it properly scale to my display. And using -fs-height=768 scales it perfectly the way I want but at the same time forces fullscreen.

**Comment by tomcw** [comment]
Currently `-fs-height=<best|nnnn>` implicitly forces AppleWin to start in full-screen mode.
Also `-f` starts AppleWin in full-screen mode, but there's no complementary "start in windowed mode".

So perhaps a new cmd line switch to start in windowed mode, eg. `-no-full-screen`.
Also add `-full-screen` as an alias for `-f`.

**Comment by tomcw** [comment]
@Keatah: I've released [AppleWin 1.30.0.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.0.0(try2)), which adds a new cmd line switch to start in windowed mode: `-no-full-screen`. Please try it and confirm.

**Comment by Keatah** [comment]
It partly works. It does indeed start in desktop mode. The new issue is that it now scales and distorts the desktop while in windowed mode. I believe the desktop resolution should be left alone. Or only change it when Applewin is in fullscreen mode.

Well don't fret over it. I can workaround with a batchfile or two setting different registry entries as needed.

**Comment by tomcw** [comment]
Ah, I understand better now:

If using `-fs-height=768` together with `-no-full-screen` then start-up in regular Windowed mode (retaining your current resolution), but if you switch to full-screen then change the resolution (eg. to height=768 in this case).

Since you are the only one requesting this, then I think it's fine to change the behaviour in the next release to what you are asking for.

**Comment by Keatah** [comment]
Yes Thanks.

**Comment by tomcw** [comment]
@Keatah - try this new [AppleWin 1.30.2.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.2.0) which should resolve this issue. Let me know.

**Comment by Keatah** [comment]
@tomcw - Yes. I'm pleased with how it works now.
Thanks to you and the team for continued work on this important piece of software.

**Comment by tomcw** [comment]
Great - thanks for confirming.
