### ISSUE TITLE
OzDOS booting error

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#88]
**BerliOS Bug #15257**

**Date:** 2009-February-13 00:48
**Submitted By:** softgear
**Category:** 1.16.0 (beta)
**Bug Group:** Future request
**Assigned To:** tomch
**Priority:** 5
# 

OzDOS is a variant of DOS 3.3 for 3.5" disk. 
OzDOS image is .po file which has 800K.  I extracted po file from original .bxy file in asimov FTP. You may download it from
http://mfiles.naver.net/68b85c8392caa4123f50/data38/2009/2/10/153/ozdos1.0r8.po?type=attachment .

In AppleWin 1.16.0.0-beta, I connected ozdos.po as HDD. However, It couldn't boot but I just display some binary code as following on AppleWin screen.
   Oz DOS 1.0
        Slot: 7
2204-     A=01 X=00 Y=00 P=75 S=F8
*

I tested this po image at KEGS. It works well.

**Comment by SEGStriker** [comment]
We have already 3.5" FDD controller requests. If added, it will solve all issues.

**Comment by tomcw** [comment]
For AppleWin versions: 1.22.0.0 - 1.30.17.0 (inclusive), you get this message:

![ozdos1 0r8-device-too-small](https://github.com/user-attachments/assets/981be2e5-529a-44b2-9f0a-08fa1a91c4aa)

NB. from the History.txt of 1.22.0.0:
```
. HDD firmware: Added support for SmartPort entrypoint.
```

Then at AppleWin 1.30.18.0, it appears to work:

![ozdos1 0r8](https://github.com/user-attachments/assets/2302b232-6705-4d3e-8cc7-5b924145415a)

From the History of 1.30.18.0:
```
. New HDC firmware v2 to support returning HDD size in Y:X for status call.
```

So I'm guessing that from 1.22.0.0 to 1.30.17.0 the HDC firmware was returning a bogus value in Y:X (but less than 800KiB or 1600 blocks).

Finally from a dump of the HDD cmds, there are no SmartPort commands.

**Comment by SEGStriker** [comment]
> [2009-February-16 00:35, by: softgear]
> 
> That link was broken.
> 
> I uploaded it on http://dcn.ssu.ac.kr/~softgear/apple/ozdos1.0r8.po

Hmmm… can't reach this page
dcn.ssu.ac.kr took too long to respond

**Comment by tomcw** [comment]
This doesn't appear to be working correctly, so I will reopen this issue.
EG. `CATALOG` or `CATALOG,S7` after a few seconds just returns a blinking cursor (without any catalog shown).

From the instructions (from your link) it says:
>GETTING STARTED
>
>  Oz-DOS boots exactly the same as a
>normal DOS diskette. The only difference, is that it cannot be moved on to a 5 1/4" diskette.
>  Insert the Oz-DOS MASTER
>DISKETTE into the drive, and power on the machine. In a couple of seconds, you should see the Applesoft HELLO program
>display a menu.

But there's no menu displayed.

**Comment by tomcw** [comment]
I quickly tried in MAME, and it boots...
```
mame apple2gs -w -flop3 ozdos1.0r8.po
```

![ozdos-apple2gs](https://github.com/user-attachments/assets/9451545a-7a39-4d39-8f1f-3a9fb5f6054c)

**Comment by tomcw** [comment]
Under MAME, IIgs:
- `eject` works, as a `catalog` afterwards results in "I/O ERROR"

**Comment by tomcw** [comment]
Under AppleWin, Enh //e:
- `eject` does nothing (presumably Oz-DOS has determined that the device isn't a Unidisk). This is contrary to the [doc](https://macgui.com/downloads/?file_id=9094), which says:
  - "If you try to EJECT a device that is not a Unidisk, you will get a VOLUME MISMATCH error."
- After formatting, the the disk doesn't boot (correct).
- After (1) "Create bootable DOS Oz-DOS disk" or (3) "Master create (Make a disk boot)", the disk still doesn't boot!
  - `This Oz-DOS disk does not boot.`

**Comment by univta0001** [comment]
> I quickly tried in MAME, and it boots... (Apple IIgs though, couldn't get Apple IIe to work with "superdrive")
> 
> ```

It is possible to start this image using Apple IIee and IIcp using the following commands in MAME

1) For Apple IIe, 
    mame apple2ee -sl6 superdrive -skip_gameinfo -flop1 "Oz-Data - Oz DOS 1.0r8.po"

2) For Apple IIc plus
    mame apple2cp -skip_gameinfo -flop3 "Oz-Data - Oz DOS 1.0r8.po"

**Comment by tomcw** [comment]
Thanks - although for the `apple2ee` I'm missing the superdrive rom :-/

**Comment by univta0001** [comment]
The superdrive rom can be found at https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Interface%20Cards/Disk%20Drive%20Controllers/Apple%20II%203.5%20Disk%20Controller%20Card/ROM%20Images/

**Comment by tomcw** [comment]
Thanks - that superdrive rom worked (after renaming to 341-0438-a.bin, and adding it to a zip file named a2superdrive.zip).

Booting identifies the drive as "Apple 1 meg":

![image](https://github.com/user-attachments/assets/81fc1552-60c5-4859-9050-8009495ee8e0)


- `eject` does nothing.
- "Oz-DOS Create", then (1) "Create a bootable DOS Oz-DOS disk":
  - "Formatting...." completes
  - Switch to MASTER disk to read some blocks (OK)
  - Switch back to SLAVE disk to write some blocks (OK)
  - This boots to the Applesoft/DOS prompt, albeit with a FILE NOT FOUND error (presumably as there's no HELLO program)

**Comment by tomcw** [comment]
Closing as BLK FORMAT is now supported by firmware & HDC.
