### ISSUE TITLE
Add command line parameter to auto-load HDD image in slot 7 and boot.

### ISSUE THREAD

**Issue by 8bit-Dude** [AppleWin/AppleWin#887]
This issue is related to https://github.com/AppleWin/AppleWin/issues/104

I package AppleWin with my 8bit-Unity SDK, and use the command parameter -d1 to auto-load and start disk images from builder scripts.

Going to 800K disks, they can only be loaded in Slot 7. But there is no command line option to auto-load and start these disks. Could you please consider adding a command line parameter? (or... allow 800K on Slot 5/6).

**Comment by tomcw** [comment]
>Going to 800K disks, they can only be loaded in Slot 7. But there is no command line option to auto-load and start these disks.

btw, you can use -h1 <image> to mount a harddisk or 800K image in slot 7.

From the AppleWin.chm help:
>Start with hard disk 1 plugged-in (and auto power-on the Apple II). NB. Hard disk controller card gets enabled.

Does that help?

**Comment by 8bit-Dude** [comment]
It does!! I was using an older version of AppleWin, which did not have the -h1 parameter.
I confirm that I was able to load and autorun an 800K disk this way, thanks!
