### ISSUE TITLE
Can't Find Executable

### ISSUE THREAD

**Issue by andypandy00** [AppleWin/AppleWin#897]
I just downloaded the zip file, extracted everything, and I can't find an Executable/installer. I'm probably just tired and missed it, but in case there's some weird external program I need to use, I thought I'd ask. Also tried using the WIN+r run command in windows directly, but don't use that often, so I probably didn't do it right.

Running Windows 10 64bit

**Comment by tomcw** [comment]
After unzipping the zip archive, then just double-click AppleWin.exe.

**Comment by philgoetz** [comment]
There is no AppleWin.exe in the zip file.  The zip file one gets if one clicks on the green "Code" button is the source code, in a zip file named AppleWin-master, which contains a directory named AppleWin-master, which contains many directories: assets, bin, ddraw_lib, etc.  It must be compiled to produce AppleWin.exe, using the instructions in ApleWin-master/docs/compiling.txt .

I have zip files for previous versions which I assume I downloaded from this site, which include just the files needed at runtime, but I don't see anyway to get such a zip file here on github.

**Comment by sicklittlemonkey** [comment]
It sounds like you accidentally downloaded the source archive.
Instead, please download the AppleWinX.XX.XX.X.zip, i.e.:
https://github.com/AppleWin/AppleWin/releases/download/v1.29.16.0/AppleWin1.29.16.0.zip

Cheers,
Nick.

**Comment by philgoetz** [comment]
How did you find that link?  I see nothing on the github page, or in the
docs, to tell anyone that it exists.

**Comment by sicklittlemonkey** [comment]
Releases are in green on the right of the GitHub webpage.

**Comment by philgoetz** [comment]
Ah!  Thanks.  I didn't look over there.

**Comment by tomcw** [comment]
>Download latest (stable) release: AppleWin v1.29.13.0

I've updated this to say & link to 1.29.16.0.
