### ISSUE TITLE
Strange new audio behavior--How to get sound under Windows 10

### ISSUE THREAD

**Issue by philgoetz** [AppleWin/AppleWin#899]
I've used AppleWin under Win 7 for almost 2 years.  I copied the same files over to a Win 10 64-bit machine, and the audio stopped working. I tried my versions back to 1.23, and the newest available version, 1.29.13, and got the same result.  This happens even if I have no other applications running except Windows Explorer.

I was able to get audio under windows 10 by going to config -> Sound, setting Device to "Sound Card" and Sound Cards to "Mockingboards".  Oddly, the sound volume after doing that depends on the Speaker volume rather than on the Mockingboard volume.

**Comment by tomcw** [comment]
Hmm, seems similar to #716, especially my last comment: https://github.com/AppleWin/AppleWin/issues/716#issuecomment-557900181.

I made this change at 1.29.7.0:
> For first-time installs of AppleWin, soundtype now defaults to WAVE (was NONE).

Seems like there's more work to do here (perhaps #355 ?).

**Comment by tomcw** [comment]
Closing this old issue, since you said that you were able "to get audio under windows 10".
