### ISSUE TITLE
BasicBot demo disk not working right?

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#906]
https://archive.org/details/bot_demo
https://archive.org/download/bot_demo/bot_demo.dsk

I'm out and about traveling and don't have access to my Apple II hardware. This disk locks up and won't run any demos IF Mockingboard sound is turned off in the sound tab on AppleWin. With MB cards in slot 4 & 5 or Phasor in slot 4 it works plays all the way through the fractal snowflake at the end.

Maybe it's a problem with AppleWin, maybe not. Tried it on 1.24.0 and 1.29.16.0. Same behavior.

Hate to not completely test the problem on real hardware myself. But if I don't mention it now I'll forget for months!

**Comment by tomcw** [comment]
@Keatah - I see you closed this.. was it just user-error on your part?

**Comment by tomcw** [comment]
Ah, I see there's still an open issue in the next issue: https://github.com/AppleWin/AppleWin/issues/907
