### ISSUE TITLE
BasicBot demo disk not working right?

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#907]
https://archive.org/details/bot_demo
https://archive.org/download/bot_demo/bot_demo.dsk

I'm out and about traveling and don't have access to my Apple II hardware. This disk locks up and won't run any demos IF Mockingboard sound is turned off in the sound tab on AppleWin. With MB cards in slot 4 & 5 or Phasor in slot 4 it works plays all the way through the fractal snowflake at the end.

Maybe it's a problem with AppleWin, maybe not. Tried it on 1.25.0.4 and 1.29.16.0. Same behavior.

Hate to not completely test the problem on real hardware myself. But if I don't mention it now I'll forget for months!

**Comment by tomcw** [comment]
The code is just infinitely looping here:
https://github.com/deater/dos33fsprogs/blob/357df41d9ca25f09872553d9360cf6540ff27db4/bot_demo/botdemo.s#L102

...waiting for an interrupt (which will never occur if there's no Mockingboard / Phasor present).

NB. From a quick look at the code, `trigger` gets set after `seconds` has counted up to `timeout` secs, with the timer interrupt occurring at 50Hz.

btw, from Vince's (Deater's) site [here](http://www.deater.net/weave/vmwprod/botdemo/), it says under "System Requirements":
>You need a Mockingboard Card, ideally in slot 4 

So I'm going to close this issue as "spec".
