### ISSUE TITLE
Base 64A: add support for F2 key

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#912]
In the comment https://github.com/AppleWin/AppleWin/pull/807#issuecomment-757461328, @ivanizag explains that the F2 key generates Apple II keycode 0x7F.

Windows keycode VK_DELETE generates Apple II code 0x7F for the Apple //e model, but not the older II/II+ models.

So when the model is Base 64A, then AppleWin just needs to support VK_DELETE too (but not VK_UP/VK_DOWN).

NB. I quickly hacked the code to test VK_DELETE for older Apple II models, and for Base 64A pressing/releasing DEL then another key results in the keyword being displayed.

**Comment by tomcw** [comment]
Commit 7d2ddb3 to use DELETE for special F2 key.

**Comment by audetto** [comment]
I started getting these warnings / errors with VS2019

... many more before this
  C:\Users\andrea\Documents\projects\AppleWin\source\Pravets.cpp(1,1): warning C4828: The file contains a character sta
rting at offset 0x18c9 that is illegal in the current source character set (codepage 65001). [C:\Users\andrea\Documents
\projects\AppleWin\AppleWinExpress2019.vcxproj]
  C:\Users\andrea\Documents\projects\AppleWin\source\Pravets.cpp(1,1): warning C4828: The file contains a character sta
rting at offset 0x18ca that is illegal in the current source character set (codepage 65001). [C:\Users\andrea\Documents
\projects\AppleWin\AppleWinExpress2019.vcxproj]


"C:\Users\andrea\Documents\projects\AppleWin\AppleWinExpress2019.sln" (default target) (1) ->
"C:\Users\andrea\Documents\projects\AppleWin\AppleWinExpress2019.vcxproj.metaproj" (default target) (2) ->
"C:\Users\andrea\Documents\projects\AppleWin\AppleWinExpress2019.vcxproj" (default target) (8) ->
(ClCompile target) ->
  C:\Users\andrea\Documents\projects\AppleWin\source\Pravets.cpp(214,23): error C2001: newline in constant [C:\Users\an
drea\Documents\projects\AppleWin\AppleWinExpress2019.vcxproj]
  C:\Users\andrea\Documents\projects\AppleWin\source\Pravets.cpp(215,2): error C2144: syntax error: 'char' should be pr
eceded by ';' [C:\Users\andrea\Documents\projects\AppleWin\AppleWinExpress2019.vcxproj]

The characters at lines 211-215 of Pravets are causing this.

It happens both on my Windows 10 and on a automated Travis build: https://travis-ci.org/github/audetto/AppleWin/jobs/754916936

**Comment by tomcw** [comment]
Sorry about that. Fixed at 44fa610.

**Comment by audetto** [comment]
Now it compiles, but looking at the length of the strings I have some doubts.
In code order, the sizeof are
32 34 64 62 62
Not sure how anything other than an old style codepage will work with a ``char`` as a return value.

For UTF-8, the interface should probably return a ``std::string`` and have something like a

``std::map<BYTE, std::string>``

to store the values.

BTW, in the constructor this is probably wrong

```
	bool g_CapsLockAllowed = false;
```

**Comment by tomcw** [comment]
re. `bool g_CapsLockAllowed = false;` ...ah yes, good spot!

And as for Pravets... all the Pravets support was added >10 years ago, when testing wasn't such a consideration. As a result there are no regression tests for any of these Pravets keyboard/printer specialisations, so making any changes to it has no guarantees... and equally since it's never tested, then that begs the question has it _ever_ worked?!

NB. this was actually broken 2 years ago when PR #604 was done to convert to UTF-8, resulting in this char array breakage as you noticed.

I can patch it up (as far as I can tell) but since there's no guarantees, then this could even be risky (ie. adding untested code to the project). IMO, better to just remove this Pravets printer specialisation. I guess I could try to make contact with the original guy that submitted this Pravets support...

**Comment by audetto** [comment]
If the choice is between 
- code which is wrong 
- or code not doing the Pravets remap
guess the choice is easy :-)

**Comment by tomcw** [comment]
OK, I've moved this Pravets issue over to #916.

**Comment by tomcw** [comment]
@ivanizag , @Drakepirate: FYI, I've released [AppleWin 1.30.0.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.0.0(try2)), which adds support for the `F2` via the Windows `Delete` key. Closing this issue.
