### ISSUE TITLE
settings file / reset to default values 

### ISSUE THREAD

**Issue by bcfrank1** [AppleWin/AppleWin#918]
Where AppleWin save settings?

The problem is that I messed with settings, now I wold restore deafult AppleWin settings deleting setting file but I can't find it...

It may be useful to add an optional to restore all settings to default values.

Sorry for my english :\

**Comment by tomcw** [comment]
In the folder that you unzipped AppleWin to, there is this file: `DELREG.INF`

On Windows 10, from Explorer, right click on this file, then select: Install
This remove all AppleWin configuration from the Registry.

**Comment by tomcw** [comment]
Updated AppleWin.chm with this information. Closing.
