### ISSUE TITLE
Learning with Fuzzywomp - .WOZ Freeze/Crash

### ISSUE THREAD

**Issue by GreatHierophant** [AppleWin/AppleWin#922]
The .woz image of Learning with Fuzzywomp, [located here](https://archive.org/details/ApplesauceImages), reboots after loading the game.  When you try to select one of the activities in the game, the disk will be accessed but the system will reboot regardless of which activity you choose with white stripes.  With an original Apple IIe and a wDrive, the system will do the same thing.  I verified that the image was good by converting the .a2r in Applesauce, which reported no errors.

**Comment by GreatHierophant** [comment]
The .woz file in the extras [here](https://archive.org/details/LearningWithFuzzywomp4amCrack) works.

**Comment by tomcw** [comment]
Hmm, I didn't download the 4.9GiB ApplesauceImages files, as instead you can click "Show all" to get at specific files inside the zip.

Anyway, for me the ApplesauceImages Fuzzywomp woz and the '4am and san inc' Fuzzywomp woz are **_binary identical_**!

ApplesauceImages version: [here](https://archive.org/download/ApplesauceImages/Learning%20with%20Fuzzywomp%20%28Sierra%20On-Line%29/Learning%20with%20Fuzzywomp%20-%20Disk%201%2C%20Side%20A.woz).
4am and san inc version: [here](https://archive.org/download/LearningWithFuzzywomp4amCrack/Learning%20with%20Fuzzywomp%20%284am%20and%20san%20inc%20crack%29%20extras.zip/Learning%20with%20Fuzzywomp%20%284am%20and%20san%20inc%20crack%29%20extras%2FLearning%20with%20Fuzzywomp%20-%20Disk%201%2C%20Side%20A.woz)

From the woz file:
- crc32=0x13ef4633
- woz v1
- Creator: "Applesauce v1.0.5               "

**Comment by tomcw** [comment]
btw, I tried selecting all 4 activities (in turn), and they all loaded ok, without any reboot.
