### ISSUE TITLE
Hi-Res Cribbage - Crashes with .woz

### ISSUE THREAD

**Issue by GreatHierophant** [AppleWin/AppleWin#928]
I finally was able to track down an .a2r of Hi-res Cribbage, released by On-line Systems, that converted to .woz in Applesauce without error.  Unfortunately when the image boots, it displays the title screen, then the main menu but the menu will not accept input and it gets stuck on track 3 and soon will show a screen of inverted @s.  I can strip the system down to a II or a II+ and the result is the same.  I also tried a wDrive, Floppy Emu, micoM8 and eapple and all show the same error.  

It could be that the image is broken in a way that Applesauce did 
not detect or the game is doing something previously unknown like Computer Foosball.
[Hi-resCribbage-Disk1SideA.zip](https://github.com/AppleWin/AppleWin/files/5975899/Hi-resCribbage-Disk1SideA.zip)

**Comment by tomcw** [comment]
If it's failing on all those emulators then it's very likely to be a .woz image problem.

You could ask John Morris (@kerthunk) to take a look. The best place to discuss problematic .a2r/woz images is on the Apple2Infinitum Slack group in the "applesauce" channel.

**Comment by GreatHierophant** [comment]
Thank you for that excellent suggestion, the good folk at Apple2Infinitum indicated that the .a2r needed to be converted in a special way, half tracks needed to be included and they were not.  I obtained a .woz that was properly converted and the game loaded just fine in AppleWin (with a II+), so this can be closed.

**Comment by tomcw** [comment]
Thanks for asking in that Slack channel. I grabbed the .woz that 4am shared and confirm it works for an unenhanced //e, but crashes to the monitor for the enhanced //e.
