### ISSUE TITLE
Mockingboard Classic Adventure - speech not working correctly

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#929]
Available here: https://archive.org/download/great-hierophant-woz-archive/Mockingboard%20-%20Crowther%20and%20Woods%20Adventure.woz

For either MB or Phasor cards, it boots and speaks "Classic Adventure" then gets into an infinite sound loop. The on-screen text says that my "Mockingboard acts as though it does not have a speech chip". It's using SSI263 speech.

Running from the debugger, it hits an assert in `AY8910_Write()`, because state == AY_LATCH (but should be AY_INACTIVE)... because the code is writing 0xFF to ORB (with DDRB=0xFF). Odd!

@GreatHierophant: this is a Mockingboard title that I've not seen before! It'll be interesting to dig into why this isn't working properly under emulation.

**Comment by GreatHierophant** [comment]
Yes, I didn't know it existed until I started to delve into making .woz images.  I don't have a speech chip to test :(

**Comment by tomcw** [comment]
To detect the speech chip, the code kicks off an interrupt-driven speech phrase ("Classic Adventure"), and then waits ~1.623s for it to complete. If it's not complete in that time then it determines there's no speech chip.

The speech phrase theoretically takes 1.200s to complete, whereas AppleWin takes >1.623, so doesn't complete the phrase quickly enough.

It looks like there's some bug when there's a _slow speech chip_ (which outside of emulation doesn't exist!), so the ISR continues to write 0xFF's to the SSI263 regs... which also writes to the 6522 regs 0..4 too! (And so hence the assert above)

Some notes: [MB-Adventure-notes.txt](https://github.com/AppleWin/AppleWin/files/5998768/MB-Adventure-notes.txt)

Anyway AppleWin needs to play the phonemes at a more accurate speed (ie. account for the 4-bit rate and 2-bit duration).
