### ISSUE TITLE
WOZ support: add some random jitter in the bit stream

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#930]
Both Wasteland (#733) & Legacy of the Ancients have a curious T$00-S$00 where there's a 35us gap between $C0EC accesses (see: https://github.com/AppleWin/AppleWin/issues/733#issuecomment-562963515).

I've tried a few fixes for this, but they just result in problems for other woz images (eg. Gruds in Space & Jump Frog).

So I'm coming to the conclusion that the 35 cycles between the two specific $C0EC accesses just needs the right "LSS alignment" with the bit-stream. Introducing a bit of jitter on T$00 (eg. after a large bit-stream gap between $C0EC accesses) is enough to get both Wasteland and LOA (v1/v2) working(*), and not cause an issue for any other woz.

(*) Maybe after 5-10 retries - on a failure the code just reboots via `JMP $C600`.

**Comment by tomcw** [comment]
AppleWin's woz support doesn't feed all the bitcells into the LSS, eg. if there's a big gap between $C0EC accesses, then it "fast forwards" the bit-stream pointer until it's within 50 bitcells of the new $C0EC access. At that point it then runs these 50 (or less) bitcells through the sequencer.

NB. this is just an optimisation. Of course I've tried feeding all bitcells through the sequencer but that didn't solve this issue.

So if it's >50 bitcells then let's call this a "big gap" between $C0EC accesses.

Here's what I've tried...

Firstly I got rid of the previous Wasteland fix (and so now Gruds in Space & Jump Frog both work).

### 1) Random IncBitStream() on track-0

Then at the point where the code detects this "big gap" (between $C0EC accesses), I tied this logic:
- if T$00 (ie. phase==0) and 10% chance: then call `IncBitStream()` - this advances the bit-stream pointer by 1 bitcell.

There are ~60 "big gaps" on T$00 before the C600 firmware jumps to $801.
Then there's another "big gap" until the first $C0EC access at $082A.

This results in ~6 random calls to `IncBitStream()`, and the $801 code will pass eventually (~10 retries?) and the game will boot. Where a retry here means start again with `JMP $C600`.

For 3(*) of the 4 images (2x Wasteland and 2x LOA) the random call to `IncBitStream()` had to occur on the "big gap" at PC=$82A for the game to ever boot.

(*) it was "Legacy of the Ancients - Side 1.woz" where the call to `IncBitStream()` _wasn't_ needed at PC=$82A.

### 2) Specific IncBitStream() on track-0 at PC=$82A

I changed the logic to:
- if T$00 (ie. phase==0) and PC=$82A: then call `IncBitStream()`

For 3(*) of the 4 images (2x Wasteland and 2x LOA) with only a call to `IncBitStream()` at this specific point at PC=$82A was enough for the game to boot.

(*) again it was "Legacy of the Ancients - Side 1.woz"

### 3) varying Dec/IncBitStream() on track-0 at PC=$82A

1. Wasteland_Boot1.woz
   - IncBitStream(): OK
   - No inc/dec: NG
   - DecBitStream(): OK
2. `Wasteland - Boot #1.woz`
   - IncBitStream(): OK
   - No inc/dec: NG
   - DecBitStream(): NG
3. Legacy of the Ancients - Side 1.woz
   - IncBitStream() x2: OK
   - IncBitStream(): NG
   - No inc/dec: OK
   - DecBitStream(): NG
4. Legacy of the Ancients - Side 1 - copy 2.woz
   - IncBitStream(): OK
   - No inc/dec: NG
   - DecBitStream(): OK

The interesting thing about this point in the bit-stream for all 4 images is that:
(a) it's right after the C600 firmware has read T$00-S$00 (obviously as it's just about to `JMP $801`)
(b) it appears to be at the point where the track was finished being written, ie. the end/start transition point:
- For Wasteland: ~10 sync nibbles + 319 consecutive zeros + large field of ~180 sync nibbles.
- For LOA: a large field of ~180 sync nibbles.

So my theory is that on a real disk there's some flux noise (smaller than a bitcell) at this transition point, which will introduce some timing jitter into the LSS. All we need is less than 1 bitcell, ie. less than 4us, which is 7 (or less) 2MHz clocks (Nb. 2MHz = the LSS's clock rate).

**Comment by tomcw** [comment]
So possible ideas for fixes at this point:

1. Just do (1) above, ie. random call to `IncBitStream()` on track-0 when there's a big gap.
   - in the general case, this will work to get from the C600 firmware to $801, but will all track-0 copy protection code tolerate this?
2. The big gap (at PC=$82A) is always $91E bitcells, so I could hardcode a fix (with +/- tolerance) just for this
   - equally the woz images have crc32, so again I could hardcode for specific crc32's... no good if someone were to re-image the game, as the crc32 would be different.
   - I don't like the idea of hardcoding, instead I prefer a generalised fix
3. If it's track-0 and the code has just left C600 firmware (ie. 1st access not in C600 firmware) then randomly call `IncBitStream()` or not.
4. Detect that the big gap traverses the transition point where the track was finished being written, and in this case randomly call `IncBitStream()` or not.
   - easier said than done, as the LOA track-0 only contains a nice, orderly set of sync FE/FF nibbles.

**Comment by tomcw** [comment]
@mr-stivo: you mentioned in the past (~June last year) that your emulator supports motor speed fluctuation, which helps with booting games like Wasteland. Can you share an overview of what approach you took for this? Thanks.

**Comment by sicklittlemonkey** [comment]
It's a fork of libemulator from OpenEmulator. John Morris wrote most of the
WOZ support, and in particular he added this behaviour to the drive motor
on start:
https://github.com/openemulator/libemulation/pull/32

Cheers,
Nick.

**Comment by tomcw** [comment]
On 22 Feb, I asked about this in the Applesauce Slack channel:

---

I'm still trying to get a good AppleWin woz emulation solution for EA's Wasteland (WL) & Legacy of the Ancients (LOA).

Details of this seemingly innocuous T$00-S$00 disk protection or code bug(?) are here: https://github.com/AppleWin/AppleWin/issues/733#issuecomment-562963515

I've implemented a few fixes in AppleWin, but they always result in causing issues for other .woz images. NB. in June'20 on this channel we saw that most other popular emulators also had trouble with these 2 games.

These AppleWin fixes basically introduce a bit of jitter into the bit-stream, which (after a number of retries) is enough to align the LSS with the bit-stream to allow this 35us gap between $C0EC access to succeed.

Anyway my current (_clutching at straws!_) theory is that there's a partial bit-cell (eg. <4us) that isn't getting transposed from the original physical image into the .a2r / .woz images... in fact the current woz spec doesn't support such a thing!

EG, on a track (T$00 in this case) there will be a bit of flux noise at the final point where the track was written... ie. it won't be a perfect number of 4us bit-cells; instead there will always be a partial bit-cell at the overlap of the last & first bits written.

Ordinarily this flux noise isn't important. But what happens when it's fed into the LSS? ...perhaps sometimes it results in an extra bit-cell, and sometimes not. So sometimes the LSS state-machine gets randomly advanced by +1 state. This occurs at the end/start point that the track was written.

Now whether or not this was intentional on the WL & LOA games isn't important, but certainly after the C600 firmware reads T$00-S$00 there are $91E bit-cells which include this (end/start) transition point. (It's very clear to see in WL, where there are ~319 sequential zero bits!) From my experiments, randomly incrementing the bit-stream must occur during this $91E bit-cell interval for these 2 games to boot. (In fact I have 2x WL images and 2x LOA images. One LOA doesn't need the increment, whereas the other 3 do... hence the random increment to make it work for all 4 images.)

`@Disk Blitz` Does this theoretical "partial bit-cell" idea sound feasible?

---
[John] I’m not sure where you are thinking that this partial bit cell should be. I’m pretty sure that the large gap (~320 bits) is the track seam and therefore different on every disk manufactured. I have looked at a few a2r images, and it is always a bit different.

Applesauce is capturing flux transitions with 48MHz accuracy and then it is getting rounded to 125ns resolution. So if there are partial cells in there they would definitely be captured.

And the noise generated in the large gaps is going to vary with every drive.

---
[me] My thinking is that the track can't be exactly an integral number of 4us bits long, ie. there must be an overlap with the last written bit and the first, resulting in this "partial bit".

---

[John] A track is never an integral number. And you can write the exact same track over and over again and it won’t ever be the same number of nibbles either.

It is an analog signal being written to media whose speed is constantly fluctuating. And the timing shifts again every time you read it.

---
[me] Maybe my mental model is too digital. So there will be fluctuating timing shifts, and so sometimes the LSS will align and be able to read the the nibble even with this 35us gap between $C0EC access. (And if it fails to read the correct nibble, then it'll just reboot and retry... until it succeeds)

It's just in my (and presumably other emulators' LSS implementations) there is no fluctuation, and so LSS never aligns, and so these 2 games never boot.

... they just endlessly reboot.

---
[John] So where is it looking for this alignment? After the gap?

---
[me] 
It reads 512 4&4-encoded nibbles, then after this last 4&4 nibble, there's a 35 cycle gap until the next $C0EC read - which is the 1st 4&4 checksum nibble.
NB. there are no hidden sync bits, it's just simple nibbles.
(There's a code snippet in the link I posted above)

BTW, LOA (which has an identical track-0/sector-0) doesn't have this large ~300 zero-bit gap on track-0, it just has a large field of 9/10-bit sync nibbles... so no opportunity to generate lots of noise.

Basically (I think) I need some way to introduce fluctuation (or jitter) enough to nudge the bit-stream by 1 bit. But not too much, so it doesn't affect any other games.


>So where is it looking for this alignment? After the gap?

Sorry, yes, after WL's ~319 zero big gap are 3x blank sectors (512x 4&4 encoded, ie. AA BB), then finally the 4th sector is the one this code at $801 is looking for.

---
[John] Hmmm, I just don’t see any extra time in there.
<img width="1280" alt="Screen Shot 2021-02-22 at 12 53 19 PM" src="https://user-images.githubusercontent.com/6696896/112695316-c3153280-8e7b-11eb-9218-2045672bd444.png">

---
[me] Thanks for checking. Actually I think this small extra time has to occur right after sector-0, ie. during the large 9/10-bit sync nibble field or the ~300 consecutive zero bits. As I state above, my thinking is that when writing a track the last bit-cell will overlap with the first, producing a short (<4us) bit cell... I guess it could also appear to be a long bit-cell too.

The track is laid out as: sector-00 (read by C600 firmware) then a big sync field/zero field, then 4x 4&4 encoded sectors. The 4th of which is the sector read & decoded by the code at $801 (ie. the code from sector-0)

So since the LSS always has to be fed the bits from this big sync field/zero field, if there were an extra short (or long) bit-cell then it would be enough to sometimes nudge the LSS on by 1 state.

As you say above "A track is never an integral number" [of 4us bits]. So there must be a point in the track where there's an overly short/long bit (caused by when it was written).

---
[John] Bit cells and time aren’t a constant kind of thing that can nudge the LSS just a bit. Here are 4 different copies of the Wasteland boot disk. I have highlighted the time from the D5 after T$0S$0 till the first D5 of the first 4&4 sector, so including the big sync field and zero field. 8252, 8217, and 8403µs. They are pretty different. As for the 4th copy, it doesn’t have a zero field at all. Possibly a protection variant, but the rest of the disk structure is seemingly identical.

<img width="1286" alt="Screen Shot 2021-02-23 at 8 07 51 PM" src="https://user-images.githubusercontent.com/6696896/112695434-f952b200-8e7b-11eb-8b6b-bb86a9b33d36.png">

Also, as for noise, it varies per drive. And noise doesn’t happen relative to bit cells. In fact, most noise is actually groups of 2 transitions being fired off with 1-2µs between them. The 3470 thinking that there is a transition and then changing its mind.

**Comment by sicklittlemonkey** [comment]
What a saga! I notice qkumba replied:
"As far as I remember, the game does occasionally reboot more than once
because of loader failure, so maybe this explains that."

Have you managed to get the WOZ images from John to test?

Cheers,
Nick.

**Comment by tomcw** [comment]
>What a saga!

Yeah totally!
And as a recap, lots of other emulators failed to boot these 2 games too: https://github.com/AppleWin/AppleWin/issues/733#issuecomment-643671348

This issue only affects these 2 games (Wasteland & Legacy of the Ancients). And the fixes I've previously put into AppleWin cause other games to fail. So I'm now going to revert those fixes, and then will probably add some game-generic random jitter to get WL+LOA working.

And the random jitter will be consistent with qkumba's comment too.

From my [21st Feb comment above](https://github.com/AppleWin/AppleWin/issues/930#issuecomment-782891123), my current best idea is:
>If it's track-0 and head has just passed the end of sector-0 then randomly call `IncBitStream()` or not.

**Comment by tomcw** [comment]
Here's the solution I've gone for:
- If it's track-0 and the head has just passed the address prologue for sector-0 then set a flag
   - actually I've gone for this non-standard address prologue: (*)
      - D5,AA,96; AA,AA; AA,AA; AA,AA; AA,AA; DE
      - ie. V=00, T=00, S=00, C=00
      - which is the address prologue for WL, LOA (and a few other titles, eg. Infocom & Wizardry games)
- After the DiskII firmware reads sector-0, then there's a "big gap" until the next $C0EC access in $8xx code.
   - NB. It must be safe to skip a bit-cell during this transition from $C6nn firmware to $8nn user code.
- So with the flag set and this "big gap" (between $C0EC accesses) then after the end of sector-0 _randomly_ skip 1 bit-cell. 

(*) NB. I did try with (4&4) Volume and Chksum matching anything (and always forcing the skip 1 bit-cell to occur), and this worked for all the WOZ test titles, but to be safe I've just stuck with this non-standard address prologue.
Also it means that I only need to test this change with the small handful of titles that use this non-standard address prologue.

**Comment by sicklittlemonkey** [comment]
Great work Tom! But it's still a mystery then? I hope John eventually gets
to the bottom of what's unusual about those 2 disks

Cheers,
Nick.

**Comment by tomcw** [comment]
It's a little unsatisfactory, since yes, it's still somewhat of a mystery. But I've spent a fair chunk of time tracing this, trying to find solutions and discussing with John. Currently this is the best I can come up with.

So for now, I will close this.

**Comment by tomcw** [comment]
NB. _'Chuck Yeager's Advance Flight Trainer'_ is another EA title from 1987 that also uses the exact same protection as WL & LOA (ie. both the 35 cycles between the two specific $C0EC accesses at $8AC; and the weak-bit protection at $666 - see #733).

**Comment by tomcw** [comment]
### Checklist of EA titles for Apple II in 1987+

EA titles for Apple II from 1987 ([ref](https://en.wikipedia.org/wiki/List_of_Electronic_Arts_games:_1983%E2%80%931999))

- [ ] The Bard's Tale II: The Destiny Knight
- [x] Chuck Yeager's Advanced Flight Trainer
- [ ] Deathlord
- [ ] Earl Weaver Baseball
- [ ] ~Earth Orbit Stations~ (Alt. protection)
- [x] Legacy of the Ancients
- [ ] ~Skate or Die!~ (IIgs)

EA titles for Apple II from 1988 ([ref](https://en.wikipedia.org/wiki/List_of_Electronic_Arts_games:_1983%E2%80%931999))

- [x] Wasteland
- [ ] The Bard's Tale III: Thief of Fate
- [ ] John Madden Football
- [ ] ~Zany Golf~ (IIgs)

**Comment by tomcw** [comment]
A small update: I tried an original LOA disk side 1 on a real //e, and occasionally see the reboot (and can hear the drive when it does `JMP $C600` and the track-0 head bashing). Also all 4 sides have the same boot code (sides 2-4 just display a the EA logo, then a TEXT message to "BOOT SIDE 1").
