### ISSUE TITLE
Swap Joystick Buttons not working

### ISSUE THREAD

**Issue by qtipbailey** [AppleWin/AppleWin#936]
As mentioned in "Swap Joystick Buttons, issue #759" I also am using an Xbox controller and the A and B (0 and 1) buttons are reversed and the suggested fixes are having no effect. When I check the box "Swap 0/1" or use the command line "-swap-buttons" nothing changes - still buttons are reversed. Why would this be?

**Comment by tomcw** [comment]
Currently it's only been implemented to swap Open / Solid Apple keys (eg. Left / Right Alt keys).

I will extend this to include:
- controller buttons (if using a real joystick)
- mouse buttons (if using a mouse for joystick emulation)
- Num Pad '0' and '.' keys (if using a num pad for joystick emulation)

**Comment by tomcw** [comment]
NB, in the AppleWin.chm help it says:

>-swap-buttons
>Swap the Windows keys used for Open Apple & Solid Apple keys.

So this will need updating too.

**Comment by tomcw** [comment]
In 1314fcc I also fixed the NumPad's Insert/Delete keys working (as button0/1) when NumLock is off (for Joystick 1 = Num Pad).

**Comment by tomcw** [comment]
Tested GUI "Swap 0/1" and GUI "Auto-fire" (buttons 0 and 1) for these variants:
- [x] Alt & Alt Gr
- [x] Left Ctrl & Left Alt (via -left-alt-control-buttons)
- [x] Right Ctrl & Right Alt (via -right-alt-control-buttons)
- [x] NumPad with NumLock on/off
- [x] Real joystick 1 (a DS4)
- [x] Mouse

**Comment by tomcw** [comment]
@qtipbailey: I've released [AppleWin 1.30.0.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.0.0(try2)), which extends support for the swapping of buttons 0 and 1. I haven't testing with an XBox controllers, but did test with a PS4 DS4 controller. Please try it and confirm.

**Comment by qtipbailey** [comment]
Yes, the button swap works on Xbox One controllers also.
