### ISSUE TITLE
Uthernet: 1 & 2, pcap and slirp 

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#949]
Hi

AppleWin is proving an endless source of interesting projects.
So, recently I enabled the Uthernet emulation in linux, and it has been a very simple process, 95% just worked. But there were a couple of hiccups, so I took a step back and looked at it again.

In linux, `libpcap` requires elevated privileges, which a normal user does not normally have. This makes debugging extremely complicated (I was lucky that I had to debug very little indeed).

Then I realised that, wait a moment, Uthernet 1 is old, we now have Uthernet 2 and nobody emulates it. Let's try!
This again has been fairly straightforward (at least in `MACRAW` mode), the same *tfe-libpcap* code can be reused to send and receive packets.

But still I was not pleased by the **I need to be root** issue: what do other emulators do? Turns out that the network code for QEMU is available as a separate library: https://gitlab.freedesktop.org/slirp/libslirp. Fantastic, let's try it.

And here is an interesting comparison.

pcap:

1. a sort of bridged network where the guest is attached directly to the same LAN
2. very easy to run a server and listen on a given port
3. only works for *Ethernet* devices in *promiscuous* mode
3. multiple instances of AppleWin on the same LAN are problematic (same MAC address)
4. in Linux this requires elevated privileges

slirp:

1. code from QEMU (wow!)
2. no special privileges required
3. works on any network interface
4. multiple AppleWin on the same LAN pose no problems (each runs in a separate sub LAN)
5. port-forwarding is required to run a server

Overall pcap is the easiest option, but if anybody finds the considerations above interesting, there are some cool projects available.

**Comment by tomcw** [comment]
Hi @audetto - it's certainly be great to emulate the Uthernet II card!
Let me link to the original issue for this request #518.

**Comment by sicklittlemonkey** [comment]
> AppleWin is proving an endless source of interesting projects.

Hah, that is the thing with emulation. It's a playground that connects to
all the real world problems in IT. Endless opportunity for exploration!

Good luck with the Uthernet II emulation, as offloading most of the
networking to the card (emulation) was one of the advantages of the actual
card. The other improvement of not requiring root for Linux would be a
massive win.

Cheers,
Nick.

**Comment by tomcw** [comment]
Let me close this, as discussion and implementation has switched to #518
