### ISSUE TITLE
Registry, floppy disks and pathnames.

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#960]
I recently have replaced \ with / on Linux and as a side effect the behaviour is very similar to AW on Windows.

So, what I noticed is that the filename of disks are saved to the registry in this way

1) Floppy Disks: just the filename and not the path
2) Hard Disks: *first* it saves the filename only and *then* overwrites with the full path

Together with the `Starting Directory` it is possible to retrieve some information, but some is lost.

If I insert 2 floppy disks from 2 separate folders, when I restart AW, only the last is loaded (as the first's working directory is lost).

Would it not be easier to just write the full path to the registry?
There is PR for this, if the idea is acceptable: https://github.com/AppleWin/AppleWin/pull/959

**Comment by tomcw** [comment]
>Would it not be easier to just write the full path to the registry?

Maybe it's that simple, but I need to thoroughly check this.

Note to self:
I did some work on paths/filenames - see these specific comments:
- https://github.com/AppleWin/AppleWin/issues/691#issuecomment-708656135
- https://github.com/AppleWin/AppleWin/pull/849#issuecomment-716031105

**Comment by audetto** [comment]
These 2 comments are relative to save states, which I agree should not have the path embedded in the filenames.

On the other hand, I am referring to disk names saved to registry.
The use case that would be lost if the PR is applied is this:

1. Someone as multiple folders with the same floppy disks (by name) in each.
2. Registry saves only the name
3. Using `-current-dir` she select which folder to start from and which set of floppy disks to use

The use case I have in mind is different

1. User has many floppy disks stored in multiple folders (games, os, utils, etc...)
2. Wants to use 2 which happen to be in different folders
3. When AW restarts, only one is loaded automatically

Moreover, floppy and hard disks behave differently. Is there a reason for this?

**Comment by tomcw** [comment]
It looks OK to extend disks to save the full pathname.
Definitely we want the same behaviour.

Another difference in the Registry is `Starting Directory` vs `HDV Starting Directory`:
- Preferences: `Starting Directory` - for the path 'Last Disk Image 1' (and 2)
  - used for other things too, eg. debugger's CWD, location of screenshots, default location of save-state, etc.
- Preferences: `HDV Starting Directory` - for the path 'Last Harddisk Image 1' (and 2)
  - surely redundant if the `Last Harddisk Image 1/2` contains the path?

And this comment made me wonder if there was an issue, but I can't see any problem with passing in the pathname, instead of just the filename:

```
// Pre: pszImageFilename is *not* qualified with path
ImageError_e Disk2InterfaceCard::InsertDisk(const int drive, LPCTSTR pszImageFilename, const bool bForceWriteProtected, const bool bCreateIfNecessary)
{
```

NB. For Harddisk it's different:

```
// Pre: pszImageFilename is qualified with path
BOOL HD_Insert(const int iDrive, const std::string & pszImageFilename)
{
```

**Comment by tomcw** [comment]
>- Preferences: HDV Starting Directory - for the path 'Last Harddisk Image 1' (and 2)
>   - surely redundant if the Last Harddisk Image 1/2 contains the path?

No.
The save-state only saves the harddisk's filename.
So `HDV Starting Directory` is still needed to locate the HDV files.

NB. If the .hdv file can't automatically be found, then it'll get the user to browse for the file.
So if the HDV files are in different folders then AppleWin will prompt.

And this is also the same for disks.
ie. if the DSK files are in different folders then AppleWin will prompt.

**Comment by tomcw** [comment]
Thoughts on forwards/backwards compatibility:
- (upgrade AppleWin) Registry has old format (DSK is just filename), and new AppleWin is "expecting" new pathname format:
  - Current Dir will have been set to `Starting Directory`
    - Actually this is an assumption, as `InsertDisk()` is called from many places.
    - eg. in Debugger's `CmdDisk()` it calls `InsertDisk()` with just a filename.
  - `InsertDisk()` will take the filename as input, and correctly be able to open it
- (downgrade AppleWin) Registry has new format (DSK is pathname), and old AppleWin is "expecting" old filename format:
  - `InsertDisk()` works correctly with pathname as input ( ie. just like `HD_Insert()` )

Summary: it should work OK in both cases.

**Comment by tomcw** [comment]
Minor local refactor 71bea5241.

Closing.
