### ISSUE TITLE
On AppleWin app shutdown, there's a display flicker as it sets the display back to the default

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#965]
Steve Nickolas on cea2 group, "AppleWin 1.30.2 and WINE - huh, that's odd":

>One thing I noticed every time I exit the current version of AppleWin
troubles me. I think it's trying to flick in and out of fullscreen or
something, and it winds up shutting off my main display for several
seconds.

---

Regression added at 1.30.2.0 in commit: f076986c045d801ba8dc6e75708b5c77834982bb

**Comment by audetto** [comment]
Good call! I observed something very similar and blamed the Ubuntu update!

**Comment by tomcw** [comment]
And Steve Nickolas confirmed on the cea2 group that this is now "Fixed".
