### ISSUE TITLE
Weird day of the week anomaly with ProLine BBS Software

### ISSUE THREAD

**Issue by blindphoneman** [AppleWin/AppleWin#969]
Hi:

Got a weird one this time.

I realize this may be hard to figure, but, maybe this has to do with how the NoSlot clock handles days of the week.

When running ProLine BBS software, the days of the week are off by one, while the actual date is correct.

At first, I thought it was merely a Y2K bug, but, I set my system clock back to 1999 and tried running the software, and, it was still off by one day.  The Week day is wrong, but, not the date.

The NoSlot Clock software does report the correct day of the week.

Any idea why this might be happening?  Does the NoSlot Clock do something weird with ProDOS's days of the week to come up with the correct day in it's programs?

Thanks!

**Comment by tomcw** [comment]
Hi @blindphoneman,

It appears that "DOW" (ie. Day of the Week) has 2 conventions...

See this old comment: https://github.com/AppleWin/AppleWin/issues/179#issuecomment-44062314

So I'd say that ProLine BBS follows the contrary convention to AppleWin's NSC support.

**Comment by blindphoneman** [comment]
One more question relating to the clock: The author of one of the programs I’m running wants people to set the clock back to 1999, for some reason.  The only way I found to do this is to set my host PC’s clock back.  I tried using the v14 utilities to set it, but, the system just beeped and nothing appeared to happen.  From this, I’m figuring it is tied to my PC’s time.  Am I correct? Thanks!

**Comment by tomcw** [comment]
>From this, I’m figuring it is tied to my PC’s time.  Am I correct?

Yes, it's tied to the PC's time.

Someone else raised a similar request recently, here: #927
In that issue, the best workaround was to use NirSoft's RunAsDate.

**Comment by blindphoneman** [comment]
Thanks! I shall take a look at it.
