### ISSUE TITLE
woz format - write protected

### ISSUE THREAD

**Issue by exoscoriae** [AppleWin/AppleWin#971]
Hello. We are having trouble with woz format files, as it appears the emulator currently will not write to them. This causes errors with any game that tries to save or modify any on disk data.

There is a simple byte change that can be made in the woz file that makes them readable, however that changes the crc of the image which in turn brings up an error message\warning at launch.

Some the primary options we have discussed is
A command line flag that tells the emulator to load a woz image and modify the hex address 0x00000016 (byte 22 according to https://applesaucefdc.com/woz/reference2/) from a "01" (write protected) to a "00" (write enabled). Then, modifications to the file could be written to a diff of some sort, that is stored in the same folder as the where the woz file was loaded from. On the next load, if a diff file for that game exists, it is loaded along with the game, the hex edit occurs in memory, and the diff is applied.

Granted, this is theoretical, and it may be difficult to implement. The main idea here is that we would like to use the woz files with out hex editing them ourselves, as that means we have to have an entire hacked set of woz files just so a user can enjoy a game such as 2400AD (which is pretty hard to play without being able to save).

So, if the woz files could some how be loaded as-is, but the write protection could be bypassed in memory. That would be great. Or hell, the ii=mages are small enough, instead of creating a small diff, what if it just created a second copy of the woz file that was modified? And when it loads, if it sees this second copy, it supersedes the base copy?

As you guys understand the internal logic of AppleWin better than us, I welcome your input on how you feel the most effective way to tackle this issue.

Thank you *so* much for taking the time to read through this and your assistance in helping us get our project moving along.

**Comment by exoscoriae** [comment]
Another option would be to write the changes directly back to the woz file. However if that is the case, it will need to ignore the crc check on the next load. As we have the woz files backed up in the game's zip file, this wouldn't cause preservation issues with the originals.

**Comment by tomcw** [comment]
>We are having trouble with woz format files, as it appears the emulator currently will not write to them. This causes errors with any game that tries to save or modify any on disk data.

Firstly, if the woz INFO chunk's `write protected` flag is disabled, then woz writes work fine.
So you must be talking about woz images that are (erroneously?) set to be protected.

@exoscoriae - I think all that's needed is just a command line switch that overrides the woz image's write-protect setting.

Any writes to the woz image will result in the write-protection being permanently disabled. So any future use of the image won't need to specify the command line option. IE, the woz image's INFO chunk's `write protected` will be set to 0, and the crc correctly updated.

Similarly I would provide a write-protect command line switch too, which does the reverse.

The switch should probably only apply to a specific woz image, ie. not all loaded images in d1 and d2.
Also if the image is ejected, and replaced with a new woz image, then the switch no longer applies to that new image.

**Comment by exoscoriae** [comment]
That would be great!

**Comment by tomcw** [comment]
@exoscoriae - NB, if any image (woz or other) is stored in a zip file, then it is always write protected.
I assume you are unzipping, and it's the unzipped images that are passed to AppleWin?

Are there any other games (in addition to 2400AD) that are set as write protected (in the woz INFO chunk)?

For my reference, in the 2400AD game, CTRL+S will allow you to save game. With the "2400 A.D. - Player Disk.woz" set as write-protected then this results in the game locking up (actually stuck in a loop seeking across various tracks).

**Comment by tomcw** [comment]
I reported the issue of 2400AD's "Player" disk being incorrectly write protected.

This was a preservation error, and 4am (the original uploader) has now fixed 2400AD so that this "Player" disk is no longer write protected. The fixed version is [here](https://archive.org/details/wozaday_2400_AD) in the woz-a-day collection on Internet Archive.

I currently think the best solution is to correctly set this "write protect" flag in the woz image - ie. fix any woz images that have this set wrong. This way everyone will benefit regardless of which emulator / front-end they are using.

Can you let me know of any other woz images with this flag set wrong?

**Comment by exoscoriae** [comment]
I can provide a list to you, or I can forward the list directly to 4am. Whichever works best.

**Comment by tomcw** [comment]
Forwarding directly to 4am is best. Thanks.
