### ISSUE TITLE
feature request: slot 5 UI config

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#975]
I've been using the "-s5 diskii" command-line option for a second disk controller.  It's great.
However, somehow a "Slot 5" value got saved to the registry, causing it to be permanently in use as a drive.
That blocked slot 5 for sound when later run without the "-s5" option, until I edited the registry.
I would like to see a UI element to control the selection in slot 5 (or that slot 5 isn't ever saved to the registry).

**Comment by tomcw** [comment]
Hi Peter - thanks for the report and request.
In fact it's good to hear of someone actually using this "-s5 diskii" feature!

I was able to repro this by doing:
- create save-state1: s4=phasor, s5=empty
- create save-state2: s4=empty, s5=diskii
- load state1
- load state2  (this saves "Slot 5" to Registry with a value of "1" ie. diskii)

I tried to revert using command line "-s5 empty", but this isn't currently supported for slot 5 (nor slots 4 and 7!).
Workarounds are: manually edit the Registry (or conf.ini), or load a prior save-state with no diskii in slot 5.

>I would like to see a UI element to control the selection in slot 5 (or that slot 5 isn't ever saved to the registry).

It's definitely easier (as a quick fix) not to save "Slot 5" = "diskii" to the Registry.

A minimum UI would be:
- Configuration Disk UI: check box for a Disk II controller in slot 5
- Configuration Disk UI: 2 extra combo drop-downs for the 2 extra drives

NB. There's already a tooltip over the Drive-1/2 UI buttons to show what's in the slot 5 drives.

Let me try to squeeze in this minimum UI.

**Comment by tomcw** [comment]
[Note to self] Something to think about is I need to consider how to persist the slot-5 image names to the Registry.
OTTOMH:
- Extend "Preferences" with "Last Disk Image 1 (s5)" and "Last Disk Image 2 (s5)"
  - And keep "Last Disk Image 1" and "Last Disk Image 2" implicitly for slot 6.
- Or create a sub-folder "Preferences\Last Disk Image", with value names "s6,d1", "s6,d2", "s5,d1", "s5,d2"
  - And deprecate "Last Disk Image 1" and "Last Disk Image 2".

**Comment by tomcw** [comment]
>I need to consider how to persist the slot-5 image names to the Registry.

Spun this off into a generalised approach in #977.

**Comment by tomcw** [comment]
@peterferrie - here's a [new build](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.4.0) with extended GUI support for a disk ii card in slot 5. Please take a look.

**Comment by peterferrie** [comment]
Thanks Tom, I like that solution.

**Comment by tomcw** [comment]
Thanks for checking it. (Closing this issue)
