### ISSUE TITLE
(Debugger) (Help) Control-PrintScreen isn't in help

### ISSUE THREAD

**Issue by Michaelangel007** [AppleWin/AppleWin#976]
We've had the debugger hotkey `Control`+`PrintScreen` support in the debugger for a while now to copy the debugger screen as text, #239, but looking through the debugger help I don't see that we ever documented this?

@tomcw I see issue #437 we discussed moving to PDF but the resolution was to stay on CHM for the time being.  Is there documentation on how to generate the CHM? ( **Update:** I've added two files: `docs\build_help_chm.txt` and `help\update.bat`.)

**Comment by tomcw** [comment]
Thanks for updating the help doc + also adding info on how to generate the CHM.
