### ISSUE TITLE
Enhanced disk access speed all drives" setting.

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#980]
Just as the title says. Applewin isn't remembering the "Enhanced disk access speed all drives" setting. It's always turned on with every restart.

**Comment by tomcw** [comment]
Thanks for reporting. I've confirm it, and will fix in the next release.

**Comment by tomcw** [comment]
@Keatah - FYI, new release [AppleWin 1.30.5.0](https://github.com/AppleWin/AppleWin/releases/download/v1.30.5.0/AppleWin1.30.5.0.zip) with this bug fixed.

**Comment by Keatah** [comment]
Yes seems to work ok.
