### ISSUE TITLE
fixed one-shot paddle timers

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#985]
Like MAME, AppleWin's support "always restart the timers when strobed. That means a controller is read perfectly every time."

See https://github.com/mamedev/mame/pull/8504
Credit to @xotmatrix for raising this against MAME's Apple II emulation.

**Comment by tomcw** [comment]
Examples on real Apple //e hardware:

![DSC_2255](https://user-images.githubusercontent.com/6696896/135762942-dbc3b1c1-0049-4eb3-838e-06607bada875.png) ![DSC_2257](https://user-images.githubusercontent.com/6696896/135762945-959c4b77-dfb8-4f59-88d2-e2a5ad2c4fc5.png)

Should read: X=44, Y=146 / Should read: X=255, Y=217

**Comment by xotmatrix** [comment]
Hey, I recognize that. I was psyching myself up to work on this myself (never built AppleWin before) but I got distracted and forgot to even report it here.

**Comment by tomcw** [comment]
I sometimes check the updates in MAME for the Apple II... and saw your PR and nice description today.
It should be an easy fix in AppleWin too, so I'll make the fix for the next release.
Thanks!
