### ISSUE TITLE
Support SHR for Total Replay box art

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#997]
This is already supported by [microm8 ](https://paleotronic.com/2019/03/11/microm8-update-super-hi-res-shr-support-1-2/) for the //e, or real Apple II with a VidHD card.

The problem is displaying a 640x200 (or 320x200) image in the 560x192 window.
NB. In #621, for the RGB AppleColor card, I squashed 640x192 into 560x192 by losing every 8th pixel.

Really we don't want to lose any of the image, so would need to expand the window. Perhaps only expand to 640x200 when in SHR mode, then drop back to 560x192 when not.

**Comment by tomcw** [comment]
See https://github.com/a2-4am/4cade/blob/master/src/4cade.init.a
```
         jsr   HasVidHDCard          ; check for VidHD card (allows super hi-res artwork even on non-IIgs machines)
```

And see https://github.com/a2-4am/4cade/blob/master/src/hw.vidhd.a
(for the magic bytes to emulate the presence of a VidHD card)

**Comment by tomcw** [comment]
WIP in branch: https://github.com/AppleWin/AppleWin/tree/Support-SHR

Expand the window to fix the SHR 640x400 pixel image (ie. 320x200 doubled in both directions):
![pop2-shr](https://user-images.githubusercontent.com/6696896/142773852-d4fea984-a97f-4531-b100-1356b141bea3.png)

But currently the older //e video modes aren't centred, so there is a right (8 pixels) & bottom border (80 pixels):
![pop-hgr](https://user-images.githubusercontent.com/6696896/142773856-fd7de5ff-c48f-4268-af78-b6490cdb8d02.png)

My current thinking is:
- When VidHD card is not inserted, then use old 560x384 window size
- When VidHD card is inserted, then use 640x400 window size + centre the older //e video modes
  - the bottom right black area below the vertical buttons will just be grey-filled (ie. same as in 2x windowed mode)

**Comment by tomcw** [comment]
The IIgs video modes have an aspect ratio of 4:3, so the images appear slightly flattened in windowed-mode (ideally they should be stretched by 20% vertically).

I've changed AppleWin's full-screen to allow separate x,y scaling.

So (eg) specifying this command line: `-no-full-screen  -fs-width=1600 -fs-height=1200`
Then the (640,400) SHR image will be x-scaled by 2 and y-scaled by 3.
On my 1920x1200 monitor, this results in an image that's 41x32cm, or 1.28:1 = 3.84:3  (which is pretty close to 4:3).

**Comment by audetto** [comment]
Quick question, which game uses this hd video mode?

**Comment by tomcw** [comment]
Only [Total Replay](https://archive.org/details/TotalReplay). So pretty niche, but there currently loads of work going on to add SHR box-art images for most of the games in this modern collection.

**Comment by sicklittlemonkey** [comment]
Fantastic work. I'm loving the updates ... I gave it a quick whirl but no
SHR screens came up.
I'm using TR 4.01 which I think shows SHR in attract mode on my IIgs. It's
been a long time.

Have you tested with that version?

I asked 4am (on Twitter) what he uses to test it, and he said MAME. But
it's nice to have another option!

Cheers,
Nick.

**Comment by audetto** [comment]
I dont see it happening.
Even Total Replay still shows the borders.

![image](https://user-images.githubusercontent.com/212523/144711411-1a3ee81a-45c2-40b3-b088-8efe6e06a21e.png)

**Comment by tomcw** [comment]
From Total Replay (4.01), type the name of a game, eg. LOD (for Lode Runner), then press SPACE for preview.
If the game has an SHR box-art image, then it will show it first, followed by the regular HGR (or DHGR) game screenshots.
Games to try are: Lode Runner, Archon I/II, Airheart, Qix... (there are loads)

NB. In this VidHD mode, you'll get black borders when in regular TEXT/GR/HGR/DHGR video modes. Only SHR is borderless.

**Comment by audetto** [comment]
Got it, but it is only for the box-art image, isn't it? The game is always in normal mode.

**Comment by tomcw** [comment]
Correct - SHR is just for the box-art image.

NB. Currently you have to set the model to //e or Enhanced //e... but bizarrely (on a real h/w VidHD setup) SHR even works on a II/II+, as the VidHD card sniffs the address/data buses and sees writes to aux mem, even though it doesn't exist on the II/II+!

**Comment by tomcw** [comment]
Release this in AppleWin 1.30.7.0, [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.7.0).
